const countries = [
    { name: "Afghanistan", region: "asia", flag: "/quiz/flags/afghanistan.png" },
    { name: "Albania", region: "europe", flag: "/quiz/flags/albania.png" },
    { name: "Algeria", region: "africa", flag: "/quiz/flags/algeria.webp" },
    { name: "Andorra", region: "europe", flag: "/quiz/flags/andorra.svg" },
    { name: "Angola", region: "africa", flag: "/quiz/flags/angola.png" },
    { name: "Antigua and Barbuda", region: "north-america", flag: "/quiz/flags/antigua-and-barbuda.svg" },
    { name: "Argentina", region: "south-america", flag: "/quiz/flags/argentina.png" },
    { name: "Armenia", region: "asia", flag: "/quiz/flags/armenia.svg" },
    { name: "Australia", region: "oceania", flag: "/quiz/flags/australia.svg" },
    { name: "Austria", region: "europe", flag: "/quiz/flags/austria.webp" },
    { name: "Azerbaijan", region: "asia", flag: "/quiz/flags/azerbaijan.png" },
    { name: "Bahamas", region: "north-america", flag: "/quiz/flags/bahamas.png" },
    { name: "Bahrain", region: "asia", flag: "/quiz/flags/bahrain.png" },
    { name: "Bangladesh", region: "asia", flag: "/quiz/flags/bangladesh.png" },
    { name: "Barbados", region: "north-america", flag: "/quiz/flags/barbados.png" },
    { name: "Belarus", region: "europe", flag: "/quiz/flags/belarus.svg" },
    { name: "Belgium", region: "europe", flag: "/quiz/flags/belgium.png" },
    { name: "Belize", region: "north-america", flag: "/quiz/flags/belize.png" },
    { name: "Benin", region: "africa", flag: "/quiz/flags/benin.png" },
    { name: "Bhutan", region: "asia", flag: "/quiz/flags/bhutan.png" },
    { name: "Bolivia", region: "south-america", flag: "/quiz/flags/bolivia.webp" },
    { name: "Bosnia and Herzegovina", region: "europe", flag: "/quiz/flags/bosnia-and-herzegovina.png" },
    { name: "Botswana", region: "africa", flag: "/quiz/flags/botswana.png" },
    { name: "Brazil", region: "south-america", flag: "/quiz/flags/brazil.png" },
    { name: "Brunei", region: "asia", flag: "/quiz/flags/brunei.png" },
    { name: "Bulgaria", region: "europe", flag: "/quiz/flags/bulgaria.webp" },
    { name: "Burkina Faso", region: "africa", flag: "/quiz/flags/burkina-faso.webp" },
    { name: "Burundi", region: "africa", flag: "/quiz/flags/burundi.png" },
    { name: "Cambodia", region: "asia", flag: "/quiz/flags/cambodia.png" },
    { name: "Cameroon", region: "africa", flag: "/quiz/flags/cameroon.png" },
    { name: "Canada", region: "north-america", flag: "/quiz/flags/canada.svg" },
    { name: "Cape Verde", region: "africa", flag: "/quiz/flags/cape-verde.png" },
    { name: "Central African Republic", region: "africa", flag: "/quiz/flags/central-african-republic.webp" },
    { name: "Chad", region: "africa", flag: "/quiz/flags/chad.png" },
    { name: "Chile", region: "south-america", flag: "/quiz/flags/chile.svg" },
    { name: "China", region: "asia", flag: "/quiz/flags/china.webp" },
    { name: "Colombia", region: "south-america", flag: "/quiz/flags/colombia.png" },
    { name: "Comoros", region: "africa", flag: "/quiz/flags/comoros.png" },
    { name: "Congo", region: "africa", flag: "/quiz/flags/congo.png" },
    { name: "Costa Rica", region: "north-america", flag: "/quiz/flags/costa-rica.png" },
    { name: "Croatia", region: "europe", flag: "/quiz/flags/croatia.png" },
    { name: "Cuba", region: "north-america", flag: "/quiz/flags/cuba.png" },
    { name: "Cyprus", region: "europe", flag: "/quiz/flags/cyprus.webp" },
    { name: "Czech Republic", region: "europe", flag: "/quiz/flags/czech-republic.webp" },
    { name: "Democratic Republic of the Congo", region: "africa", flag: "/quiz/flags/democratic-republic-of-the-congo.png" },
    { name: "Denmark", region: "europe", flag: "/quiz/flags/denmark.png" },
    { name: "Djibouti", region: "africa", flag: "/quiz/flags/djibouti.svg" },
    { name: "Dominica", region: "north-america", flag: "/quiz/flags/dominica.png" },
    { name: "Dominican Republic", region: "north-america", flag: "/quiz/flags/dominican-republic.png" },
    { name: "East Timor", region: "asia", flag: "/quiz/flags/east-timor.png" },
    { name: "Ecuador", region: "south-america", flag: "/quiz/flags/ecuador.png" },
    { name: "Egypt", region: "africa", flag: "/quiz/flags/egypt.webp" },
    { name: "El Salvador", region: "north-america", flag: "/quiz/flags/el-salvador.png" },
    { name: "Equatorial Guinea", region: "africa", flag: "/quiz/flags/equatorial-guinea.png" },
    { name: "Eritrea", region: "africa", flag: "/quiz/flags/eritrea.svg" },
    { name: "Estonia", region: "europe", flag: "/quiz/flags/estonia.png" },
    { name: "Eswatini", region: "africa", flag: "/quiz/flags/eswatini.png" },
    { name: "Ethiopia", region: "africa", flag: "/quiz/flags/ethiopia.webp" },
    { name: "Fiji", region: "oceania", flag: "/quiz/flags/fiji.svg" },
    { name: "Finland", region: "europe", flag: "/quiz/flags/finland.png" },
    { name: "France", region: "europe", flag: "/quiz/flags/france.webp" },
    { name: "Gabon", region: "africa", flag: "/quiz/flags/gabon.svg" },
    { name: "Gambia", region: "africa", flag: "/quiz/flags/gambia.png" },
    { name: "Georgia", region: "asia", flag: "/quiz/flags/georgia.png" },
    { name: "Germany", region: "europe", flag: "/quiz/flags/germany.webp" },
    { name: "Ghana", region: "africa", flag: "/quiz/flags/ghana.png" },
    { name: "Greece", region: "europe", flag: "/quiz/flags/greece.webp" },
    { name: "Grenada", region: "north-america", flag: "/quiz/flags/grenada.png" },
    { name: "Guatemala", region: "north-america", flag: "/quiz/flags/guatemala.svg" },
    { name: "Guinea", region: "africa", flag: "/quiz/flags/guinea.png" },
    { name: "Guinea-Bissau", region: "africa", flag: "/quiz/flags/guinea-bissau.png" },
    { name: "Guyana", region: "south-america", flag: "/quiz/flags/guyana.png" },
    { name: "Haiti", region: "north-america", flag: "/quiz/flags/haiti.png" },
    { name: "Honduras", region: "north-america", flag: "/quiz/flags/honduras.webp" },
    { name: "Hungary", region: "europe", flag: "/quiz/flags/hungary.png" },
    { name: "Iceland", region: "europe", flag: "/quiz/flags/iceland.png" },
    { name: "India", region: "asia", flag: "/quiz/flags/india.png" },
    { name: "Indonesia", region: "asia", flag: "/quiz/flags/indonesia.png" },
    { name: "Iran", region: "asia", flag: "/quiz/flags/iran.webp" },
    { name: "Iraq", region: "asia", flag: "/quiz/flags/iraq.webp" },
    { name: "Ireland", region: "europe", flag: "/quiz/flags/ireland.webp" },
    { name: "Israel", region: "asia", flag: "/quiz/flags/israel.webp" },
    { name: "Italy", region: "europe", flag: "/quiz/flags/italy.png" },
    { name: "Ivory Coast", region: "africa", flag: "/quiz/flags/ivory-coast.png" },
    { name: "Jamaica", region: "north-america", flag: "/quiz/flags/jamaica.png" },
    { name: "Japan", region: "asia", flag: "/quiz/flags/japan.png" },
    { name: "Jordan", region: "asia", flag: "/quiz/flags/jordan.png" },
    { name: "Kazakhstan", region: "asia", flag: "/quiz/flags/kazakhstan.png" },
    { name: "Kenya", region: "africa", flag: "/quiz/flags/kenya.svg" },
    { name: "Kiribati", region: "oceania", flag: "/quiz/flags/kiribati.png" },
    { name: "Kuwait", region: "asia", flag: "/quiz/flags/kuwait.png" },
    { name: "Kyrgyzstan", region: "asia", flag: "/quiz/flags/kyrgyzstan.png" },
    { name: "Laos", region: "asia", flag: "/quiz/flags/laos.png" },
    { name: "Latvia", region: "europe", flag: "/quiz/flags/latvia.png" },
    { name: "Lebanon", region: "asia", flag: "/quiz/flags/lebanon.webp" },
    { name: "Lesotho", region: "africa", flag: "/quiz/flags/lesotho.svg" },
    { name: "Liberia", region: "africa", flag: "/quiz/flags/liberia.webp" },
    { name: "Libya", region: "africa", flag: "/quiz/flags/libya.png" },
    { name: "Liechtenstein", region: "europe", flag: "/quiz/flags/liechtenstein.svg" },
    { name: "Lithuania", region: "europe", flag: "/quiz/flags/lithuania.webp" },
    { name: "Luxembourg", region: "europe", flag: "/quiz/flags/luxembourg.png" },
    { name: "Madagascar", region: "africa", flag: "/quiz/flags/madagascar.svg" },
    { name: "Malawi", region: "africa", flag: "/quiz/flags/malawi.png" },
    { name: "Malaysia", region: "asia", flag: "/quiz/flags/malaysia.svg" },
    { name: "Maldives", region: "asia", flag: "/quiz/flags/maldives.png" },
    { name: "Mali", region: "africa", flag: "/quiz/flags/mali.png" },
    { name: "Malta", region: "europe", flag: "/quiz/flags/malta.webp" },
    { name: "Marshall Islands", region: "oceania", flag: "/quiz/flags/marshall-islands.png" },
    { name: "Mauritania", region: "africa", flag: "/quiz/flags/mauritania.png" },
    { name: "Mauritius", region: "africa", flag: "/quiz/flags/mauritius.png" },
    { name: "Mexico", region: "north-america", flag: "/quiz/flags/mexico.png" },
    { name: "Micronesia", region: "oceania", flag: "/quiz/flags/micronesia.png" },
    { name: "Moldova", region: "europe", flag: "/quiz/flags/moldova.png" },
    { name: "Monaco", region: "europe", flag: "/quiz/flags/monaco.png" },
    { name: "Mongolia", region: "asia", flag: "/quiz/flags/mongolia.png" },
    { name: "Montenegro", region: "europe", flag: "/quiz/flags/montenegro.svg" },
    { name: "Morocco", region: "africa", flag: "/quiz/flags/morocco.png" },
    { name: "Mozambique", region: "africa", flag: "/quiz/flags/mozambique.png" },
    { name: "Myanmar", region: "asia", flag: "/quiz/flags/myanmar.png" },
    { name: "Namibia", region: "africa", flag: "/quiz/flags/namibia.svg" },
    { name: "Nauru", region: "oceania", flag: "/quiz/flags/nauru.png" },
    { name: "Nepal", region: "asia", flag: "/quiz/flags/nepal.webp" },
    { name: "Netherlands", region: "europe", flag: "/quiz/flags/netherlands.webp" },
    { name: "New Zealand", region: "oceania", flag: "/quiz/flags/new-zealand.png" },
    { name: "Nicaragua", region: "north-america", flag: "/quiz/flags/nicaragua.svg" },
    { name: "Niger", region: "africa", flag: "/quiz/flags/niger.png" },
    { name: "Nigeria", region: "africa", flag: "/quiz/flags/nigeria.png" },
    { name: "North Korea", region: "asia", flag: "/quiz/flags/north-korea.png" },
    { name: "North Macedonia", region: "europe", flag: "/quiz/flags/north-macedonia.png" },
    { name: "Norway", region: "europe", flag: "/quiz/flags/norway.webp" },
    { name: "Oman", region: "asia", flag: "/quiz/flags/oman.webp" },
    { name: "Pakistan", region: "asia", flag: "/quiz/flags/pakistan.svg" },
    { name: "Palau", region: "oceania", flag: "/quiz/flags/palau.png" },
    { name: "Palestine", region: "asia", flag: "/quiz/flags/palestine.png" },
    { name: "Panama", region: "north-america", flag: "/quiz/flags/panama.webp" },
    { name: "Papua New Guinea", region: "oceania", flag: "/quiz/flags/papua-new-guinea.png" },
    { name: "Paraguay", region: "south-america", flag: "/quiz/flags/paraguay.png" },
    { name: "Peru", region: "south-america", flag: "/quiz/flags/peru.png" },
    { name: "Philippines", region: "asia", flag: "/quiz/flags/philippines.svg" },
    { name: "Poland", region: "europe", flag: "/quiz/flags/poland.webp" },
    { name: "Portugal", region: "europe", flag: "/quiz/flags/portugal.png" },
    { name: "Qatar", region: "asia", flag: "/quiz/flags/qatar.jpg" },
    { name: "Romania", region: "europe", flag: "/quiz/flags/romania.webp" },
    { name: "Russia", region: "europe", flag: "/quiz/flags/russia.png" },
    { name: "Rwanda", region: "africa", flag: "/quiz/flags/rwanda.png" },
    { name: "Saint Kitts and Nevis", region: "north-america", flag: "/quiz/flags/saint-kitts-and-nevis.png" },
    { name: "Saint Lucia", region: "north-america", flag: "/quiz/flags/saint-lucia.png" },
    { name: "Saint Vincent and the Grenadines", region: "north-america", flag: "/quiz/flags/saint-vincent-and-the-grenadines.svg" },
    { name: "Samoa", region: "oceania", flag: "/quiz/flags/samoa.webp" },
    { name: "San Marino", region: "europe", flag: "/quiz/flags/san-marino.svg" },
    { name: "Sao Tome and Principe", region: "africa", flag: "/quiz/flags/sao-tome-and-principe.svg" },
    { name: "Saudi Arabia", region: "asia", flag: "/quiz/flags/saudi-arabia.webp" },
    { name: "Senegal", region: "africa", flag: "/quiz/flags/senegal.png" },
    { name: "Serbia", region: "europe", flag: "/quiz/flags/serbia.webp" },
    { name: "Seychelles", region: "africa", flag: "/quiz/flags/seychelles.png" },
    { name: "Sierra Leone", region: "africa", flag: "/quiz/flags/sierra-leone.webp" },
    { name: "Singapore", region: "asia", flag: "/quiz/flags/singapore.png" },
    { name: "Slovakia", region: "europe", flag: "/quiz/flags/slovakia.png" },
    { name: "Slovenia", region: "europe", flag: "/quiz/flags/slovenia.svg" },
    { name: "Solomon Islands", region: "oceania", flag: "/quiz/flags/solomon-islands.png" },
    { name: "Somalia", region: "africa", flag: "/quiz/flags/somalia.png" },
    { name: "South Africa", region: "africa", flag: "/quiz/flags/south-africa.png" },
    { name: "South Korea", region: "asia", flag: "/quiz/flags/south-korea.png" },
    { name: "South Sudan", region: "africa", flag: "/quiz/flags/south-sudan.png" },
    { name: "Spain", region: "europe", flag: "/quiz/flags/spain.svg" },
    { name: "Sri Lanka", region: "asia", flag: "/quiz/flags/sri-lanka.svg" },
    { name: "Sudan", region: "africa", flag: "/quiz/flags/sudan.webp" },
    { name: "Suriname", region: "south-america", flag: "/quiz/flags/suriname.png" },
    { name: "Sweden", region: "europe", flag: "/quiz/flags/sweden.png" },
    { name: "Switzerland", region: "europe", flag: "/quiz/flags/switzerland.webp" },
    { name: "Syria", region: "asia", flag: "/quiz/flags/syria.png" },
    { name: "Taiwan", region: "asia", flag: "/quiz/flags/taiwan.webp" },
    { name: "Tajikistan", region: "asia", flag: "/quiz/flags/tajikistan.png" },
    { name: "Tanzania", region: "africa", flag: "/quiz/flags/tanzania.png" },
    { name: "Thailand", region: "asia", flag: "/quiz/flags/thailand.svg" },
    { name: "Togo", region: "africa", flag: "/quiz/flags/togo.png" },
    { name: "Tonga", region: "oceania", flag: "/quiz/flags/tonga.png" },
    { name: "Trinidad and Tobago", region: "north-america", flag: "/quiz/flags/trinidad-and-tobago.png" },
    { name: "Tunisia", region: "africa", flag: "/quiz/flags/tunisia.png" },
    { name: "Turkey", region: "asia", flag: "/quiz/flags/turkey.png" },
    { name: "Turkmenistan", region: "asia", flag: "/quiz/flags/turkmenistan.svg" },
    { name: "Tuvalu", region: "oceania", flag: "/quiz/flags/tuvalu.png" },
    { name: "Uganda", region: "africa", flag: "/quiz/flags/uganda.svg" },
    { name: "Ukraine", region: "europe", flag: "/quiz/flags/ukraine.png" },
    { name: "United Arab Emirates", region: "asia", flag: "/quiz/flags/united-arab-emirates.png" },
    { name: "United Kingdom", region: "europe", flag: "/quiz/flags/united-kingdom.webp" },
    { name: "United States", region: "north-america", flag: "/quiz/flags/united-states.png" },
    { name: "Uruguay", region: "south-america", flag: "/quiz/flags/uruguay.png" },
    { name: "Uzbekistan", region: "asia", flag: "/quiz/flags/uzbekistan.png" },
    { name: "Vanuatu", region: "oceania", flag: "/quiz/flags/vanuatu.png" },
    { name: "Vatican City", region: "europe", flag: "/quiz/flags/vatican-city.png" },
    { name: "Venezuela", region: "south-america", flag: "/quiz/flags/venezuela.webp" },
    { name: "Vietnam", region: "asia", flag: "/quiz/flags/vietnam.png" },
    { name: "Yemen", region: "asia", flag: "/quiz/flags/yemen.png" },
    { name: "Zambia", region: "africa", flag: "/quiz/flags/zambia.png" },
    { name: "Zimbabwe", region: "africa", flag: "/quiz/flags/zimbabwe.webp" }
];
