const countries = [
    { name: "Afghanistan", region: "asia", flag: "/quiz/flags/afghanistan.png" },
    { name: "Albania", region: "europe", flag: "/quiz/flags/albania.png" },
    { name: "Algeria", region: "africa", flag: "/quiz/flags/algeria.webp" },
    { name: "Andorra", region: "europe", flag: "/quiz/flags/andorra.svg" },
    { name: "Angola", region: "africa", flag: "/quiz/flags/angola.png" },
    { name: "Antigua and Barbuda", region: "north-america", flag: "/quiz/flags/antigua-and-barbuda.svg" },
    { name: "Argentina", region: "south-america", flag: "/quiz/flags/argentina.png" },
    { name: "Armenia", region: "asia", flag: "/quiz/flags/armenia.svg" },
    { name: "Australia", region: "oceania", flag: "/quiz/flags/australia.svg" },
    { name: "Austria", region: "europe", flag: "/quiz/flags/austria.webp" },
    { name: "Azerbaijan", region: "asia", flag: "/quiz/flags/azerbaijan.png" },
    { name: "Bahamas", region: "north-america", flag: "/quiz/flags/bahamas.png" },
    { name: "Bahrain", region: "asia", flag: "/quiz/flags/bahrain.png" },
    { name: "Bangladesh", region: "asia", flag: "/quiz/flags/bangladesh.png" },
    { name: "Barbados", region: "north-america", flag: "/quiz/flags/barbados.png" },
    { name: "Belarus", region: "europe", flag: "/quiz/flags/belarus.svg" },
    { name: "Belgium", region: "europe", flag: "/quiz/flags/belgium.png" },
    { name: "Belize", region: "north-america", flag: "/quiz/flags/belize.png" },
    { name: "Benin", region: "africa", flag: "/quiz/flags/benin.png" },
    { name: "Bhutan", region: "asia", flag: "/quiz/flags/bhutan.png" },
    { name: "Bolivia", region: "south-america", flag: "/quiz/flags/bolivia.webp" },
    { name: "Bosnia and Herzegovina", region: "europe", flag: "/quiz/flags/bosnia-and-herzegovina.png" },
    { name: "Botswana", region: "africa", flag: "/quiz/flags/botswana.png" },
    { name: "Brazil", region: "south-america", flag: "/quiz/flags/brazil.png" },
    { name: "Brunei", region: "asia", flag: "/quiz/flags/brunei.png" },
    { name: "Bulgaria", region: "europe", flag: "/quiz/flags/bulgaria.webp" },
    { name: "Burkina Faso", region: "africa", flag: "/quiz/flags/burkina-faso.webp" },
    { name: "Burundi", region: "africa", flag: "/quiz/flags/burundi.png" },
    { name: "Cambodia", region: "asia", flag: "/quiz/flags/cambodia.png" },
    { name: "Cameroon", region: "africa", flag: "/quiz/flags/cameroon.png" },
    { name: "Canada", region: "north-america", flag: "/quiz/flags/canada.svg" },
    { name: "Cape Verde", region: "africa", flag: "/quiz/flags/cape-verde.png" },
    { name: "Central African Republic", region: "africa", flag: "/quiz/flags/central-african-republic.webp" },
    { name: "Chad", region: "africa", flag: "/quiz/flags/chad.png" },
    { name: "Chile", region: "south-america", flag: "/quiz/flags/chile.svg" },
    { name: "China", region: "asia", flag: "/quiz/flags/china.webp" },
    { name: "Colombia", region: "south-america", flag: "/quiz/flags/colombia.png" },
    { name: "Comoros", region: "africa", flag: "/quiz/flags/comoros.png" },
    { name: "Congo", region: "africa", flag: "/quiz/flags/congo.png" },
    { name: "Costa Rica", region: "north-america", flag: "/quiz/flags/costa-rica.png" },
    { name: "Croatia", region: "europe", flag: "/quiz/flags/croatia.png" },
    { name: "Cuba", region: "north-america", flag: "/quiz/flags/cuba.png" },
    { name: "Cyprus", region: "europe", flag: "/quiz/flags/cyprus.webp" },
    { name: "Czech Republic", region: "europe", flag: "/quiz/flags/czech-republic.webp" },
    { name: "Democratic Republic of the Congo", region: "africa", flag: "/quiz/flags/democratic-republic-of-the-congo.png" },
    { name: "Denmark", region: "europe", flag: "/quiz/flags/denmark.png" },
    { name: "Djibouti", region: "africa", flag: "/quiz/flags/djibouti.svg" },
    { name: "Dominica", region: "north-america", flag: "/quiz/flags/dominica.png" },
    { name: "Dominican Republic", region: "north-america", flag: "/quiz/flags/dominican-republic.png" },
    { name: "East Timor", region: "asia", flag: "/quiz/flags/east-timor.png" },
    { name: "Ecuador", region: "south-america", flag: "/quiz/flags/ecuador.png" },
    { name: "Egypt", region: "africa", flag: "/quiz/flags/egypt.webp" },
    { name: "El Salvador", region: "north-america", flag: "/quiz/flags/el-salvador.png" },
    { name: "Equatorial Guinea", region: "africa", flag: "/quiz/flags/equatorial-guinea.png" },
    { name: "Eritrea", region: "africa", flag: "/quiz/flags/eritrea.svg" },
    { name: "Estonia", region: "europe", flag: "/quiz/flags/estonia.png" },
    { name: "Eswatini", region: "africa", flag: "/quiz/flags/eswatini.png" },
    { name: "Ethiopia", region: "africa", flag: "/quiz/flags/ethiopia.webp" },
    { name: "Fiji", region: "oceania", flag: "/quiz/flags/fiji.svg" },
    { name: "Finland", region: "europe", flag: "/quiz/flags/finland.png" },
    { name: "France", region: "europe", flag: "/quiz/flags/france.webp" },
    { name: "Gabon", region: "africa", flag: "/quiz/flags/gabon.svg" },
    { name: "Gambia", region: "africa", flag: "/quiz/flags/gambia.png" },
    { name: "Georgia", region: "asia", flag: "/quiz/flags/georgia.png" },
    { name: "Germany", region: "europe", flag: "/quiz/flags/germany.webp" },
    { name: "Ghana", region: "africa", flag: "/quiz/flags/ghana.png" },
    { name: "Greece", region: "europe", flag: "/quiz/flags/greece.webp" },
    { name: "Grenada", region: "north-america", flag: "/quiz/flags/grenada.png" },
    { name: "Guatemala", region: "north-america", flag: "/quiz/flags/guatemala.svg" },
    { name: "Guinea", region: "africa", flag: "/quiz/flags/guinea.png" },
    { name: "Guinea-Bissau", region: "africa", flag: "/quiz/flags/guinea-bissau.png" },
    { name: "Guyana", region: "south-america", flag: "/quiz/flags/guyana.png" },
    { name: "Haiti", region: "north-america", flag: "/quiz/flags/haiti.png" },
    { name: "Honduras", region: "north-america", flag: "/quiz/flags/honduras.webp" },
    { name: "Hungary", region: "europe", flag: "/quiz/flags/hungary.png" },
    { name: "Iceland", region: "europe", flag: "/quiz/flags/iceland.png" },
    { name: "India", region: "asia", flag: "/quiz/flags/india.png" },
    { name: "Indonesia", region: "asia", flag: "/quiz/flags/indonesia.png" },
    { name: "Iran", region: "asia", flag: "/quiz/flags/iran.webp" },
    { name: "Iraq", region: "asia", flag: "/quiz/flags/iraq.webp" },
    { name: "Ireland", region: "europe", flag: "/quiz/flags/ireland.webp" },
    { name: "Israel", region: "asia", flag: "/quiz/flags/israel.webp" },
    { name: "Italy", region: "europe", flag: "/quiz/flags/italy.png" },
    { name: "Ivory Coast", region: "africa", flag: "/quiz/flags/ivory-coast.png" },
    { name: "Jamaica", region: "north-america", flag: "/quiz/flags/jamaica.png" },
    { name: "Japan", region: "asia", flag: "/quiz/flags/japan.png" },
    { name: "Jordan", region: "asia", flag: "/quiz/flags/jordan.png" },
    { name: "Kazakhstan", region: "asia", flag: "/quiz/flags/kazakhstan.png" },
    { name: "Kenya", region: "africa", flag: "/quiz/flags/kenya.svg" },
    { name: "Kiribati", region: "oceania", flag: "/quiz/flags/kiribati.png" },
    { name: "Kuwait", region: "asia", flag: "/quiz/flags/kuwait.png" },
    { name: "Kyrgyzstan", region: "asia", flag: "/quiz/flags/kyrgyzstan.png" },
    { name: "Laos", region: "asia", flag: "/quiz/flags/laos.png" },
    { name: "Latvia", region: "europe", flag: "/quiz/flags/latvia.png" },
    { name: "Lebanon", region: "asia", flag: "/quiz/flags/lebanon.webp" },
    { name: "Lesotho", region: "africa", flag: "/quiz/flags/lesotho.svg" },
    { name: "Liberia", region: "africa", flag: "/quiz/flags/liberia.webp" },
    { name: "Libya", region: "africa", flag: "/quiz/flags/libya.png" },
    { name: "Liechtenstein", region: "europe", flag: "/quiz/flags/liechtenstein.svg" },
    { name: "Lithuania", region: "europe", flag: "/quiz/flags/lithuania.webp" },
    { name: "Luxembourg", region: "europe", flag: "/quiz/flags/luxembourg.png" },
    { name: "Madagascar", region: "africa", flag: "/quiz/flags/madagascar.svg" },
    { name: "Malawi", region: "africa", flag: "/quiz/flags/malawi.png" },
    { name: "Malaysia", region: "asia", flag: "/quiz/flags/malaysia.svg" },
    { name: "Maldives", region: "asia", flag: "/quiz/flags/maldives.png" },
    { name: "Mali", region: "africa", flag: "/quiz/flags/mali.png" },
    { name: "Malta", region: "europe", flag: "/quiz/flags/malta.webp" },
    { name: "Marshall Islands", region: "oceania", flag: "/quiz/flags/marshall-islands.png" },
    { name: "Mauritania", region: "africa", flag: "/quiz/flags/mauritania.png" },
    { name: "Mauritius", region: "africa", flag: "/quiz/flags/mauritius.png" },
    { name: "Mexico", region: "north-america", flag: "/quiz/flags/mexico.png" },
    { name: "Micronesia", region: "oceania", flag: "/quiz/flags/micronesia.png" },
    { name: "Moldova", region: "europe", flag: "/quiz/flags/moldova.png" },
    { name: "Monaco", region: "europe", flag: "/quiz/flags/monaco.png" },
    { name: "Mongolia", region: "asia", flag: "/quiz/flags/mongolia.png" },
    { name: "Montenegro", region: "europe", flag: "/quiz/flags/montenegro.svg" },
    { name: "Morocco", region: "africa", flag: "/quiz/flags/morocco.png" },
    { name: "Mozambique", region: "africa", flag: "/quiz/flags/mozambique.png" },
    { name: "Myanmar", region: "asia", flag: "/quiz/flags/myanmar.png" },
    { name: "Namibia", region: "africa", flag: "/quiz/flags/namibia.svg" },
    { name: "Nauru", region: "oceania", flag: "/quiz/flags/nauru.png" },
    { name: "Nepal", region: "asia", flag: "/quiz/flags/nepal.webp" },
    { name: "Netherlands", region: "europe", flag: "/quiz/flags/netherlands.webp" },
    { name: "New Zealand", region: "oceania", flag: "/quiz/flags/new-zealand.png" },
    { name: "Nicaragua", region: "north-america", flag: "/quiz/flags/nicaragua.svg" },
    { name: "Niger", region: "africa", flag: "/quiz/flags/niger.png" },
    { name: "Nigeria", region: "africa", flag: "/quiz/flags/nigeria.png" },
    { name: "North Korea", region: "asia", flag: "/quiz/flags/north-korea.png" },
    { name: "North Macedonia", region: "europe", flag: "/quiz/flags/north-macedonia.png" },
    { name: "Norway", region: "europe", flag: "/quiz/flags/norway.webp" },
    { name: "Oman", region: "asia", flag: "/quiz/flags/oman.webp" },
    { name: "Pakistan", region: "asia", flag: "/quiz/flags/pakistan.svg" },
    { name: "Palau", region: "oceania", flag: "/quiz/flags/palau.png" },
    { name: "Palestine", region: "asia", flag: "/quiz/flags/palestine.png" },
    { name: "Panama", region: "north-america", flag: "/quiz/flags/panama.webp" },
    { name: "Papua New Guinea", region: "oceania", flag: "/quiz/flags/papua-new-guinea.png" },
    { name: "Paraguay", region: "south-america", flag: "/quiz/flags/paraguay.png" },
    { name: "Peru", region: "south-america", flag: "/quiz/flags/peru.png" },
    { name: "Philippines", region: "asia", flag: "/quiz/flags/philippines.svg" },
    { name: "Poland", region: "europe", flag: "/quiz/flags/poland.webp" },
    { name: "Portugal", region: "europe", flag: "/quiz/flags/portugal.png" },
    { name: "Qatar", region: "asia", flag: "/quiz/flags/qatar.jpg" },
    { name: "Romania", region: "europe", flag: "/quiz/flags/romania.webp" },
    { name: "Russia", region: "europe", flag: "/quiz/flags/russia.png" },
    { name: "Rwanda", region: "africa", flag: "/quiz/flags/rwanda.png" },
    { name: "Saint Kitts and Nevis", region: "north-america", flag: "/quiz/flags/saint-kitts-and-nevis.png" },
    { name: "Saint Lucia", region: "north-america", flag: "/quiz/flags/saint-lucia.png" },
    { name: "Saint Vincent and the Grenadines", region: "north-america", flag: "/quiz/flags/saint-vincent-and-the-grenadines.svg" },
    { name: "Samoa", region: "oceania", flag: "/quiz/flags/samoa.webp" },
    { name: "San Marino", region: "europe", flag: "/quiz/flags/san-marino.svg" },
    { name: "Sao Tome and Principe", region: "africa", flag: "/quiz/flags/sao-tome-and-principe.svg" },
    { name: "Saudi Arabia", region: "asia", flag: "/quiz/flags/saudi-arabia.webp" },
    { name: "Senegal", region: "africa", flag: "/quiz/flags/senegal.png" },
    { name: "Serbia", region: "europe", flag: "/quiz/flags/serbia.webp" },
    { name: "Seychelles", region: "africa", flag: "/quiz/flags/seychelles.png" },
    { name: "Sierra Leone", region: "africa", flag: "/quiz/flags/sierra-leone.webp" },
    { name: "Singapore", region: "asia", flag: "/quiz/flags/singapore.png" },
    { name: "Slovakia", region: "europe", flag: "/quiz/flags/slovakia.png" },
    { name: "Slovenia", region: "europe", flag: "/quiz/flags/slovenia.svg" },
    { name: "Solomon Islands", region: "oceania", flag: "/quiz/flags/solomon-islands.png" },
    { name: "Somalia", region: "africa", flag: "/quiz/flags/somalia.png" },
    { name: "South Africa", region: "africa", flag: "/quiz/flags/south-africa.png" },
    { name: "South Korea", region: "asia", flag: "/quiz/flags/south-korea.png" },
    { name: "South Sudan", region: "africa", flag: "/quiz/flags/south-sudan.png" },
    { name: "Spain", region: "europe", flag: "/quiz/flags/spain.svg" },
    { name: "Sri Lanka", region: "asia", flag: "/quiz/flags/sri-lanka.svg" },
    { name: "Sudan", region: "africa", flag: "/quiz/flags/sudan.webp" },
    { name: "Suriname", region: "south-america", flag: "/quiz/flags/suriname.png" },
    { name: "Sweden", region: "europe", flag: "/quiz/flags/sweden.png" },
    { name: "Switzerland", region: "europe", flag: "/quiz/flags/switzerland.webp" },
    { name: "Syria", region: "asia", flag: "/quiz/flags/syria.png" },
    { name: "Taiwan", region: "asia", flag: "/quiz/flags/taiwan.webp" },
    { name: "Tajikistan", region: "asia", flag: "/quiz/flags/tajikistan.png" },
    { name: "Tanzania", region: "africa", flag: "/quiz/flags/tanzania.png" },
    { name: "Thailand", region: "asia", flag: "/quiz/flags/thailand.svg" },
    { name: "Togo", region: "africa", flag: "/quiz/flags/togo.png" },
    { name: "Tonga", region: "oceania", flag: "/quiz/flags/tonga.png" },
    { name: "Trinidad and Tobago", region: "north-america", flag: "/quiz/flags/trinidad-and-tobago.png" },
    { name: "Tunisia", region: "africa", flag: "/quiz/flags/tunisia.png" },
    { name: "Turkey", region: "asia", flag: "/quiz/flags/turkey.png" },
    { name: "Turkmenistan", region: "asia", flag: "/quiz/flags/turkmenistan.svg" },
    { name: "Tuvalu", region: "oceania", flag: "/quiz/flags/tuvalu.png" },
    { name: "Uganda", region: "africa", flag: "/quiz/flags/uganda.svg" },
    { name: "Ukraine", region: "europe", flag: "/quiz/flags/ukraine.png" },
    { name: "United Arab Emirates", region: "asia", flag: "/quiz/flags/united-arab-emirates.png" },
    { name: "United Kingdom", region: "europe", flag: "/quiz/flags/united-kingdom.webp" },
    { name: "United States", region: "north-america", flag: "/quiz/flags/united-states.png" },
    { name: "Uruguay", region: "south-america", flag: "/quiz/flags/uruguay.png" },
    { name: "Uzbekistan", region: "asia", flag: "/quiz/flags/uzbekistan.png" },
    { name: "Vanuatu", region: "oceania", flag: "/quiz/flags/vanuatu.png" },
    { name: "Vatican City", region: "europe", flag: "/quiz/flags/vatican-city.png" },
    { name: "Venezuela", region: "south-america", flag: "/quiz/flags/venezuela.webp" },
    { name: "Vietnam", region: "asia", flag: "/quiz/flags/vietnam.png" },
    { name: "Yemen", region: "asia", flag: "/quiz/flags/yemen.png" },
    { name: "Zambia", region: "africa", flag: "/quiz/flags/zambia.png" },
    { name: "Zimbabwe", region: "africa", flag: "/quiz/flags/zimbabwe.webp" },
{ name: "Baden-Württemberg", region: "region", flag: "/quiz/flags/baden-wuerttemberg.svg" },
{ name: "Bavaria", region: "region", flag: "/quiz/flags/bavaria.svg" },
{ name: "Berlin", region: "region", flag: "/quiz/flags/berlin.png" },
{ name: "Brandenburg", region: "region", flag: "/quiz/flags/brandenburg.svg" },
{ name: "Bremen", region: "region", flag: "/quiz/flags/bremen.png" },
{ name: "Hamburg", region: "region", flag: "/quiz/flags/hamburg.svg" },
{ name: "Hesse", region: "region", flag: "/quiz/flags/hesse.png" },
{ name: "Lower Saxony", region: "region", flag: "/quiz/flags/lower-saxony.webp" },
{ name: "Mecklenburg-Vorpommern", region: "region", flag: "/quiz/flags/mecklenburg-vorpommern.svg" },
{ name: "North Rhine-Westphalia", region: "region", flag: "/quiz/flags/north-rhine-westphalia.png" },
{ name: "Rhineland-Palatinate", region: "region", flag: "/quiz/flags/rhineland-palatinate.svg" },
{ name: "Saarland", region: "region", flag: "/quiz/flags/saarland.png" },
{ name: "Saxony", region: "region", flag: "/quiz/flags/saxony.png" },
{ name: "Saxony-Anhalt", region: "region", flag: "/quiz/flags/saxony-anhalt.png" },
{ name: "Schleswig-Holstein", region: "region", flag: "/quiz/flags/schleswig-holstein.png" },
{ name: "Thuringia", region: "region", flag: "/quiz/flags/thuringia.png" },
{ name: "California", region: "region", flag: "/quiz/flags/california.webp" },
{ name: "Texas", region: "region", flag: "/quiz/flags/texas.svg" },
{ name: "New York", region: "region", flag: "/quiz/flags/new-york.webp" },
{ name: "Florida", region: "region", flag: "/quiz/flags/florida.png" },
{ name: "Alaska", region: "region", flag: "/quiz/flags/alaska.png" },
{ name: "Hawaii", region: "region", flag: "/quiz/flags/hawaii.svg" },
{ name: "England", region: "region", flag: "/quiz/flags/england.webp" },
{ name: "Scotland", region: "region", flag: "/quiz/flags/scotland.png" },
{ name: "Wales", region: "region", flag: "/quiz/flags/wales.svg" },
{ name: "Northern Ireland", region: "region", flag: "/quiz/flags/northern-ireland.webp" },
{ name: "Catalonia", region: "region", flag: "/quiz/flags/catalonia.png" },
{ name: "Basque Country", region: "region", flag: "/quiz/flags/basque-country.png" },
{ name: "Andalusia", region: "region", flag: "/quiz/flags/andalusia.svg" },
{ name: "Galicia", region: "region", flag: "/quiz/flags/galicia.png" },
{ name: "Quebec", region: "region", flag: "/quiz/flags/quebec.svg" },
{ name: "Greenland", region: "region", flag: "/quiz/flags/greenland.webp" },
{ name: "Hong Kong", region: "region", flag: "/quiz/flags/hong-kong.svg" },
{ name: "Macau", region: "region", flag: "/quiz/flags/macau.png" },
{ name: "Olympic", region: "region", flag: "/quiz/flags/olympic.png" },
{ name: "Faroe Islands", region: "region", flag: "/quiz/flags/faroe-islands.png" },
{ name: "European Union", region: "organization", flag: "/quiz/flags/eu.webp" },
{ name: "United Nations", region: "organization", flag: "/quiz/flags/un.webp" },
{ name: "NATO", region: "organization", flag: "/quiz/flags/nato.png" },
{ name: "African Union", region: "organization", flag: "/quiz/flags/african-union.png" },
{ name: "ASEAN", region: "organization", flag: "/quiz/flags/asean.svg" },
{ name: "Arab League", region: "organization", flag: "/quiz/flags/arab-league.png" },
{ name: "Organization of American States", region: "organization", flag: "/quiz/flags/oas.svg" },
{ name: "Commonwealth of Nations", region: "organization", flag: "/quiz/flags/commonwealth.svg" },
{ name: "Northern Cyprus", region: "special", flag: "/quiz/flags/northern-cyprus.svg" },
{ name: "Abkhazia", region: "special", flag: "/quiz/flags/abkhazia.png" },
{ name: "South Ossetia", region: "special", flag: "/quiz/flags/south-ossetia.png" },
{ name: "Transnistria", region: "special", flag: "/quiz/flags/transnistria.svg" },
{ name: "Nagorno-Karabakh", region: "special", flag: "/quiz/flags/nagorno-karabakh.png" },
{ name: "Tibet", region: "special", flag: "/quiz/flags/tibet.png" },
{ name: "Kurdistan", region: "special", flag: "/quiz/flags/kurdistan.webp" },
{ name: "Sami", region: "special", flag: "/quiz/flags/sami.svg" },
{ name: "Assyrian", region: "special", flag: "/quiz/flags/assyrian.png" },
{ name: "Roma", region: "special", flag: "/quiz/flags/roma.png" },
{ name: "Puerto Rico", region: "territory", flag: "/quiz/flags/puerto-rico.webp" },
{ name: "Guam", region: "territory", flag: "/quiz/flags/guam.svg" },
{ name: "American Samoa", region: "territory", flag: "/quiz/flags/american-samoa.svg" },
{ name: "Northern Mariana Islands", region: "territory", flag: "/quiz/flags/northern-mariana-islands.svg" },
{ name: "U.S. Virgin Islands", region: "territory", flag: "/quiz/flags/us-virgin-islands.png" },
{ name: "Bermuda", region: "territory", flag: "/quiz/flags/bermuda.png" },
{ name: "Cayman Islands", region: "territory", flag: "/quiz/flags/cayman-islands.svg" },
{ name: "Turks and Caicos Islands", region: "territory", flag: "/quiz/flags/turks-and-caicos.png" },
{ name: "British Virgin Islands", region: "territory", flag: "/quiz/flags/british-virgin-islands.svg" },
{ name: "Falkland Islands", region: "territory", flag: "/quiz/flags/falkland-islands.png" },
{ name: "Gibraltar", region: "territory", flag: "/quiz/flags/gibraltar.svg" },
{ name: "Montserrat", region: "territory", flag: "/quiz/flags/montserrat.png" },
{ name: "Anguilla", region: "territory", flag: "/quiz/flags/anguilla.png" },
{ name: "French Guiana", region: "territory", flag: "/quiz/flags/french-guiana.png" },
{ name: "Martinique", region: "territory", flag: "/quiz/flags/martinique.png" },
{ name: "Isle of Man", region: "territory", flag: "/quiz/flags/isle-of-man.png" },
{ name: "Réunion", region: "territory", flag: "/quiz/flags/reunion.png" },
{ name: "Mayotte", region: "territory", flag: "/quiz/flags/mayotte.png" },
{ name: "New Caledonia", region: "territory", flag: "/quiz/flags/new-caledonia.jpg" },
{ name: "French Polynesia", region: "territory", flag: "/quiz/flags/french-polynesia.svg" },
{ name: "Aruba", region: "territory", flag: "/quiz/flags/aruba.png" },
{ name: "Curaçao", region: "territory", flag: "/quiz/flags/curacao.png" },
{ name: "Sint Maarten", region: "territory", flag: "/quiz/flags/sint-maarten.png" },
{ name: "Bonaire", region: "territory", flag: "/quiz/flags/bonaire.png" },
{ name: "Sint Eustatius", region: "territory", flag: "/quiz/flags/sint-eustatius.svg" },
{ name: "Saba", region: "territory", flag: "/quiz/flags/saba.svg" },
{ name: "Åland Islands", region: "territory", flag: "/quiz/flags/aland.svg" },
{ name: "Cook Islands", region: "territory", flag: "/quiz/flags/cook-islands.svg" },
{ name: "Norfolk Island", region: "territory", flag: "/quiz/flags/norfolk-island.png" },
{ name: "Christmas Island", region: "territory", flag: "/quiz/flags/christmas-island.png" },
{ name: "Somaliland", region: "special", flag: "/quiz/flags/somaliland.png" },
{ name: "Alabama", region: "region", flag: "/quiz/flags/alabama.png" },
{ name: "Arizona", region: "region", flag: "/quiz/flags/arizona.svg" },
{ name: "Arkansas", region: "region", flag: "/quiz/flags/arkansas.png" },
{ name: "Colorado", region: "region", flag: "/quiz/flags/colorado.svg" },
{ name: "Connecticut", region: "region", flag: "/quiz/flags/connecticut.svg" },
{ name: "Delaware", region: "region", flag: "/quiz/flags/delaware.svg" },
{ name: "Georgia (US)", region: "region", flag: "/quiz/flags/georgia-us.png" },
{ name: "Idaho", region: "region", flag: "/quiz/flags/idaho.png" },
{ name: "Illinois", region: "region", flag: "/quiz/flags/illinois.svg" },
{ name: "Indiana", region: "region", flag: "/quiz/flags/indiana.svg" },
{ name: "Iowa", region: "region", flag: "/quiz/flags/iowa.png" },
{ name: "Kansas", region: "region", flag: "/quiz/flags/kansas.png" },
{ name: "Kentucky", region: "region", flag: "/quiz/flags/kentucky.png" },
{ name: "Louisiana", region: "region", flag: "/quiz/flags/louisiana.png" },
{ name: "Maine", region: "region", flag: "/quiz/flags/maine.png" },
{ name: "Maryland", region: "region", flag: "/quiz/flags/maryland.png" },
{ name: "Massachusetts", region: "region", flag: "/quiz/flags/massachusetts.svg" },
{ name: "Michigan", region: "region", flag: "/quiz/flags/michigan.png" },
{ name: "Minnesota", region: "region", flag: "/quiz/flags/minnesota.svg" },
{ name: "Mississippi", region: "region", flag: "/quiz/flags/mississippi.svg" },
{ name: "Missouri", region: "region", flag: "/quiz/flags/missouri.svg" },
{ name: "Montana", region: "region", flag: "/quiz/flags/montana.png" },
{ name: "Nebraska", region: "region", flag: "/quiz/flags/nebraska.svg" },
{ name: "Nevada", region: "region", flag: "/quiz/flags/nevada.png" },
{ name: "New Hampshire", region: "region", flag: "/quiz/flags/new-hampshire.svg" },
{ name: "New Jersey", region: "region", flag: "/quiz/flags/new-jersey.png" },
{ name: "New Mexico", region: "region", flag: "/quiz/flags/new-mexico.png" },
{ name: "North Carolina", region: "region", flag: "/quiz/flags/north-carolina.svg" },
{ name: "North Dakota", region: "region", flag: "/quiz/flags/north-dakota.svg" },
{ name: "Ohio", region: "region", flag: "/quiz/flags/ohio.webp" },
{ name: "Oklahoma", region: "region", flag: "/quiz/flags/oklahoma.png" },
{ name: "Oregon", region: "region", flag: "/quiz/flags/oregon.svg" },
{ name: "Pennsylvania", region: "region", flag: "/quiz/flags/pennsylvania.webp" },
{ name: "Rhode Island", region: "region", flag: "/quiz/flags/rhode-island.svg" },
{ name: "South Carolina", region: "region", flag: "/quiz/flags/south-carolina.png" },
{ name: "South Dakota", region: "region", flag: "/quiz/flags/south-dakota.svg" },
{ name: "Tennessee", region: "region", flag: "/quiz/flags/tennessee.svg" },
{ name: "Utah", region: "region", flag: "/quiz/flags/utah.png" },
{ name: "Vermont", region: "region", flag: "/quiz/flags/vermont.svg" },
{ name: "Virginia", region: "region", flag: "/quiz/flags/virginia.webp" },
{ name: "Washington", region: "region", flag: "/quiz/flags/washington.png" },
{ name: "West Virginia", region: "region", flag: "/quiz/flags/west-virginia.svg" },
{ name: "Wisconsin", region: "region", flag: "/quiz/flags/wisconsin.png" },
{ name: "Wyoming", region: "region", flag: "/quiz/flags/wyoming.png" },
{ name: "Chinese Taipei", region: "region", flag: "/quiz/flags/chinese-taipei.svg" },
{ name: "Burgenland", region: "region", flag: "/quiz/flags/burgenland.png" },
{ name: "Carinthia", region: "region", flag: "/quiz/flags/carinthia.png" },
{ name: "Lower Austria", region: "region", flag: "/quiz/flags/lower-austria.png" },
{ name: "Upper Austria", region: "region", flag: "/quiz/flags/upper-austria.png" },
{ name: "Salzburg", region: "region", flag: "/quiz/flags/salzburg.png" },
{ name: "Styria", region: "region", flag: "/quiz/flags/styria.png" },
{ name: "Tyrol", region: "region", flag: "/quiz/flags/tyrol.svg" },
{ name: "Vorarlberg", region: "region", flag: "/quiz/flags/vorarlberg.png" },
{ name: "Vienna", region: "region", flag: "/quiz/flags/vienna.png" },
{ name: "Aragon", region: "region", flag: "/quiz/flags/aragon.png" },
{ name: "Asturias", region: "region", flag: "/quiz/flags/asturias.svg" },
{ name: "Balearic Islands", region: "region", flag: "/quiz/flags/balearic-islands.svg" },
{ name: "Canary Islands", region: "region", flag: "/quiz/flags/canary-islands.png" },
{ name: "Cantabria", region: "region", flag: "/quiz/flags/cantabria.svg" },
{ name: "Castile and León", region: "region", flag: "/quiz/flags/castile-leon.svg" },
{ name: "Castile-La Mancha", region: "region", flag: "/quiz/flags/castile-la-mancha.svg" },
{ name: "Extremadura", region: "region", flag: "/quiz/flags/extremadura.svg" },
{ name: "La Rioja", region: "region", flag: "/quiz/flags/la-rioja.png" },
{ name: "Madrid", region: "region", flag: "/quiz/flags/madrid.svg" },
{ name: "Murcia", region: "region", flag: "/quiz/flags/murcia.png" },
{ name: "Navarre", region: "region", flag: "/quiz/flags/navarre.svg" },
{ name: "Valencia", region: "region", flag: "/quiz/flags/valencia.png" },
{ name: "Ceuta", region: "region", flag: "/quiz/flags/ceuta.svg" },
{ name: "Melilla", region: "region", flag: "/quiz/flags/melilla.png" },
{ name: "Alberta", region: "region", flag: "/quiz/flags/alberta.svg" },
{ name: "British Columbia", region: "region", flag: "/quiz/flags/british-columbia.png" },
{ name: "Manitoba", region: "region", flag: "/quiz/flags/manitoba.svg" },
{ name: "New Brunswick", region: "region", flag: "/quiz/flags/new-brunswick.png" },
{ name: "Newfoundland and Labrador", region: "region", flag: "/quiz/flags/newfoundland-labrador.svg" },
{ name: "Nova Scotia", region: "region", flag: "/quiz/flags/nova-scotia.svg" },
{ name: "Ontario", region: "region", flag: "/quiz/flags/ontario.png" },
{ name: "Prince Edward Island", region: "region", flag: "/quiz/flags/prince-edward-island.svg" },
{ name: "Saskatchewan", region: "region", flag: "/quiz/flags/saskatchewan.svg" },
{ name: "Northwest Territories", region: "region", flag: "/quiz/flags/northwest-territories.svg" },
{ name: "Nunavut", region: "region", flag: "/quiz/flags/nunavut.svg" },
{ name: "Yukon", region: "region", flag: "/quiz/flags/yukon.svg" },
{ name: "Auvergne-Rhône-Alpes", region: "region", flag: "/quiz/flags/auvergne-rhone-alpes.png" },
{ name: "Bourgogne-Franche-Comté", region: "region", flag: "/quiz/flags/bourgogne-franche-comte.png" },
{ name: "Brittany", region: "region", flag: "/quiz/flags/brittany.png" },
{ name: "Centre-Val de Loire", region: "region", flag: "/quiz/flags/centre-val-de-loire.png" },
{ name: "Corsica", region: "region", flag: "/quiz/flags/corsica.png" },
{ name: "Grand Est", region: "region", flag: "/quiz/flags/grand-est.png" },
{ name: "Hauts-de-France", region: "region", flag: "/quiz/flags/hauts-de-france.png" },
{ name: "Île-de-France", region: "region", flag: "/quiz/flags/ile-de-france.png" },
{ name: "Normandy", region: "region", flag: "/quiz/flags/normandy.png" },
{ name: "Nouvelle-Aquitaine", region: "region", flag: "/quiz/flags/nouvelle-aquitaine.png" },
{ name: "Occitanie", region: "region", flag: "/quiz/flags/occitanie.png" },
{ name: "Pays de la Loire", region: "region", flag: "/quiz/flags/pays-de-la-loire.png" },
{ name: "Provence-Alpes-Côte d'Azur", region: "region", flag: "/quiz/flags/provence-alpes-cote-dazur.png" },
{ name: "Hokkaido", region: "region", flag: "/quiz/flags/hokkaido.svg" },
{ name: "Aomori", region: "region", flag: "/quiz/flags/aomori.png" },
{ name: "Iwate", region: "region", flag: "/quiz/flags/iwate.svg" },
{ name: "Miyagi", region: "region", flag: "/quiz/flags/miyagi.svg" },
{ name: "Akita", region: "region", flag: "/quiz/flags/akita.png" },
{ name: "Yamagata", region: "region", flag: "/quiz/flags/yamagata.png" },
{ name: "Fukushima", region: "region", flag: "/quiz/flags/fukushima.png" },
{ name: "Ibaraki", region: "region", flag: "/quiz/flags/ibaraki.svg" },
{ name: "Tochigi", region: "region", flag: "/quiz/flags/tochigi.png" },
{ name: "Gunma", region: "region", flag: "/quiz/flags/gunma.png" },
{ name: "Saitama", region: "region", flag: "/quiz/flags/saitama.png" },
{ name: "Chiba", region: "region", flag: "/quiz/flags/chiba.png" },
{ name: "Tokyo", region: "region", flag: "/quiz/flags/tokyo.png" },
{ name: "Kanagawa", region: "region", flag: "/quiz/flags/kanagawa.png" },
{ name: "Niigata", region: "region", flag: "/quiz/flags/niigata.png" },
{ name: "Toyama", region: "region", flag: "/quiz/flags/toyama.png" },
{ name: "Ishikawa", region: "region", flag: "/quiz/flags/ishikawa.png" },
{ name: "Fukui", region: "region", flag: "/quiz/flags/fukui.png" },
{ name: "Yamanashi", region: "region", flag: "/quiz/flags/yamanashi.png" },
{ name: "Nagano", region: "region", flag: "/quiz/flags/nagano.png" },
{ name: "Gifu", region: "region", flag: "/quiz/flags/gifu.png" },
{ name: "Shizuoka", region: "region", flag: "/quiz/flags/shizuoka.png" },
{ name: "Aichi", region: "region", flag: "/quiz/flags/aichi.svg" },
{ name: "Mie", region: "region", flag: "/quiz/flags/mie.png" },
{ name: "Shiga", region: "region", flag: "/quiz/flags/shiga.png" },
{ name: "Kyoto", region: "region", flag: "/quiz/flags/kyoto.png" },
{ name: "Osaka", region: "region", flag: "/quiz/flags/osaka.png" },
{ name: "Hyogo", region: "region", flag: "/quiz/flags/hyogo.png" },
{ name: "Nara", region: "region", flag: "/quiz/flags/nara.png" },
{ name: "Wakayama", region: "region", flag: "/quiz/flags/wakayama.png" },
{ name: "Tottori", region: "region", flag: "/quiz/flags/tottori.png" },
{ name: "Shimane", region: "region", flag: "/quiz/flags/shimane.png" },
{ name: "Okayama", region: "region", flag: "/quiz/flags/okayama.svg" },
{ name: "Hiroshima", region: "region", flag: "/quiz/flags/hiroshima.svg" },
{ name: "Yamaguchi", region: "region", flag: "/quiz/flags/yamaguchi.png" },
{ name: "Tokushima", region: "region", flag: "/quiz/flags/tokushima.png" },
{ name: "Kagawa", region: "region", flag: "/quiz/flags/kagawa.png" },
{ name: "Ehime", region: "region", flag: "/quiz/flags/ehime.png" },
{ name: "Kochi", region: "region", flag: "/quiz/flags/kochi.png" },
{ name: "Fukuoka", region: "region", flag: "/quiz/flags/fukuoka.png" },
{ name: "Saga", region: "region", flag: "/quiz/flags/saga.png" },
{ name: "Nagasaki", region: "region", flag: "/quiz/flags/nagasaki.png" },
{ name: "Kumamoto", region: "region", flag: "/quiz/flags/kumamoto.png" },
{ name: "Oita", region: "region", flag: "/quiz/flags/oita.png" },
{ name: "Miyazaki", region: "region", flag: "/quiz/flags/miyazaki.png" },
{ name: "Kagoshima", region: "region", flag: "/quiz/flags/kagoshima.svg" },
{ name: "Okinawa", region: "region", flag: "/quiz/flags/okinawa.svg" },
];
