const countriesTLD = [
    { name: "Afghanistan", de: "Afghanistan", region: "asia", tld: ".af" },
    { name: "Albania", de: "Albanien", region: "europe", tld: ".al" },
    { name: "Algeria", de: "Algerien", region: "africa", tld: ".dz" },
    { name: "Andorra", de: "Andorra", region: "europe", tld: ".ad" },
    { name: "Angola", de: "Angola", region: "africa", tld: ".ao" },
    { name: "Antigua and Barbuda", de: "Antigua und Barbuda", region: "north-america", tld: ".ag", aliases: ["antigua"] },
    { name: "Argentina", de: "Argentinien", region: "south-america", tld: ".ar" },
    { name: "Armenia", de: "Armenien", region: "asia", tld: ".am" },
    { name: "Australia", de: "Australien", region: "oceania", tld: ".au", aliases: ["aus"] },
    { name: "Austria", de: "Österreich", region: "europe", tld: ".at", aliases: ["oesterreich"] },
    { name: "Azerbaijan", de: "Aserbaidschan", region: "asia", tld: ".az" },
    { name: "Bahamas", de: "Bahamas", region: "north-america", tld: ".bs", aliases: ["the bahamas"] },
    { name: "Bahrain", de: "Bahrain", region: "asia", tld: ".bh" },
    { name: "Bangladesh", de: "Bangladesch", region: "asia", tld: ".bd" },
    { name: "Barbados", de: "Barbados", region: "north-america", tld: ".bb" },
    { name: "Belarus", de: "Weißrussland", region: "europe", tld: ".by", aliases: ["weissrussland", "byelorussia"] },
    { name: "Belgium", de: "Belgien", region: "europe", tld: ".be" },
    { name: "Belize", de: "Belize", region: "north-america", tld: ".bz" },
    { name: "Benin", de: "Benin", region: "africa", tld: ".bj" },
    { name: "Bhutan", de: "Bhutan", region: "asia", tld: ".bt" },
    { name: "Bolivia", de: "Bolivien", region: "south-america", tld: ".bo" },
    { name: "Bosnia and Herzegovina", de: "Bosnien und Herzegowina", region: "europe", tld: ".ba", aliases: ["bosnia", "bosnien", "bih", "bosnia & herzegovina"] },
    { name: "Botswana", de: "Botswana", region: "africa", tld: ".bw" },
    { name: "Brazil", de: "Brasilien", region: "south-america", tld: ".br", aliases: ["brasil"] },
    { name: "Brunei", de: "Brunei", region: "asia", tld: ".bn", aliases: ["brunei darussalam"] },
    { name: "Bulgaria", de: "Bulgarien", region: "europe", tld: ".bg" },
    { name: "Burkina Faso", de: "Burkina Faso", region: "africa", tld: ".bf" },
    { name: "Burundi", de: "Burundi", region: "africa", tld: ".bi" },
    { name: "Cambodia", de: "Kambodscha", region: "asia", tld: ".kh" },
    { name: "Cameroon", de: "Kamerun", region: "africa", tld: ".cm" },
    { name: "Canada", de: "Kanada", region: "north-america", tld: ".ca", aliases: ["can"] },
    { name: "Cape Verde", de: "Kap Verde", region: "africa", tld: ".cv", aliases: ["cabo verde"] },
    { name: "Central African Republic", de: "Zentralafrikanische Republik", region: "africa", tld: ".cf", aliases: ["car", "zar"] },
    { name: "Chad", de: "Tschad", region: "africa", tld: ".td" },
    { name: "Chile", de: "Chile", region: "south-america", tld: ".cl" },
    { name: "China", de: "China", region: "asia", tld: ".cn", aliases: ["prc", "volksrepublik china", "people's republic of china"] },
    { name: "Colombia", de: "Kolumbien", region: "south-america", tld: ".co" },
    { name: "Comoros", de: "Komoren", region: "africa", tld: ".km" },
    { name: "Congo", de: "Kongo", region: "africa", tld: ".cg", aliases: ["republic of the congo", "republic of congo"] },
    { name: "Costa Rica", de: "Costa Rica", region: "north-america", tld: ".cr" },
    { name: "Croatia", de: "Kroatien", region: "europe", tld: ".hr" },
    { name: "Cuba", de: "Kuba", region: "north-america", tld: ".cu" },
    { name: "Cyprus", de: "Zypern", region: "europe", tld: ".cy" },
    { name: "Czech Republic", de: "Tschechien", region: "europe", tld: ".cz", aliases: ["czechia", "tschechische republik"] },
    { name: "Democratic Republic of the Congo", de: "Demokratische Republik Kongo", region: "africa", tld: ".cd", aliases: ["dr congo", "drc", "dr. congo", "demokratische republik kongo"] },
    { name: "Denmark", de: "Dänemark", region: "europe", tld: ".dk", aliases: ["danemark"] },
    { name: "Djibouti", de: "Dschibuti", region: "africa", tld: ".dj" },
    { name: "Dominica", de: "Dominica", region: "north-america", tld: ".dm" },
    { name: "Dominican Republic", de: "Dominikanische Republik", region: "north-america", tld: ".do", aliases: ["dom. rep.", "dom rep"] },
    { name: "East Timor", de: "Osttimor", region: "asia", tld: ".tl", aliases: ["timor-leste", "timor leste"] },
    { name: "Ecuador", de: "Ecuador", region: "south-america", tld: ".ec" },
    { name: "Egypt", de: "Ägypten", region: "africa", tld: ".eg", aliases: ["agypten"] },
    { name: "El Salvador", de: "El Salvador", region: "north-america", tld: ".sv", aliases: ["salvador"] },
    { name: "Equatorial Guinea", de: "Äquatorialguinea", region: "africa", tld: ".gq", aliases: ["aquatorialguinea"] },
    { name: "Eritrea", de: "Eritrea", region: "africa", tld: ".er" },
    { name: "Estonia", de: "Estland", region: "europe", tld: ".ee" },
    { name: "Eswatini", de: "Eswatini", region: "africa", tld: ".sz", aliases: ["swaziland"] },
    { name: "Ethiopia", de: "Äthiopien", region: "africa", tld: ".et", aliases: ["athiopien"] },
    { name: "Fiji", de: "Fidschi", region: "oceania", tld: ".fj" },
    { name: "Finland", de: "Finnland", region: "europe", tld: ".fi", aliases: ["fin"] },
    { name: "France", de: "Frankreich", region: "europe", tld: ".fr", aliases: ["fra"] },
    { name: "Gabon", de: "Gabun", region: "africa", tld: ".ga" },
    { name: "Gambia", de: "Gambia", region: "africa", tld: ".gm", aliases: ["the gambia"] },
    { name: "Georgia", de: "Georgien", region: "asia", tld: ".ge" },
    { name: "Germany", de: "Deutschland", region: "europe", tld: ".de", aliases: ["ger", "deu"] },
    { name: "Ghana", de: "Ghana", region: "africa", tld: ".gh" },
    { name: "Greece", de: "Griechenland", region: "europe", tld: ".gr", aliases: ["hellas"] },
    { name: "Grenada", de: "Grenada", region: "north-america", tld: ".gd" },
    { name: "Guatemala", de: "Guatemala", region: "north-america", tld: ".gt" },
    { name: "Guinea", de: "Guinea", region: "africa", tld: ".gn" },
    { name: "Guinea-Bissau", de: "Guinea-Bissau", region: "africa", tld: ".gw" },
    { name: "Guyana", de: "Guyana", region: "south-america", tld: ".gy" },
    { name: "Haiti", de: "Haiti", region: "north-america", tld: ".ht" },
    { name: "Honduras", de: "Honduras", region: "north-america", tld: ".hn" },
    { name: "Hungary", de: "Ungarn", region: "europe", tld: ".hu" },
    { name: "Iceland", de: "Island", region: "europe", tld: ".is" },
    { name: "India", de: "Indien", region: "asia", tld: ".in", aliases: ["ind"] },
    { name: "Indonesia", de: "Indonesien", region: "asia", tld: ".id" },
    { name: "Iran", de: "Iran", region: "asia", tld: ".ir" },
    { name: "Iraq", de: "Irak", region: "asia", tld: ".iq" },
    { name: "Ireland", de: "Irland", region: "europe", tld: ".ie", aliases: ["eire", "éire", "republic of ireland"] },
    { name: "Israel", de: "Israel", region: "asia", tld: ".il" },
    { name: "Italy", de: "Italien", region: "europe", tld: ".it", aliases: ["ita"] },
    { name: "Ivory Coast", de: "Elfenbeinküste", region: "africa", tld: ".ci", aliases: ["cote d'ivoire", "côte d'ivoire", "elfenbeinkuste"] },
    { name: "Jamaica", de: "Jamaika", region: "north-america", tld: ".jm" },
    { name: "Japan", de: "Japan", region: "asia", tld: ".jp", aliases: ["jpn"] },
    { name: "Jordan", de: "Jordanien", region: "asia", tld: ".jo" },
    { name: "Kazakhstan", de: "Kasachstan", region: "asia", tld: ".kz" },
    { name: "Kenya", de: "Kenia", region: "africa", tld: ".ke" },
    { name: "Kiribati", de: "Kiribati", region: "oceania", tld: ".ki" },
    { name: "Kuwait", de: "Kuwait", region: "asia", tld: ".kw" },
    { name: "Kyrgyzstan", de: "Kirgisistan", region: "asia", tld: ".kg", aliases: ["kyrgyz republic", "kirgisien"] },
    { name: "Laos", de: "Laos", region: "asia", tld: ".la" },
    { name: "Latvia", de: "Lettland", region: "europe", tld: ".lv" },
    { name: "Lebanon", de: "Libanon", region: "asia", tld: ".lb" },
    { name: "Lesotho", de: "Lesotho", region: "africa", tld: ".ls" },
    { name: "Liberia", de: "Liberia", region: "africa", tld: ".lr" },
    { name: "Libya", de: "Libyen", region: "africa", tld: ".ly" },
    { name: "Liechtenstein", de: "Liechtenstein", region: "europe", tld: ".li" },
    { name: "Lithuania", de: "Litauen", region: "europe", tld: ".lt" },
    { name: "Luxembourg", de: "Luxemburg", region: "europe", tld: ".lu", aliases: ["lux"] },
    { name: "Madagascar", de: "Madagaskar", region: "africa", tld: ".mg" },
    { name: "Malawi", de: "Malawi", region: "africa", tld: ".mw" },
    { name: "Malaysia", de: "Malaysia", region: "asia", tld: ".my" },
    { name: "Maldives", de: "Malediven", region: "asia", tld: ".mv" },
    { name: "Mali", de: "Mali", region: "africa", tld: ".ml" },
    { name: "Malta", de: "Malta", region: "europe", tld: ".mt" },
    { name: "Marshall Islands", de: "Marshallinseln", region: "oceania", tld: ".mh", aliases: ["marshall"] },
    { name: "Mauritania", de: "Mauretanien", region: "africa", tld: ".mr" },
    { name: "Mauritius", de: "Mauritius", region: "africa", tld: ".mu" },
    { name: "Mexico", de: "Mexiko", region: "north-america", tld: ".mx", aliases: ["mex"] },
    { name: "Micronesia", de: "Mikronesien", region: "oceania", tld: ".fm", aliases: ["fsm", "federated states of micronesia"] },
    { name: "Moldova", de: "Moldau", region: "europe", tld: ".md", aliases: ["republic of moldova", "moldavia"] },
    { name: "Monaco", de: "Monaco", region: "europe", tld: ".mc" },
    { name: "Mongolia", de: "Mongolei", region: "asia", tld: ".mn" },
    { name: "Montenegro", de: "Montenegro", region: "europe", tld: ".me" },
    { name: "Morocco", de: "Marokko", region: "africa", tld: ".ma" },
    { name: "Mozambique", de: "Mosambik", region: "africa", tld: ".mz" },
    { name: "Myanmar", de: "Myanmar", region: "asia", tld: ".mm", aliases: ["burma"] },
    { name: "Namibia", de: "Namibia", region: "africa", tld: ".na" },
    { name: "Nauru", de: "Nauru", region: "oceania", tld: ".nr" },
    { name: "Nepal", de: "Nepal", region: "asia", tld: ".np" },
    { name: "Netherlands", de: "Niederlande", region: "europe", tld: ".nl", aliases: ["holland", "the netherlands"] },
    { name: "New Zealand", de: "Neuseeland", region: "oceania", tld: ".nz", aliases: ["nz", "aotearoa"] },
    { name: "Nicaragua", de: "Nicaragua", region: "north-america", tld: ".ni" },
    { name: "Niger", de: "Niger", region: "africa", tld: ".ne" },
    { name: "Nigeria", de: "Nigeria", region: "africa", tld: ".ng" },
    { name: "North Korea", de: "Nordkorea", region: "asia", tld: ".kp", aliases: ["dprk", "korea north"] },
    { name: "North Macedonia", de: "Nordmazedonien", region: "europe", tld: ".mk", aliases: ["macedonia", "mazedonien", "mkd"] },
    { name: "Norway", de: "Norwegen", region: "europe", tld: ".no", aliases: ["nor"] },
    { name: "Oman", de: "Oman", region: "asia", tld: ".om" },
    { name: "Pakistan", de: "Pakistan", region: "asia", tld: ".pk", aliases: ["pak"] },
    { name: "Palau", de: "Palau", region: "oceania", tld: ".pw" },
    { name: "Panama", de: "Panama", region: "north-america", tld: ".pa" },
    { name: "Papua New Guinea", de: "Papua-Neuguinea", region: "oceania", tld: ".pg", aliases: ["png", "papua"] },
    { name: "Paraguay", de: "Paraguay", region: "south-america", tld: ".py" },
    { name: "Peru", de: "Peru", region: "south-america", tld: ".pe" },
    { name: "Philippines", de: "Philippinen", region: "asia", tld: ".ph", aliases: ["the philippines"] },
    { name: "Poland", de: "Polen", region: "europe", tld: ".pl", aliases: ["pol"] },
    { name: "Portugal", de: "Portugal", region: "europe", tld: ".pt", aliases: ["por"] },
    { name: "Qatar", de: "Katar", region: "asia", tld: ".qa" },
    { name: "Romania", de: "Rumänien", region: "europe", tld: ".ro", aliases: ["rumanien"] },
    { name: "Russia", de: "Russland", region: "europe", tld: ".ru", aliases: ["rus", "russian federation", "russische foderation", "russische föderation"] },
    { name: "Rwanda", de: "Ruanda", region: "africa", tld: ".rw" },
    { name: "Saint Kitts and Nevis", de: "St. Kitts und Nevis", region: "north-america", tld: ".kn", aliases: ["st kitts", "st. kitts"] },
    { name: "Saint Lucia", de: "St. Lucia", region: "north-america", tld: ".lc", aliases: ["st lucia"] },
    { name: "Saint Vincent and the Grenadines", de: "St. Vincent und die Grenadinen", region: "north-america", tld: ".vc", aliases: ["st vincent", "st. vincent", "svg"] },
    { name: "Samoa", de: "Samoa", region: "oceania", tld: ".ws", aliases: ["western samoa"] },
    { name: "San Marino", de: "San Marino", region: "europe", tld: ".sm" },
    { name: "Saudi Arabia", de: "Saudi-Arabien", region: "asia", tld: ".sa", aliases: ["ksa", "saudi"] },
    { name: "Senegal", de: "Senegal", region: "africa", tld: ".sn" },
    { name: "Serbia", de: "Serbien", region: "europe", tld: ".rs" },
    { name: "Seychelles", de: "Seychellen", region: "africa", tld: ".sc" },
    { name: "Sierra Leone", de: "Sierra Leone", region: "africa", tld: ".sl" },
    { name: "Singapore", de: "Singapur", region: "asia", tld: ".sg" },
    { name: "Slovakia", de: "Slowakei", region: "europe", tld: ".sk" },
    { name: "Slovenia", de: "Slowenien", region: "europe", tld: ".si" },
    { name: "Solomon Islands", de: "Salomonen", region: "oceania", tld: ".sb", aliases: ["solomons"] },
    { name: "Somalia", de: "Somalia", region: "africa", tld: ".so" },
    { name: "South Africa", de: "Südafrika", region: "africa", tld: ".za", aliases: ["rsa", "sudafrika"] },
    { name: "South Korea", de: "Südkorea", region: "asia", tld: ".kr", aliases: ["korea", "kor", "republic of korea", "rok", "sudkorea"] },
    { name: "South Sudan", de: "Südsudan", region: "africa", tld: ".ss", aliases: ["sudsudan"] },
    { name: "Spain", de: "Spanien", region: "europe", tld: ".es", aliases: ["esp"] },
    { name: "Sri Lanka", de: "Sri Lanka", region: "asia", tld: ".lk", aliases: ["ceylon"] },
    { name: "Sudan", de: "Sudan", region: "africa", tld: ".sd" },
    { name: "Suriname", de: "Suriname", region: "south-america", tld: ".sr", aliases: ["surinam"] },
    { name: "Sweden", de: "Schweden", region: "europe", tld: ".se", aliases: ["swe"] },
    { name: "Switzerland", de: "Schweiz", region: "europe", tld: ".ch", aliases: ["sui", "che"] },
    { name: "Syria", de: "Syrien", region: "asia", tld: ".sy" },
    { name: "São Tomé and Príncipe", de: "São Tomé und Príncipe", region: "africa", tld: ".st", aliases: ["sao tome", "são tomé"] },
    { name: "Taiwan", de: "Taiwan", region: "asia", tld: ".tw", aliases: ["roc", "republic of china", "chinese taipei"] },
    { name: "Tajikistan", de: "Tadschikistan", region: "asia", tld: ".tj" },
    { name: "Tanzania", de: "Tansania", region: "africa", tld: ".tz" },
    { name: "Thailand", de: "Thailand", region: "asia", tld: ".th", aliases: ["tha"] },
    { name: "Togo", de: "Togo", region: "africa", tld: ".tg" },
    { name: "Tonga", de: "Tonga", region: "oceania", tld: ".to" },
    { name: "Trinidad and Tobago", de: "Trinidad und Tobago", region: "north-america", tld: ".tt", aliases: ["trinidad", "t&t"] },
    { name: "Tunisia", de: "Tunesien", region: "africa", tld: ".tn" },
    { name: "Turkey", de: "Türkei", region: "asia", tld: ".tr", aliases: ["turkiye", "türkiye", "tur", "turkei"] },
    { name: "Turkmenistan", de: "Turkmenistan", region: "asia", tld: ".tm" },
    { name: "Tuvalu", de: "Tuvalu", region: "oceania", tld: ".tv" },
    { name: "Uganda", de: "Uganda", region: "africa", tld: ".ug" },
    { name: "Ukraine", de: "Ukraine", region: "europe", tld: ".ua", aliases: ["ukr"] },
    { name: "United Arab Emirates", de: "Vereinigte Arabische Emirate", region: "asia", tld: ".ae", aliases: ["uae", "emirates", "vae"] },
    { name: "United Kingdom", de: "Vereinigtes Königreich", region: "europe", tld: ".uk", aliases: ["uk", "gb", "great britain", "britain", "england", "grossbritannien"] },
    { name: "United States", de: "Vereinigte Staaten", region: "north-america", tld: ".us", aliases: ["usa", "us", "america", "united states of america"] },
    { name: "Uruguay", de: "Uruguay", region: "south-america", tld: ".uy" },
    { name: "Uzbekistan", de: "Usbekistan", region: "asia", tld: ".uz" },
    { name: "Vanuatu", de: "Vanuatu", region: "oceania", tld: ".vu" },
    { name: "Vatican City", de: "Vatikanstadt", region: "europe", tld: ".va", aliases: ["vatican", "holy see", "heiliger stuhl"] },
    { name: "Venezuela", de: "Venezuela", region: "south-america", tld: ".ve" },
    { name: "Vietnam", de: "Vietnam", region: "asia", tld: ".vn", aliases: ["viet nam"] },
    { name: "Yemen", de: "Jemen", region: "asia", tld: ".ye" },
    { name: "Zambia", de: "Sambia", region: "africa", tld: ".zm" },
    { name: "Zimbabwe", de: "Simbabwe", region: "africa", tld: ".zw" },
];