const countriesTLD = [
    { name: "Afghanistan", region: "asia", tld: ".af" },
    { name: "Albania", region: "europe", tld: ".al" },
    { name: "Algeria", region: "africa", tld: ".dz" },
    { name: "Andorra", region: "europe", tld: ".ad" },
    { name: "Angola", region: "africa", tld: ".ao" },
    { name: "Antigua and Barbuda", region: "north-america", tld: ".ag" },
    { name: "Argentina", region: "south-america", tld: ".ar" },
    { name: "Armenia", region: "asia", tld: ".am" },
    { name: "Australia", region: "oceania", tld: ".au" },
    { name: "Austria", region: "europe", tld: ".at" },
    { name: "Azerbaijan", region: "asia", tld: ".az" },
    { name: "Bahamas", region: "north-america", tld: ".bs" },
    { name: "Bahrain", region: "asia", tld: ".bh" },
    { name: "Bangladesh", region: "asia", tld: ".bd" },
    { name: "Barbados", region: "north-america", tld: ".bb" },
    { name: "Belarus", region: "europe", tld: ".by" },
    { name: "Belgium", region: "europe", tld: ".be" },
    { name: "Belize", region: "north-america", tld: ".bz" },
    { name: "Benin", region: "africa", tld: ".bj" },
    { name: "Bhutan", region: "asia", tld: ".bt" },
    { name: "Bolivia", region: "south-america", tld: ".bo" },
    { name: "Bosnia and Herzegovina", region: "europe", tld: ".ba" },
    { name: "Botswana", region: "africa", tld: ".bw" },
    { name: "Brazil", region: "south-america", tld: ".br" },
    { name: "Brunei", region: "asia", tld: ".bn" },
    { name: "Bulgaria", region: "europe", tld: ".bg" },
    { name: "Burkina Faso", region: "africa", tld: ".bf" },
    { name: "Burundi", region: "africa", tld: ".bi" },
    { name: "Cambodia", region: "asia", tld: ".kh" },
    { name: "Cameroon", region: "africa", tld: ".cm" },
    { name: "Canada", region: "north-america", tld: ".ca" },
    { name: "Cape Verde", region: "africa", tld: ".cv" },
    { name: "Central African Republic", region: "africa", tld: ".cf" },
    { name: "Chad", region: "africa", tld: ".td" },
    { name: "Chile", region: "south-america", tld: ".cl" },
    { name: "China", region: "asia", tld: ".cn" },
    { name: "Colombia", region: "south-america", tld: ".co" },
    { name: "Comoros", region: "africa", tld: ".km" },
    { name: "Congo", region: "africa", tld: ".cg" },
    { name: "Costa Rica", region: "north-america", tld: ".cr" },
    { name: "Croatia", region: "europe", tld: ".hr" },
    { name: "Cuba", region: "north-america", tld: ".cu" },
    { name: "Cyprus", region: "europe", tld: ".cy" },
    { name: "Czech Republic", region: "europe", tld: ".cz" },
    { name: "Democratic Republic of the Congo", region: "africa", tld: ".cd" },
    { name: "Denmark", region: "europe", tld: ".dk" },
    { name: "Djibouti", region: "africa", tld: ".dj" },
    { name: "Dominica", region: "north-america", tld: ".dm" },
    { name: "Dominican Republic", region: "north-america", tld: ".do" },
    { name: "East Timor", region: "asia", tld: ".tl" },
    { name: "Ecuador", region: "south-america", tld: ".ec" },
    { name: "Egypt", region: "africa", tld: ".eg" },
    { name: "El Salvador", region: "north-america", tld: ".sv" },
    { name: "Equatorial Guinea", region: "africa", tld: ".gq" },
    { name: "Eritrea", region: "africa", tld: ".er" },
    { name: "Estonia", region: "europe", tld: ".ee" },
    { name: "Eswatini", region: "africa", tld: ".sz" },
    { name: "Ethiopia", region: "africa", tld: ".et" },
    { name: "Fiji", region: "oceania", tld: ".fj" },
    { name: "Finland", region: "europe", tld: ".fi" },
    { name: "France", region: "europe", tld: ".fr" },
    { name: "Gabon", region: "africa", tld: ".ga" },
    { name: "Gambia", region: "africa", tld: ".gm" },
    { name: "Georgia", region: "asia", tld: ".ge" },
    { name: "Germany", region: "europe", tld: ".de" },
    { name: "Ghana", region: "africa", tld: ".gh" },
    { name: "Greece", region: "europe", tld: ".gr" },
    { name: "Grenada", region: "north-america", tld: ".gd" },
    { name: "Guatemala", region: "north-america", tld: ".gt" },
    { name: "Guinea", region: "africa", tld: ".gn" },
    { name: "Guinea-Bissau", region: "africa", tld: ".gw" },
    { name: "Guyana", region: "south-america", tld: ".gy" },
    { name: "Haiti", region: "north-america", tld: ".ht" },
    { name: "Honduras", region: "north-america", tld: ".hn" },
    { name: "Hungary", region: "europe", tld: ".hu" },
    { name: "Iceland", region: "europe", tld: ".is" },
    { name: "India", region: "asia", tld: ".in" },
    { name: "Indonesia", region: "asia", tld: ".id" },
    { name: "Iran", region: "asia", tld: ".ir" },
    { name: "Iraq", region: "asia", tld: ".iq" },
    { name: "Ireland", region: "europe", tld: ".ie" },
    { name: "Israel", region: "asia", tld: ".il" },
    { name: "Italy", region: "europe", tld: ".it" },
    { name: "Ivory Coast", region: "africa", tld: ".ci" },
    { name: "Jamaica", region: "north-america", tld: ".jm" },
    { name: "Japan", region: "asia", tld: ".jp" },
    { name: "Jordan", region: "asia", tld: ".jo" },
    { name: "Kazakhstan", region: "asia", tld: ".kz" },
    { name: "Kenya", region: "africa", tld: ".ke" },
    { name: "Kiribati", region: "oceania", tld: ".ki" },
    { name: "Kuwait", region: "asia", tld: ".kw" },
    { name: "Kyrgyzstan", region: "asia", tld: ".kg" },
    { name: "Laos", region: "asia", tld: ".la" },
    { name: "Latvia", region: "europe", tld: ".lv" },
    { name: "Lebanon", region: "asia", tld: ".lb" },
    { name: "Lesotho", region: "africa", tld: ".ls" },
    { name: "Liberia", region: "africa", tld: ".lr" },
    { name: "Libya", region: "africa", tld: ".ly" },
    { name: "Liechtenstein", region: "europe", tld: ".li" },
    { name: "Lithuania", region: "europe", tld: ".lt" },
    { name: "Luxembourg", region: "europe", tld: ".lu" },
    { name: "Madagascar", region: "africa", tld: ".mg" },
    { name: "Malawi", region: "africa", tld: ".mw" },
    { name: "Malaysia", region: "asia", tld: ".my" },
    { name: "Maldives", region: "asia", tld: ".mv" },
    { name: "Mali", region: "africa", tld: ".ml" },
    { name: "Malta", region: "europe", tld: ".mt" },
    { name: "Marshall Islands", region: "oceania", tld: ".mh" },
    { name: "Mauritania", region: "africa", tld: ".mr" },
    { name: "Mauritius", region: "africa", tld: ".mu" },
    { name: "Mexico", region: "north-america", tld: ".mx" },
    { name: "Micronesia", region: "oceania", tld: ".fm" },
    { name: "Moldova", region: "europe", tld: ".md" },
    { name: "Monaco", region: "europe", tld: ".mc" },
    { name: "Mongolia", region: "asia", tld: ".mn" },
    { name: "Montenegro", region: "europe", tld: ".me" },
    { name: "Morocco", region: "africa", tld: ".ma" },
    { name: "Mozambique", region: "africa", tld: ".mz" },
    { name: "Myanmar", region: "asia", tld: ".mm" },
    { name: "Namibia", region: "africa", tld: ".na" },
    { name: "Nauru", region: "oceania", tld: ".nr" },
    { name: "Nepal", region: "asia", tld: ".np" },
    { name: "Netherlands", region: "europe", tld: ".nl" },
    { name: "New Zealand", region: "oceania", tld: ".nz" },
    { name: "Nicaragua", region: "north-america", tld: ".ni" },
    { name: "Niger", region: "africa", tld: ".ne" },
    { name: "Nigeria", region: "africa", tld: ".ng" },
    { name: "North Korea", region: "asia", tld: ".kp" },
    { name: "North Macedonia", region: "europe", tld: ".mk" },
    { name: "Norway", region: "europe", tld: ".no" },
    { name: "Oman", region: "asia", tld: ".om" },
    { name: "Pakistan", region: "asia", tld: ".pk" },
    { name: "Palau", region: "oceania", tld: ".pw" },
    { name: "Panama", region: "north-america", tld: ".pa" },
    { name: "Papua New Guinea", region: "oceania", tld: ".pg" },
    { name: "Paraguay", region: "south-america", tld: ".py" },
    { name: "Peru", region: "south-america", tld: ".pe" },
    { name: "Philippines", region: "asia", tld: ".ph" },
    { name: "Poland", region: "europe", tld: ".pl" },
    { name: "Portugal", region: "europe", tld: ".pt" },
    { name: "Qatar", region: "asia", tld: ".qa" },
    { name: "Romania", region: "europe", tld: ".ro" },
    { name: "Russia", region: "europe", tld: ".ru" },
    { name: "Rwanda", region: "africa", tld: ".rw" },
    { name: "Saint Kitts and Nevis", region: "north-america", tld: ".kn" },
    { name: "Saint Lucia", region: "north-america", tld: ".lc" },
    { name: "Saint Vincent and the Grenadines", region: "north-america", tld: ".vc" },
    { name: "Samoa", region: "oceania", tld: ".ws" },
    { name: "San Marino", region: "europe", tld: ".sm" },
    { name: "Saudi Arabia", region: "asia", tld: ".sa" },
    { name: "Senegal", region: "africa", tld: ".sn" },
    { name: "Serbia", region: "europe", tld: ".rs" },
    { name: "Seychelles", region: "africa", tld: ".sc" },
    { name: "Sierra Leone", region: "africa", tld: ".sl" },
    { name: "Singapore", region: "asia", tld: ".sg" },
    { name: "Slovakia", region: "europe", tld: ".sk" },
    { name: "Slovenia", region: "europe", tld: ".si" },
    { name: "Solomon Islands", region: "oceania", tld: ".sb" },
    { name: "Somalia", region: "africa", tld: ".so" },
    { name: "South Africa", region: "africa", tld: ".za" },
    { name: "South Korea", region: "asia", tld: ".kr" },
    { name: "South Sudan", region: "africa", tld: ".ss" },
    { name: "Spain", region: "europe", tld: ".es" },
    { name: "Sri Lanka", region: "asia", tld: ".lk" },
    { name: "Sudan", region: "africa", tld: ".sd" },
    { name: "Suriname", region: "south-america", tld: ".sr" },
    { name: "Sweden", region: "europe", tld: ".se" },
    { name: "Switzerland", region: "europe", tld: ".ch" },
    { name: "Syria", region: "asia", tld: ".sy" },
    { name: "São Tomé and Príncipe", region: "africa", tld: ".st" },
    { name: "Taiwan", region: "asia", tld: ".tw" },
    { name: "Tajikistan", region: "asia", tld: ".tj" },
    { name: "Tanzania", region: "africa", tld: ".tz" },
    { name: "Thailand", region: "asia", tld: ".th" },
    { name: "Togo", region: "africa", tld: ".tg" },
    { name: "Tonga", region: "oceania", tld: ".to" },
    { name: "Trinidad and Tobago", region: "north-america", tld: ".tt" },
    { name: "Tunisia", region: "africa", tld: ".tn" },
    { name: "Turkey", region: "asia", tld: ".tr" },
    { name: "Turkmenistan", region: "asia", tld: ".tm" },
    { name: "Tuvalu", region: "oceania", tld: ".tv" },
    { name: "Uganda", region: "africa", tld: ".ug" },
    { name: "Ukraine", region: "europe", tld: ".ua" },
    { name: "United Arab Emirates", region: "asia", tld: ".ae" },
    { name: "United Kingdom", region: "europe", tld: ".uk" },
    { name: "United States", region: "north-america", tld: ".us" },
    { name: "Uruguay", region: "south-america", tld: ".uy" },
    { name: "Uzbekistan", region: "asia", tld: ".uz" },
    { name: "Vanuatu", region: "oceania", tld: ".vu" },
    { name: "Vatican City", region: "europe", tld: ".va" },
    { name: "Venezuela", region: "south-america", tld: ".ve" },
    { name: "Vietnam", region: "asia", tld: ".vn" },
    { name: "Yemen", region: "asia", tld: ".ye" },
    { name: "Zambia", region: "africa", tld: ".zm" },
    { name: "Zimbabwe", region: "africa", tld: ".zw" },
];