const germanyPlates = [
  { code: "0-1", filename: "0-1", name: "Bundespräsident", region: "Sonderkennzeichen" },
  { code: "0-2", filename: "0-2", name: "Bundeskanzler", region: "Sonderkennzeichen" },
  { code: "0-3", filename: "0-3", name: "Bundesminister des Auswärtigen", region: "Sonderkennzeichen" },
  { code: "0-4", filename: "0-4", name: "Erster Staatssekretär des Auswärtigen Amt", region: "Sonderkennzeichen" },
  { code: "1-1", filename: "1-1", name: "Präsident des Deutschen Bundestags", region: "Sonderkennzeichen" },
  { code: "A", filename: "a", name: "Augsburg", region: "Bayern" },
  { code: "AA", filename: "aa", name: "Ostalbkreis", region: "Baden-Württemberg", aliases: ["Aalen"] },
  { code: "AB", filename: "ab", name: "Aschaffenburg", region: "Bayern" },
  { code: "ABG", filename: "abg", name: "Altenburger Land", region: "Thüringen", aliases: ["Altenburg"] },
  { code: "ABI", filename: "abi", name: "Anhalt-Bitterfeld", region: "Sachsen-Anhalt" },
  { code: "AC", filename: "ac", name: "Aachen (Städteregion)", region: "Nordrhein-Westfalen", aliases: ["Aachen"] },
  { code: "AE", filename: "ae", name: "Erzgebirgskreis (Aue)", region: "Sachsen", aliases: ["Aue"] },
  { code: "AH", filename: "ah", name: "Ahaus", region: "Nordrhein-Westfalen" },
  { code: "AIB", filename: "aib", name: "Ebersberg (Alt-Aibling)", region: "Bayern", aliases: ["Alt-Aibling"] },
  { code: "AIC", filename: "aic", name: "Aichach-Friedberg", region: "Bayern" },
  { code: "AK", filename: "ak", name: "Altenkirchen (Westerwald)", region: "Rheinland-Pfalz" },
  { code: "AL", filename: "al", name: "Altötting", region: "Bayern" },
  { code: "ALF", filename: "alf", name: "Hildesheim (Alfeld)", region: "Niedersachsen", aliases: ["Alfeld"] },
  { code: "ALS", filename: "als", name: "Vogelsbergkreis (Alsfeld)", region: "Hessen", aliases: ["Alsfeld"] },
  { code: "ALZ", filename: "alz", name: "Altötting (Alzenau)", region: "Bayern", aliases: ["Alzenau"] },
  { code: "AM", filename: "am", name: "Amberg-Sulzbach", region: "Bayern" },
  { code: "AN", filename: "an", name: "Ansbach", region: "Bayern" },
  { code: "ANA", filename: "ana", name: "Erzgebirgskreis (Annaberg)", region: "Sachsen", aliases: ["Annaberg-Buchholz"] },
  { code: "ANG", filename: "ang", name: "Stendal (Angermünde)", region: "Brandenburg", aliases: ["Angermünde"] },
  { code: "ANK", filename: "ank", name: "Uckermark (Angermünde)", region: "Brandenburg" },
  { code: "AOE", filename: "aoe", name: "Altötting", region: "Bayern" },
  { code: "AP", filename: "ap", name: "Weimarer Land (Apolda)", region: "Thüringen", aliases: ["Apolda"] },
  { code: "APD", filename: "apd", name: "Weimarer Land", region: "Thüringen" },
  { code: "AR", filename: "ar", name: "Vorpommern-Rügen (Rügen)", region: "Mecklenburg-Vorpommern" },
  { code: "ARN", filename: "arn", name: "Ilm-Kreis (Arnstadt)", region: "Thüringen", aliases: ["Arnstadt"] },
  { code: "ART", filename: "art", name: "Ilm-Kreis", region: "Thüringen" },
  { code: "AS", filename: "as", name: "Schwandorf", region: "Bayern" },
  { code: "ASD", filename: "asd", name: "Salzlandkreis (Aschersleben)", region: "Sachsen-Anhalt", aliases: ["Aschersleben"] },
  { code: "ASL", filename: "asl", name: "Mansfeld-Südharz (Aschersleben)", region: "Sachsen-Anhalt" },
  { code: "ASZ", filename: "asz", name: "Erzgebirgskreis (Aue-Schwarzenberg)", region: "Sachsen", aliases: ["Aue-Schwarzenberg"] },
  { code: "AT", filename: "at", name: "Weimarer Land", region: "Thüringen" },
  { code: "AU", filename: "au", name: "Erzgebirgskreis", region: "Sachsen" },
  { code: "AUR", filename: "aur", name: "Aurich", region: "Niedersachsen" },
  { code: "AW", filename: "aw", name: "Ahrweiler", region: "Rheinland-Pfalz" },
  { code: "AZ", filename: "az", name: "Alzey-Worms", region: "Rheinland-Pfalz" },
  { code: "AZE", filename: "aze", name: "Anhalt-Zerbst", region: "Sachsen-Anhalt" },
  { code: "B", filename: "b", name: "Berlin", region: "Berlin" },
  { code: "BA", filename: "ba", name: "Bamberg", region: "Bayern" },
  { code: "BAD", filename: "bad", name: "Baden-Baden", region: "Baden-Württemberg" },
  { code: "BAR", filename: "bar", name: "Barnim", region: "Brandenburg" },
  { code: "BB", filename: "bb", name: "Böblingen", region: "Baden-Württemberg" },
  { code: "BBG", filename: "bbg", name: "Bernburg (Salzlandkreis)", region: "Sachsen-Anhalt", aliases: ["Bernburg"] },
  { code: "BBL", filename: "bbl", name: "Landesregierung Brandenburg", region: "Sonderkennzeichen" },
  { code: "BC", filename: "bc", name: "Biberach an der Riß", region: "Baden-Württemberg", aliases: ["Biberach"] },
  { code: "BCH", filename: "bch", name: "Göppingen (Biberach/Riß hist.)", region: "Baden-Württemberg" },
  { code: "BD1", filename: "bd1", name: "Deutscher Bundestag", region: "Sonderkennzeichen" },
  { code: "BD3", filename: "bd3", name: "Bundesrat", region: "Sonderkennzeichen" },
  { code: "BD4", filename: "bd4", name: "Bundesverfassungsgericht", region: "Sonderkennzeichen" },
  { code: "BD5", filename: "bd5", name: "Bundespräsidialamt", region: "Sonderkennzeichen" },
  { code: "BD6", filename: "bd6", name: "Bundeskanzleramt", region: "Sonderkennzeichen" },
  { code: "BD7", filename: "bd7", name: "Auswärtiges Amt", region: "Sonderkennzeichen" },
  { code: "BD8", filename: "bd8", name: "Zoll", region: "Sonderkennzeichen" },
  { code: "BD9", filename: "bd9", name: "Bundesinnenministerium", region: "Sonderkennzeichen" },
  { code: "BD10", filename: "bd10", name: "Bundesjustizministerium", region: "Sonderkennzeichen" },
  { code: "BD11", filename: "bd11", name: "Bundesfinanzministerium", region: "Sonderkennzeichen" },
  { code: "BD12", filename: "bd12", name: "Bundesministerium für Wirtschaft und Energie", region: "Sonderkennzeichen" },
  { code: "BD13", filename: "bd13", name: "Bundesministerium für Verkehr und digitale Infrastruktur", region: "Sonderkennzeichen" },
  { code: "BD14", filename: "bd14", name: "Bundesministerium für Ernährung und Landwirtschaft", region: "Sonderkennzeichen" },
  { code: "BD15", filename: "bd15", name: "Bundesministerium für Arbeit und Soziales", region: "Sonderkennzeichen" },
  { code: "BD18", filename: "bd18", name: "Bundesverteidigungsministerium", region: "Sonderkennzeichen" },
  { code: "BD19", filename: "bd19", name: "Bundesministerium für Bildung und Forschung", region: "Sonderkennzeichen" },
  { code: "BD20", filename: "bd20", name: "Bundesministerium für Umwelt, Naturschutz, Bau und Reaktorsicherheit", region: "Sonderkennzeichen" },
  { code: "BD21", filename: "bd21", name: "Bundesministerium für Familie, Senioren, Frauen und Jugend", region: "Sonderkennzeichen" },
  { code: "BD22", filename: "bd22", name: "Bundesgesundheitsministerium", region: "Sonderkennzeichen" },
  { code: "BD23", filename: "bd23", name: "Bundeskriminalamt", region: "Sonderkennzeichen" },
  { code: "BD26", filename: "bd26", name: "Bundesministerium für wirtschaftliche Zusammenarbeit und Entwicklung", region: "Sonderkennzeichen" },
  { code: "BE", filename: "be", name: "Bernkastel-Wittlich", region: "Rheinland-Pfalz" },
  { code: "BED", filename: "bed", name: "Jerichower Land (Bad Belzig)", region: "Brandenburg", aliases: ["Bad Belzig"] },
  { code: "BEI", filename: "bei", name: "Eichstätt", region: "Bayern" },
  { code: "BEL", filename: "bel", name: "Jerichower Land", region: "Brandenburg" },
  { code: "BER", filename: "ber", name: "Berchtesgadener Land", region: "Bayern" },
  { code: "BF", filename: "bf", name: "Steinfurt (Burgsteinfurt)", region: "Nordrhein-Westfalen", aliases: ["Burgsteinfurt"] },
  { code: "BGD", filename: "bgd", name: "Berchtesgadener Land (hist.)", region: "Bayern" },
  { code: "BGL", filename: "bgl", name: "Berchtesgadener Land", region: "Bayern" },
  { code: "BH", filename: "bh", name: "Bergheim (Rhein-Erft-Kreis)", region: "Nordrhein-Westfalen" },
  { code: "BI", filename: "bi", name: "Bielefeld", region: "Nordrhein-Westfalen" },
  { code: "BID", filename: "bid", name: "Bergstraße (Bensheim)", region: "Hessen", aliases: ["Bensheim"] },
  { code: "BIN", filename: "bin", name: "Mainz-Bingen (hist.)", region: "Rheinland-Pfalz" },
  { code: "BIR", filename: "bir", name: "Birkenfeld", region: "Rheinland-Pfalz" },
  { code: "BIT", filename: "bit", name: "Eifelkreis Bitburg-Prüm", region: "Rheinland-Pfalz", aliases: ["Bitburg","Bitburg-Prüm"] },
  { code: "BIW", filename: "biw", name: "Bitterfeld-Wolfen", region: "Sachsen-Anhalt" },
  { code: "BK", filename: "bk", name: "Börde (Haldensleben)", region: "Sachsen-Anhalt" },
  { code: "BKS", filename: "bks", name: "Schwarzwald-Baar-Kreis (hist.)", region: "Baden-Württemberg" },
  { code: "BL", filename: "bl", name: "Zollernalbkreis", region: "Baden-Württemberg", aliases: ["Balingen"] },
  { code: "BLB", filename: "blb", name: "Stadtverband Saarbrücken (Blies)", region: "Saarland" },
  { code: "BLK", filename: "blk", name: "Burgenlandkreis", region: "Sachsen-Anhalt" },
  { code: "BM", filename: "bm", name: "Rhein-Erft-Kreis (Bergheim)", region: "Nordrhein-Westfalen" },
  { code: "BN", filename: "bn", name: "Bonn", region: "Nordrhein-Westfalen" },
  { code: "BNA", filename: "bna", name: "Leipzig (Borna)", region: "Sachsen", aliases: ["Borna"] },
  { code: "BO", filename: "bo", name: "Bochum", region: "Nordrhein-Westfalen" },
  { code: "BOE", filename: "boe", name: "Böblingen", region: "Baden-Württemberg" },
  { code: "BOG", filename: "bog", name: "Straubing-Bogen", region: "Bayern" },
  { code: "BOH", filename: "boh", name: "Werra-Meißner-Kreis", region: "Hessen" },
  { code: "BOR", filename: "bor", name: "Borken", region: "Nordrhein-Westfalen" },
  { code: "BOT", filename: "bot", name: "Bottrop", region: "Nordrhein-Westfalen" },
  { code: "BP", filename: "bp", name: "Bundespolizei", region: "Sonderkennzeichen" },
  { code: "BR", filename: "br", name: "Breisgau-Hochschwarzwald", region: "Baden-Württemberg" },
  { code: "BRA", filename: "bra", name: "Wesermarsch (Brake)", region: "Niedersachsen", aliases: ["Brake"] },
  { code: "BRB", filename: "brb", name: "Brandenburg an der Havel", region: "Brandenburg" },
  { code: "BRG", filename: "brg", name: "Stendal (Burg)", region: "Sachsen-Anhalt", aliases: ["Burg"] },
  { code: "BRI", filename: "bri", name: "Landshut (Vilsbiburg/Bruck)", region: "Bayern" },
  { code: "BRK", filename: "brk", name: "Rosenheim (Wasserburg/Inn)", region: "Bayern" },
  { code: "BRL", filename: "brl", name: "Braunschweig (hist.)", region: "Niedersachsen" },
  { code: "BRV", filename: "brv", name: "Rotenburg (Wümme) (Bremervörde)", region: "Niedersachsen", aliases: ["Bremervörde"] },
  { code: "BS", filename: "bs", name: "Braunschweig", region: "Niedersachsen" },
  { code: "BSB", filename: "bsb", name: "Ortenaukreis (Bühl)", region: "Baden-Württemberg", aliases: ["Bühl"] },
  { code: "BSK", filename: "bsk", name: "Oberspreewald-Lausitz", region: "Brandenburg" },
  { code: "BT", filename: "bt", name: "Bayreuth", region: "Bayern" },
  { code: "BTF", filename: "btf", name: "Anhalt-Bitterfeld (Bitterfeld)", region: "Sachsen-Anhalt", aliases: ["Bitterfeld"] },
  { code: "BU", filename: "bu", name: "Neuburg-Schrobenhausen (Burgau)", region: "Bayern", aliases: ["Burgau"] },
  { code: "BÜD", filename: "bued", name: "Wetteraukreis (Bad Nauheim / hist.)", region: "Hessen" },
  { code: "BÜR", filename: "buer", name: "Recklinghausen (Buer / hist.)", region: "Nordrhein-Westfalen", aliases: ["Buer"] },
  { code: "BÜS", filename: "bues", name: "Büsingen am Hochrhein", region: "Baden-Württemberg" },
  { code: "BÜZ", filename: "buez", name: "Landkreis Rostock (Bützow)", region: "Mecklenburg-Vorpommern", aliases: ["Bützow"] },
  { code: "BUL", filename: "bul", name: "Schwandorf (Burglengenfeld)", region: "Bayern", aliases: ["Burglengenfeld"] },
  { code: "BW1", filename: "bw1", name: "Wasser- und Schifffahrtsverwaltung", region: "Sonderkennzeichen" },
  { code: "BWL", filename: "bwl", name: "Landesregierung Baden-Württemberg", region: "Sonderkennzeichen" },
  { code: "BYL", filename: "byl", name: "Landesregierung Bayern", region: "Sonderkennzeichen" },
  { code: "BZ", filename: "bz", name: "Bautzen", region: "Sachsen" },
  { code: "BZA", filename: "bza", name: "Bautzen (Bischofswerda/hist.)", region: "Sachsen", aliases: ["Bischofswerda"] },
  { code: "C", filename: "c", name: "Chemnitz", region: "Sachsen" },
  { code: "CA", filename: "ca", name: "Cottbus (alt)", region: "Brandenburg" },
  { code: "CAS", filename: "cas", name: "Recklinghausen (Castrop-Rauxel)", region: "Nordrhein-Westfalen", aliases: ["Castrop-Rauxel"] },
  { code: "CB", filename: "cb", name: "Cottbus", region: "Brandenburg" },
  { code: "CE", filename: "ce", name: "Celle", region: "Niedersachsen" },
  { code: "CHA", filename: "cha", name: "Cham", region: "Bayern" },
  { code: "CLP", filename: "clp", name: "Cloppenburg", region: "Niedersachsen" },
  { code: "CLZ", filename: "clz", name: "Goslar (Clausthal-Zellerfeld/hist.)", region: "Niedersachsen", aliases: ["Clausthal-Zellerfeld"] },
  { code: "CO", filename: "co", name: "Coburg", region: "Bayern" },
  { code: "COC", filename: "coc", name: "Cochem-Zell", region: "Rheinland-Pfalz" },
  { code: "COE", filename: "coe", name: "Coesfeld", region: "Nordrhein-Westfalen" },
  { code: "CR", filename: "cr", name: "Nordvorpommern (Grimmen/hist.)", region: "Mecklenburg-Vorpommern" },
  { code: "CUX", filename: "cux", name: "Cuxhaven", region: "Niedersachsen" },
  { code: "CW", filename: "cw", name: "Calw", region: "Baden-Württemberg" },
  { code: "D", filename: "d", name: "Düsseldorf", region: "Nordrhein-Westfalen" },
  { code: "DA", filename: "da", name: "Darmstadt", region: "Hessen" },
  { code: "DAH", filename: "dah", name: "Dachau", region: "Bayern" },
  { code: "DAN", filename: "dan", name: "Lüchow-Dannenberg", region: "Niedersachsen" },
  { code: "DAU", filename: "dau", name: "Vulkaneifel (Daun)", region: "Rheinland-Pfalz", aliases: ["Daun"] },
  { code: "DBR", filename: "dbr", name: "Landkreis Rostock (Bad Doberan)", region: "Mecklenburg-Vorpommern", aliases: ["Bad Doberan"] },
  { code: "DD", filename: "dd", name: "Dresden", region: "Sachsen" },
  { code: "DE", filename: "de", name: "Dessau-Roßlau", region: "Sachsen-Anhalt" },
  { code: "DEG", filename: "deg", name: "Deggendorf", region: "Bayern" },
  { code: "DEL", filename: "del", name: "Delmenhorst", region: "Niedersachsen" },
  { code: "DGF", filename: "dgf", name: "Dingolfing-Landau", region: "Bayern" },
  { code: "DH", filename: "dh", name: "Diepholz", region: "Niedersachsen" },
  { code: "DI", filename: "di", name: "Darmstadt-Dieburg", region: "Hessen" },
  { code: "DIL", filename: "dil", name: "Lahn-Dill-Kreis (Dillenburg)", region: "Hessen", aliases: ["Dillenburg"] },
  { code: "DIN", filename: "din", name: "Neuburg-Schrobenhausen (Neuburg/Donau hist.)", region: "Bayern" },
  { code: "DIZ", filename: "diz", name: "Zwickau (Diesbar-Seußlitz / hist.)", region: "Sachsen" },
  { code: "DKB", filename: "dkb", name: "Weißenburg-Gunzenhausen (Dinkelsbühl)", region: "Bayern", aliases: ["Dinkelsbühl"] },
  { code: "DL", filename: "dl", name: "Mittelsachsen (Döbeln)", region: "Sachsen", aliases: ["Döbeln"] },
  { code: "DLG", filename: "dlg", name: "Dillingen an der Donau", region: "Bayern" },
  { code: "DM", filename: "dm", name: "Mecklenburgische Seenplatte (Demmin)", region: "Mecklenburg-Vorpommern", aliases: ["Demmin"] },
  { code: "DN", filename: "dn", name: "Düren", region: "Nordrhein-Westfalen" },
  { code: "DO", filename: "do", name: "Dortmund", region: "Nordrhein-Westfalen" },
  { code: "DON", filename: "don", name: "Donau-Ries", region: "Bayern" },
  { code: "DS", filename: "ds", name: "Rhein-Neckar-Kreis (Heidelberg hist.)", region: "Baden-Württemberg" },
  { code: "DT", filename: "dt", name: "Landshut (Dingolfing hist.)", region: "Bayern" },
  { code: "DU", filename: "du", name: "Duisburg", region: "Nordrhein-Westfalen" },
  { code: "DUD", filename: "dud", name: "Goslar (Duderstadt)", region: "Niedersachsen", aliases: ["Duderstadt"] },
  { code: "DÜW", filename: "duew", name: "Bad Dürkheim", region: "Rheinland-Pfalz" },
  { code: "DW", filename: "dw", name: "Sächsische Schweiz-Osterzgebirge (Dippoldiswalde)", region: "Sachsen", aliases: ["Dippoldiswalde"] },
  { code: "DZ", filename: "dz", name: "Nordsachsen (Delitzsch)", region: "Sachsen", aliases: ["Delitzsch"] },
  { code: "E", filename: "e", name: "Essen", region: "Nordrhein-Westfalen" },
  { code: "EA", filename: "ea", name: "Wartburgkreis (Eisenach)", region: "Thüringen", aliases: ["Eisenach"] },
  { code: "EB", filename: "eb", name: "Erzgebirgskreis", region: "Sachsen" },
  { code: "EBE", filename: "ebe", name: "Ebersberg", region: "Bayern" },
  { code: "EBN", filename: "ebn", name: "Haßberge (Ebern)", region: "Bayern", aliases: ["Ebern"] },
  { code: "EBS", filename: "ebs", name: "Neustadt/Waldnaab (Eschenbach)", region: "Bayern" },
  { code: "ECK", filename: "eck", name: "Rendsburg-Eckernförde (Eckernförde)", region: "Schleswig-Holstein", aliases: ["Eckernförde"] },
  { code: "ED", filename: "ed", name: "Erding", region: "Bayern" },
  { code: "EE", filename: "ee", name: "Elbe-Elster", region: "Brandenburg" },
  { code: "EF", filename: "ef", name: "Erfurt", region: "Thüringen" },
  { code: "EG", filename: "eg", name: "Rottal-Inn (Eggenfelden)", region: "Bayern", aliases: ["Eggenfelden"] },
  { code: "EH", filename: "eh", name: "Erlangen-Höchstadt (Herzogenaurach)", region: "Bayern" },
  { code: "EHI", filename: "ehi", name: "Werra-Meißner-Kreis (Eschwege hist.)", region: "Hessen" },
  { code: "EI", filename: "ei", name: "Eichstätt", region: "Bayern" },
  { code: "EIC", filename: "eic", name: "Eichsfeld", region: "Thüringen" },
  { code: "EIH", filename: "eih", name: "Eichstätt", region: "Bayern" },
  { code: "EIL", filename: "eil", name: "Saalekreis (Eilenburg)", region: "Sachsen-Anhalt", aliases: ["Eilenburg"] },
  { code: "EIN", filename: "ein", name: "Emsland (Lingen hist.)", region: "Niedersachsen" },
  { code: "EIS", filename: "eis", name: "Saale-Holzland-Kreis (Eisenberg)", region: "Thüringen", aliases: ["Eisenberg"] },
  { code: "EL", filename: "el", name: "Emsland", region: "Niedersachsen" },
  { code: "EM", filename: "em", name: "Emmendingen", region: "Baden-Württemberg" },
  { code: "EMD", filename: "emd", name: "Emden", region: "Niedersachsen" },
  { code: "EMS", filename: "ems", name: "Rhein-Lahn-Kreis (Bad Ems)", region: "Rheinland-Pfalz", aliases: ["Bad Ems"] },
  { code: "EN", filename: "en", name: "Ennepe-Ruhr-Kreis", region: "Nordrhein-Westfalen" },
  { code: "ER", filename: "er", name: "Erlangen", region: "Bayern" },
  { code: "ERB", filename: "erb", name: "Odenwaldkreis (Erbach)", region: "Hessen", aliases: ["Erbach"] },
  { code: "ERH", filename: "erh", name: "Erlangen-Höchstadt", region: "Bayern" },
  { code: "ERK", filename: "erk", name: "Krefeld (Kempen/Krefeld hist.)", region: "Nordrhein-Westfalen" },
  { code: "ERZ", filename: "erz", name: "Erzgebirgskreis", region: "Sachsen" },
  { code: "ES", filename: "es", name: "Esslingen am Neckar", region: "Baden-Württemberg" },
  { code: "ESA", filename: "esa", name: "Wartburgkreis (Eisenach alt)", region: "Thüringen" },
  { code: "ESB", filename: "esb", name: "Neustadt/Waldnaab (Eschenbach i.d.OPf.)", region: "Bayern", aliases: ["Eschenbach"] },
  { code: "ESW", filename: "esw", name: "Werra-Meißner-Kreis (Eschwege)", region: "Hessen", aliases: ["Eschwege"] },
  { code: "EU", filename: "eu", name: "Euskirchen", region: "Nordrhein-Westfalen" },
  { code: "EUT", filename: "eut", name: "Plön (Eutin)", region: "Schleswig-Holstein", aliases: ["Eutin"] },
  { code: "EW", filename: "ew", name: "Barnim", region: "Brandenburg" },
  { code: "F", filename: "f", name: "Frankfurt am Main", region: "Hessen" },
  { code: "FAL", filename: "fal", name: "Northeim (Einbeck / hist.)", region: "Niedersachsen" },
  { code: "FB", filename: "fb", name: "Wetteraukreis (Friedberg)", region: "Hessen", aliases: ["Friedberg (Hessen)"] },
  { code: "FD", filename: "fd", name: "Fulda", region: "Hessen" },
  { code: "FDB", filename: "fdb", name: "Fürstenfeldbruck", region: "Bayern" },
  { code: "FDS", filename: "fds", name: "Freudenstadt", region: "Baden-Württemberg" },
  { code: "FEU", filename: "feu", name: "Ansbach (Feuchtwangen)", region: "Bayern", aliases: ["Feuchtwangen"] },
  { code: "FF", filename: "ff", name: "Frankfurt (Oder)", region: "Brandenburg" },
  { code: "FFB", filename: "ffb", name: "Fürstenfeldbruck", region: "Bayern" },
  { code: "FG", filename: "fg", name: "Mittelsachsen (Freiberg)", region: "Sachsen", aliases: ["Freiberg"] },
  { code: "FH", filename: "fh", name: "Flensburg (hist.)", region: "Schleswig-Holstein" },
  { code: "FI", filename: "fi", name: "Vorpommern-Greifswald (Freest hist.)", region: "Mecklenburg-Vorpommern" },
  { code: "FKB", filename: "fkb", name: "Waldeck-Frankenberg (Frankenberg)", region: "Hessen", aliases: ["Frankenberg"] },
  { code: "FL", filename: "fl", name: "Flensburg", region: "Schleswig-Holstein" },
  { code: "FLÖ", filename: "floe", name: "Mittelsachsen (Flöha)", region: "Sachsen", aliases: ["Flöha"] },
  { code: "FN", filename: "fn", name: "Bodenseekreis (Friedrichshafen)", region: "Baden-Württemberg", aliases: ["Friedrichshafen"] },
  { code: "FO", filename: "fo", name: "Forchheim", region: "Bayern" },
  { code: "FOR", filename: "for", name: "Görlitz (Forst)", region: "Sachsen", aliases: ["Forst (Lausitz)"] },
  { code: "FR", filename: "fr", name: "Freiburg im Breisgau", region: "Baden-Württemberg" },
  { code: "FRG", filename: "frg", name: "Freyung-Grafenau", region: "Bayern" },
  { code: "FRI", filename: "fri", name: "Friesland", region: "Niedersachsen" },
  { code: "FRW", filename: "frw", name: "Vorpommern-Greifswald (hist.)", region: "Mecklenburg-Vorpommern" },
  { code: "FS", filename: "fs", name: "Freising", region: "Bayern" },
  { code: "FT", filename: "ft", name: "Frankenthal (Pfalz)", region: "Rheinland-Pfalz" },
  { code: "FTL", filename: "ftl", name: "Sächsische Schweiz-Osterzgebirge", region: "Sachsen" },
  { code: "FÜ", filename: "fue", name: "Fürth", region: "Bayern" },
  { code: "FÜS", filename: "fues", name: "Ostallgäu (Füssen)", region: "Bayern", aliases: ["Füssen"] },
  { code: "FW", filename: "fw", name: "Vorpommern-Greifswald (Greifswald hist.)", region: "Mecklenburg-Vorpommern" },
  { code: "FZ", filename: "fz", name: "Altenkirchen (Westerwald hist.)", region: "Rheinland-Pfalz" },
  { code: "G", filename: "g", name: "Gera", region: "Thüringen" },
  { code: "GA", filename: "ga", name: "Nordhausen", region: "Thüringen" },
  { code: "GAN", filename: "gan", name: "Garmisch-Partenkirchen (hist.)", region: "Bayern" },
  { code: "GAP", filename: "gap", name: "Garmisch-Partenkirchen", region: "Bayern" },
  { code: "GC", filename: "gc", name: "Zwickau (Glauchau hist.)", region: "Sachsen", aliases: ["Glauchau"] },
  { code: "GD", filename: "gd", name: "Unstrut-Hainich-Kreis (Mühlhausen hist.)", region: "Thüringen" },
  { code: "GDB", filename: "gdb", name: "Leipzig (Grimma)", region: "Sachsen", aliases: ["Grimma"] },
  { code: "GE", filename: "ge", name: "Gelsenkirchen", region: "Nordrhein-Westfalen" },
  { code: "GEL", filename: "gel", name: "Geldern (Kleve)", region: "Nordrhein-Westfalen", aliases: ["Geldern"] },
  { code: "GEM", filename: "gem", name: "Emsland (Meppen hist.)", region: "Niedersachsen" },
  { code: "GEO", filename: "geo", name: "Schweinfurt (Gerolzhofen)", region: "Bayern", aliases: ["Gerolzhofen"] },
  { code: "GER", filename: "ger", name: "Germersheim", region: "Rheinland-Pfalz" },
  { code: "GF", filename: "gf", name: "Gifhorn", region: "Niedersachsen" },
  { code: "GG", filename: "gg", name: "Groß-Gerau", region: "Hessen" },
  { code: "GHA", filename: "gha", name: "Leipzig (Geithain)", region: "Sachsen", aliases: ["Geithain"] },
  { code: "GHC", filename: "ghc", name: "Görlitz", region: "Sachsen" },
  { code: "GI", filename: "gi", name: "Gießen", region: "Hessen" },
  { code: "GK", filename: "gk", name: "Viersen (Kempen-Krefeld hist.)", region: "Nordrhein-Westfalen" },
  { code: "GL", filename: "gl", name: "Rheinisch-Bergischer Kreis", region: "Nordrhein-Westfalen" },
  { code: "GLA", filename: "gla", name: "Meißen (Großenhain hist.)", region: "Sachsen" },
  { code: "GM", filename: "gm", name: "Oberbergischer Kreis (Gummersbach)", region: "Nordrhein-Westfalen", aliases: ["Gummersbach"] },
  { code: "GMN", filename: "gmn", name: "Zwickau (Glauchau)", region: "Sachsen" },
  { code: "GN", filename: "gn", name: "Main-Kinzig-Kreis (Gelnhausen)", region: "Hessen", aliases: ["Gelnhausen"] },
  { code: "GNT", filename: "gnt", name: "Hildburghausen", region: "Thüringen" },
  { code: "GOA", filename: "goa", name: "Gotha", region: "Thüringen" },
  { code: "GÖ", filename: "goe", name: "Göppingen", region: "Baden-Württemberg" },
  { code: "GOH", filename: "goh", name: "Gotha (hist.)", region: "Thüringen" },
  { code: "GP", filename: "gp", name: "Göppingen", region: "Baden-Württemberg" },
  { code: "GR", filename: "gr", name: "Görlitz", region: "Sachsen" },
  { code: "GRA", filename: "gra", name: "Freyung-Grafenau (Grafenau)", region: "Bayern", aliases: ["Grafenau"] },
  { code: "GRH", filename: "grh", name: "Meißen (Großenhain)", region: "Sachsen", aliases: ["Großenhain"] },
  { code: "GRI", filename: "gri", name: "Rottal-Inn", region: "Bayern" },
  { code: "GRM", filename: "grm", name: "Leipzig (Grimma alt)", region: "Sachsen" },
  { code: "GRS", filename: "grs", name: "Greiz", region: "Thüringen" },
  { code: "GRZ", filename: "grz", name: "Greiz", region: "Thüringen" },
  { code: "GS", filename: "gs", name: "Goslar", region: "Niedersachsen" },
  { code: "GT", filename: "gt", name: "Gütersloh", region: "Nordrhein-Westfalen" },
  { code: "GTH", filename: "gth", name: "Gotha", region: "Thüringen" },
  { code: "GUB", filename: "gub", name: "Spree-Neiße (Guben)", region: "Brandenburg", aliases: ["Guben"] },
  { code: "GÜ", filename: "gue", name: "Güstrow (Landkreis Rostock)", region: "Mecklenburg-Vorpommern", aliases: ["Güstrow"] },
  { code: "GUN", filename: "gun", name: "Weißenburg-Gunzenhausen (Gunzenhausen)", region: "Bayern", aliases: ["Gunzenhausen"] },
  { code: "GV", filename: "gv", name: "Steinfurt (Gronau)", region: "Nordrhein-Westfalen", aliases: ["Gronau"] },
  { code: "GVM", filename: "gvm", name: "Mecklenburgische Seenplatte", region: "Mecklenburg-Vorpommern" },
  { code: "GW", filename: "gw", name: "Vorpommern-Greifswald (Greifswald)", region: "Mecklenburg-Vorpommern", aliases: ["Greifswald"] },
  { code: "GZ", filename: "gz", name: "Günzburg", region: "Bayern" },
  { code: "H", filename: "h", name: "Hannover (Region Hannover)", region: "Niedersachsen", aliases: ["Hannover"] },
  { code: "HA", filename: "ha", name: "Hagen", region: "Nordrhein-Westfalen" },
  { code: "HAB", filename: "hab", name: "Bad Kissingen (Hammelburg)", region: "Bayern", aliases: ["Hammelburg"] },
  { code: "HAL", filename: "hal", name: "Halle (Saale)", region: "Sachsen-Anhalt" },
  { code: "HAM", filename: "ham", name: "Hamm", region: "Nordrhein-Westfalen" },
  { code: "HAS", filename: "has", name: "Haßberge", region: "Bayern" },
  { code: "HB", filename: "hb", name: "Bremen", region: "Bremen" },
  { code: "HBN", filename: "hbn", name: "Hildburghausen", region: "Thüringen" },
  { code: "HBS", filename: "hbs", name: "Harz (Halberstadt)", region: "Sachsen-Anhalt", aliases: ["Halberstadt"] },
  { code: "HC", filename: "hc", name: "Saale-Holzland-Kreis (hist.)", region: "Thüringen" },
  { code: "HCH", filename: "hch", name: "Schwarzwald-Baar-Kreis (Donaueschingen hist.)", region: "Baden-Württemberg" },
  { code: "HD", filename: "hd", name: "Heidelberg", region: "Baden-Württemberg" },
  { code: "HDH", filename: "hdh", name: "Heidenheim an der Brenz", region: "Baden-Württemberg" },
  { code: "HDL", filename: "hdl", name: "Börde (Haldensleben)", region: "Sachsen-Anhalt", aliases: ["Haldensleben"] },
  { code: "HE", filename: "he", name: "Helmstedt", region: "Niedersachsen" },
  { code: "HEB", filename: "heb", name: "Bergstraße", region: "Hessen" },
  { code: "HEF", filename: "hef", name: "Hersfeld-Rotenburg", region: "Hessen" },
  { code: "HEI", filename: "hei", name: "Dithmarschen", region: "Schleswig-Holstein" },
  { code: "HEL", filename: "hel", name: "Landesregierung Hessen", region: "Sonderkennzeichen" },
  { code: "HER", filename: "her", name: "Herne", region: "Nordrhein-Westfalen" },
  { code: "HET", filename: "het", name: "Wartburgkreis", region: "Thüringen" },
  { code: "HF", filename: "hf", name: "Herford", region: "Nordrhein-Westfalen" },
  { code: "HG", filename: "hg", name: "Hochtaunuskreis (Bad Homburg)", region: "Hessen", aliases: ["Bad Homburg"] },
  { code: "HGN", filename: "hgn", name: "Ludwigslust-Parchim (Hagenow)", region: "Mecklenburg-Vorpommern", aliases: ["Hagenow"] },
  { code: "HGW", filename: "hgw", name: "Vorpommern-Greifswald (Greifswald)", region: "Mecklenburg-Vorpommern" },
  { code: "HH", filename: "hh", name: "Hamburg", region: "Hamburg" },
  { code: "HHM", filename: "hhm", name: "Vorpommern-Rügen (Stralsund hist.)", region: "Mecklenburg-Vorpommern" },
  { code: "HI", filename: "hi", name: "Hildesheim", region: "Niedersachsen" },
  { code: "HIG", filename: "hig", name: "Eichsfeld (Heiligenstadt)", region: "Thüringen", aliases: ["Heiligenstadt"] },
  { code: "HIP", filename: "hip", name: "Roth (Hilpoltstein)", region: "Bayern", aliases: ["Hilpoltstein"] },
  { code: "HK", filename: "hk", name: "Hameln-Pyrmont", region: "Niedersachsen" },
  { code: "HL", filename: "hl", name: "Lübeck", region: "Schleswig-Holstein" },
  { code: "HM", filename: "hm", name: "Hameln-Pyrmont", region: "Niedersachsen" },
  { code: "HMÜ", filename: "hmue", name: "Hildesheim (hist.)", region: "Niedersachsen" },
  { code: "HN", filename: "hn", name: "Heilbronn", region: "Baden-Württemberg" },
  { code: "HO", filename: "ho", name: "Hof", region: "Bayern" },
  { code: "HOES", filename: "hoes", name: "Sigmaringen (hist.)", region: "Baden-Württemberg" },
  { code: "HOG", filename: "hog", name: "Hof (Rehau hist.)", region: "Bayern" },
  { code: "HOH", filename: "hoh", name: "Holzminden (hist.)", region: "Niedersachsen" },
  { code: "HOL", filename: "hol", name: "Holzminden", region: "Niedersachsen" },
  { code: "HOM", filename: "hom", name: "Saarpfalz-Kreis (Homburg)", region: "Saarland", aliases: ["Homburg"] },
  { code: "HOR", filename: "hor", name: "Cham (Roding hist.)", region: "Bayern" },
  { code: "HOT", filename: "hot", name: "Hildburghausen", region: "Thüringen" },
  { code: "HP", filename: "hp", name: "Bergstraße (Heppenheim)", region: "Hessen", aliases: ["Heppenheim"] },
  { code: "HR", filename: "hr", name: "Hersfeld-Rotenburg", region: "Hessen" },
  { code: "HRO", filename: "hro", name: "Rostock", region: "Mecklenburg-Vorpommern" },
  { code: "HS", filename: "hs", name: "Heinsberg", region: "Nordrhein-Westfalen" },
  { code: "HSK", filename: "hsk", name: "Hochsauerlandkreis", region: "Nordrhein-Westfalen" },
  { code: "HST", filename: "hst", name: "Vorpommern-Rügen (Stralsund)", region: "Mecklenburg-Vorpommern", aliases: ["Stralsund"] },
  { code: "HU", filename: "hu", name: "Main-Kinzig-Kreis (Hanau)", region: "Hessen", aliases: ["Hanau"] },
  { code: "HÜN", filename: "huen", name: "Neunkirchen (Hüsten hist.)", region: "Nordrhein-Westfalen" },
  { code: "HUS", filename: "hus", name: "Nordfriesland (Husum)", region: "Schleswig-Holstein", aliases: ["Husum"] },
  { code: "HV", filename: "hv", name: "Saale-Holzland-Kreis", region: "Thüringen" },
  { code: "HVL", filename: "hvl", name: "Havelland", region: "Brandenburg" },
  { code: "HW", filename: "hw", name: "Nordwestmecklenburg (Wismar hist.)", region: "Mecklenburg-Vorpommern" },
  { code: "HWI", filename: "hwi", name: "Nordwestmecklenburg (Wismar)", region: "Mecklenburg-Vorpommern", aliases: ["Wismar"] },
  { code: "HX", filename: "hx", name: "Höxter", region: "Nordrhein-Westfalen" },
  { code: "HY", filename: "hy", name: "Bautzen (Hoyerswerda)", region: "Sachsen", aliases: ["Hoyerswerda"] },
  { code: "HZ", filename: "hz", name: "Anhalt-Bitterfeld", region: "Sachsen-Anhalt" },
  { code: "IF", filename: "if", name: "US-Streitkräfte", region: "Sonderkennzeichen" },
  { code: "IGB", filename: "igb", name: "Saarpfalz-Kreis (St. Ingbert)", region: "Saarland", aliases: ["St. Ingbert"] },
  { code: "IK", filename: "ik", name: "Ilm-Kreis", region: "Thüringen" },
  { code: "IL", filename: "il", name: "Ilm-Kreis (Ilmenau)", region: "Thüringen", aliases: ["Ilmenau"] },
  { code: "ILL", filename: "ill", name: "Neu-Ulm (Illertissen)", region: "Bayern", aliases: ["Illertissen"] },
  { code: "IN", filename: "in", name: "Ingolstadt", region: "Bayern" },
  { code: "IS", filename: "is", name: "Steinburg (Itzehoe)", region: "Schleswig-Holstein" },
  { code: "IZ", filename: "iz", name: "Steinburg (Itzehoe)", region: "Schleswig-Holstein" },
  { code: "J", filename: "j", name: "Jena", region: "Thüringen" },
  { code: "JB", filename: "jb", name: "Jerichower Land (Burg)", region: "Sachsen-Anhalt" },
  { code: "JE", filename: "je", name: "Wittenberg (Jessen)", region: "Sachsen-Anhalt", aliases: ["Jessen"] },
  { code: "JEV", filename: "jev", name: "Friesland (Jever)", region: "Niedersachsen", aliases: ["Jever"] },
  { code: "JL", filename: "jl", name: "Jerichower Land", region: "Sachsen-Anhalt" },
  { code: "JÜL", filename: "juel", name: "Jülich (Düren)", region: "Nordrhein-Westfalen", aliases: ["Jülich"] },
  { code: "K", filename: "k", name: "Köln", region: "Nordrhein-Westfalen" },
  { code: "KA", filename: "ka", name: "Karlsruhe", region: "Baden-Württemberg" },
  { code: "KAR", filename: "kar", name: "Karlsruhe (Land)", region: "Baden-Württemberg" },
  { code: "KB", filename: "kb", name: "Waldeck-Frankenberg (Korbach)", region: "Hessen", aliases: ["Korbach"] },
  { code: "KC", filename: "kc", name: "Kronach", region: "Bayern" },
  { code: "KE", filename: "ke", name: "Kempten (Allgäu)", region: "Bayern" },
  { code: "KEH", filename: "keh", name: "Kelheim", region: "Bayern" },
  { code: "KEL", filename: "kel", name: "Bernkastel-Wittlich (Bernkastel-Kues)", region: "Rheinland-Pfalz" },
  { code: "KEM", filename: "kem", name: "Tirschenreuth (Kemnath)", region: "Bayern", aliases: ["Kemnath"] },
  { code: "KF", filename: "kf", name: "Kaufbeuren", region: "Bayern" },
  { code: "KG", filename: "kg", name: "Bad Kissingen", region: "Bayern" },
  { code: "KH", filename: "kh", name: "Bad Kreuznach", region: "Rheinland-Pfalz" },
  { code: "KI", filename: "ki", name: "Kiel", region: "Schleswig-Holstein" },
  { code: "KIB", filename: "kib", name: "Donnersbergkreis", region: "Rheinland-Pfalz" },
  { code: "KK", filename: "kk", name: "Viersen (Kempen-Krefeld)", region: "Nordrhein-Westfalen", aliases: ["Kempen"] },
  { code: "KL", filename: "kl", name: "Kaiserslautern", region: "Rheinland-Pfalz" },
  { code: "KLE", filename: "kle", name: "Kleve", region: "Nordrhein-Westfalen" },
  { code: "KLZ", filename: "klz", name: "Altmarkkreis Salzwedel", region: "Sachsen-Anhalt" },
  { code: "KM", filename: "km", name: "Bautzen (Kamenz)", region: "Sachsen", aliases: ["Kamenz"] },
  { code: "KN", filename: "kn", name: "Konstanz", region: "Baden-Württemberg" },
  { code: "KO", filename: "ko", name: "Koblenz", region: "Rheinland-Pfalz" },
  { code: "KÖN", filename: "koen", name: "Rhön-Grabfeld (Bad Königshofen)", region: "Bayern", aliases: ["Bad Königshofen"] },
  { code: "KÖT", filename: "koet", name: "Anhalt-Bitterfeld (Köthen)", region: "Sachsen-Anhalt", aliases: ["Köthen"] },
  { code: "KÖZ", filename: "koez", name: "Cham (Kötzting)", region: "Bayern", aliases: ["Kötzting"] },
  { code: "KR", filename: "kr", name: "Krefeld", region: "Nordrhein-Westfalen" },
  { code: "KRU", filename: "kru", name: "Günzburg (Krumbach)", region: "Bayern", aliases: ["Krumbach"] },
  { code: "KS", filename: "ks", name: "Kassel", region: "Hessen" },
  { code: "KT", filename: "kt", name: "Kitzingen", region: "Bayern" },
  { code: "KU", filename: "ku", name: "Kulmbach", region: "Bayern" },
  { code: "KÜN", filename: "kuen", name: "Hohenlohekreis (Künzelsau)", region: "Baden-Württemberg", aliases: ["Künzelsau"] },
  { code: "KUS", filename: "kus", name: "Kusel", region: "Rheinland-Pfalz" },
  { code: "KW", filename: "kw", name: "Kyffhäuserkreis (Sondershausen hist.)", region: "Thüringen" },
  { code: "KY", filename: "ky", name: "Kyffhäuserkreis", region: "Thüringen" },
  { code: "KYF", filename: "kyf", name: "Kyffhäuserkreis", region: "Thüringen" },
  { code: "L", filename: "l", name: "Leipzig", region: "Sachsen" },
  { code: "LA", filename: "la", name: "Landshut", region: "Bayern" },
  { code: "LAN", filename: "lan", name: "Landsberg am Lech", region: "Bayern" },
  { code: "LAT", filename: "lat", name: "Landshut (hist.)", region: "Bayern" },
  { code: "LAU", filename: "lau", name: "Nürnberger Land (Lauf)", region: "Bayern", aliases: ["Lauf an der Pegnitz"] },
  { code: "LB", filename: "lb", name: "Ludwigsburg", region: "Baden-Württemberg" },
  { code: "LBS", filename: "lbs", name: "Saalfeld-Rudolstadt", region: "Thüringen" },
  { code: "LBZ", filename: "lbz", name: "Mecklenburgische Seenplatte (Waren hist.)", region: "Mecklenburg-Vorpommern" },
  { code: "LC", filename: "lc", name: "Elbe-Elster (Luckau)", region: "Brandenburg", aliases: ["Luckau"] },
  { code: "LD", filename: "ld", name: "Landau in der Pfalz", region: "Rheinland-Pfalz" },
  { code: "LDK", filename: "ldk", name: "Lahn-Dill-Kreis", region: "Hessen" },
  { code: "LDS", filename: "lds", name: "Dahme-Spreewald", region: "Brandenburg" },
  { code: "LE", filename: "le", name: "Leverkusen", region: "Nordrhein-Westfalen" },
  { code: "LEO", filename: "leo", name: "Böblingen (hist.)", region: "Baden-Württemberg" },
  { code: "LER", filename: "ler", name: "Leer", region: "Niedersachsen" },
  { code: "LEV", filename: "lev", name: "Leverkusen", region: "Nordrhein-Westfalen" },
  { code: "LF", filename: "lf", name: "Lüneburg (Lüchow hist.)", region: "Niedersachsen" },
  { code: "LG", filename: "lg", name: "Lüneburg", region: "Niedersachsen" },
  { code: "LH", filename: "lh", name: "Heidenheim (hist.)", region: "Baden-Württemberg" },
  { code: "LI", filename: "li", name: "Lindau (Bodensee)", region: "Bayern" },
  { code: "LIB", filename: "lib", name: "Saale-Orla-Kreis", region: "Thüringen" },
  { code: "LIF", filename: "lif", name: "Lichtenfels", region: "Bayern" },
  { code: "LIN", filename: "lin", name: "Emsland (Lingen)", region: "Niedersachsen", aliases: ["Lingen"] },
  { code: "LIP", filename: "lip", name: "Lippe", region: "Nordrhein-Westfalen" },
  { code: "LK", filename: "lk", name: "Landsberg am Lech (hist.)", region: "Bayern" },
  { code: "LL", filename: "ll", name: "Landsberg am Lech", region: "Bayern" },
  { code: "LM", filename: "lm", name: "Limburg-Weilburg", region: "Hessen" },
  { code: "LN", filename: "ln", name: "Lüchow-Dannenberg", region: "Niedersachsen" },
  { code: "LÖ", filename: "loe", name: "Lörrach", region: "Baden-Württemberg" },
  { code: "LÖB", filename: "loeb", name: "Görlitz (Löbau)", region: "Sachsen", aliases: ["Löbau"] },
  { code: "LOH", filename: "loh", name: "Northeim (Einbeck hist.)", region: "Niedersachsen" },
  { code: "LOS", filename: "los", name: "Oder-Spree", region: "Brandenburg" },
  { code: "LP", filename: "lp", name: "Wittenberg (Lutherstadt Wittenberg hist.)", region: "Sachsen-Anhalt" },
  { code: "LR", filename: "lr", name: "Hildburghausen (hist.)", region: "Thüringen" },
  { code: "LRO", filename: "lro", name: "Landkreis Rostock", region: "Mecklenburg-Vorpommern" },
  { code: "LS", filename: "ls", name: "Mettmann", region: "Nordrhein-Westfalen" },
  { code: "LSA", filename: "lsa", name: "Landesregierung Sachsen-Anhalt", region: "Sonderkennzeichen" },
  { code: "LSN", filename: "lsn", name: "Landesregierung Sachsen", region: "Sonderkennzeichen" },
  { code: "LSZ", filename: "lsz", name: "Saalekreis", region: "Sachsen-Anhalt" },
  { code: "LU", filename: "lu", name: "Ludwigshafen am Rhein", region: "Rheinland-Pfalz" },
  { code: "LÜD", filename: "lued", name: "Lüdenscheid (Märkischer Kreis)", region: "Nordrhein-Westfalen", aliases: ["Lüdenscheid"] },
  { code: "LÜN", filename: "luen", name: "Lüneburg", region: "Niedersachsen" },
  { code: "LUK", filename: "luk", name: "Elbe-Elster (Luckau)", region: "Brandenburg" },
  { code: "LUP", filename: "lup", name: "Ludwigslust-Parchim", region: "Mecklenburg-Vorpommern" },
  { code: "LWL", filename: "lwl", name: "Ludwigslust-Parchim", region: "Mecklenburg-Vorpommern" },
  { code: "M", filename: "m", name: "München", region: "Bayern" },
  { code: "MA", filename: "ma", name: "Mannheim", region: "Baden-Württemberg" },
  { code: "MAB", filename: "mab", name: "Erzgebirgskreis (Marienberg)", region: "Sachsen", aliases: ["Marienberg"] },
  { code: "MAI", filename: "mai", name: "Kelheim (Mainburg)", region: "Bayern", aliases: ["Mainburg"] },
  { code: "MAK", filename: "mak", name: "Ansbach (Wassertrüdingen hist.)", region: "Bayern" },
  { code: "MAL", filename: "mal", name: "Miesbach", region: "Bayern" },
  { code: "MAR", filename: "mar", name: "Marburg-Biedenkopf", region: "Hessen" },
  { code: "MB", filename: "mb", name: "Miesbach", region: "Bayern" },
  { code: "MC", filename: "mc", name: "Mecklenburgische Seenplatte", region: "Mecklenburg-Vorpommern" },
  { code: "MD", filename: "md", name: "Magdeburg", region: "Sachsen-Anhalt" },
  { code: "ME", filename: "me", name: "Mettmann", region: "Nordrhein-Westfalen" },
  { code: "MED", filename: "med", name: "Schwabach (hist.)", region: "Bayern" },
  { code: "MEG", filename: "meg", name: "Schwabach", region: "Bayern" },
  { code: "MEI", filename: "mei", name: "Meißen", region: "Sachsen" },
  { code: "MEK", filename: "mek", name: "Erzgebirgskreis", region: "Sachsen" },
  { code: "MEL", filename: "mel", name: "Nienburg (Weser) (hist.)", region: "Niedersachsen" },
  { code: "MEP", filename: "mep", name: "Emsland (Meppen)", region: "Niedersachsen", aliases: ["Meppen"] },
  { code: "MER", filename: "mer", name: "Saalekreis (Merseburg)", region: "Sachsen-Anhalt", aliases: ["Merseburg"] },
  { code: "MES", filename: "mes", name: "Augsburg (Mering hist.)", region: "Bayern" },
  { code: "MET", filename: "met", name: "Ansbach (Feuchtwangen hist.)", region: "Bayern" },
  { code: "MG", filename: "mg", name: "Mönchengladbach", region: "Nordrhein-Westfalen" },
  { code: "MGH", filename: "mgh", name: "Hohenlohekreis (Mergentheim hist.)", region: "Baden-Württemberg", aliases: ["Bad Mergentheim"] },
  { code: "MGN", filename: "mgn", name: "Schmalkalden-Meiningen", region: "Thüringen" },
  { code: "MH", filename: "mh", name: "Mülheim an der Ruhr", region: "Nordrhein-Westfalen" },
  { code: "MHL", filename: "mhl", name: "Unstrut-Hainich-Kreis (Mühlhausen)", region: "Thüringen", aliases: ["Mühlhausen"] },
  { code: "MI", filename: "mi", name: "Minden-Lübbecke", region: "Nordrhein-Westfalen" },
  { code: "MIL", filename: "mil", name: "Miltenberg", region: "Bayern" },
  { code: "MK", filename: "mk", name: "Märkischer Kreis", region: "Nordrhein-Westfalen" },
  { code: "MKK", filename: "mkk", name: "Main-Kinzig-Kreis", region: "Hessen" },
  { code: "ML", filename: "ml", name: "Burgenlandkreis", region: "Sachsen-Anhalt" },
  { code: "MM", filename: "mm", name: "Memmingen", region: "Bayern" },
  { code: "MN", filename: "mn", name: "Unterallgäu (Mindelheim)", region: "Bayern", aliases: ["Mindelheim"] },
  { code: "MO", filename: "mo", name: "Rhein-Lahn-Kreis (Montabaur)", region: "Rheinland-Pfalz", aliases: ["Montabaur"] },
  { code: "MOD", filename: "mod", name: "Amberg-Sulzbach", region: "Bayern" },
  { code: "MOL", filename: "mol", name: "Märkisch-Oderland", region: "Brandenburg" },
  { code: "MON", filename: "mon", name: "Cochem-Zell (hist.)", region: "Rheinland-Pfalz" },
  { code: "MOS", filename: "mos", name: "Neckar-Odenwald-Kreis", region: "Baden-Württemberg" },
  { code: "MQ", filename: "mq", name: "Anhalt-Bitterfeld", region: "Sachsen-Anhalt" },
  { code: "MR", filename: "mr", name: "Marburg-Biedenkopf", region: "Hessen" },
  { code: "MS", filename: "ms", name: "Münster", region: "Nordrhein-Westfalen" },
  { code: "MSE", filename: "mse", name: "Mecklenburgische Seenplatte", region: "Mecklenburg-Vorpommern" },
  { code: "MSH", filename: "msh", name: "Mansfeld-Südharz", region: "Sachsen-Anhalt" },
  { code: "MSP", filename: "msp", name: "Main-Spessart", region: "Bayern" },
  { code: "MST", filename: "mst", name: "Mecklenburgische Seenplatte (Mecklenburg-Strelitz)", region: "Mecklenburg-Vorpommern", aliases: ["Mecklenburg-Strelitz"] },
  { code: "MT", filename: "mt", name: "Marburg-Biedenkopf", region: "Hessen" },
  { code: "MTK", filename: "mtk", name: "Main-Taunus-Kreis", region: "Hessen" },
  { code: "MTL", filename: "mtl", name: "Leipzig (Muldentalkreis)", region: "Sachsen", aliases: ["Muldentalkreis"] },
  { code: "MU", filename: "mu", name: "Murnau am Staffelsee (hist.)", region: "Bayern" },
  { code: "MÜ", filename: "mü", name: "Mühldorf am Inn", region: "Bayern" },
  { code: "MÜ", filename: "mue", name: "Mühldorf am Inn", region: "Bayern" },
  { code: "MÜB", filename: "mueb", name: "Rosenheim (Mühldorf hist.)", region: "Bayern" },
  { code: "MÜL", filename: "muel", name: "Zwickau (Mülsen hist.)", region: "Sachsen", aliases: ["Mülsen"] },
  { code: "MÜN", filename: "muen", name: "München", region: "Bayern" },
  { code: "MÜR", filename: "muer", name: "Mecklenburgische Seenplatte (Müritz)", region: "Mecklenburg-Vorpommern", aliases: ["Müritz"] },
  { code: "MVL", filename: "mvl", name: "Landesregierung Mecklenburg-Vorpommern", region: "Sonderkennzeichen" },
  { code: "MW", filename: "mw", name: "Mittelsachsen (Mittweida)", region: "Sachsen", aliases: ["Mittweida"] },
  { code: "MY", filename: "my", name: "Mayen-Koblenz", region: "Rheinland-Pfalz" },
  { code: "MYK", filename: "myk", name: "Mayen-Koblenz", region: "Rheinland-Pfalz" },
  { code: "MZ", filename: "mz", name: "Mainz", region: "Rheinland-Pfalz" },
  { code: "MZG", filename: "mzg", name: "Merzig-Wadern", region: "Saarland" },
  { code: "N", filename: "n", name: "Nürnberg", region: "Bayern" },
  { code: "NAB", filename: "nab", name: "Schwandorf (Nabburg)", region: "Bayern", aliases: ["Nabburg"] },
  { code: "NAI", filename: "nai", name: "Wunsiedel (Naila)", region: "Bayern", aliases: ["Naila"] },
  { code: "NAU", filename: "nau", name: "Stendal (Nauen)", region: "Brandenburg", aliases: ["Nauen"] },
  { code: "NB", filename: "nb", name: "Mecklenburgische Seenplatte (Neubrandenburg)", region: "Mecklenburg-Vorpommern", aliases: ["Neubrandenburg"] },
  { code: "ND", filename: "nd", name: "Neuburg-Schrobenhausen", region: "Bayern" },
  { code: "NDH", filename: "ndh", name: "Nordhausen", region: "Thüringen" },
  { code: "NE", filename: "ne", name: "Rhein-Kreis Neuss", region: "Nordrhein-Westfalen" },
  { code: "NEA", filename: "nea", name: "Neustadt an der Aisch-Bad Windsheim", region: "Bayern" },
  { code: "NEB", filename: "neb", name: "Burgenlandkreis (Nebra)", region: "Sachsen-Anhalt", aliases: ["Nebra"] },
  { code: "NEC", filename: "nec", name: "Coburg (Zweckverband Zulassungsstelle)", region: "Bayern" },
  { code: "NEN", filename: "nen", name: "Neumarkt i.d.OPf. (hist.)", region: "Bayern" },
  { code: "NES", filename: "nes", name: "Rhön-Grabfeld (Bad Neustadt a.d.S.)", region: "Bayern", aliases: ["Bad Neustadt an der Saale"] },
  { code: "NEU", filename: "neu", name: "Neuwied", region: "Rheinland-Pfalz" },
  { code: "NEW", filename: "new", name: "Neustadt an der Waldnaab", region: "Bayern" },
  { code: "NF", filename: "nf", name: "Nordfriesland", region: "Schleswig-Holstein" },
  { code: "NH", filename: "nh", name: "Nordhausen (hist.)", region: "Thüringen" },
  { code: "NI", filename: "ni", name: "Nienburg (Weser)", region: "Niedersachsen" },
  { code: "NIB", filename: "nib", name: "Sigmaringen (hist.)", region: "Baden-Württemberg" },
  { code: "NK", filename: "nk", name: "Neunkirchen", region: "Saarland" },
  { code: "NL", filename: "nl", name: "Landesregierung Niedersachsen", region: "Sonderkennzeichen" },
  { code: "NM", filename: "nm", name: "Neumarkt in der Oberpfalz", region: "Bayern" },
  { code: "NMB", filename: "nmb", name: "Burgenlandkreis (Naumburg)", region: "Sachsen-Anhalt", aliases: ["Naumburg"] },
  { code: "NMS", filename: "nms", name: "Neumünster", region: "Schleswig-Holstein" },
  { code: "NOE", filename: "noe", name: "Vogtlandkreis (Netzschkau hist.)", region: "Sachsen" },
  { code: "NOH", filename: "noh", name: "Grafschaft Bentheim", region: "Niedersachsen" },
  { code: "NOL", filename: "nol", name: "Görlitz (Niederschlesischer Oberlausitzkreis)", region: "Sachsen" },
  { code: "NOM", filename: "nom", name: "Northeim", region: "Niedersachsen" },
  { code: "NOR", filename: "nor", name: "Nordfriesland", region: "Schleswig-Holstein" },
  { code: "NP", filename: "np", name: "Havelland (Neuruppin hist.)", region: "Brandenburg" },
  { code: "NR", filename: "nr", name: "Neuwied", region: "Rheinland-Pfalz" },
  { code: "NRÜ", filename: "nrue", name: "Nordrhein-Westfalen (hist.)", region: "Nordrhein-Westfalen" },
  { code: "NRW", filename: "nrw", name: "Landesregierung Nordrhein-Westfalen", region: "Sonderkennzeichen" },
  { code: "NT", filename: "nt", name: "Rems-Murr-Kreis (Backnang hist.)", region: "Baden-Württemberg" },
  { code: "NU", filename: "nu", name: "Neu-Ulm", region: "Bayern" },
  { code: "NVP", filename: "nvp", name: "Vorpommern-Rügen (Nordvorpommern)", region: "Mecklenburg-Vorpommern", aliases: ["Nordvorpommern"] },
  { code: "NW", filename: "nw", name: "Neustadt an der Weinstraße", region: "Rheinland-Pfalz" },
  { code: "NWM", filename: "nwm", name: "Nordwestmecklenburg", region: "Mecklenburg-Vorpommern" },
  { code: "NY", filename: "ny", name: "Mecklenburgische Seenplatte", region: "Mecklenburg-Vorpommern" },
  { code: "NZ", filename: "nz", name: "Mecklenburgische Seenplatte", region: "Mecklenburg-Vorpommern" },
  { code: "OA", filename: "oa", name: "Oberallgäu", region: "Bayern" },
  { code: "OAL", filename: "oal", name: "Ostallgäu", region: "Bayern" },
  { code: "OB", filename: "ob", name: "Oberhausen", region: "Nordrhein-Westfalen" },
  { code: "OBB", filename: "obb", name: "München (hist.)", region: "Bayern" },
  { code: "OBG", filename: "obg", name: "Havelland (Oranienburg hist.)", region: "Brandenburg" },
  { code: "OC", filename: "oc", name: "Elbe-Elster (Herzberg hist.)", region: "Brandenburg" },
  { code: "OCH", filename: "och", name: "Würzburg (Ochsenfurt)", region: "Bayern", aliases: ["Ochsenfurt"] },
  { code: "OD", filename: "od", name: "Stormarn", region: "Schleswig-Holstein" },
  { code: "OE", filename: "oe", name: "Olpe", region: "Nordrhein-Westfalen" },
  { code: "ÖHR", filename: "oehr", name: "Sigmaringen (Burg Hohenzollern / hist.)", region: "Baden-Württemberg" },
  { code: "OF", filename: "of", name: "Offenbach am Main", region: "Hessen" },
  { code: "OG", filename: "og", name: "Ortenaukreis", region: "Baden-Württemberg" },
  { code: "OH", filename: "oh", name: "Ostholstein", region: "Schleswig-Holstein" },
  { code: "OHA", filename: "oha", name: "Osterode am Harz", region: "Niedersachsen" },
  { code: "OHV", filename: "ohv", name: "Oberhavel", region: "Brandenburg" },
  { code: "OHZ", filename: "ohz", name: "Osterholz", region: "Niedersachsen" },
  { code: "OK", filename: "ok", name: "Börde", region: "Sachsen-Anhalt" },
  { code: "OL", filename: "ol", name: "Oldenburg (Oldb)", region: "Niedersachsen" },
  { code: "OLD", filename: "old", name: "Oldenburg (Oldb)", region: "Niedersachsen" },
  { code: "OP", filename: "op", name: "Oldenburg (Oldb) (hist.)", region: "Niedersachsen" },
  { code: "OPR", filename: "opr", name: "Ostprignitz-Ruppin", region: "Brandenburg" },
  { code: "OR", filename: "or", name: "Havelland (Oranienburg hist.)", region: "Brandenburg" },
  { code: "OS", filename: "os", name: "Osnabrück", region: "Niedersachsen" },
  { code: "OSL", filename: "osl", name: "Oberspreewald-Lausitz", region: "Brandenburg" },
  { code: "OTT", filename: "ott", name: "Nordwestmecklenburg (hist.)", region: "Mecklenburg-Vorpommern" },
  { code: "OTW", filename: "otw", name: "Lüchow-Dannenberg (hist.)", region: "Niedersachsen" },
  { code: "OVI", filename: "ovi", name: "Schwandorf", region: "Bayern" },
  { code: "OVL", filename: "ovl", name: "Görlitz", region: "Sachsen" },
  { code: "OVP", filename: "ovp", name: "Vorpommern-Greifswald (Ostvorpommern)", region: "Mecklenburg-Vorpommern", aliases: ["Ostvorpommern"] },
  { code: "OZ", filename: "oz", name: "Nordsachsen (Oschatz)", region: "Sachsen", aliases: ["Oschatz"] },
  { code: "P", filename: "p", name: "Potsdam", region: "Brandenburg" },
  { code: "PA", filename: "pa", name: "Passau", region: "Bayern" },
  { code: "PAF", filename: "paf", name: "Pfaffenhofen an der Ilm", region: "Bayern" },
  { code: "PAN", filename: "pan", name: "Rottal-Inn (Pfarrkirchen)", region: "Bayern", aliases: ["Pfarrkirchen"] },
  { code: "PAR", filename: "par", name: "Regensburg (Parsberg)", region: "Bayern", aliases: ["Parsberg"] },
  { code: "PB", filename: "pb", name: "Paderborn", region: "Nordrhein-Westfalen" },
  { code: "PCH", filename: "pch", name: "Ludwigslust-Parchim (Parchim)", region: "Mecklenburg-Vorpommern", aliases: ["Parchim"] },
  { code: "PE", filename: "pe", name: "Peine", region: "Niedersachsen" },
  { code: "PEG", filename: "peg", name: "Bayreuth (Pegnitz)", region: "Bayern", aliases: ["Pegnitz"] },
  { code: "PER", filename: "per", name: "Oberspreewald-Lausitz (Senftenberg hist.)", region: "Brandenburg" },
  { code: "PF", filename: "pf", name: "Pforzheim", region: "Baden-Württemberg" },
  { code: "PI", filename: "pi", name: "Pinneberg", region: "Schleswig-Holstein" },
  { code: "PIR", filename: "pir", name: "Sächsische Schweiz-Osterzgebirge (Pirna)", region: "Sachsen", aliases: ["Pirna"] },
  { code: "PK", filename: "pk", name: "Saale-Orla-Kreis", region: "Thüringen" },
  { code: "PL", filename: "pl", name: "Vogtlandkreis (Plauen)", region: "Sachsen", aliases: ["Plauen"] },
  { code: "PLÖ", filename: "ploe", name: "Plön", region: "Schleswig-Holstein" },
  { code: "PM", filename: "pm", name: "Potsdam-Mittelmark", region: "Brandenburg" },
  { code: "PN", filename: "pn", name: "Weimarer Land", region: "Thüringen" },
  { code: "PR", filename: "pr", name: "Prignitz", region: "Brandenburg" },
  { code: "PRÜ", filename: "prue", name: "Eifelkreis Bitburg-Prüm (hist.)", region: "Rheinland-Pfalz", aliases: ["Prüm"] },
  { code: "PS", filename: "ps", name: "Pirmasens", region: "Rheinland-Pfalz" },
  { code: "PW", filename: "pw", name: "Saale-Orla-Kreis", region: "Thüringen" },
  { code: "PZ", filename: "pz", name: "Saale-Orla-Kreis (Pößneck hist.)", region: "Thüringen", aliases: ["Pößneck"] },
  { code: "QFT", filename: "qft", name: "Saalekreis (Querfurt)", region: "Sachsen-Anhalt", aliases: ["Querfurt"] },
  { code: "QLB", filename: "qlb", name: "Harz (Quedlinburg)", region: "Sachsen-Anhalt", aliases: ["Quedlinburg"] },
  { code: "R", filename: "r", name: "Regensburg", region: "Bayern" },
  { code: "RA", filename: "ra", name: "Rastatt", region: "Baden-Württemberg" },
  { code: "RC", filename: "rc", name: "Zwickau (Reichenbach)", region: "Sachsen", aliases: ["Reichenbach"] },
  { code: "RD", filename: "rd", name: "Rendsburg-Eckernförde", region: "Schleswig-Holstein" },
  { code: "RDG", filename: "rdg", name: "Vorpommern-Rügen (Rügen)", region: "Mecklenburg-Vorpommern" },
  { code: "RE", filename: "re", name: "Recklinghausen", region: "Nordrhein-Westfalen" },
  { code: "REG", filename: "reg", name: "Regen", region: "Bayern" },
  { code: "REH", filename: "reh", name: "Straubing-Bogen (Regen hist.)", region: "Bayern" },
  { code: "REI", filename: "rei", name: "Berchtesgadener Land (Bad Reichenhall)", region: "Bayern", aliases: ["Bad Reichenhall"] },
  { code: "RG", filename: "rg", name: "Meißen (Riesa-Großenhain)", region: "Sachsen", aliases: ["Riesa"] },
  { code: "RH", filename: "rh", name: "Roth", region: "Bayern" },
  { code: "RI", filename: "ri", name: "Steinfurt (Rheine hist.)", region: "Nordrhein-Westfalen" },
  { code: "RID", filename: "rid", name: "Straubing-Bogen (Riedenburg)", region: "Bayern", aliases: ["Riedenburg"] },
  { code: "RIE", filename: "rie", name: "Mittelsachsen (Flöha hist.)", region: "Sachsen" },
  { code: "RL", filename: "rl", name: "Mittelsachsen (Rochlitz)", region: "Sachsen", aliases: ["Rochlitz"] },
  { code: "RM", filename: "rm", name: "Vorpommern-Rügen", region: "Mecklenburg-Vorpommern" },
  { code: "RN", filename: "rn", name: "Vorpommern-Rügen (hist.)", region: "Mecklenburg-Vorpommern" },
  { code: "RO", filename: "ro", name: "Rosenheim", region: "Bayern" },
  { code: "ROD", filename: "rod", name: "Cham (Roding)", region: "Bayern", aliases: ["Roding"] },
  { code: "ROF", filename: "rof", name: "Vogelsbergkreis (Lauterbach hist.)", region: "Hessen" },
  { code: "ROK", filename: "rok", name: "Cham (hist.)", region: "Bayern" },
  { code: "ROL", filename: "rol", name: "Ansbach (Rothenburg hist.)", region: "Bayern" },
  { code: "ROS", filename: "ros", name: "Landkreis Rostock", region: "Mecklenburg-Vorpommern" },
  { code: "ROT", filename: "rot", name: "Ansbach (Rothenburg ob der Tauber)", region: "Bayern", aliases: ["Rothenburg ob der Tauber"] },
  { code: "ROW", filename: "row", name: "Rotenburg (Wümme)", region: "Niedersachsen" },
  { code: "RP", filename: "rp", name: "Rhein-Pfalz-Kreis", region: "Rheinland-Pfalz" },
  { code: "RPL", filename: "rpl", name: "Landesregierung Rheinland-Pfalz", region: "Sonderkennzeichen" },
  { code: "RS", filename: "rs", name: "Remscheid", region: "Nordrhein-Westfalen" },
  { code: "RSL", filename: "rsl", name: "Saalfeld-Rudolstadt", region: "Thüringen" },
  { code: "RT", filename: "rt", name: "Reutlingen", region: "Baden-Württemberg" },
  { code: "RU", filename: "ru", name: "Saalfeld-Rudolstadt", region: "Thüringen" },
  { code: "RÜD", filename: "rued", name: "Rheingau-Taunus-Kreis", region: "Hessen" },
  { code: "RÜG", filename: "rueg", name: "Vorpommern-Rügen", region: "Mecklenburg-Vorpommern" },
  { code: "RV", filename: "rv", name: "Ravensburg", region: "Baden-Württemberg" },
  { code: "RW", filename: "rw", name: "Rottweil", region: "Baden-Württemberg" },
  { code: "RY", filename: "ry", name: "Heinsberg (hist.)", region: "Nordrhein-Westfalen" },
  { code: "RZ", filename: "rz", name: "Herzogtum Lauenburg", region: "Schleswig-Holstein" },
  { code: "S", filename: "s", name: "Stuttgart", region: "Baden-Württemberg" },
  { code: "SAB", filename: "sab", name: "Würzburg (Karlstadt hist.)", region: "Bayern" },
  { code: "SAD", filename: "sad", name: "Schwandorf", region: "Bayern" },
  { code: "SÄK", filename: "saek", name: "Sigmaringen (Stockach hist.)", region: "Baden-Württemberg" },
  { code: "SAL", filename: "sal", name: "Saarpfalz-Kreis", region: "Saarland" },
  { code: "SAN", filename: "san", name: "Neustadt a.d.A. (Rothenburg hist.)", region: "Bayern" },
  { code: "SAW", filename: "saw", name: "Altmarkkreis Salzwedel", region: "Sachsen-Anhalt" },
  { code: "SB", filename: "sb", name: "Saarbrücken", region: "Saarland" },
  { code: "SBG", filename: "sbg", name: "Saalfeld-Rudolstadt", region: "Thüringen" },
  { code: "SBK", filename: "sbk", name: "Salzlandkreis (Schönebeck)", region: "Sachsen-Anhalt", aliases: ["Schönebeck"] },
  { code: "SC", filename: "sc", name: "Schwabach", region: "Bayern" },
  { code: "SCZ", filename: "scz", name: "Zwickau", region: "Sachsen" },
  { code: "SDH", filename: "sdh", name: "Kyffhäuserkreis (Sondershausen)", region: "Thüringen", aliases: ["Sondershausen"] },
  { code: "SDL", filename: "sdl", name: "Stendal", region: "Sachsen-Anhalt" },
  { code: "SDT", filename: "sdt", name: "Stendal (hist.)", region: "Sachsen-Anhalt" },
  { code: "SE", filename: "se", name: "Segeberg", region: "Schleswig-Holstein" },
  { code: "SEB", filename: "seb", name: "Görlitz (Sebnitz hist.)", region: "Sachsen", aliases: ["Sebnitz"] },
  { code: "SEE", filename: "see", name: "Jerichower Land", region: "Sachsen-Anhalt" },
  { code: "SEF", filename: "sef", name: "Neustadt a.d.A. (Scheinfeld hist.)", region: "Bayern" },
  { code: "SEL", filename: "sel", name: "Schwalm-Eder-Kreis (Schwalmstadt)", region: "Hessen", aliases: ["Schwalmstadt"] },
  { code: "SF", filename: "sf", name: "Spree-Neiße (Spremberg hist.)", region: "Brandenburg" },
  { code: "SFA", filename: "sfa", name: "Mecklenburg (hist.)", region: "Mecklenburg-Vorpommern" },
  { code: "SFB", filename: "sfb", name: "Oberspreewald-Lausitz (Senftenberg)", region: "Brandenburg", aliases: ["Senftenberg"] },
  { code: "SFT", filename: "sft", name: "Mansfeld-Südharz (Sangerhausen)", region: "Sachsen-Anhalt", aliases: ["Sangerhausen"] },
  { code: "SG", filename: "sg", name: "Schwäbisch Gmünd (Ostalbkreis)", region: "Baden-Württemberg", aliases: ["Schwäbisch Gmünd"] },
  { code: "SGH", filename: "sgh", name: "Mansfeld-Südharz", region: "Sachsen-Anhalt" },
  { code: "SHA", filename: "sha", name: "Schwäbisch Hall", region: "Baden-Württemberg" },
  { code: "SHG", filename: "shg", name: "Schaumburg", region: "Niedersachsen" },
  { code: "SHK", filename: "shk", name: "Saale-Holzland-Kreis", region: "Thüringen" },
  { code: "SHL", filename: "shl", name: "Hildburghausen (Suhl)", region: "Thüringen", aliases: ["Suhl"] },
  { code: "SI", filename: "si", name: "Siegen-Wittgenstein", region: "Nordrhein-Westfalen" },
  { code: "SIG", filename: "sig", name: "Sigmaringen", region: "Baden-Württemberg" },
  { code: "SIM", filename: "sim", name: "Rhein-Hunsrück-Kreis (Simmern)", region: "Rheinland-Pfalz", aliases: ["Simmern"] },
  { code: "SK", filename: "sk", name: "Sächsische Schweiz-Osterzgebirge", region: "Sachsen" },
  { code: "SL", filename: "sl", name: "Schleswig-Flensburg", region: "Schleswig-Holstein" },
  { code: "SLE", filename: "sle", name: "Cochem-Zell (hist.)", region: "Rheinland-Pfalz" },
  { code: "SLF", filename: "slf", name: "Saalfeld-Rudolstadt", region: "Thüringen" },
  { code: "SLG", filename: "slg", name: "Böblingen (Leonberg hist.)", region: "Baden-Württemberg" },
  { code: "SLK", filename: "slk", name: "Salzlandkreis", region: "Sachsen-Anhalt" },
  { code: "SLN", filename: "sln", name: "Saale-Orla-Kreis", region: "Thüringen" },
  { code: "SLS", filename: "sls", name: "Saarlouis", region: "Saarland" },
  { code: "SLÜ", filename: "slue", name: "Schleswig-Flensburg (Schleswig)", region: "Schleswig-Holstein", aliases: ["Schleswig"] },
  { code: "SLZ", filename: "slz", name: "Schmalkalden-Meiningen", region: "Thüringen" },
  { code: "SM", filename: "sm", name: "Schmalkalden-Meiningen", region: "Thüringen" },
  { code: "SMÜ", filename: "smue", name: "Schmalkalden-Meiningen", region: "Thüringen" },
  { code: "SN", filename: "sn", name: "Ludwigslust-Parchim (Schwerin hist.)", region: "Mecklenburg-Vorpommern" },
  { code: "SNH", filename: "snh", name: "Northeim", region: "Niedersachsen" },
  { code: "SO", filename: "so", name: "Soest", region: "Nordrhein-Westfalen" },
  { code: "SOB", filename: "sob", name: "Neuburg-Schrobenhausen (Schrobenhausen)", region: "Bayern", aliases: ["Schrobenhausen"] },
  { code: "SÖM", filename: "soem", name: "Sömmerda", region: "Thüringen" },
  { code: "SOG", filename: "sog", name: "Garmisch-Partenkirchen (Schongau)", region: "Bayern", aliases: ["Schongau"] },
  { code: "SOK", filename: "sok", name: "Saale-Orla-Kreis", region: "Thüringen" },
  { code: "SOL", filename: "sol", name: "Rhein-Lahn-Kreis (Westerburg hist.)", region: "Rheinland-Pfalz" },
  { code: "SON", filename: "son", name: "Sonneberg", region: "Thüringen" },
  { code: "SP", filename: "sp", name: "Speyer", region: "Rheinland-Pfalz" },
  { code: "SPB", filename: "spb", name: "Dahme-Spreewald (Lübben/Spreewald)", region: "Brandenburg", aliases: ["Lübben"] },
  { code: "SPN", filename: "spn", name: "Spree-Neiße", region: "Brandenburg" },
  { code: "SPR", filename: "spr", name: "Dahme-Spreewald (hist.)", region: "Brandenburg" },
  { code: "SR", filename: "sr", name: "Straubing", region: "Bayern" },
  { code: "SRB", filename: "srb", name: "Vorpommern-Rügen", region: "Mecklenburg-Vorpommern" },
  { code: "SRO", filename: "sro", name: "Saalfeld-Rudolstadt", region: "Thüringen" },
  { code: "ST", filename: "st", name: "Steinfurt", region: "Nordrhein-Westfalen" },
  { code: "STA", filename: "sta", name: "Starnberg", region: "Bayern" },
  { code: "STB", filename: "stb", name: "Nordwestmecklenburg (Sternberg)", region: "Mecklenburg-Vorpommern", aliases: ["Sternberg"] },
  { code: "STD", filename: "std", name: "Stade", region: "Niedersachsen" },
  { code: "STE", filename: "ste", name: "Gotha (Stadtilm hist.)", region: "Thüringen" },
  { code: "STH", filename: "sth", name: "Hildburghausen", region: "Thüringen" },
  { code: "STL", filename: "stl", name: "Zwickau (Stollberg)", region: "Sachsen", aliases: ["Stollberg"] },
  { code: "STO", filename: "sto", name: "Konstanz (Stockach)", region: "Baden-Württemberg", aliases: ["Stockach"] },
  { code: "SU", filename: "su", name: "Rhein-Sieg-Kreis", region: "Nordrhein-Westfalen" },
  { code: "SÜW", filename: "suew", name: "Südliche Weinstraße", region: "Rheinland-Pfalz" },
  { code: "SUL", filename: "sul", name: "Amberg-Sulzbach (Sulzbach-Rosenberg)", region: "Bayern", aliases: ["Sulzbach-Rosenberg"] },
  { code: "SW", filename: "sw", name: "Schweinfurt", region: "Bayern" },
  { code: "SWA", filename: "swa", name: "Waldeck-Frankenberg (Schwalmstadt hist.)", region: "Hessen" },
  { code: "SY", filename: "sy", name: "Nordfriesland (Sylt)", region: "Schleswig-Holstein", aliases: ["Sylt"] },
  { code: "SZ", filename: "sz", name: "Schwarzwald-Baar-Kreis (hist.)", region: "Baden-Württemberg" },
  { code: "SZB", filename: "szb", name: "Erzgebirgskreis (Schwarzenberg)", region: "Sachsen", aliases: ["Schwarzenberg"] },
  { code: "TBB", filename: "tbb", name: "Main-Tauber-Kreis (Tauberbischofsheim)", region: "Baden-Württemberg", aliases: ["Tauberbischofsheim"] },
  { code: "TDO", filename: "tdo", name: "Nordsachsen (Torgau-Delitzsch-Oschatz)", region: "Sachsen", aliases: ["Torgau","Delitzsch","Oschatz"] },
  { code: "TE", filename: "te", name: "Borken (Ahaus hist.)", region: "Nordrhein-Westfalen" },
  { code: "TET", filename: "tet", name: "Nordwestmecklenburg", region: "Mecklenburg-Vorpommern" },
  { code: "TF", filename: "tf", name: "Teltow-Fläming", region: "Brandenburg" },
  { code: "TG", filename: "tg", name: "Nordsachsen (Torgau)", region: "Sachsen", aliases: ["Torgau"] },
  { code: "THL", filename: "thl", name: "Landesregierung Thüringen", region: "Sonderkennzeichen" },
  { code: "THW", filename: "thw", name: "Technisches Hilfswerk", region: "Sonderkennzeichen" },
  { code: "TIR", filename: "tir", name: "Tirschenreuth", region: "Bayern" },
  { code: "TO", filename: "to", name: "Nordsachsen", region: "Sachsen" },
  { code: "TÖL", filename: "toel", name: "Bad Tölz-Wolfratshausen", region: "Bayern", aliases: ["Bad Tölz"] },
  { code: "TÖN", filename: "toen", name: "Nordfriesland (Tönning hist.)", region: "Schleswig-Holstein", aliases: ["Tönning"] },
  { code: "TP", filename: "tp", name: "Saale-Orla-Kreis (hist.)", region: "Thüringen" },
  { code: "TR", filename: "tr", name: "Trier", region: "Rheinland-Pfalz" },
  { code: "TS", filename: "ts", name: "Traunstein", region: "Bayern" },
  { code: "TT", filename: "tt", name: "Calw (Nagold hist.)", region: "Baden-Württemberg" },
  { code: "TÜ", filename: "tue", name: "Tübingen", region: "Baden-Württemberg" },
  { code: "TUT", filename: "tut", name: "Tuttlingen", region: "Baden-Württemberg" },
  { code: "UE", filename: "ue", name: "Uelzen", region: "Niedersachsen" },
  { code: "UEB", filename: "ueb", name: "Oldenburg (Oldb) (Ammerland hist.)", region: "Niedersachsen" },
  { code: "UEM", filename: "uem", name: "Vorpommern-Greifswald (Uecker-Randow)", region: "Mecklenburg-Vorpommern", aliases: ["Uecker-Randow"] },
  { code: "UER", filename: "uer", name: "Mecklenburgische Seenplatte", region: "Mecklenburg-Vorpommern" },
  { code: "UFF", filename: "uff", name: "Neustadt a.d.A. (Uffenheim)", region: "Bayern", aliases: ["Uffenheim"] },
  { code: "UH", filename: "uh", name: "Unstrut-Hainich-Kreis", region: "Thüringen" },
  { code: "UL", filename: "ul", name: "Ulm", region: "Baden-Württemberg" },
  { code: "UM", filename: "um", name: "Uckermark", region: "Brandenburg" },
  { code: "UN", filename: "un", name: "Unna", region: "Nordrhein-Westfalen" },
  { code: "USI", filename: "usi", name: "Siegen-Wittgenstein (hist.)", region: "Nordrhein-Westfalen" },
  { code: "V", filename: "v", name: "Vogtlandkreis", region: "Sachsen" },
  { code: "VAI", filename: "vai", name: "Böblingen (Vaihingen hist.)", region: "Baden-Württemberg" },
  { code: "VB", filename: "vb", name: "Vogelsbergkreis", region: "Hessen" },
  { code: "VEC", filename: "vec", name: "Vechta", region: "Niedersachsen" },
  { code: "VER", filename: "ver", name: "Verden", region: "Niedersachsen" },
  { code: "VG", filename: "vg", name: "Vorpommern-Greifswald", region: "Mecklenburg-Vorpommern" },
  { code: "VIB", filename: "vib", name: "Landshut (Vilsbiburg)", region: "Bayern", aliases: ["Vilsbiburg"] },
  { code: "VIE", filename: "vie", name: "Viersen", region: "Nordrhein-Westfalen" },
  { code: "VIT", filename: "vit", name: "Vorpommern-Greifswald (Wolgast hist.)", region: "Mecklenburg-Vorpommern" },
  { code: "VK", filename: "vk", name: "Völklingen", region: "Saarland" },
  { code: "VL", filename: "vl", name: "Schwarzwald-Baar-Kreis (Villingen hist.)", region: "Baden-Württemberg" },
  { code: "VOF", filename: "vof", name: "Görlitz (Forst hist.)", region: "Sachsen" },
  { code: "VOH", filename: "voh", name: "Neustadt/Waldnaab (Vohenstrauß)", region: "Bayern", aliases: ["Vohenstrauß"] },
  { code: "VR", filename: "vr", name: "Vorpommern-Rügen", region: "Mecklenburg-Vorpommern" },
  { code: "VS", filename: "vs", name: "Schwarzwald-Baar-Kreis", region: "Baden-Württemberg", aliases: ["Villingen-Schwenningen"] },
  { code: "W", filename: "w", name: "Wuppertal", region: "Nordrhein-Westfalen" },
  { code: "WA", filename: "wa", name: "Weilheim-Schongau (hist.)", region: "Bayern" },
  { code: "WAF", filename: "waf", name: "Warendorf", region: "Nordrhein-Westfalen" },
  { code: "WAK", filename: "wak", name: "Wartburgkreis", region: "Thüringen" },
  { code: "WAN", filename: "wan", name: "Gelsenkirchen (Wanne-Eickel hist.)", region: "Nordrhein-Westfalen", aliases: ["Wanne-Eickel"] },
  { code: "WAR", filename: "war", name: "Warendorf", region: "Nordrhein-Westfalen" },
  { code: "WAT", filename: "wat", name: "Bochum (Wattenscheid hist.)", region: "Nordrhein-Westfalen", aliases: ["Wattenscheid"] },
  { code: "WB", filename: "wb", name: "Lutherstadt Wittenberg", region: "Sachsen-Anhalt" },
  { code: "WBG", filename: "wbg", name: "Lutherstadt Wittenberg (hist.)", region: "Sachsen-Anhalt" },
  { code: "WBS", filename: "wbs", name: "Burgenlandkreis (Weißenfels hist.)", region: "Sachsen-Anhalt" },
  { code: "WD", filename: "wd", name: "Böblingen (Waldenbuch hist.)", region: "Baden-Württemberg" },
  { code: "WDA", filename: "wda", name: "Wittenberg", region: "Sachsen-Anhalt" },
  { code: "WE", filename: "we", name: "Weimarer Land (Weimar)", region: "Thüringen", aliases: ["Weimar"] },
  { code: "WEB", filename: "web", name: "Altenkirchen (Westerwald hist.)", region: "Rheinland-Pfalz" },
  { code: "WEG", filename: "weg", name: "Ansbach (Dinkelsbühl / hist.)", region: "Bayern" },
  { code: "WEL", filename: "wel", name: "Cochem-Zell (Zell/Mosel hist.)", region: "Rheinland-Pfalz", aliases: ["Zell an der Mosel"] },
  { code: "WEM", filename: "wem", name: "Unterallgäu (Mindelheim)", region: "Bayern" },
  { code: "WEN", filename: "wen", name: "Weiden in der Oberpfalz", region: "Bayern" },
  { code: "WER", filename: "wer", name: "Augsburg (Wertingen hist.)", region: "Bayern" },
  { code: "WES", filename: "wes", name: "Wesel", region: "Nordrhein-Westfalen" },
  { code: "WF", filename: "wf", name: "Wolfenbüttel", region: "Niedersachsen" },
  { code: "WG", filename: "wg", name: "Starnberg (Wolfratshausen hist.)", region: "Bayern" },
  { code: "WHV", filename: "whv", name: "Wilhelmshaven", region: "Niedersachsen" },
  { code: "WI", filename: "wi", name: "Wiesbaden", region: "Hessen" },
  { code: "WIL", filename: "wil", name: "Bernkastel-Wittlich", region: "Rheinland-Pfalz" },
  { code: "WIS", filename: "wis", name: "Nordwestmecklenburg (Wismar hist.)", region: "Mecklenburg-Vorpommern" },
  { code: "WIT", filename: "wit", name: "Ennepe-Ruhr-Kreis (Witten)", region: "Nordrhein-Westfalen", aliases: ["Witten"] },
  { code: "WIZ", filename: "wiz", name: "Ulm (Biberach hist.)", region: "Baden-Württemberg" },
  { code: "WK", filename: "wk", name: "Saale-Orla-Kreis (Schleiz hist.)", region: "Thüringen" },
  { code: "WL", filename: "wl", name: "Harburg", region: "Niedersachsen" },
  { code: "WLG", filename: "wlg", name: "Saale-Orla-Kreis", region: "Thüringen" },
  { code: "WM", filename: "wm", name: "Weilheim-Schongau", region: "Bayern" },
  { code: "WMS", filename: "wms", name: "Saale-Orla-Kreis (Werdau hist.)", region: "Sachsen", aliases: ["Werdau"] },
  { code: "WN", filename: "wn", name: "Rems-Murr-Kreis (Waiblingen)", region: "Baden-Württemberg", aliases: ["Waiblingen"] },
  { code: "WND", filename: "wnd", name: "Sankt Wendel", region: "Saarland" },
  { code: "WO", filename: "wo", name: "Worms", region: "Rheinland-Pfalz" },
  { code: "WOB", filename: "wob", name: "Wolfsburg", region: "Niedersachsen" },
  { code: "WOH", filename: "woh", name: "Freising (Wolfratshausen hist.)", region: "Bayern" },
  { code: "WOL", filename: "wol", name: "Worms (hist.)", region: "Rheinland-Pfalz" },
  { code: "WOR", filename: "wor", name: "Worms", region: "Rheinland-Pfalz" },
  { code: "WOS", filename: "wos", name: "Rosenheim (Wasserburg am Inn)", region: "Bayern", aliases: ["Wasserburg am Inn"] },
  { code: "WR", filename: "wr", name: "Wittenberg (Wittenberg hist.)", region: "Sachsen-Anhalt" },
  { code: "WRN", filename: "wrn", name: "Ludwigslust-Parchim (Waren/Müritz)", region: "Mecklenburg-Vorpommern", aliases: ["Waren (Müritz)"] },
  { code: "WS", filename: "ws", name: "Ansbach (Wolframs-Eschenbach)", region: "Bayern", aliases: ["Wolframs-Eschenbach"] },
  { code: "WSF", filename: "wsf", name: "Burgenlandkreis (Weißenfels)", region: "Sachsen-Anhalt", aliases: ["Weißenfels"] },
  { code: "WST", filename: "wst", name: "Ammerland", region: "Niedersachsen" },
  { code: "WSW", filename: "wsw", name: "Zwickau (Werdau hist.)", region: "Sachsen" },
  { code: "WT", filename: "wt", name: "Waldshut", region: "Baden-Württemberg" },
  { code: "WTL", filename: "wtl", name: "Goslar (Wolfenbüttel hist.)", region: "Niedersachsen" },
  { code: "WTM", filename: "wtm", name: "Wittmund", region: "Niedersachsen" },
  { code: "WÜ", filename: "wue", name: "Würzburg", region: "Bayern" },
  { code: "WÜM", filename: "wuem", name: "Regen (Viechtach hist.)", region: "Bayern", aliases: ["Viechtach"] },
  { code: "WUG", filename: "wug", name: "Weißenburg-Gunzenhausen", region: "Bayern" },
  { code: "WUN", filename: "wun", name: "Wunsiedel im Fichtelgebirge", region: "Bayern" },
  { code: "WUR", filename: "wur", name: "Wunsiedel (hist.)", region: "Bayern" },
  { code: "WW", filename: "ww", name: "Westerwaldkreis", region: "Rheinland-Pfalz" },
  { code: "WZ", filename: "wz", name: "Lahn-Dill-Kreis (Wetzlar)", region: "Hessen", aliases: ["Wetzlar"] },
  { code: "WZL", filename: "wzl", name: "Börde", region: "Sachsen-Anhalt" },
  { code: "X", filename: "x", name: "NATO", region: "Sonderkennzeichen" },
  { code: "Y", filename: "y", name: "Bundeswehr", region: "Sonderkennzeichen" },
  { code: "Z", filename: "z", name: "Zwickau", region: "Sachsen" },
  { code: "ZE", filename: "ze", name: "Anhalt-Bitterfeld (Zerbst)", region: "Sachsen-Anhalt", aliases: ["Zerbst"] },
  { code: "ZEL", filename: "zel", name: "Cochem-Zell (Zell an der Mosel)", region: "Rheinland-Pfalz", aliases: ["Zell an der Mosel"] },
  { code: "ZI", filename: "zi", name: "Görlitz (Zittau)", region: "Sachsen", aliases: ["Zittau"] },
  { code: "ZIG", filename: "zig", name: "Schweinfurt (Gerolzhofen hist.)", region: "Bayern" },
  { code: "ZP", filename: "zp", name: "Greiz (Zeulenroda)", region: "Thüringen", aliases: ["Zeulenroda"] },
  { code: "ZR", filename: "zr", name: "Greiz", region: "Thüringen" },
  { code: "ZS", filename: "zs", name: "Dahme-Spreewald (Zossen hist.)", region: "Brandenburg", aliases: ["Zossen"] },
  { code: "ZW", filename: "zw", name: "Zweibrücken", region: "Rheinland-Pfalz" },
  { code: "ZZ", filename: "zz", name: "Burgenlandkreis (Zeitz)", region: "Sachsen-Anhalt", aliases: ["Zeitz"] },
];