const germanyPlates = [
  { code: "AM", filename: "am-at", name: "Amstetten", region: "Österreich", aliases: ["Amstetten"] },
  { code: "B", filename: "b-at", name: "Bregenz", region: "Österreich", aliases: ["Bregenz"] },
  { code: "BA", filename: "ba-at", name: "Bad Aussee", region: "Österreich", aliases: ["Bad Aussee"] },
  { code: "BL", filename: "bl-at", name: "Bruck an der Leitha", region: "Österreich", aliases: ["Bruck an der Leitha"] },
  { code: "BM", filename: "bm-at", name: "Bruck-Mürzzuschlag", region: "Österreich", aliases: ["Bruck-Mürzzuschlag"] },
  { code: "BN", filename: "bn-at", name: "Baden", region: "Österreich", aliases: ["Baden"] },
  { code: "BR", filename: "br-at", name: "Braunau am Inn", region: "Österreich", aliases: ["Braunau am Inn"] },
  { code: "BZ", filename: "bz-at", name: "Bludenz", region: "Österreich", aliases: ["Bludenz"] },
  { code: "DL", filename: "dl-at", name: "Deutschlandsberg", region: "Österreich", aliases: ["Deutschlandsberg"] },
  { code: "DO", filename: "do-at", name: "Dornbirn", region: "Österreich", aliases: ["Dornbirn"] },
  { code: "E", filename: "e-at", name: "Eisenstadt", region: "Österreich", aliases: ["Eisenstadt"] },
  { code: "EF", filename: "ef-at", name: "Eferding", region: "Österreich", aliases: ["Eferding"] },
  { code: "EU", filename: "eu-at", name: "Eisenstadt-Umgebung", region: "Österreich", aliases: ["Eisenstadt"] },
  { code: "FB", filename: "fb-at", name: "Feldbach", region: "Österreich", aliases: ["Feldbach"] },
  { code: "FE", filename: "fe-at", name: "Feldkirchen", region: "Österreich", aliases: ["Feldkirchen"] },
  { code: "FF", filename: "ff-at", name: "Fürstenfeld", region: "Österreich", aliases: ["Fürstenfeld"] },
  { code: "FK", filename: "fk-at", name: "Feldkirch", region: "Österreich", aliases: ["Feldkirch"] },
  { code: "FR", filename: "fr-at", name: "Freistadt", region: "Österreich", aliases: ["Freistadt"] },
  { code: "G", filename: "g-at", name: "Graz", region: "Österreich", aliases: ["Graz"] },
  { code: "GB", filename: "gb-at", name: "Gröbming", region: "Österreich", aliases: ["Gröbming"] },
  { code: "GD", filename: "gd-at", name: "Gmünd", region: "Österreich", aliases: ["Gmünd"] },
  { code: "GF", filename: "gf-at", name: "Gänserndorf", region: "Österreich", aliases: ["Gänserndorf"] },
  { code: "GM", filename: "gm-at", name: "Gmunden", region: "Österreich", aliases: ["Gmunden"] },
  { code: "GR", filename: "gr-at", name: "Grieskirchen", region: "Österreich", aliases: ["Grieskirchen"] },
  { code: "GS", filename: "gs-at", name: "Güssing", region: "Österreich", aliases: ["Güssing"] },
  { code: "GU", filename: "gu-at", name: "Graz-Umgebung", region: "Österreich", aliases: ["Graz"] },
  { code: "HA", filename: "ha-at", name: "Hallein", region: "Österreich", aliases: ["Hallein"] },
  { code: "HB", filename: "hb-at", name: "Hartberg", region: "Österreich", aliases: ["Hartberg"] },
  { code: "HE", filename: "he-at", name: "Hermagor", region: "Österreich", aliases: ["Hermagor"] },
  { code: "HF", filename: "hf-at", name: "Hartberg-Fürstenfeld", region: "Österreich", aliases: ["Hartberg", "Fürstenfeld"] },
  { code: "HL", filename: "hl-at", name: "Hollabrunn", region: "Österreich", aliases: ["Hollabrunn"] },
  { code: "HO", filename: "ho-at", name: "Horn", region: "Österreich", aliases: ["Horn"] },
  { code: "IL", filename: "il-at", name: "Innsbruck-Land", region: "Österreich", aliases: ["Innsbruck"] },
  { code: "I", filename: "i-at", name: "Innsbruck", region: "Österreich", aliases: ["Innsbruck"] },
  { code: "IM", filename: "im-at", name: "Imst", region: "Österreich", aliases: ["Imst"] },
  { code: "JE", filename: "je-at", name: "Jennersdorf", region: "Österreich", aliases: ["Jennersdorf"] },
  { code: "JO", filename: "jo-at", name: "St. Johann im Pongau", region: "Österreich", aliases: ["Sankt Johann"] },
  { code: "JU", filename: "ju-at", name: "Judenburg", region: "Österreich", aliases: ["Judenburg"] },
  { code: "K", filename: "k-at", name: "Klagenfurt", region: "Österreich", aliases: ["Klagenfurt"] },
  { code: "KB", filename: "kb-at", name: "Kitzbühel", region: "Österreich", aliases: ["Kitzbühel"] },
  { code: "KF", filename: "kf-at", name: "Knittelfeld", region: "Österreich", aliases: ["Knittelfeld"] },
  { code: "KI", filename: "ki-at", name: "Kirchdorf an der Krems", region: "Österreich", aliases: ["Kirchdorf"] },
  { code: "KL", filename: "kl-at", name: "Klagenfurt-Land", region: "Österreich", aliases: ["Klagenfurt"] },
  { code: "KO", filename: "ko-at", name: "Korneuburg", region: "Österreich", aliases: ["Korneuburg"] },
  { code: "KR", filename: "kr-at", name: "Krems-Land", region: "Österreich", aliases: ["Krems"] },
  { code: "KS", filename: "ks-at", name: "Krems an der Donau", region: "Österreich", aliases: ["Krems"] },
  { code: "KU", filename: "ku-at", name: "Kufstein", region: "Österreich", aliases: ["Kufstein"] },
  { code: "L", filename: "l-at", name: "Linz", region: "Österreich", aliases: ["Linz"] },
  { code: "LA", filename: "la-at", name: "Landeck", region: "Österreich", aliases: ["Landeck"] },
  { code: "LB", filename: "lb-at", name: "Leibnitz", region: "Österreich", aliases: ["Leibnitz"] },
  { code: "LE", filename: "le-at", name: "Leoben", region: "Österreich", aliases: ["Leoben"] },
  { code: "LF", filename: "lf-at", name: "Lilienfeld", region: "Österreich", aliases: ["Lilienfeld"] },
  { code: "LI", filename: "li-at", name: "Liezen", region: "Österreich", aliases: ["Liezen"] },
  { code: "LL", filename: "ll-at", name: "Linz-Land", region: "Österreich", aliases: ["Linz"] },
  { code: "LN", filename: "ln-at", name: "Leoben", region: "Österreich", aliases: ["Leoben"] },
  { code: "LZ", filename: "lz-at", name: "Lienz", region: "Österreich", aliases: ["Lienz"] },
  { code: "MA", filename: "ma-at", name: "Mattersburg", region: "Österreich", aliases: ["Mattersburg"] },
  { code: "MD", filename: "md-at", name: "Mödling", region: "Österreich", aliases: ["Mödling"] },
  { code: "ME", filename: "me-at", name: "Melk", region: "Österreich", aliases: ["Melk"] },
  { code: "MI", filename: "mi-at", name: "Mistelbach", region: "Österreich", aliases: ["Mistelbach"] },
  { code: "MT", filename: "mt-at", name: "Murtal", region: "Österreich", aliases: ["Murtal"] },
  { code: "MU", filename: "mu-at", name: "Murau", region: "Österreich", aliases: ["Murau"] },
  { code: "MZ", filename: "lz-at", name: "Mürzzuschlag", region: "Österreich", aliases: ["Mürzzuschlag"] },
  { code: "ND", filename: "nd-at", name: "Neusiedl am See", region: "Österreich", aliases: ["Neusiedl"] },
  { code: "NK", filename: "nk-at", name: "Neunkirchen", region: "Österreich", aliases: ["Neunkirchen"] },
  { code: "OP", filename: "op-at", name: "Oberpullendorf", region: "Österreich", aliases: ["Oberpullendorf"] },
  { code: "OW", filename: "ow-at", name: "Oberwart", region: "Österreich", aliases: ["Oberwart"] },
  { code: "P", filename: "p-at", name: "St. Pölten", region: "Österreich", aliases: ["Sankt Pölten"] },
  { code: "PE", filename: "pe-at", name: "Perg", region: "Österreich", aliases: ["Perg"] },
  { code: "PL", filename: "pl-at", name: "St. Pölten-Land", region: "Österreich", aliases: ["St. Pölten"] },
  { code: "RA", filename: "ra-at", name: "Radkersburg", region: "Österreich", aliases: ["Radkersburg"] },
  { code: "RE", filename: "re-at", name: "Reutte", region: "Österreich", aliases: ["Reutte"] },
  { code: "RI", filename: "ri-at", name: "Ried im Innkreis", region: "Österreich", aliases: ["Ried"] },
  { code: "RO", filename: "ro-at", name: "Rohrbach", region: "Österreich", aliases: ["Rohrbach"] },
  { code: "S", filename: "s-at", name: "Salzburg", region: "Österreich", aliases: ["Salzburg"] },
  { code: "SB", filename: "sb-at", name: "Scheibbs", region: "Österreich", aliases: ["Scheibbs"] },
  { code: "SD", filename: "sd-at", name: "Schärding", region: "Österreich", aliases: ["Schärding"] },
  { code: "SE", filename: "se-at", name: "Steyr-Land", region: "Österreich", aliases: ["Steyr"] },
  { code: "SL", filename: "sl-at", name: "Salzburg-Land", region: "Österreich", aliases: ["Salzburg"] },
  { code: "SO", filename: "so-at", name: "Südoststeiermark", region: "Österreich", aliases: ["Südoststeiermark"] },
  { code: "SP", filename: "sp-at", name: "Spittal an der Drau", region: "Österreich", aliases: ["Spittal"] },
  { code: "SR", filename: "sr-at", name: "Steyr", region: "Österreich", aliases: ["Steyr"] },
  { code: "SV", filename: "sv-at", name: "St. Veit an der Glan", region: "Österreich", aliases: ["Sankt Veit"] },
  { code: "SW", filename: "sw-at", name: "Schwechat", region: "Österreich", aliases: ["Schwechat"] },
  { code: "SZ", filename: "sz-at", name: "Schwaz", region: "Österreich", aliases: ["Schwaz"] },
  { code: "TA", filename: "ta-at", name: "Tamsweg", region: "Österreich", aliases: ["Tamsweg"] },
  { code: "TU", filename: "tu-at", name: "Tulln", region: "Österreich", aliases: ["Tulln"] },
  { code: "UU", filename: "uu-at", name: "Urfahr-Umgebung", region: "Österreich", aliases: ["Urfahr"] },
  { code: "VB", filename: "vb-at", name: "Vöcklabruck", region: "Österreich", aliases: ["Vöcklabruck"] },
  { code: "VI", filename: "vi-at", name: "Villach", region: "Österreich", aliases: ["Villach"] },
  { code: "VK", filename: "vk-at", name: "Völkermarkt", region: "Österreich", aliases: ["Völkermarkt"] },
  { code: "VL", filename: "vl-at", name: "Villach-Land", region: "Österreich", aliases: ["Villach-Land"] },
  { code: "VO", filename: "vo-at", name: "Voitsberg", region: "Österreich", aliases: ["Voitsberg"] },
  { code: "W", filename: "w-at", name: "Wien", region: "Österreich", aliases: ["Wien"] },
  { code: "WB", filename: "wb-at", name: "Wiener Neustadt-Land", region: "Österreich", aliases: ["Wiener Neustadt"] },
  { code: "WE", filename: "we-at", name: "Wels", region: "Österreich", aliases: ["Wels"] },
  { code: "WL", filename: "wl-at", name: "Wels-Land", region: "Österreich", aliases: ["Wels-Land"] },
  { code: "WN", filename: "wn-at", name: "Wiener Neustadt", region: "Österreich", aliases: ["Wiener Neustadt"] },
  { code: "WO", filename: "wo-at", name: "Wolfsberg", region: "Österreich", aliases: ["Wolfsberg"] },
  { code: "WT", filename: "wt-at", name: "Waidhofen an der Thaya", region: "Österreich", aliases: ["Waidhofen"] },
  { code: "WU", filename: "wu-at", name: "Wien-Umgebung", region: "Österreich", aliases: ["Wien-Umgebung"] },
  { code: "WY", filename: "wy-at", name: "Waidhofen an der Ybbs", region: "Österreich", aliases: ["Waidhofen"] },
  { code: "WZ", filename: "wz-at", name: "Weiz", region: "Österreich", aliases: ["Weiz"] },
  { code: "ZE", filename: "ze-at", name: "Zell am See", region: "Österreich", aliases: ["Zell"] },
  { code: "ZT", filename: "zt-at", name: "Zwettl", region: "Österreich", aliases: ["Zwettl"] },
  { code: "AL", filename: "al-al", name: "Albanien", region: "Albanien", aliases: ["Albanien"] },
  { code: "AND", filename: "and-and", name: "Andorra", region: "Andorra", aliases: ["Andorra"] },
  { code: "BY", filename: "by-by", name: "Belarus", region: "Belarus", aliases: ["Belarus"] },
  { code: "BE", filename: "be-be", name: "Belgien", region: "Belgien", aliases: ["Belgien"] },
  { code: "BIH", filename: "bih-bih", name: "Bosnien und Herzegowina", region: "Bosnien und Herzegowina", aliases: ["Bosnien"] },
  { code: "C", filename: "c-bg", name: "Sofia", region: "Bulgarien", aliases: ["Sofia"] },
  { code: "P", filename: "p-bg", name: "Russe", region: "Bulgarien", aliases: ["Russe"] },
  { code: "PB", filename: "pb-bg", name: "Plowdiw", region: "Bulgarien", aliases: ["Plovdiv"] },
  { code: "A", filename: "a-cz", name: "Prag", region: "Tschechien", aliases: ["Prag"] },
  { code: "DK", filename: "dk-dk", name: "Dänemark", region: "Dänemark", aliases: ["Dänemark"] },
  { code: "EST", filename: "est-est", name: "Estland", region: "Estland", aliases: ["Estland"] },
  { code: "FIN", filename: "fin-fin", name: "Finnland", region: "Finnland", aliases: ["Finnland"] },
  { code: "06", filename: "06-fr", name: "Alpes-Maritimes", region: "Frankreich", aliases: ["Provence-Alpes-Côte d'Azur"] },
  { code: "2a", filename: "2a-fr", name: "Corsica", region: "Frankreich", aliases: ["Corsica"] },
  { code: "67", filename: "67-fr", name: "Bas-Rhin", region: "Frankreich", aliases: ["Elsass", "Strasbourg"] },
  { code: "75", filename: "75-fr", name: "Paris", region: "Frankreich", aliases: ["Paris"] },
  { code: "86", filename: "86-fr", name: "Vienne", region: "Frankreich", aliases: ["Poitiers", "Poitou-Charentes"] },
  { code: "GE", filename: "ge-ge", name: "Georgien", region: "Georgien", aliases: ["Georgien"] },
  { code: "XX", filename: "xx-gr", name: "Athen", region: "Griechenland", aliases: ["Athen"] },
  { code: "H", filename: "h-h", name: "Ungarn", region: "Ungarn", aliases: ["Ungarn"] },
  { code: "D", filename: "d-irl", name: "Dublin", region: "Irland", aliases: ["Dublin"] },
  { code: "C", filename: "c-irl", name: "Cork", region: "Irland", aliases: ["Cork"] },
  { code: "ROMA", filename: "roma-it", name: "Rom", region: "Italien", aliases: ["Rome"] },
  { code: "BZ", filename: "bz-it", name: "Bozen", region: "Italien", aliases: ["Bozen"] },
  { code: "FL", filename: "fl-it", name: "Florenz", region: "Italien", aliases: ["Florenz"] },
  { code: "MI", filename: "mi-it", name: "Milano", region: "Italien", aliases: ["Mailand"] },
  { code: "AG", filename: "ag-it", name: "Agrigento", region: "Italien", aliases: ["Agrigento"] },
  { code: "AL", filename: "al-it", name: "Alessandria", region: "Italien", aliases: ["Alessandria"] },
  { code: "AN", filename: "an-it", name: "Ancona", region: "Italien", aliases: ["Ancona"] },
  { code: "AO", filename: "ao-it", name: "Aosta", region: "Italien", aliases: ["Aosta"] },
  { code: "AP", filename: "ap-it", name: "Ascoli Piceno", region: "Italien", aliases: ["Ascoli Piceno"] },
  { code: "AQ", filename: "aq-it", name: "L'Aquila", region: "Italien", aliases: ["Aquila"] },
  { code: "AR", filename: "ar-it", name: "Arezzo", region: "Italien", aliases: ["Arezzo"] },
  { code: "AT", filename: "at-it", name: "Asti", region: "Italien", aliases: ["Asti"] },
  { code: "AV", filename: "av-it", name: "Avellino", region: "Italien", aliases: ["Avellino"] },
  { code: "BA", filename: "ba-it", name: "Bari", region: "Italien", aliases: ["Bari"] },
  { code: "BG", filename: "bg-it", name: "Bergamo", region: "Italien", aliases: ["Bergamo"] },
  { code: "BI", filename: "bi-it", name: "Biella", region: "Italien", aliases: ["Biella"] },
  { code: "BL", filename: "bl-it", name: "Belluno", region: "Italien", aliases: ["Belluno"] },
  { code: "BN", filename: "bn-it", name: "Benevento", region: "Italien", aliases: ["Benevento"] },
  { code: "BO", filename: "bo-it", name: "Bologna", region: "Italien", aliases: ["Bologna"] },
  { code: "BR", filename: "br-it", name: "Brindisi", region: "Italien", aliases: ["Brindisi"] },
  { code: "BS", filename: "bs-it", name: "Brescia", region: "Italien", aliases: ["Brescia"] },
  { code: "BT", filename: "bt-it", name: "Barletta-Andria-Trani", region: "Italien", aliases: ["Barletta-Andria-Trani"] },
  { code: "CA", filename: "ca-it", name: "Cagliari", region: "Italien", aliases: ["Cagliari"] },
  { code: "CB", filename: "cb-it", name: "Campobasso", region: "Italien", aliases: ["Campobasso"] },
  { code: "CE", filename: "ce-it", name: "Caserta", region: "Italien", aliases: ["Caserta"] },
  { code: "CH", filename: "ch-it", name: "Chieti", region: "Italien", aliases: ["Chieti"] },
  { code: "CL", filename: "cl-it", name: "Caltanissetta", region: "Italien", aliases: ["Caltanissetta"] },
  { code: "CN", filename: "cn-it", name: "Cuneo", region: "Italien", aliases: ["Cuneo"] },
  { code: "CO", filename: "co-it", name: "Como", region: "Italien", aliases: ["Como"] },
  { code: "CR", filename: "cr-it", name: "Cremona", region: "Italien", aliases: ["Cremona"] },
  { code: "CS", filename: "cs-it", name: "Cosenza", region: "Italien", aliases: ["Cosenza"] },
  { code: "CT", filename: "ct-it", name: "Catania", region: "Italien", aliases: ["Catania"] },
  { code: "CZ", filename: "cz-it", name: "Catanzaro", region: "Italien", aliases: ["Catanzaro"] },
  { code: "EN", filename: "en-it", name: "Enna", region: "Italien", aliases: ["Enna"] },
  { code: "FC", filename: "fc-it", name: "Forlì-Cesena", region: "Italien", aliases: ["Forli Cesena"] },
  { code: "FE", filename: "fe-it", name: "Ferrara", region: "Italien", aliases: ["Ferrara"] },
  { code: "FG", filename: "fg-it", name: "Foggia", region: "Italien", aliases: ["Foggia"] },
  { code: "FM", filename: "fm-it", name: "Fermo", region: "Italien", aliases: ["Fermo"] },
  { code: "FO", filename: "fo-it", name: "Forlì", region: "Italien", aliases: ["Forli"] },
  { code: "FR", filename: "fr-it", name: "Frosinone", region: "Italien", aliases: ["Frosinone"] },
  { code: "GE", filename: "ge-it", name: "Genoa", region: "Italien", aliases: ["Genoa", "Genova"] },
  { code: "GO", filename: "go-it", name: "Gorizia", region: "Italien", aliases: ["Gorizia"] },
  { code: "GR", filename: "gr-it", name: "Grosseto", region: "Italien", aliases: ["Grosseto"] },
  { code: "IM", filename: "im-it", name: "Imperia", region: "Italien", aliases: ["Imperia"] },
  { code: "IS", filename: "is-it", name: "Isernia", region: "Italien", aliases: ["Isernia"] },
  { code: "KR", filename: "kr-it", name: "Crotone", region: "Italien", aliases: ["Crotone"] },
  { code: "LC", filename: "lc-it", name: "Lecco", region: "Italien", aliases: ["Lecco"] },
  { code: "LE", filename: "le-it", name: "Lecce", region: "Italien", aliases: ["Lecce"] },
  { code: "LI", filename: "li-it", name: "Livorno", region: "Italien", aliases: ["Livorno"] },
  { code: "LO", filename: "lo-it", name: "Lodi", region: "Italien", aliases: ["Lodi"] },
  { code: "LT", filename: "lt-it", name: "Latina", region: "Italien", aliases: ["Latina"] },
  { code: "LU", filename: "lu-it", name: "Lucca", region: "Italien", aliases: ["Lucca"] },
  { code: "MB", filename: "mb-it", name: "Monza und Brianza", region: "Italien", aliases: ["Monza und Brianza"] },
  { code: "MC", filename: "mc-it", name: "Macerata", region: "Italien", aliases: ["Macerata"] },
  { code: "ME", filename: "me-it", name: "Messina", region: "Italien", aliases: ["Messina"] },
  { code: "MN", filename: "mn-it", name: "Mantua", region: "Italien", aliases: ["Mantua", "Mantova"] },
  { code: "MO", filename: "mo-it", name: "Modena", region: "Italien", aliases: ["Modena"] },
  { code: "MS", filename: "ms-it", name: "Massa-Carrara", region: "Italien", aliases: ["Massa Carrara"] },
  { code: "MT", filename: "mt-it", name: "Matera", region: "Italien", aliases: ["Matera"] },
  { code: "NA", filename: "na-it", name: "Napoli", region: "Italien", aliases: ["Napoli"] },
  { code: "NO", filename: "no-it", name: "Novara", region: "Italien", aliases: ["Novara"] },
  { code: "NU", filename: "nu-it", name: "Nuoro", region: "Italien", aliases: ["Nuoro"] },
  { code: "OG", filename: "og-it", name: "Ogliastra", region: "Italien", aliases: ["Ogliastra"] },
  { code: "OR", filename: "or-it", name: "Oristano", region: "Italien", aliases: ["Oristano"] },
  { code: "OT", filename: "ot-it", name: "Olbia-Tempio", region: "Italien", aliases: ["Olbia Tempio"] },
  { code: "PA", filename: "pa-it", name: "Palermo", region: "Italien", aliases: ["Palermo"] },
  { code: "PC", filename: "pc-it", name: "Piacenza", region: "Italien", aliases: ["Piacenza"] },
  { code: "PD", filename: "pd-it", name: "Padua", region: "Italien", aliases: ["Padua"] },
  { code: "PE", filename: "pe-it", name: "Pescara", region: "Italien", aliases: ["Pescara"] },
  { code: "PG", filename: "pg-it", name: "Perugia", region: "Italien", aliases: ["Perugia"] },
  { code: "PI", filename: "pi-it", name: "Pisa", region: "Italien", aliases: ["Pisa"] },
  { code: "PN", filename: "pn-it", name: "Pordenone", region: "Italien", aliases: ["Pordenone"] },
  { code: "PO", filename: "po-it", name: "Prato", region: "Italien", aliases: ["Prato"] },
  { code: "PR", filename: "pr-it", name: "Parma", region: "Italien", aliases: ["Parma"] },
  { code: "PS", filename: "ps-it", name: "Pesaro", region: "Italien", aliases: ["Pesaro"] },
  { code: "PT", filename: "pt-it", name: "Pistoia", region: "Italien", aliases: ["Pistoia"] },
  { code: "PU", filename: "pu-it", name: "Pesaro und Urbino", region: "Italien", aliases: ["Pesaro und Urbino"] },
  { code: "PV", filename: "pv-it", name: "Pavia", region: "Italien", aliases: ["Pavia"] },
  { code: "PZ", filename: "pz-it", name: "Potenza", region: "Italien", aliases: ["Potenza"] },
  { code: "RA", filename: "ra-it", name: "Ravenna", region: "Italien", aliases: ["Ravenna"] },
  { code: "RC", filename: "rc-it", name: "Reggio Calabria", region: "Italien", aliases: ["Reggio Calabria"] },
  { code: "RE", filename: "re-it", name: "Reggio Emilia", region: "Italien", aliases: ["Reggio Emilia"] },
  { code: "RG", filename: "rg-it", name: "Ragusa", region: "Italien", aliases: ["Ragusa"] },
  { code: "RI", filename: "ri-it", name: "Rieti", region: "Italien", aliases: ["Rieti"] },
  { code: "RN", filename: "rn-it", name: "Rimini", region: "Italien", aliases: ["Rimini"] },
  { code: "RO", filename: "ro-it", name: "Rovigo", region: "Italien", aliases: ["Rovigo"] },
  { code: "SA", filename: "sa-it", name: "Salerno", region: "Italien", aliases: ["Salerno"] },
  { code: "SI", filename: "si-it", name: "Siena", region: "Italien", aliases: ["Siena"] },
  { code: "SO", filename: "so-it", name: "Sondrio", region: "Italien", aliases: ["Sondrio"] },
  { code: "SP", filename: "sp-it", name: "La Spezia", region: "Italien", aliases: ["La Spezia"] },
  { code: "SR", filename: "sr-it", name: "Siracusa", region: "Italien", aliases: ["Syracuse"] },
  { code: "SS", filename: "ss-it", name: "Sassari", region: "Italien", aliases: ["Sassari"] },
  { code: "SV", filename: "sv-it", name: "Savona", region: "Italien", aliases: ["Savona"] },
  { code: "TA", filename: "ta-it", name: "Taranto", region: "Italien", aliases: ["Taranto"] },
  { code: "TN", filename: "tn-it", name: "Trento", region: "Italien", aliases: ["Trento"] },
  { code: "TO", filename: "to-it", name: "Torino", region: "Italien", aliases: ["Turin"] },
  { code: "TP", filename: "tp-it", name: "Trapani", region: "Italien", aliases: ["Trapani"] },
  { code: "TR", filename: "tr-it", name: "Terni", region: "Italien", aliases: ["Terni"] },
  { code: "TS", filename: "ts-it", name: "Trieste", region: "Italien", aliases: ["Trieste"] },
  { code: "TV", filename: "tv-it", name: "Treviso", region: "Italien", aliases: ["Treviso"] },
  { code: "UD", filename: "ud-it", name: "Udine", region: "Italien", aliases: ["Udine"] },
  { code: "VA", filename: "va-it", name: "Varese", region: "Italien", aliases: ["Varese"] },
  { code: "VB", filename: "vb-it", name: "Verbano-Cusio-Ossola", region: "Italien", aliases: ["Verbano Cusio Ossola"] },
  { code: "VC", filename: "vc-it", name: "Vercelli", region: "Italien", aliases: ["Vercelli"] },
  { code: "VE", filename: "ve-it", name: "Venezia", region: "Italien", aliases: ["Venedig"] },
  { code: "VI", filename: "vi-it", name: "Vicenza", region: "Italien", aliases: ["Vicenza"] },
  { code: "VR", filename: "vr-it", name: "Verona", region: "Italien", aliases: ["Verona"] },
  { code: "VS", filename: "vs-it", name: "Medio Campidano", region: "Italien", aliases: ["Medio Campidano"] },
  { code: "VT", filename: "vt-it", name: "Viterbo", region: "Italien", aliases: ["Viterbo"] },
  { code: "VV", filename: "vv-it", name: "Vibo Valentia", region: "Italien", aliases: ["Vibo Valentia"] },
  { code: "POL", filename: "pol-it", name: "Polizei", region: "Italien", aliases: ["Polizia"] },
  { code: "CD", filename: "cd-it", name: "Diplomat Italien", region: "Italien", aliases: ["Diplomat Italien"] },

  { code: "FL", filename: "fl-fl", name: "Liechtenstein", region: "Liechtenstein", aliases: ["Liechtenstein"] },
  { code: "L", filename: "l-l", name: "Luxemburg", region: "Luxemburg", aliases: ["Luxembourg"] },
  { code: "MC", filename: "mc-mc", name: "Monaco", region: "Monaco", aliases: ["Monaco"] },
  { code: "MNE", filename: "mne-mne", name: "Montenegro", region: "Montenegro", aliases: ["Montenegro"] },
  { code: "NL", filename: "nl-nl", name: "Niederlande", region: "Niederlande", aliases: ["Niederlande"] },
  { code: "SK", filename: "sk-mk", name: "Skopje", region: "Nordmazedonien", aliases: ["Skopje"] },
  { code: "N", filename: "n-n", name: "Norwegen", region: "Norwegen", aliases: ["Norwegen"] },
  { code: "P", filename: "p-p", name: "Portugal", region: "Portugal", aliases: ["Portugal"] },
  { code: "B", filename: "b-ro", name: "Bukarest", region: "Rumänien", aliases: ["Bukarest"] },
  { code: "777", filename: "777-ru", name: "Moskau", region: "Russland", aliases: ["Moskau"] },
  { code: "790", filename: "790-ru", name: "Moskau", region: "Russland", aliases: ["Moskau"] },
  { code: "RSM", filename: "rsm-rsm", name: "San Marino", region: "San Marino", aliases: ["San Marino"] },
  { code: "BG", filename: "bg-srb", name: "Belgrad", region: "Serbien", aliases: ["Belgrad"] },
  { code: "LJ", filename: "lj-slo", name: "Ljubljana", region: "Slowenien", aliases: ["Ljubljana"] },
  { code: "MB", filename: "mb-slo", name: "Maribor", region: "Slowenien", aliases: ["Maribor"] },
  { code: "CE", filename: "ce-slo", name: "Celje", region: "Slowenien", aliases: ["Celje"] },
  { code: "E", filename: "e-e", name: "Spanien", region: "Spanien", aliases: ["Madrid"] },
  { code: "S", filename: "s-s", name: "Schweden", region: "Schweden", aliases: ["Schweden"] },
  { code: "AG", filename: "ag-ch", name: "Aargau", region: "Schweiz", aliases: ["Aargau"] },
  { code: "BE", filename: "be-ch", name: "Bern", region: "Schweiz", aliases: ["Bern"] },
  { code: "BL", filename: "bl-ch", name: "Basel-Landschaft", region: "Schweiz", aliases: ["Basel-Landschaft"] },
  { code: "BS", filename: "bs-ch", name: "Basel-Stadt", region: "Schweiz", aliases: ["Basel-Stadt"] },
  { code: "FR", filename: "fr-ch", name: "Freiburg", region: "Schweiz", aliases: ["Freiburg"] },
  { code: "GE", filename: "ge-ch", name: "Genf", region: "Schweiz", aliases: ["Genf"] },
  { code: "GL", filename: "gl-ch", name: "Glarus", region: "Schweiz", aliases: ["Glarus"] },
  { code: "GR", filename: "gr-ch", name: "Graubünden", region: "Schweiz", aliases: ["Graubünden"] },
  { code: "JU", filename: "ju-ch", name: "Jura", region: "Schweiz", aliases: ["Jura"] },
  { code: "LU", filename: "lu-ch", name: "Luzern", region: "Schweiz", aliases: ["Luzern"] },
  { code: "NE", filename: "ne-ch", name: "Neuenburg", region: "Schweiz", aliases: ["Neuenburg"] },
  { code: "NW", filename: "nw-ch", name: "Nidwalden", region: "Schweiz", aliases: ["Nidwalden"] },
  { code: "OW", filename: "ow-ch", name: "Obwalden", region: "Schweiz", aliases: ["Obwalden"] },
  { code: "SG", filename: "sg-ch", name: "St. Gallen", region: "Schweiz", aliases: ["St. Gallen"] },
  { code: "SH", filename: "sh-ch", name: "Schaffhausen", region: "Schweiz", aliases: ["Schaffhausen"] },
  { code: "SO", filename: "so-ch", name: "Solothurn", region: "Schweiz", aliases: ["Solothurn"] },
  { code: "SZ", filename: "sz-ch", name: "Schwyz", region: "Schweiz", aliases: ["Schwyz"] },
  { code: "TG", filename: "tg-ch", name: "Thurgau", region: "Schweiz", aliases: ["Thurgau"] },
  { code: "TI", filename: "ti-ch", name: "Tessin", region: "Schweiz", aliases: ["Tessin"] },
  { code: "UR", filename: "ur-ch", name: "Uri", region: "Schweiz", aliases: ["Uri"] },
  { code: "VD", filename: "vd-ch", name: "Waadt", region: "Schweiz", aliases: ["Waadt"] },
  { code: "VS", filename: "vs-ch", name: "Wallis", region: "Schweiz", aliases: ["Wallis"] },
  { code: "ZG", filename: "zg-ch", name: "Zug", region: "Schweiz", aliases: ["Zug"] },
  { code: "ZH", filename: "zh-ch", name: "Zürich", region: "Schweiz", aliases: ["Zürich"] },
  { code: "06", filename: "06-tr", name: "Ankara", region: "Türkei", aliases: ["Ankara"] },
  { code: "34", filename: "34-tr", name: "Istanbul", region: "Türkei", aliases: ["Istanbul"] },
  { code: "AA", filename: "aa-ua", name: "Kiew", region: "Ukraine", aliases: ["Kiev"] },
  { code: "AK", filename: "ak-ua", name: "Krim", region: "Ukraine", aliases: ["Krim"] },
  { code: "HC", filename: "hc-ua", name: "Lwiw", region: "Ukraine", aliases: ["Lviv"] },
  { code: "HH", filename: "hh-ua", name: "Odessa", region: "Ukraine", aliases: ["Odessa"] },
  { code: "KX", filename: "kx-ua", name: "Charkiw", region: "Ukraine", aliases: ["Charkiv"] },
  { code: "CD", filename: "cd-ua", name: "Diplomat Ukraine", region: "Ukraine", aliases: ["Diplomat Ukraine"] },
  { code: "POL", filename: "pol-ua", name: "Polizei", region: "Ukraine", aliases: ["Polizei"] },
  { code: "LJ", filename: "lj-uk", name: "London", region: "Großbritannien", aliases: ["London"] },
  { code: "GR", filename: "gr-uk", name: "Brighton", region: "Großbritannien", aliases: ["Brighton"] },
  { code: "KD", filename: "kd-uk", name: "Luton", region: "Großbritannien", aliases: ["Luton"] },
  { code: "ME", filename: "me-uk", name: "Manchester", region: "Großbritannien", aliases: ["Manchester"] },
  { code: "OA", filename: "oa-uk", name: "Oxford", region: "Großbritannien", aliases: ["Oxford"] },
  { code: "SC", filename: "sc-uk", name: "Glasgow", region: "Großbritannien", aliases: ["Glasgow"] },
  { code: "SK", filename: "sk-uk", name: "Edinburgh", region: "Großbritannien", aliases: ["Edinburgh"] },
  { code: "CD", filename: "cd-uk", name: "Diplomat Großbritannien", region: "Großbritannien", aliases: ["Diplomat UK"] },
  { code: "BD", filename: "bd-uk", name: "Birmingham", region: "Großbritannien", aliases: ["Birmingham"] },
  { code: "V", filename: "v-v", name: "Vatikan", region: "Vatikanstadt", aliases: ["Vatikanstadt"] },
  { code: "ALA", filename: "ala-ala", name: "Aland", region: "Aland", aliases: ["Aland"] },
  { code: "DU", filename: "du-hr", name: "Dubrovnik", region: "Kroatien", aliases: ["Dubrovnik"] },
  { code: "KR", filename: "kr-hr", name: "Krampina", region: "Kroatien", aliases: ["Krampina"] },
  { code: "ST", filename: "st-hr", name: "Split", region: "Kroatien", aliases: ["Split"] },
  { code: "ZG", filename: "zg-hr", name: "Zagreb", region: "Kroatien", aliases: ["Zagreb"] },
  { code: "POL", filename: "pol-hr", name: "Polizei", region: "Kroatien", aliases: ["Polizei"] },
  { code: "CY", filename: "cy-cy", name: "Zypern", region: "Zypern", aliases: ["Zypern"] },
  { code: "17", filename: "17-fr", name: "Charente-Maritime", region: "Frankreich", aliases: ["Charente Maritime"] },
  { code: "62", filename: "62-fr", name: "Pas-de-Calais", region: "Frankreich", aliases: ["Pas de Calais"] },
  { code: "68", filename: "68-fr", name: "Haut-Rhin", region: "Frankreich", aliases: ["Haut Rhin"] },
  { code: "33", filename: "33-fr", name: "Gironde", region: "Frankreich", aliases: ["Gironde", "Bordeaux"] },
  { code: "CD", filename: "cd-fr", name: "Diplomat Frankreich", region: "Frankreich", aliases: ["Diplomat Frankreich"] },
  { code: "MP", filename: "mp-gr", name: "Sparta", region: "Griechenland", aliases: ["Sparta"] },
  { code: "NA", filename: "na-gr", name: "Thessaloniki", region: "Griechenland", aliases: ["Thessaloniki"] },
  { code: "PO", filename: "po-gr", name: "Rhodos", region: "Griechenland", aliases: ["Rhodos"] },
  { code: "POL", filename: "pol-gr", name: "Polizei", region: "Griechenland", aliases: ["Polizei"] },
  { code: "GBZ", filename: "gbz-gbz", name: "Gibraltar", region: "Gibraltar", aliases: ["Gibraltar"] },
  { code: "GBJ", filename: "gbj-gbj", name: "Jersey", region: "Jersey", aliases: ["Jersey"] },
  { code: "01", filename: "01-kz", name: "Astana", region: "Kasachstan", aliases: ["Astana"] },
  { code: "ED", filename: "ed-pl", name: "Lodz", region: "Polen", aliases: ["Lodz"] },
  { code: "WW", filename: "ww-pl", name: "Warschau", region: "Polen", aliases: ["Warschau"] },
  { code: "GD", filename: "gd-pl", name: "Gdansk", region: "Polen", aliases: ["Gdansk", "Danzig"] },
  { code: "CD", filename: "cd-pl", name: "Diplomat Polen", region: "Polen", aliases: ["Diplomat Polen"] },
  { code: "TM", filename: "tm-ro", name: "Timisoara", region: "Rumänien", aliases: ["Timis"] },
  { code: "IS", filename: "is-ro", name: "Iasi", region: "Rumänien", aliases: ["Iasi"] },
  { code: "GL", filename: "gl-ro", name: "Galati", region: "Rumänien", aliases: ["Galati"] },
  { code: "CD", filename: "cd-ro", name: "Diplomat Rumänien", region: "Rumänien", aliases: ["Diplomat Rumänien"] },
  { code: "198", filename: "198-ru", name: "Sankt Petersburg", region: "Russland", aliases: ["Saint Petersburg"] },
  { code: "39", filename: "39-ru", name: "Kaliningrad", region: "Russland", aliases: ["Kaliningrad", "Königsberg"] },
  { code: "82", filename: "82-ru", name: "Krim", region: "Russland", aliases: ["Krim"] },
  { code: "CD", filename: "cd-ru", name: "Diplomat Russland", region: "Russland", aliases: ["Diplomat Russland"] },
  { code: "161", filename: "161-ru", name: "Rostow", region: "Russland", aliases: ["Rostow", "Rostov"] },
  { code: "BA", filename: "ba-sk", name: "Bratislava", region: "Slowakei", aliases: ["Bratislava"] },
  { code: "MT", filename: "mt-sk", name: "Martin", region: "Slowakei", aliases: ["Martin"] },
  { code: "PO", filename: "po-sk", name: "Presov", region: "Slowakei", aliases: ["Presov"] },
  { code: "CD", filename: "cd-sk", name: "Diplomat Slowakei", region: "Slowakei", aliases: ["Diplomat Slowakei"] },
  { code: "CD", filename: "cd-at", name: "Diplomat Österreich", region: "Österreich", aliases: ["Diplomat Österreich"] },
  { code: "CD", filename: "cd-cz", name: "Diplomat Tschechien", region: "Tschechien", aliases: ["Diplomat Tschechien"] },
  { code: "CD", filename: "cd-est", name: "Diplomat Estland", region: "Estland", aliases: ["Diplomat Estland"] },
  { code: "CD", filename: "cd-h", name: "Diplomat Ungarn", region: "Ungarn", aliases: ["Diplomat Ungarn"] },
  { code: "CD", filename: "cd-is", name: "Diplomat Island", region: "Island", aliases: ["Diplomat Island"] },
  { code: "CD", filename: "cd-lv", name: "Diplomat Lettland", region: "Lettland", aliases: ["Diplomat Lettland"] },
  { code: "CD", filename: "cd-l", name: "Diplomat Luxemburg", region: "Luxemburg", aliases: ["Diplomat Luxembourg"] },
  { code: "CD", filename: "cd-lt", name: "Diplomat Litauen", region: "Litauen", aliases: ["Diplomat Litauen"] },
  { code: "POL", filename: "pol-mne", name: "Polizei Montenegro", region: "Montenegro", aliases: ["Diplomat Montenegro"] },
  { code: "CD", filename: "cd-no", name: "Diplomat Norwegen", region: "Norwegen", aliases: ["Diplomat Norwegen"] },
  { code: "POL", filename: "pol-srb", name: "Polizei Serbien", region: "Serbien", aliases: ["Diplomat Serbien"] },
  { code: "CD", filename: "cd-e", name: "Diplomat Spanien", region: "Spanien", aliases: ["Diplomat Spanien"] },
  { code: "CD", filename: "cd-s", name: "Diplomat Schweden", region: "Schweden", aliases: ["Diplomat Schweden"] },
  { code: "CD", filename: "cd-ch", name: "Diplomat Schweiz", region: "Schweiz", aliases: ["Diplomat Schweiz"] },
  { code: "POL", filename: "pol-tr", name: "Polizei Türkei", region: "Türkei", aliases: ["Diplomat Türkei"] },
  { code: "CD", filename: "cd-tr", name: "Diplomat Türkei", region: "Türkei", aliases: ["Diplomat Türkei"] },



  













  

  




];
