/* ═══════════════════════════════════════════════════════════════
   VOCAB DATA
   lang: "fr" (Französisch) | "en" (Englisch)
   level: "easy" | "medium" | "hard"
   term: das fremdsprachige Wort/die Wendung (ggf. mit Konjugation/Form)
   answers: Array möglicher korrekter deutscher Antworten
   note: optionale Zusatzinfo (z.B. Grammatikhinweis), wird als Hint genutzt
═══════════════════════════════════════════════════════════════ */
const quizVocab = [

/* ═══════════════════ FRANZÖSISCH — EASY ═══════════════════ */
{ lang:"fr", level:"easy", term:"la table", answers:["der tisch","tisch"] },
{ lang:"fr", level:"easy", term:"la chaise", answers:["der stuhl","stuhl"] },
{ lang:"fr", level:"easy", term:"le pain", answers:["das brot","brot"] },
{ lang:"fr", level:"easy", term:"l'eau", answers:["das wasser","wasser"] },
{ lang:"fr", level:"easy", term:"la maison", answers:["das haus","haus"] },
{ lang:"fr", level:"easy", term:"le chat", answers:["die katze","katze"] },
{ lang:"fr", level:"easy", term:"le chien", answers:["der hund","hund"] },
{ lang:"fr", level:"easy", term:"la voiture", answers:["das auto","auto","der wagen"] },
{ lang:"fr", level:"easy", term:"le livre", answers:["das buch","buch"] },
{ lang:"fr", level:"easy", term:"la fenêtre", answers:["das fenster","fenster"] },
{ lang:"fr", level:"easy", term:"la porte", answers:["die tür","tür"] },
{ lang:"fr", level:"easy", term:"le lit", answers:["das bett","bett"] },
{ lang:"fr", level:"easy", term:"manger", answers:["essen"] },
{ lang:"fr", level:"easy", term:"boire", answers:["trinken"] },
{ lang:"fr", level:"easy", term:"dormir", answers:["schlafen"] },
{ lang:"fr", level:"easy", term:"parler", answers:["sprechen","reden"] },
{ lang:"fr", level:"easy", term:"aimer", answers:["lieben","mögen"] },
{ lang:"fr", level:"easy", term:"il mange", answers:["er isst"], note:"3. Person Singular" },
{ lang:"fr", level:"easy", term:"nous parlons", answers:["wir sprechen","wir reden"], note:"1. Person Plural" },
{ lang:"fr", level:"easy", term:"vous aimez", answers:["ihr mögt","ihr liebt","sie mögen","sie lieben"], note:"2. Person Plural/Höflichkeitsform" },
{ lang:"fr", level:"easy", term:"le soleil", answers:["die sonne","sonne"] },
{ lang:"fr", level:"easy", term:"la lune", answers:["der mond","mond"] },
{ lang:"fr", level:"easy", term:"le jour", answers:["der tag","tag"] },
{ lang:"fr", level:"easy", term:"la nuit", answers:["die nacht","nacht"] },
{ lang:"fr", level:"easy", term:"grand", answers:["groß"] },
{ lang:"fr", level:"easy", term:"petit", answers:["klein"] },
{ lang:"fr", level:"easy", term:"chaud", answers:["heiß","warm"] },
{ lang:"fr", level:"easy", term:"froid", answers:["kalt"] },
{ lang:"fr", level:"easy", term:"la mère", answers:["die mutter","mutter"] },
{ lang:"fr", level:"easy", term:"le père", answers:["der vater","vater"] },
{ lang:"fr", level:"easy", term:"la sœur", answers:["die schwester","schwester"] },
{ lang:"fr", level:"easy", term:"le frère", answers:["der bruder","bruder"] },
{ lang:"fr", level:"easy", term:"l'ami", answers:["der freund","freund"] },
{ lang:"fr", level:"easy", term:"l'école", answers:["die schule","schule"] },
{ lang:"fr", level:"easy", term:"le travail", answers:["die arbeit","arbeit"] },
{ lang:"fr", level:"easy", term:"la rue", answers:["die straße","straße"] },
{ lang:"fr", level:"easy", term:"la ville", answers:["die stadt","stadt"] },
{ lang:"fr", level:"easy", term:"le pays", answers:["das land","land"] },
{ lang:"fr", level:"easy", term:"aujourd'hui", answers:["heute"] },
{ lang:"fr", level:"easy", term:"demain", answers:["morgen"] },
{ lang:"fr", level:"easy", term:"hier", answers:["gestern"] },
{ lang:"fr", level:"easy", term:"maintenant", answers:["jetzt"] },
{ lang:"fr", level:"easy", term:"toujours", answers:["immer"] },
{ lang:"fr", level:"easy", term:"jamais", answers:["nie","niemals"] },
{ lang:"fr", level:"easy", term:"beaucoup", answers:["viel","viele"] },
{ lang:"fr", level:"easy", term:"un peu", answers:["ein wenig","ein bisschen"] },
{ lang:"fr", level:"easy", term:"le matin", answers:["der morgen","morgen"] },
{ lang:"fr", level:"easy", term:"le soir", answers:["der abend","abend"] },
{ lang:"fr", level:"easy", term:"la semaine", answers:["die woche","woche"] },
{ lang:"fr", level:"easy", term:"l'année", answers:["das jahr","jahr"] },
{ lang:"fr", level:"easy", term:"le mois", answers:["der monat","monat"] },
{ lang:"fr", level:"easy", term:"heureux", answers:["glücklich"] },
{ lang:"fr", level:"easy", term:"triste", answers:["traurig"] },
{ lang:"fr", level:"easy", term:"fatigué", answers:["müde"] },
{ lang:"fr", level:"easy", term:"la fourchette", answers:["die gabel","gabel"] },
{ lang:"fr", level:"easy", term:"le couteau", answers:["das messer","messer"] },
{ lang:"fr", level:"easy", term:"la cuillère", answers:["der löffel","löffel"] },
{ lang:"fr", level:"easy", term:"l'assiette", answers:["der teller","teller"] },
{ lang:"fr", level:"easy", term:"le verre", answers:["das glas","glas"] },
{ lang:"fr", level:"easy", term:"la cuisine", answers:["die küche","küche"] },
{ lang:"fr", level:"easy", term:"la salle de bain", answers:["das badezimmer","badezimmer"] },
{ lang:"fr", level:"easy", term:"le jardin", answers:["der garten","garten"] },
{ lang:"fr", level:"easy", term:"la fleur", answers:["die blume","blume"] },
{ lang:"fr", level:"easy", term:"l'arbre", answers:["der baum","baum"] },

/* ═══════════════════ FRANZÖSISCH — MEDIUM ═══════════════════ */
{ lang:"fr", level:"medium", term:"le quotidien", answers:["der alltag","alltag"] },
{ lang:"fr", level:"medium", term:"le réveil", answers:["der wecker","wecker"] },
{ lang:"fr", level:"medium", term:"la serviette", answers:["das handtuch","handtuch","die serviette"] },
{ lang:"fr", level:"medium", term:"le tiroir", answers:["die schublade","schublade"] },
{ lang:"fr", level:"medium", term:"le placard", answers:["der schrank","schrank"] },
{ lang:"fr", level:"medium", term:"la poubelle", answers:["der mülleimer","mülleimer","der abfalleimer"] },
{ lang:"fr", level:"medium", term:"le balai", answers:["der besen","besen"] },
{ lang:"fr", level:"medium", term:"l'aspirateur", answers:["der staubsauger","staubsauger"] },
{ lang:"fr", level:"medium", term:"le parapluie", answers:["der regenschirm","regenschirm","der schirm"] },
{ lang:"fr", level:"medium", term:"les ciseaux", answers:["die schere","schere"] },
{ lang:"fr", level:"medium", term:"le portefeuille", answers:["die brieftasche","brieftasche","das portemonnaie","der geldbeutel"] },
{ lang:"fr", level:"medium", term:"la clé", answers:["der schlüssel","schlüssel"] },
{ lang:"fr", level:"medium", term:"la serrure", answers:["das schloss","schloss"] },
{ lang:"fr", level:"medium", term:"le quai", answers:["der bahnsteig","bahnsteig","das kai"] },
{ lang:"fr", level:"medium", term:"le trajet", answers:["die fahrt","fahrt","die strecke","der weg"] },
{ lang:"fr", level:"medium", term:"le rendez-vous", answers:["der termin","termin","die verabredung"] },
{ lang:"fr", level:"medium", term:"la facture", answers:["die rechnung","rechnung"] },
{ lang:"fr", level:"medium", term:"le loyer", answers:["die miete","miete"] },
{ lang:"fr", level:"medium", term:"le locataire", answers:["der mieter","mieter"] },
{ lang:"fr", level:"medium", term:"le propriétaire", answers:["der eigentümer","eigentümer","der vermieter","der besitzer"] },
{ lang:"fr", level:"medium", term:"l'entretien", answers:["die instandhaltung","instandhaltung","die wartung","das vorstellungsgespräch"] },
{ lang:"fr", level:"medium", term:"le formulaire", answers:["das formular","formular"] },
{ lang:"fr", level:"medium", term:"le justificatif", answers:["der nachweis","nachweis","der beleg"] },
{ lang:"fr", level:"medium", term:"la démarche", answers:["der vorgang","vorgang","das verfahren","der schritt"] },
{ lang:"fr", level:"medium", term:"l'échéance", answers:["die frist","frist","der fälligkeitstermin"] },
{ lang:"fr", level:"medium", term:"il faut que je parte", answers:["ich muss gehen"], note:"unpersönlicher Ausdruck + Subjonctif" },
{ lang:"fr", level:"medium", term:"nous devrions partir", answers:["wir sollten gehen"], note:"Conditionnel présent" },
{ lang:"fr", level:"medium", term:"j'aurais dû savoir", answers:["ich hätte wissen sollen"], note:"Conditionnel passé" },
{ lang:"fr", level:"medium", term:"elle vient de partir", answers:["sie ist gerade gegangen"], note:"venir de + Infinitiv (unmittelbare Vergangenheit)" },
{ lang:"fr", level:"medium", term:"ils étaient en train de manger", answers:["sie waren gerade am essen","sie aßen gerade"], note:"Verlaufsform in der Vergangenheit" },
{ lang:"fr", level:"medium", term:"se dépêcher", answers:["sich beeilen"] },
{ lang:"fr", level:"medium", term:"se débrouiller", answers:["sich zurechtfinden","sich durchwursteln","klarkommen"] },
{ lang:"fr", level:"medium", term:"s'inquiéter", answers:["sich sorgen","sich sorgen machen"] },
{ lang:"fr", level:"medium", term:"se plaindre", answers:["sich beschweren","sich beklagen"] },
{ lang:"fr", level:"medium", term:"se souvenir", answers:["sich erinnern"] },
{ lang:"fr", level:"medium", term:"il se souvient", answers:["er erinnert sich"], note:"3. Person Singular, reflexiv" },
{ lang:"fr", level:"medium", term:"je me plains", answers:["ich beschwere mich"], note:"1. Person Singular" },
{ lang:"fr", level:"medium", term:"vous vous débrouillez", answers:["ihr kommt klar","sie kommen klar","ihr findet euch zurecht"], note:"2. Person Plural/Höflichkeitsform" },
{ lang:"fr", level:"medium", term:"la déception", answers:["die enttäuschung","enttäuschung"] },
{ lang:"fr", level:"medium", term:"le soulagement", answers:["die erleichterung","erleichterung"] },
{ lang:"fr", level:"medium", term:"la fierté", answers:["der stolz","stolz"] },
{ lang:"fr", level:"medium", term:"la honte", answers:["die scham","scham"] },
{ lang:"fr", level:"medium", term:"la jalousie", answers:["die eifersucht","eifersucht"] },
{ lang:"fr", level:"medium", term:"le mépris", answers:["die verachtung","verachtung"] },
{ lang:"fr", level:"medium", term:"la méfiance", answers:["das misstrauen","misstrauen"] },
{ lang:"fr", level:"medium", term:"la confiance", answers:["das vertrauen","vertrauen"] },
{ lang:"fr", level:"medium", term:"le doute", answers:["der zweifel","zweifel"] },
{ lang:"fr", level:"medium", term:"convaincre", answers:["überzeugen"] },
{ lang:"fr", level:"medium", term:"exiger", answers:["fordern","verlangen"] },
{ lang:"fr", level:"medium", term:"soulever", answers:["heben","aufwerfen","hochheben"] },
{ lang:"fr", level:"medium", term:"souligner", answers:["betonen","unterstreichen"] },
{ lang:"fr", level:"medium", term:"envisager", answers:["in betracht ziehen","erwägen"] },
{ lang:"fr", level:"medium", term:"repérer", answers:["ausmachen","entdecken","erkennen"] },
{ lang:"fr", level:"medium", term:"éviter", answers:["vermeiden"] },
{ lang:"fr", level:"medium", term:"parvenir", answers:["gelangen","erreichen","es schaffen"] },
{ lang:"fr", level:"medium", term:"aboutir", answers:["münden","enden","zum erfolg führen"] },
{ lang:"fr", level:"medium", term:"la fac", answers:["die uni","die universität"], note:"umgangssprachlich" },
{ lang:"fr", level:"medium", term:"le boulot", answers:["der job","die arbeit"], note:"umgangssprachlich" },
{ lang:"fr", level:"medium", term:"la bouffe", answers:["das essen"], note:"umgangssprachlich" },
{ lang:"fr", level:"medium", term:"le mec", answers:["der typ","der kerl"], note:"umgangssprachlich" },
{ lang:"fr", level:"medium", term:"la meuf", answers:["die frau","das mädel"], note:"umgangssprachlich (Verlan)" },
{ lang:"fr", level:"medium", term:"chouette", answers:["toll","klasse","super"], note:"umgangssprachlich" },
{ lang:"fr", level:"medium", term:"génial", answers:["genial","großartig"] },
{ lang:"fr", level:"medium", term:"pénible", answers:["mühsam","lästig","anstrengend"] },
{ lang:"fr", level:"medium", term:"étonnant", answers:["erstaunlich"] },
{ lang:"fr", level:"medium", term:"la maladresse", answers:["die ungeschicklichkeit","ungeschicklichkeit"] },
{ lang:"fr", level:"medium", term:"le hasard", answers:["der zufall","zufall"] },
{ lang:"fr", level:"medium", term:"le destin", answers:["das schicksal","schicksal"] },
{ lang:"fr", level:"medium", term:"l'avenir", answers:["die zukunft","zukunft"] },
{ lang:"fr", level:"medium", term:"le passé", answers:["die vergangenheit","vergangenheit"] },
{ lang:"fr", level:"medium", term:"le souvenir", answers:["die erinnerung","erinnerung"] },
{ lang:"fr", level:"medium", term:"la promesse", answers:["das versprechen","versprechen"] },
{ lang:"fr", level:"medium", term:"le mensonge", answers:["die lüge","lüge"] },
{ lang:"fr", level:"medium", term:"la vérité", answers:["die wahrheit","wahrheit"] },
{ lang:"fr", level:"medium", term:"le mensonge blanc", answers:["die notlüge","notlüge"] },
{ lang:"fr", level:"medium", term:"la trahison", answers:["der verrat","verrat"] },
{ lang:"fr", level:"medium", term:"le pardon", answers:["die verzeihung","verzeihung","die vergebung"] },
{ lang:"fr", level:"medium", term:"la rancune", answers:["der groll","groll"] },
{ lang:"fr", level:"medium", term:"le reproche", answers:["der vorwurf","vorwurf"] },
{ lang:"fr", level:"medium", term:"la faute", answers:["die schuld","schuld","der fehler"] },
{ lang:"fr", level:"medium", term:"le remords", answers:["die reue","reue"] },
{ lang:"fr", level:"medium", term:"les commérages", answers:["der klatsch","klatsch","das gerede"] },
{ lang:"fr", level:"medium", term:"le potin", answers:["der klatsch","klatsch","das gerücht"] },
{ lang:"fr", level:"medium", term:"la rumeur", answers:["das gerücht","gerücht"] },
{ lang:"fr", level:"medium", term:"médire", answers:["lästern","verleumden"] },
{ lang:"fr", level:"medium", term:"se moquer", answers:["sich lustig machen","spotten"] },
{ lang:"fr", level:"medium", term:"vexer", answers:["kränken","beleidigen"] },
{ lang:"fr", level:"medium", term:"blesser", answers:["verletzen"] },
{ lang:"fr", level:"medium", term:"réconforter", answers:["trösten"] },
{ lang:"fr", level:"medium", term:"encourager", answers:["ermutigen","ermuntern"] },
{ lang:"fr", level:"medium", term:"décourager", answers:["entmutigen"] },
{ lang:"fr", level:"medium", term:"la patience", answers:["die geduld","geduld"] },
{ lang:"fr", level:"medium", term:"l'impatience", answers:["die ungeduld","ungeduld"] },
{ lang:"fr", level:"medium", term:"la ténacité", answers:["die hartnäckigkeit","hartnäckigkeit","die beharrlichkeit"] },
{ lang:"fr", level:"medium", term:"la maladie", answers:["die krankheit","krankheit"] },
{ lang:"fr", level:"medium", term:"le remède", answers:["das heilmittel","heilmittel","das mittel"] },
{ lang:"fr", level:"medium", term:"le médicament", answers:["das medikament","medikament"] },
{ lang:"fr", level:"medium", term:"la blessure", answers:["die wunde","wunde","die verletzung"] },
{ lang:"fr", level:"medium", term:"le pansement", answers:["der verband","verband","das pflaster"] },
{ lang:"fr", level:"medium", term:"la cicatrice", answers:["die narbe","narbe"] },
{ lang:"fr", level:"medium", term:"la grossesse", answers:["die schwangerschaft","schwangerschaft"] },
{ lang:"fr", level:"medium", term:"l'accouchement", answers:["die geburt","geburt","die entbindung"] },
{ lang:"fr", level:"medium", term:"le deuil", answers:["die trauer","trauer"] },
{ lang:"fr", level:"medium", term:"l'enterrement", answers:["die beerdigung","beerdigung"] },
{ lang:"fr", level:"medium", term:"le testament", answers:["das testament","testament"] },
{ lang:"fr", level:"medium", term:"l'héritage", answers:["das erbe","erbe"] },
{ lang:"fr", level:"medium", term:"le voisinage", answers:["die nachbarschaft","nachbarschaft"] },
{ lang:"fr", level:"medium", term:"l'immeuble", answers:["das gebäude","gebäude","das mehrfamilienhaus"] },
{ lang:"fr", level:"medium", term:"le trottoir", answers:["der gehweg","gehweg","der bürgersteig"] },
{ lang:"fr", level:"medium", term:"le feu rouge", answers:["die ampel","ampel"] },
{ lang:"fr", level:"medium", term:"le passage piéton", answers:["der zebrastreifen","zebrastreifen","der fußgängerüberweg"] },
{ lang:"fr", level:"medium", term:"l'embouteillage", answers:["der stau","stau"] },
{ lang:"fr", level:"medium", term:"le péage", answers:["die maut","maut"] },
{ lang:"fr", level:"medium", term:"le carrefour", answers:["die kreuzung","kreuzung"] },
{ lang:"fr", level:"medium", term:"le rond-point", answers:["der kreisverkehr","kreisverkehr"] },
{ lang:"fr", level:"medium", term:"le permis de conduire", answers:["der führerschein","führerschein"] },
{ lang:"fr", level:"medium", term:"l'essence", answers:["das benzin","benzin"] },
{ lang:"fr", level:"medium", term:"le pneu", answers:["der reifen","reifen"] },
{ lang:"fr", level:"medium", term:"le coffre", answers:["der kofferraum","kofferraum"] },
{ lang:"fr", level:"medium", term:"la panne", answers:["die panne","panne"] },
{ lang:"fr", level:"medium", term:"l'entrepreneur", answers:["der unternehmer","unternehmer"] },
{ lang:"fr", level:"medium", term:"la concurrence", answers:["die konkurrenz","konkurrenz","der wettbewerb"] },
{ lang:"fr", level:"medium", term:"la faillite", answers:["der bankrott","bankrott","die insolvenz"] },
{ lang:"fr", level:"medium", term:"le chiffre d'affaires", answers:["der umsatz","umsatz"] },
{ lang:"fr", level:"medium", term:"le bénéfice", answers:["der gewinn","gewinn"] },
{ lang:"fr", level:"medium", term:"la perte", answers:["der verlust","verlust"] },
{ lang:"fr", level:"medium", term:"l'impôt", answers:["die steuer","steuer"] },
{ lang:"fr", level:"medium", term:"le salaire", answers:["das gehalt","gehalt","der lohn"] },
{ lang:"fr", level:"medium", term:"la retraite", answers:["die rente","rente","der ruhestand"] },
{ lang:"fr", level:"medium", term:"le chômage", answers:["die arbeitslosigkeit","arbeitslosigkeit"] },
{ lang:"fr", level:"medium", term:"l'embauche", answers:["die einstellung","einstellung"], note:"im Sinne von Anstellung" },
{ lang:"fr", level:"medium", term:"le licenciement", answers:["die kündigung","kündigung","die entlassung"] },
{ lang:"fr", level:"medium", term:"la démission", answers:["der rücktritt","rücktritt","die kündigung"] },
{ lang:"fr", level:"medium", term:"le collègue", answers:["der kollege","kollege"] },
{ lang:"fr", level:"medium", term:"le supérieur", answers:["der vorgesetzte","vorgesetzte"] },
{ lang:"fr", level:"medium", term:"la réunion", answers:["die besprechung","besprechung","das meeting"] },

/* ═══════════════════ FRANZÖSISCH — HARD ═══════════════════ */
{ lang:"fr", level:"hard", term:"l'ébauche", answers:["der entwurf","entwurf","die skizze"] },
{ lang:"fr", level:"hard", term:"l'entrave", answers:["das hindernis","hindernis","die behinderung"] },
{ lang:"fr", level:"hard", term:"l'acharnement", answers:["die verbissenheit","verbissenheit","der fanatismus"] },
{ lang:"fr", level:"hard", term:"la lassitude", answers:["die müdigkeit","müdigkeit","der überdruss"] },
{ lang:"fr", level:"hard", term:"la lucidité", answers:["die klarsicht","klarsicht","die klarheit"] },
{ lang:"fr", level:"hard", term:"l'entêtement", answers:["die sturheit","sturheit","der starrsinn"] },
{ lang:"fr", level:"hard", term:"la désinvolture", answers:["die lässigkeit","lässigkeit","die unbekümmertheit"] },
{ lang:"fr", level:"hard", term:"l'insouciance", answers:["die sorglosigkeit","sorglosigkeit"] },
{ lang:"fr", level:"hard", term:"la clairvoyance", answers:["die hellsichtigkeit","hellsichtigkeit"] },
{ lang:"fr", level:"hard", term:"la bienveillance", answers:["das wohlwollen","wohlwollen"] },
{ lang:"fr", level:"hard", term:"la malveillance", answers:["die böswilligkeit","böswilligkeit"] },
{ lang:"fr", level:"hard", term:"l'obstination", answers:["die hartnäckigkeit","hartnäckigkeit","die sturheit"] },
{ lang:"fr", level:"hard", term:"la circonspection", answers:["die umsicht","umsicht","die vorsicht"] },
{ lang:"fr", level:"hard", term:"la nonchalance", answers:["die lässigkeit","lässigkeit","die gelassenheit"] },
{ lang:"fr", level:"hard", term:"l'engouement", answers:["die begeisterung","begeisterung","der enthusiasmus"] },
{ lang:"fr", level:"hard", term:"le désarroi", answers:["die verzweiflung","verzweiflung","die ratlosigkeit"] },
{ lang:"fr", level:"hard", term:"l'acrimonie", answers:["die verbitterung","verbitterung","die bissigkeit"] },
{ lang:"fr", level:"hard", term:"la mésentente", answers:["das zerwürfnis","zerwürfnis","die uneinigkeit"] },
{ lang:"fr", level:"hard", term:"le contentieux", answers:["der rechtsstreit","rechtsstreit","der streitfall"] },
{ lang:"fr", level:"hard", term:"la mésaventure", answers:["das missgeschick","missgeschick"] },
{ lang:"fr", level:"hard", term:"le subterfuge", answers:["die ausflucht","ausflucht","die list"] },
{ lang:"fr", level:"hard", term:"le stratagème", answers:["die kriegslist","kriegslist","der trick","die taktik"] },
{ lang:"fr", level:"hard", term:"la ruse", answers:["die list","list"] },
{ lang:"fr", level:"hard", term:"l'artifice", answers:["die täuschung","täuschung","der kunstgriff"] },
{ lang:"fr", level:"hard", term:"la duperie", answers:["der betrug","betrug","die täuschung"] },
{ lang:"fr", level:"hard", term:"l'escroquerie", answers:["der betrug","betrug","der schwindel"] },
{ lang:"fr", level:"hard", term:"le détournement", answers:["die veruntreuung","veruntreuung","die unterschlagung"] },
{ lang:"fr", level:"hard", term:"le préjudice", answers:["der schaden","schaden","der nachteil"] },
{ lang:"fr", level:"hard", term:"le recours", answers:["der rechtsbehelf","rechtsbehelf","der rückgriff","die berufung"] },
{ lang:"fr", level:"hard", term:"le litige", answers:["der rechtsstreit","rechtsstreit","der streitfall"] },
{ lang:"fr", level:"hard", term:"la mise en demeure", answers:["die mahnung","mahnung","die abmahnung"] },
{ lang:"fr", level:"hard", term:"le préavis", answers:["die kündigungsfrist","kündigungsfrist","die vorankündigung"] },
{ lang:"fr", level:"hard", term:"la caution", answers:["die kaution","kaution","die bürgschaft"] },
{ lang:"fr", level:"hard", term:"l'aval", answers:["die zustimmung","zustimmung","die bürgschaft"] },
{ lang:"fr", level:"hard", term:"le cautionnement", answers:["die bürgschaft","bürgschaft"] },
{ lang:"fr", level:"hard", term:"la clause", answers:["die klausel","klausel"] },
{ lang:"fr", level:"hard", term:"l'avenant", answers:["der nachtrag","nachtrag","die zusatzvereinbarung"] },
{ lang:"fr", level:"hard", term:"la résiliation", answers:["die kündigung","kündigung"] },
{ lang:"fr", level:"hard", term:"la reconduction", answers:["die verlängerung","verlängerung"] },
{ lang:"fr", level:"hard", term:"l'échéancier", answers:["der zahlungsplan","zahlungsplan","der terminplan"] },
{ lang:"fr", level:"hard", term:"le contentieux fiscal", answers:["der steuerstreit","steuerstreit"] },
{ lang:"fr", level:"hard", term:"la fiscalité", answers:["das steuerwesen","steuerwesen","die besteuerung"] },
{ lang:"fr", level:"hard", term:"l'exonération", answers:["die befreiung","befreiung"], note:"z.B. Steuerbefreiung" },
{ lang:"fr", level:"hard", term:"le prélèvement", answers:["der abzug","abzug","die abbuchung"] },
{ lang:"fr", level:"hard", term:"la surenchère", answers:["das überbieten","überbieten","das höhere gebot"] },
{ lang:"fr", level:"hard", term:"la conjoncture", answers:["die konjunktur","konjunktur"] },
{ lang:"fr", level:"hard", term:"l'essor", answers:["der aufschwung","aufschwung"] },
{ lang:"fr", level:"hard", term:"le repli", answers:["der rückgang","rückgang","der rückzug"] },
{ lang:"fr", level:"hard", term:"la récession", answers:["die rezession","rezession"] },
{ lang:"fr", level:"hard", term:"la relance", answers:["das ankurbeln","ankurbeln","der aufschwung","die konjunkturbelebung"] },
{ lang:"fr", level:"hard", term:"l'endettement", answers:["die verschuldung","verschuldung"] },
{ lang:"fr", level:"hard", term:"le désendettement", answers:["der schuldenabbau","schuldenabbau"] },
{ lang:"fr", level:"hard", term:"la trésorerie", answers:["die liquidität","liquidität","die kasse"] },
{ lang:"fr", level:"hard", term:"le plafonnement", answers:["die deckelung","deckelung","die obergrenze"] },
{ lang:"fr", level:"hard", term:"l'assouplissement", answers:["die lockerung","lockerung"] },
{ lang:"fr", level:"hard", term:"le durcissement", answers:["die verschärfung","verschärfung"] },
{ lang:"fr", level:"hard", term:"la mainmise", answers:["die kontrolle","kontrolle","die vorherrschaft"] },
{ lang:"fr", level:"hard", term:"l'emprise", answers:["der einfluss","einfluss","die kontrolle"] },
{ lang:"fr", level:"hard", term:"la mouvance", answers:["die strömung","strömung"], note:"politische Bewegung" },
{ lang:"fr", level:"hard", term:"le clivage", answers:["die spaltung","spaltung","der graben"] },
{ lang:"fr", level:"hard", term:"la scission", answers:["die abspaltung","abspaltung"] },
{ lang:"fr", level:"hard", term:"le compromis", answers:["der kompromiss","kompromiss"] },
{ lang:"fr", level:"hard", term:"le consensus", answers:["der konsens","konsens"] },
{ lang:"fr", level:"hard", term:"l'entente", answers:["die einigung","einigung","das einvernehmen"] },
{ lang:"fr", level:"hard", term:"le désaveu", answers:["die zurückweisung","zurückweisung","das dementi"] },
{ lang:"fr", level:"hard", term:"le démenti", answers:["das dementi","dementi"] },
{ lang:"fr", level:"hard", term:"l'aveu", answers:["das geständnis","geständnis"] },
{ lang:"fr", level:"hard", term:"le désaccord", answers:["die uneinigkeit","uneinigkeit","der widerspruch"] },
{ lang:"fr", level:"hard", term:"quoi qu'il en soit", answers:["wie dem auch sei"] },
{ lang:"fr", level:"hard", term:"quoique cela soit vrai", answers:["obwohl das wahr ist"], note:"Konjunktion mit Subjonctif" },
{ lang:"fr", level:"hard", term:"il se pourrait qu'il vienne", answers:["es könnte sein, dass er kommt"], note:"Subjonctif nach unpersönlichem Ausdruck" },
{ lang:"fr", level:"hard", term:"pour peu qu'il pleuve", answers:["falls es auch nur ein bisschen regnet"], note:"Subjonctif nach 'pour peu que'" },
{ lang:"fr", level:"hard", term:"bien qu'il soit tard", answers:["obwohl es spät ist"], note:"Subjonctif nach 'bien que'" },
{ lang:"fr", level:"hard", term:"à moins qu'il ne pleuve", answers:["es sei denn, es regnet","außer es regnet"], note:"Subjonctif nach 'à moins que'" },
{ lang:"fr", level:"hard", term:"afin qu'il comprenne", answers:["damit er versteht"], note:"Subjonctif nach 'afin que'" },
{ lang:"fr", level:"hard", term:"j'eusse aimé", answers:["ich hätte gern gehabt"], note:"Plus-que-parfait du subjonctif (literarisch)" },
{ lang:"fr", level:"hard", term:"eût-il su", answers:["hätte er gewusst"], note:"Inversion im literarischen Subjonctif" },
{ lang:"fr", level:"hard", term:"fût-ce vrai", answers:["wäre es auch wahr"], note:"literarischer Subjonctif" },
{ lang:"fr", level:"hard", term:"nonobstant", answers:["ungeachtet","trotzdem"], note:"gehobene Sprache/Amtssprache" },
{ lang:"fr", level:"hard", term:"partant", answers:["folglich","demzufolge"], note:"gehobene Sprache" },
{ lang:"fr", level:"hard", term:"dès lors", answers:["von da an","folglich","demnach"] },
{ lang:"fr", level:"hard", term:"toutefois", answers:["jedoch","dennoch"] },
{ lang:"fr", level:"hard", term:"néanmoins", answers:["dennoch","trotzdem"] },
{ lang:"fr", level:"hard", term:"par ailleurs", answers:["außerdem","im übrigen"] },
{ lang:"fr", level:"hard", term:"qui plus est", answers:["obendrein","zudem"] },
{ lang:"fr", level:"hard", term:"cela étant dit", answers:["dies gesagt","dennoch","davon abgesehen"] },
{ lang:"fr", level:"hard", term:"force est de constater", answers:["man muss feststellen"] },
{ lang:"fr", level:"hard", term:"il n'en demeure pas moins", answers:["dennoch bleibt bestehen","nichtsdestotrotz"] },
{ lang:"fr", level:"hard", term:"loin s'en faut", answers:["bei weitem nicht"] },
{ lang:"fr", level:"hard", term:"tant s'en faut", answers:["bei weitem nicht","keineswegs"] },
{ lang:"fr", level:"hard", term:"il n'empêche que", answers:["trotzdem","dennoch"] },
{ lang:"fr", level:"hard", term:"l'entrelacs", answers:["das geflecht","geflecht","das gewirr"] },
{ lang:"fr", level:"hard", term:"l'écheveau", answers:["das knäuel","knäuel","das gewirr"] },
{ lang:"fr", level:"hard", term:"la friche", answers:["die brachfläche","brachfläche","brachland"] },
{ lang:"fr", level:"hard", term:"le terreau", answers:["der nährboden","nährboden","die erde"] },
{ lang:"fr", level:"hard", term:"la jachère", answers:["die brache","brache"] },
{ lang:"fr", level:"hard", term:"le sillon", answers:["die furche","furche"] },
{ lang:"fr", level:"hard", term:"la récolte", answers:["die ernte","ernte"] },
{ lang:"fr", level:"hard", term:"la moisson", answers:["die ernte","ernte"], note:"insb. Getreideernte" },
{ lang:"fr", level:"hard", term:"le terroir", answers:["die heimaterde","heimaterde","das anbaugebiet"] },
{ lang:"fr", level:"hard", term:"l'exode rural", answers:["die landflucht","landflucht"] },
{ lang:"fr", level:"hard", term:"l'étalement urbain", answers:["die zersiedelung","zersiedelung"] },
{ lang:"fr", level:"hard", term:"la friche industrielle", answers:["die industriebrache","industriebrache"] },
{ lang:"fr", level:"hard", term:"le gisement", answers:["die lagerstätte","lagerstätte","das vorkommen"] },
{ lang:"fr", level:"hard", term:"la pénurie", answers:["die knappheit","knappheit","der mangel"] },
{ lang:"fr", level:"hard", term:"la surabondance", answers:["der überfluss","überfluss","das überangebot"] },
{ lang:"fr", level:"hard", term:"le gaspillage", answers:["die verschwendung","verschwendung"] },
{ lang:"fr", level:"hard", term:"la parcimonie", answers:["die sparsamkeit","sparsamkeit","die knauserigkeit"] },
{ lang:"fr", level:"hard", term:"la prodigalité", answers:["die verschwendungssucht","verschwendungssucht"] },
{ lang:"fr", level:"hard", term:"l'avarice", answers:["der geiz","geiz"] },
{ lang:"fr", level:"hard", term:"la cupidité", answers:["die habgier","habgier","die gier"] },
{ lang:"fr", level:"hard", term:"la convoitise", answers:["die begierde","begierde","das verlangen"] },
{ lang:"fr", level:"hard", term:"l'appât du gain", answers:["die profitgier","profitgier","die gewinnsucht"] },
{ lang:"fr", level:"hard", term:"le désir", answers:["das verlangen","verlangen","der wunsch"] },
{ lang:"fr", level:"hard", term:"l'aspiration", answers:["das streben","streben","die sehnsucht"] },
{ lang:"fr", level:"hard", term:"le renoncement", answers:["der verzicht","verzicht"] },
{ lang:"fr", level:"hard", term:"l'abnégation", answers:["die selbstaufgabe","selbstaufgabe","die selbstlosigkeit"] },
{ lang:"fr", level:"hard", term:"le dévouement", answers:["die hingabe","hingabe","die aufopferung"] },
{ lang:"fr", level:"hard", term:"l'altruisme", answers:["der altruismus","altruismus","die selbstlosigkeit"] },
{ lang:"fr", level:"hard", term:"l'égoïsme", answers:["der egoismus","egoismus"] },
{ lang:"fr", level:"hard", term:"la vanité", answers:["die eitelkeit","eitelkeit"] },
{ lang:"fr", level:"hard", term:"l'arrogance", answers:["die arroganz","arroganz"] },
{ lang:"fr", level:"hard", term:"l'humilité", answers:["die demut","demut","die bescheidenheit"] },
{ lang:"fr", level:"hard", term:"la modestie", answers:["die bescheidenheit","bescheidenheit"] },
{ lang:"fr", level:"hard", term:"la vantardise", answers:["die angeberei","angeberei","die prahlerei"] },
{ lang:"fr", level:"hard", term:"la présomption", answers:["die anmaßung","anmaßung","die vermutung"] },
{ lang:"fr", level:"hard", term:"le culot", answers:["die frechheit","frechheit","die dreistigkeit"], note:"umgangssprachlich" },
{ lang:"fr", level:"hard", term:"l'effronterie", answers:["die unverschämtheit","unverschämtheit","die frechheit"] },
{ lang:"fr", level:"hard", term:"la pudeur", answers:["die scham","scham","die schamhaftigkeit"] },
{ lang:"fr", level:"hard", term:"l'impudeur", answers:["die schamlosigkeit","schamlosigkeit"] },
{ lang:"fr", level:"hard", term:"la décence", answers:["der anstand","anstand","die schicklichkeit"] },
{ lang:"fr", level:"hard", term:"l'indécence", answers:["die unanständigkeit","unanständigkeit"] },
{ lang:"fr", level:"hard", term:"l'insolence", answers:["die unverschämtheit","unverschämtheit","die frechheit"] },
{ lang:"fr", level:"hard", term:"la désobéissance", answers:["der ungehorsam","ungehorsam"] },
{ lang:"fr", level:"hard", term:"l'entrave à la justice", answers:["die justizbehinderung","justizbehinderung"] },
{ lang:"fr", level:"hard", term:"l'outrage", answers:["die beleidigung","beleidigung"], note:"insb. gegen Amtsträger" },
{ lang:"fr", level:"hard", term:"le sévices", answers:["die misshandlung","misshandlung"] },
{ lang:"fr", level:"hard", term:"la maltraitance", answers:["die misshandlung","misshandlung"] },
{ lang:"fr", level:"hard", term:"l'atermoiement", answers:["das zögern","zögern","die verzögerung"] },
{ lang:"fr", level:"hard", term:"la tergiversation", answers:["das zaudern","zaudern","das hin und her"] },
{ lang:"fr", level:"hard", term:"la procrastination", answers:["das aufschieben","aufschieben","die prokrastination"] },
{ lang:"fr", level:"hard", term:"la précipitation", answers:["die eile","eile","die überstürzung"] },
{ lang:"fr", level:"hard", term:"l'empressement", answers:["der eifer","eifer","die eile"] },
{ lang:"fr", level:"hard", term:"la diligence", answers:["die sorgfalt","sorgfalt","der fleiß"] },
{ lang:"fr", level:"hard", term:"la négligence", answers:["die nachlässigkeit","nachlässigkeit"] },
{ lang:"fr", level:"hard", term:"l'insouciance juvénile", answers:["die jugendliche sorglosigkeit","jugendliche sorglosigkeit"] },
{ lang:"fr", level:"hard", term:"la désinvolture affichée", answers:["die zur schau gestellte lässigkeit","zur schau gestellte lässigkeit"] },
{ lang:"fr", level:"hard", term:"le zèle", answers:["der eifer","eifer"] },
{ lang:"fr", level:"hard", term:"la ferveur", answers:["die inbrunst","inbrunst","der eifer"] },
{ lang:"fr", level:"hard", term:"la piété", answers:["die frömmigkeit","frömmigkeit"] },
{ lang:"fr", level:"hard", term:"l'impiété", answers:["die gottlosigkeit","gottlosigkeit"] },
{ lang:"fr", level:"hard", term:"la dévotion", answers:["die hingabe","hingabe","die frömmigkeit"] },

/* ═══════════════════ ENGLISCH — EASY ═══════════════════ */
{ lang:"en", level:"easy", term:"table", answers:["der tisch","tisch"] },
{ lang:"en", level:"easy", term:"chair", answers:["der stuhl","stuhl"] },
{ lang:"en", level:"easy", term:"bread", answers:["das brot","brot"] },
{ lang:"en", level:"easy", term:"water", answers:["das wasser","wasser"] },
{ lang:"en", level:"easy", term:"house", answers:["das haus","haus"] },
{ lang:"en", level:"easy", term:"cat", answers:["die katze","katze"] },
{ lang:"en", level:"easy", term:"dog", answers:["der hund","hund"] },
{ lang:"en", level:"easy", term:"car", answers:["das auto","auto","der wagen"] },
{ lang:"en", level:"easy", term:"book", answers:["das buch","buch"] },
{ lang:"en", level:"easy", term:"window", answers:["das fenster","fenster"] },
{ lang:"en", level:"easy", term:"door", answers:["die tür","tür"] },
{ lang:"en", level:"easy", term:"bed", answers:["das bett","bett"] },
{ lang:"en", level:"easy", term:"to eat", answers:["essen"] },
{ lang:"en", level:"easy", term:"to drink", answers:["trinken"] },
{ lang:"en", level:"easy", term:"to sleep", answers:["schlafen"] },
{ lang:"en", level:"easy", term:"to speak", answers:["sprechen","reden"] },
{ lang:"en", level:"easy", term:"to love", answers:["lieben"] },
{ lang:"en", level:"easy", term:"he eats", answers:["er isst"], note:"3. Person Singular Präsens" },
{ lang:"en", level:"easy", term:"we speak", answers:["wir sprechen","wir reden"], note:"1. Person Plural Präsens" },
{ lang:"en", level:"easy", term:"they loved", answers:["sie liebten"], note:"Simple Past" },
{ lang:"en", level:"easy", term:"sun", answers:["die sonne","sonne"] },
{ lang:"en", level:"easy", term:"moon", answers:["der mond","mond"] },
{ lang:"en", level:"easy", term:"day", answers:["der tag","tag"] },
{ lang:"en", level:"easy", term:"night", answers:["die nacht","nacht"] },
{ lang:"en", level:"easy", term:"big", answers:["groß"] },
{ lang:"en", level:"easy", term:"small", answers:["klein"] },
{ lang:"en", level:"easy", term:"hot", answers:["heiß"] },
{ lang:"en", level:"easy", term:"cold", answers:["kalt"] },
{ lang:"en", level:"easy", term:"mother", answers:["die mutter","mutter"] },
{ lang:"en", level:"easy", term:"father", answers:["der vater","vater"] },
{ lang:"en", level:"easy", term:"sister", answers:["die schwester","schwester"] },
{ lang:"en", level:"easy", term:"brother", answers:["der bruder","bruder"] },
{ lang:"en", level:"easy", term:"friend", answers:["der freund","freund","die freundin"] },
{ lang:"en", level:"easy", term:"school", answers:["die schule","schule"] },
{ lang:"en", level:"easy", term:"work", answers:["die arbeit","arbeit"] },
{ lang:"en", level:"easy", term:"street", answers:["die straße","straße"] },
{ lang:"en", level:"easy", term:"city", answers:["die stadt","stadt"] },
{ lang:"en", level:"easy", term:"country", answers:["das land","land"] },
{ lang:"en", level:"easy", term:"today", answers:["heute"] },
{ lang:"en", level:"easy", term:"tomorrow", answers:["morgen"] },
{ lang:"en", level:"easy", term:"yesterday", answers:["gestern"] },
{ lang:"en", level:"easy", term:"now", answers:["jetzt"] },
{ lang:"en", level:"easy", term:"always", answers:["immer"] },
{ lang:"en", level:"easy", term:"never", answers:["nie","niemals"] },
{ lang:"en", level:"easy", term:"a lot", answers:["viel","viele"] },
{ lang:"en", level:"easy", term:"a little", answers:["ein wenig","ein bisschen"] },
{ lang:"en", level:"easy", term:"morning", answers:["der morgen","morgen"] },
{ lang:"en", level:"easy", term:"evening", answers:["der abend","abend"] },
{ lang:"en", level:"easy", term:"week", answers:["die woche","woche"] },
{ lang:"en", level:"easy", term:"year", answers:["das jahr","jahr"] },
{ lang:"en", level:"easy", term:"month", answers:["der monat","monat"] },
{ lang:"en", level:"easy", term:"happy", answers:["glücklich"] },
{ lang:"en", level:"easy", term:"sad", answers:["traurig"] },
{ lang:"en", level:"easy", term:"tired", answers:["müde"] },
{ lang:"en", level:"easy", term:"fork", answers:["die gabel","gabel"] },
{ lang:"en", level:"easy", term:"knife", answers:["das messer","messer"] },
{ lang:"en", level:"easy", term:"spoon", answers:["der löffel","löffel"] },
{ lang:"en", level:"easy", term:"plate", answers:["der teller","teller"] },
{ lang:"en", level:"easy", term:"glass", answers:["das glas","glas"] },
{ lang:"en", level:"easy", term:"kitchen", answers:["die küche","küche"] },
{ lang:"en", level:"easy", term:"bathroom", answers:["das badezimmer","badezimmer"] },
{ lang:"en", level:"easy", term:"garden", answers:["der garten","garten"] },
{ lang:"en", level:"easy", term:"flower", answers:["die blume","blume"] },
{ lang:"en", level:"easy", term:"tree", answers:["der baum","baum"] },

/* ═══════════════════ ENGLISCH — MEDIUM ═══════════════════ */
{ lang:"en", level:"medium", term:"everyday life", answers:["der alltag","alltag"] },
{ lang:"en", level:"medium", term:"alarm clock", answers:["der wecker","wecker"] },
{ lang:"en", level:"medium", term:"towel", answers:["das handtuch","handtuch"] },
{ lang:"en", level:"medium", term:"drawer", answers:["die schublade","schublade"] },
{ lang:"en", level:"medium", term:"cupboard", answers:["der schrank","schrank"] },
{ lang:"en", level:"medium", term:"trash can", answers:["der mülleimer","mülleimer"] },
{ lang:"en", level:"medium", term:"broom", answers:["der besen","besen"] },
{ lang:"en", level:"medium", term:"vacuum cleaner", answers:["der staubsauger","staubsauger"] },
{ lang:"en", level:"medium", term:"umbrella", answers:["der regenschirm","regenschirm","der schirm"] },
{ lang:"en", level:"medium", term:"scissors", answers:["die schere","schere"] },
{ lang:"en", level:"medium", term:"wallet", answers:["die brieftasche","brieftasche","das portemonnaie"] },
{ lang:"en", level:"medium", term:"key", answers:["der schlüssel","schlüssel"] },
{ lang:"en", level:"medium", term:"lock", answers:["das schloss","schloss"] },
{ lang:"en", level:"medium", term:"platform", answers:["der bahnsteig","bahnsteig"], note:"Bahnhof" },
{ lang:"en", level:"medium", term:"appointment", answers:["der termin","termin"] },
{ lang:"en", level:"medium", term:"invoice", answers:["die rechnung","rechnung"] },
{ lang:"en", level:"medium", term:"rent", answers:["die miete","miete"] },
{ lang:"en", level:"medium", term:"tenant", answers:["der mieter","mieter"] },
{ lang:"en", level:"medium", term:"landlord", answers:["der vermieter","vermieter"] },
{ lang:"en", level:"medium", term:"maintenance", answers:["die instandhaltung","instandhaltung","die wartung"] },
{ lang:"en", level:"medium", term:"form", answers:["das formular","formular"] },
{ lang:"en", level:"medium", term:"proof", answers:["der nachweis","nachweis","der beleg"] },
{ lang:"en", level:"medium", term:"deadline", answers:["die frist","frist"] },
{ lang:"en", level:"medium", term:"I should have known", answers:["ich hätte wissen sollen"], note:"Perfekt Konditional" },
{ lang:"en", level:"medium", term:"she has just left", answers:["sie ist gerade gegangen"], note:"Present Perfect + 'just'" },
{ lang:"en", level:"medium", term:"they were eating", answers:["sie aßen gerade","sie waren gerade am essen"], note:"Past Continuous" },
{ lang:"en", level:"medium", term:"I will have finished", answers:["ich werde fertig sein","ich werde es beendet haben"], note:"Future Perfect" },
{ lang:"en", level:"medium", term:"if I were you", answers:["wenn ich du wäre","an deiner stelle"], note:"Conditional / Subjunctive" },
{ lang:"en", level:"medium", term:"to hurry", answers:["sich beeilen"] },
{ lang:"en", level:"medium", term:"to manage", answers:["schaffen","klarkommen","es hinbekommen"] },
{ lang:"en", level:"medium", term:"to worry", answers:["sich sorgen","sich sorgen machen"] },
{ lang:"en", level:"medium", term:"to complain", answers:["sich beschweren","sich beklagen"] },
{ lang:"en", level:"medium", term:"to remember", answers:["sich erinnern"] },
{ lang:"en", level:"medium", term:"he remembers", answers:["er erinnert sich"], note:"3. Person Singular" },
{ lang:"en", level:"medium", term:"I am complaining", answers:["ich beschwere mich"], note:"Present Continuous" },
{ lang:"en", level:"medium", term:"you manage", answers:["du kommst klar","ihr kommt klar","sie kommen klar"], note:"2. Person" },
{ lang:"en", level:"medium", term:"disappointment", answers:["die enttäuschung","enttäuschung"] },
{ lang:"en", level:"medium", term:"relief", answers:["die erleichterung","erleichterung"] },
{ lang:"en", level:"medium", term:"pride", answers:["der stolz","stolz"] },
{ lang:"en", level:"medium", term:"shame", answers:["die scham","scham"] },
{ lang:"en", level:"medium", term:"jealousy", answers:["die eifersucht","eifersucht"] },
{ lang:"en", level:"medium", term:"contempt", answers:["die verachtung","verachtung"] },
{ lang:"en", level:"medium", term:"distrust", answers:["das misstrauen","misstrauen"] },
{ lang:"en", level:"medium", term:"trust", answers:["das vertrauen","vertrauen"] },
{ lang:"en", level:"medium", term:"doubt", answers:["der zweifel","zweifel"] },
{ lang:"en", level:"medium", term:"to convince", answers:["überzeugen"] },
{ lang:"en", level:"medium", term:"to demand", answers:["fordern","verlangen"] },
{ lang:"en", level:"medium", term:"to raise", answers:["heben","erheben","aufwerfen"] },
{ lang:"en", level:"medium", term:"to emphasize", answers:["betonen"] },
{ lang:"en", level:"medium", term:"to consider", answers:["erwägen","in betracht ziehen","berücksichtigen"] },
{ lang:"en", level:"medium", term:"to spot", answers:["ausmachen","entdecken","erkennen"] },
{ lang:"en", level:"medium", term:"to avoid", answers:["vermeiden"] },
{ lang:"en", level:"medium", term:"to achieve", answers:["erreichen","erzielen"] },
{ lang:"en", level:"medium", term:"to result in", answers:["führen zu","enden in"] },
{ lang:"en", level:"medium", term:"uni", answers:["die uni","die universität"], note:"umgangssprachlich" },
{ lang:"en", level:"medium", term:"gig", answers:["der job","der auftritt"], note:"umgangssprachlich" },
{ lang:"en", level:"medium", term:"grub", answers:["das essen"], note:"umgangssprachlich" },
{ lang:"en", level:"medium", term:"dude", answers:["der typ","der kerl"], note:"umgangssprachlich" },
{ lang:"en", level:"medium", term:"chick", answers:["die frau","das mädel"], note:"umgangssprachlich" },
{ lang:"en", level:"medium", term:"cool", answers:["toll","klasse","cool"], note:"umgangssprachlich" },
{ lang:"en", level:"medium", term:"awesome", answers:["großartig","genial"] },
{ lang:"en", level:"medium", term:"tedious", answers:["mühsam","lästig","langwierig"] },
{ lang:"en", level:"medium", term:"astonishing", answers:["erstaunlich"] },
{ lang:"en", level:"medium", term:"clumsiness", answers:["die ungeschicklichkeit","ungeschicklichkeit"] },
{ lang:"en", level:"medium", term:"chance", answers:["der zufall","zufall"] },
{ lang:"en", level:"medium", term:"fate", answers:["das schicksal","schicksal"] },
{ lang:"en", level:"medium", term:"future", answers:["die zukunft","zukunft"] },
{ lang:"en", level:"medium", term:"past", answers:["die vergangenheit","vergangenheit"] },
{ lang:"en", level:"medium", term:"memory", answers:["die erinnerung","erinnerung","das gedächtnis"] },
{ lang:"en", level:"medium", term:"promise", answers:["das versprechen","versprechen"] },
{ lang:"en", level:"medium", term:"lie", answers:["die lüge","lüge"] },
{ lang:"en", level:"medium", term:"truth", answers:["die wahrheit","wahrheit"] },
{ lang:"en", level:"medium", term:"white lie", answers:["die notlüge","notlüge"] },
{ lang:"en", level:"medium", term:"betrayal", answers:["der verrat","verrat"] },
{ lang:"en", level:"medium", term:"forgiveness", answers:["die vergebung","vergebung","die verzeihung"] },
{ lang:"en", level:"medium", term:"grudge", answers:["der groll","groll"] },
{ lang:"en", level:"medium", term:"reproach", answers:["der vorwurf","vorwurf"] },
{ lang:"en", level:"medium", term:"guilt", answers:["die schuld","schuld"] },
{ lang:"en", level:"medium", term:"remorse", answers:["die reue","reue"] },
{ lang:"en", level:"medium", term:"gossip", answers:["der klatsch","klatsch","das gerede"] },
{ lang:"en", level:"medium", term:"rumor", answers:["das gerücht","gerücht"] },
{ lang:"en", level:"medium", term:"to slander", answers:["verleumden","lästern"] },
{ lang:"en", level:"medium", term:"to mock", answers:["sich lustig machen","verspotten"] },
{ lang:"en", level:"medium", term:"to offend", answers:["kränken","beleidigen"] },
{ lang:"en", level:"medium", term:"to hurt", answers:["verletzen"] },
{ lang:"en", level:"medium", term:"to comfort", answers:["trösten"] },
{ lang:"en", level:"medium", term:"to encourage", answers:["ermutigen","ermuntern"] },
{ lang:"en", level:"medium", term:"to discourage", answers:["entmutigen"] },
{ lang:"en", level:"medium", term:"patience", answers:["die geduld","geduld"] },
{ lang:"en", level:"medium", term:"impatience", answers:["die ungeduld","ungeduld"] },
{ lang:"en", level:"medium", term:"tenacity", answers:["die hartnäckigkeit","hartnäckigkeit","die beharrlichkeit"] },
{ lang:"en", level:"medium", term:"illness", answers:["die krankheit","krankheit"] },
{ lang:"en", level:"medium", term:"remedy", answers:["das heilmittel","heilmittel","das mittel"] },
{ lang:"en", level:"medium", term:"medication", answers:["das medikament","medikament"] },
{ lang:"en", level:"medium", term:"wound", answers:["die wunde","wunde"] },
{ lang:"en", level:"medium", term:"bandage", answers:["der verband","verband","das pflaster"] },
{ lang:"en", level:"medium", term:"scar", answers:["die narbe","narbe"] },
{ lang:"en", level:"medium", term:"pregnancy", answers:["die schwangerschaft","schwangerschaft"] },
{ lang:"en", level:"medium", term:"childbirth", answers:["die geburt","geburt","die entbindung"] },
{ lang:"en", level:"medium", term:"grief", answers:["die trauer","trauer"] },
{ lang:"en", level:"medium", term:"funeral", answers:["die beerdigung","beerdigung"] },
{ lang:"en", level:"medium", term:"will", answers:["das testament","testament"], note:"letzter Wille" },
{ lang:"en", level:"medium", term:"inheritance", answers:["das erbe","erbe"] },
{ lang:"en", level:"medium", term:"neighborhood", answers:["die nachbarschaft","nachbarschaft"] },
{ lang:"en", level:"medium", term:"building", answers:["das gebäude","gebäude"] },
{ lang:"en", level:"medium", term:"sidewalk", answers:["der gehweg","gehweg","der bürgersteig"] },
{ lang:"en", level:"medium", term:"traffic light", answers:["die ampel","ampel"] },
{ lang:"en", level:"medium", term:"crosswalk", answers:["der zebrastreifen","zebrastreifen","der fußgängerüberweg"] },
{ lang:"en", level:"medium", term:"traffic jam", answers:["der stau","stau"] },
{ lang:"en", level:"medium", term:"toll", answers:["die maut","maut"] },
{ lang:"en", level:"medium", term:"intersection", answers:["die kreuzung","kreuzung"] },
{ lang:"en", level:"medium", term:"roundabout", answers:["der kreisverkehr","kreisverkehr"] },
{ lang:"en", level:"medium", term:"driver's license", answers:["der führerschein","führerschein"] },
{ lang:"en", level:"medium", term:"gasoline", answers:["das benzin","benzin"] },
{ lang:"en", level:"medium", term:"tire", answers:["der reifen","reifen"] },
{ lang:"en", level:"medium", term:"trunk", answers:["der kofferraum","kofferraum"], note:"Auto" },
{ lang:"en", level:"medium", term:"breakdown", answers:["die panne","panne"], note:"Fahrzeugpanne" },
{ lang:"en", level:"medium", term:"entrepreneur", answers:["der unternehmer","unternehmer"] },
{ lang:"en", level:"medium", term:"competition", answers:["die konkurrenz","konkurrenz","der wettbewerb"] },
{ lang:"en", level:"medium", term:"bankruptcy", answers:["der bankrott","bankrott","die insolvenz"] },
{ lang:"en", level:"medium", term:"turnover", answers:["der umsatz","umsatz"] },
{ lang:"en", level:"medium", term:"profit", answers:["der gewinn","gewinn"] },
{ lang:"en", level:"medium", term:"loss", answers:["der verlust","verlust"] },
{ lang:"en", level:"medium", term:"tax", answers:["die steuer","steuer"] },
{ lang:"en", level:"medium", term:"salary", answers:["das gehalt","gehalt","der lohn"] },
{ lang:"en", level:"medium", term:"pension", answers:["die rente","rente"] },
{ lang:"en", level:"medium", term:"unemployment", answers:["die arbeitslosigkeit","arbeitslosigkeit"] },
{ lang:"en", level:"medium", term:"hiring", answers:["die einstellung","einstellung"] },
{ lang:"en", level:"medium", term:"layoff", answers:["die entlassung","entlassung","die kündigung"] },
{ lang:"en", level:"medium", term:"resignation", answers:["die kündigung","kündigung","der rücktritt"] },
{ lang:"en", level:"medium", term:"colleague", answers:["der kollege","kollege"] },
{ lang:"en", level:"medium", term:"supervisor", answers:["der vorgesetzte","vorgesetzte"] },
{ lang:"en", level:"medium", term:"meeting", answers:["die besprechung","besprechung","das meeting"] },

/* ═══════════════════ ENGLISCH — HARD ═══════════════════ */
{ lang:"en", level:"hard", term:"draft", answers:["der entwurf","entwurf","die skizze"] },
{ lang:"en", level:"hard", term:"obstacle", answers:["das hindernis","hindernis"] },
{ lang:"en", level:"hard", term:"relentlessness", answers:["die unerbittlichkeit","unerbittlichkeit","die verbissenheit"] },
{ lang:"en", level:"hard", term:"weariness", answers:["die müdigkeit","müdigkeit","der überdruss"] },
{ lang:"en", level:"hard", term:"lucidity", answers:["die klarsicht","klarsicht","die klarheit"] },
{ lang:"en", level:"hard", term:"stubbornness", answers:["die sturheit","sturheit","der starrsinn"] },
{ lang:"en", level:"hard", term:"nonchalance", answers:["die lässigkeit","lässigkeit","die gelassenheit"] },
{ lang:"en", level:"hard", term:"carefreeness", answers:["die sorglosigkeit","sorglosigkeit"] },
{ lang:"en", level:"hard", term:"clairvoyance", answers:["die hellsichtigkeit","hellsichtigkeit"] },
{ lang:"en", level:"hard", term:"benevolence", answers:["das wohlwollen","wohlwollen"] },
{ lang:"en", level:"hard", term:"malevolence", answers:["die böswilligkeit","böswilligkeit"] },
{ lang:"en", level:"hard", term:"obstinacy", answers:["die hartnäckigkeit","hartnäckigkeit","die sturheit"] },
{ lang:"en", level:"hard", term:"circumspection", answers:["die umsicht","umsicht","die vorsicht"] },
{ lang:"en", level:"hard", term:"infatuation", answers:["die schwärmerei","schwärmerei","die begeisterung"] },
{ lang:"en", level:"hard", term:"disarray", answers:["die verwirrung","verwirrung","die ratlosigkeit"] },
{ lang:"en", level:"hard", term:"acrimony", answers:["die verbitterung","verbitterung","die bissigkeit"] },
{ lang:"en", level:"hard", term:"discord", answers:["die zwietracht","zwietracht","die uneinigkeit"] },
{ lang:"en", level:"hard", term:"litigation", answers:["der rechtsstreit","rechtsstreit"] },
{ lang:"en", level:"hard", term:"mishap", answers:["das missgeschick","missgeschick"] },
{ lang:"en", level:"hard", term:"subterfuge", answers:["die ausflucht","ausflucht","die list"] },
{ lang:"en", level:"hard", term:"stratagem", answers:["die kriegslist","kriegslist","der trick","die taktik"] },
{ lang:"en", level:"hard", term:"cunning", answers:["die list","list","die schläue"] },
{ lang:"en", level:"hard", term:"deceit", answers:["die täuschung","täuschung","der betrug"] },
{ lang:"en", level:"hard", term:"fraud", answers:["der betrug","betrug"] },
{ lang:"en", level:"hard", term:"embezzlement", answers:["die veruntreuung","veruntreuung","die unterschlagung"] },
{ lang:"en", level:"hard", term:"damage (legal)", answers:["der schaden","schaden"] },
{ lang:"en", level:"hard", term:"legal remedy", answers:["der rechtsbehelf","rechtsbehelf","die berufung"] },
{ lang:"en", level:"hard", term:"dispute", answers:["der streitfall","streitfall","der rechtsstreit"] },
{ lang:"en", level:"hard", term:"formal notice", answers:["die mahnung","mahnung","die abmahnung"] },
{ lang:"en", level:"hard", term:"notice period", answers:["die kündigungsfrist","kündigungsfrist"] },
{ lang:"en", level:"hard", term:"deposit (legal)", answers:["die kaution","kaution"] },
{ lang:"en", level:"hard", term:"endorsement", answers:["die zustimmung","zustimmung","die bürgschaft"] },
{ lang:"en", level:"hard", term:"surety", answers:["die bürgschaft","bürgschaft"] },
{ lang:"en", level:"hard", term:"clause", answers:["die klausel","klausel"] },
{ lang:"en", level:"hard", term:"amendment", answers:["der nachtrag","nachtrag","die änderung"] },
{ lang:"en", level:"hard", term:"termination", answers:["die kündigung","kündigung"] },
{ lang:"en", level:"hard", term:"renewal", answers:["die verlängerung","verlängerung"] },
{ lang:"en", level:"hard", term:"payment schedule", answers:["der zahlungsplan","zahlungsplan"] },
{ lang:"en", level:"hard", term:"tax dispute", answers:["der steuerstreit","steuerstreit"] },
{ lang:"en", level:"hard", term:"taxation", answers:["die besteuerung","besteuerung","das steuerwesen"] },
{ lang:"en", level:"hard", term:"exemption", answers:["die befreiung","befreiung"] },
{ lang:"en", level:"hard", term:"deduction", answers:["der abzug","abzug"] },
{ lang:"en", level:"hard", term:"overbidding", answers:["das überbieten","überbieten"] },
{ lang:"en", level:"hard", term:"economic climate", answers:["die konjunktur","konjunktur"] },
{ lang:"en", level:"hard", term:"upswing", answers:["der aufschwung","aufschwung"] },
{ lang:"en", level:"hard", term:"downturn", answers:["der rückgang","rückgang"] },
{ lang:"en", level:"hard", term:"recession", answers:["die rezession","rezession"] },
{ lang:"en", level:"hard", term:"stimulus", answers:["die konjunkturbelebung","konjunkturbelebung","das ankurbeln"] },
{ lang:"en", level:"hard", term:"indebtedness", answers:["die verschuldung","verschuldung"] },
{ lang:"en", level:"hard", term:"debt reduction", answers:["der schuldenabbau","schuldenabbau"] },
{ lang:"en", level:"hard", term:"liquidity", answers:["die liquidität","liquidität"] },
{ lang:"en", level:"hard", term:"cap (limit)", answers:["die deckelung","deckelung","die obergrenze"] },
{ lang:"en", level:"hard", term:"relaxation (of rules)", answers:["die lockerung","lockerung"] },
{ lang:"en", level:"hard", term:"tightening", answers:["die verschärfung","verschärfung"] },
{ lang:"en", level:"hard", term:"stranglehold", answers:["die kontrolle","kontrolle","die vorherrschaft"] },
{ lang:"en", level:"hard", term:"influence", answers:["der einfluss","einfluss"] },
{ lang:"en", level:"hard", term:"political current", answers:["die strömung","strömung"] },
{ lang:"en", level:"hard", term:"divide", answers:["die spaltung","spaltung","der graben"] },
{ lang:"en", level:"hard", term:"split (organizational)", answers:["die abspaltung","abspaltung"] },
{ lang:"en", level:"hard", term:"compromise", answers:["der kompromiss","kompromiss"] },
{ lang:"en", level:"hard", term:"consensus", answers:["der konsens","konsens"] },
{ lang:"en", level:"hard", term:"agreement", answers:["die einigung","einigung","das einvernehmen"] },
{ lang:"en", level:"hard", term:"repudiation", answers:["die zurückweisung","zurückweisung"] },
{ lang:"en", level:"hard", term:"denial", answers:["das dementi","dementi","die leugnung"] },
{ lang:"en", level:"hard", term:"confession", answers:["das geständnis","geständnis"] },
{ lang:"en", level:"hard", term:"disagreement", answers:["die uneinigkeit","uneinigkeit"] },
{ lang:"en", level:"hard", term:"be that as it may", answers:["wie dem auch sei"] },
{ lang:"en", level:"hard", term:"notwithstanding", answers:["ungeachtet","trotzdem"], note:"gehobene Sprache" },
{ lang:"en", level:"hard", term:"henceforth", answers:["von nun an","fortan"], note:"gehobene Sprache" },
{ lang:"en", level:"hard", term:"nevertheless", answers:["dennoch","trotzdem"] },
{ lang:"en", level:"hard", term:"nonetheless", answers:["nichtsdestotrotz","trotzdem"] },
{ lang:"en", level:"hard", term:"furthermore", answers:["außerdem","des weiteren"] },
{ lang:"en", level:"hard", term:"what is more", answers:["obendrein","zudem"] },
{ lang:"en", level:"hard", term:"that being said", answers:["dies gesagt","davon abgesehen","dennoch"] },
{ lang:"en", level:"hard", term:"it must be noted that", answers:["man muss feststellen"] },
{ lang:"en", level:"hard", term:"far from it", answers:["bei weitem nicht","keineswegs"] },
{ lang:"en", level:"hard", term:"interwoven mesh", answers:["das geflecht","geflecht","das gewirr"] },
{ lang:"en", level:"hard", term:"tangle", answers:["das gewirr","gewirr","das knäuel"] },
{ lang:"en", level:"hard", term:"wasteland", answers:["die brachfläche","brachfläche","das brachland"] },
{ lang:"en", level:"hard", term:"topsoil", answers:["der nährboden","nährboden","die ackerkrume"] },
{ lang:"en", level:"hard", term:"fallow land", answers:["die brache","brache"] },
{ lang:"en", level:"hard", term:"furrow", answers:["die furche","furche"] },
{ lang:"en", level:"hard", term:"harvest", answers:["die ernte","ernte"] },
{ lang:"en", level:"hard", term:"rural exodus", answers:["die landflucht","landflucht"] },
{ lang:"en", level:"hard", term:"urban sprawl", answers:["die zersiedelung","zersiedelung"] },
{ lang:"en", level:"hard", term:"brownfield", answers:["die industriebrache","industriebrache"] },
{ lang:"en", level:"hard", term:"deposit (resource)", answers:["die lagerstätte","lagerstätte","das vorkommen"] },
{ lang:"en", level:"hard", term:"scarcity", answers:["die knappheit","knappheit","der mangel"] },
{ lang:"en", level:"hard", term:"oversupply", answers:["das überangebot","überangebot","der überfluss"] },
{ lang:"en", level:"hard", term:"waste (of resources)", answers:["die verschwendung","verschwendung"] },
{ lang:"en", level:"hard", term:"frugality", answers:["die sparsamkeit","sparsamkeit"] },
{ lang:"en", level:"hard", term:"prodigality", answers:["die verschwendungssucht","verschwendungssucht"] },
{ lang:"en", level:"hard", term:"greed", answers:["die gier","gier","die habgier"] },
{ lang:"en", level:"hard", term:"covetousness", answers:["die begierde","begierde","das verlangen"] },
{ lang:"en", level:"hard", term:"profit-seeking", answers:["die profitgier","profitgier","die gewinnsucht"] },
{ lang:"en", level:"hard", term:"aspiration", answers:["das streben","streben","die sehnsucht"] },
{ lang:"en", level:"hard", term:"renunciation", answers:["der verzicht","verzicht"] },
{ lang:"en", level:"hard", term:"self-abnegation", answers:["die selbstaufgabe","selbstaufgabe"] },
{ lang:"en", level:"hard", term:"devotion", answers:["die hingabe","hingabe"] },
{ lang:"en", level:"hard", term:"altruism", answers:["der altruismus","altruismus","die selbstlosigkeit"] },
{ lang:"en", level:"hard", term:"selfishness", answers:["der egoismus","egoismus"] },
{ lang:"en", level:"hard", term:"vanity", answers:["die eitelkeit","eitelkeit"] },
{ lang:"en", level:"hard", term:"arrogance", answers:["die arroganz","arroganz"] },
{ lang:"en", level:"hard", term:"humility", answers:["die demut","demut","die bescheidenheit"] },
{ lang:"en", level:"hard", term:"modesty", answers:["die bescheidenheit","bescheidenheit"] },
{ lang:"en", level:"hard", term:"boastfulness", answers:["die angeberei","angeberei","die prahlerei"] },
{ lang:"en", level:"hard", term:"presumption", answers:["die anmaßung","anmaßung","die vermutung"] },
{ lang:"en", level:"hard", term:"cheek (nerve)", answers:["die frechheit","frechheit","die dreistigkeit"], note:"umgangssprachlich" },
{ lang:"en", level:"hard", term:"effrontery", answers:["die unverschämtheit","unverschämtheit"] },
{ lang:"en", level:"hard", term:"modesty (shame)", answers:["die scham","scham","die schamhaftigkeit"] },
{ lang:"en", level:"hard", term:"shamelessness", answers:["die schamlosigkeit","schamlosigkeit"] },
{ lang:"en", level:"hard", term:"decency", answers:["der anstand","anstand"] },
{ lang:"en", level:"hard", term:"indecency", answers:["die unanständigkeit","unanständigkeit"] },
{ lang:"en", level:"hard", term:"insolence", answers:["die unverschämtheit","unverschämtheit","die frechheit"] },
{ lang:"en", level:"hard", term:"disobedience", answers:["der ungehorsam","ungehorsam"] },
{ lang:"en", level:"hard", term:"obstruction of justice", answers:["die justizbehinderung","justizbehinderung"] },
{ lang:"en", level:"hard", term:"outrage (offense)", answers:["die beleidigung","beleidigung","die empörung"] },
{ lang:"en", level:"hard", term:"abuse (mistreatment)", answers:["die misshandlung","misshandlung"] },
{ lang:"en", level:"hard", term:"procrastination", answers:["das aufschieben","aufschieben","die prokrastination"] },
{ lang:"en", level:"hard", term:"prevarication", answers:["das zaudern","zaudern","die ausflucht"] },
{ lang:"en", level:"hard", term:"haste", answers:["die eile","eile","die überstürzung"] },
{ lang:"en", level:"hard", term:"eagerness", answers:["der eifer","eifer"] },
{ lang:"en", level:"hard", term:"diligence", answers:["die sorgfalt","sorgfalt","der fleiß"] },
{ lang:"en", level:"hard", term:"negligence", answers:["die nachlässigkeit","nachlässigkeit"] },
{ lang:"en", level:"hard", term:"zeal", answers:["der eifer","eifer"] },
{ lang:"en", level:"hard", term:"fervor", answers:["die inbrunst","inbrunst","der eifer"] },
{ lang:"en", level:"hard", term:"piety", answers:["die frömmigkeit","frömmigkeit"] },
{ lang:"en", level:"hard", term:"impiety", answers:["die gottlosigkeit","gottlosigkeit"] },

];