/* ═══════════════════════════════════════════════════════
   CARS.JS  –  Auto-Quiz Datenbank
   Marken: VW, Tesla, Audi, BMW, Porsche, Ferrari,
           Lamborghini, Škoda, Opel, Mini, Bentley, Mercedes
   Format: { brand, model, year, cat, img }
   img = relativer Bildpfad  →  cars/<dateiname>.jpg
═══════════════════════════════════════════════════════ */

const CARS = [

  /* ── VOLKSWAGEN ────────────────────────────────────── */
  { brand: "Volkswagen", model: "Käfer 1300",              year: "1965–1978", cat: "Ikone",        img: "cars/vw_kaefer.jpg" },
  { brand: "Volkswagen", model: "Karmann-Ghia",            year: "1955–1974", cat: "Coupé",        img: "cars/vw_karmann_ghia.jpg" },
  { brand: "Volkswagen", model: "Scirocco II",             year: "1981–1992", cat: "Coupé",        img: "cars/vw_scirocco2.jpg" },
  { brand: "Volkswagen", model: "Corrado",                 year: "1988–1995", cat: "Coupé",        img: "cars/vw_corrado.jpg" },
  { brand: "Volkswagen", model: "Golf I",                  year: "1974–1983", cat: "Kompakt",      img: "cars/vw_golf1.avif" },
  { brand: "Volkswagen", model: "Golf IV",                 year: "1997–2006", cat: "Kompakt",      img: "cars/vw_golf4.jpg" },
  { brand: "Volkswagen", model: "Golf VI",                 year: "2008–2013", cat: "Kompakt",      img: "cars/vw_golf6.jpg" },
  { brand: "Volkswagen", model: "Golf VII",                year: "2012–2020", cat: "Kompakt",      img: "cars/vw_golf7.jpg" },
  { brand: "Volkswagen", model: "Golf VIII",               year: "2019–",     cat: "Kompakt",      img: "cars/vw_golf8.jpg" },
  { brand: "Volkswagen", model: "Golf R Mk7",              year: "2013–2020", cat: "Hot Hatch",    img: "cars/vw_golf_r_mk7.webp" },
  { brand: "Volkswagen", model: "Golf R Mk8",              year: "2021–",     cat: "Hot Hatch",    img: "cars/vw_golf_r_mk8.jpg" },
  { brand: "Volkswagen", model: "Polo VI (AW)",            year: "2017–",     cat: "Kleinwagen",   img: "cars/vw_polo6.jpg" },
  { brand: "Volkswagen", model: "Passat B7",               year: "2010–2015", cat: "Mittelklasse", img: "cars/vw_passat_b7.jpg" },
  { brand: "Volkswagen", model: "Passat B8",               year: "2014–",     cat: "Mittelklasse", img: "cars/vw_passat_b8.jpeg" },
  { brand: "Volkswagen", model: "Arteon",                  year: "2017–",     cat: "Fastback",     img: "cars/vw_arteon.jpg" },
  { brand: "Volkswagen", model: "Phaeton",                 year: "2002–2016", cat: "Luxus",        img: "cars/vw_phaeton.jpg" },
  { brand: "Volkswagen", model: "Touareg I",               year: "2002–2010", cat: "SUV",          img: "cars/vw_touareg1.jpg" },
  { brand: "Volkswagen", model: "Touareg II",              year: "2010–2018", cat: "SUV",          img: "cars/vw_touareg2.png" },
  { brand: "Volkswagen", model: "Touareg III",             year: "2018–",     cat: "SUV",          img: "cars/vw_touareg3.webp" },
  { brand: "Volkswagen", model: "Tiguan II",               year: "2016–",     cat: "SUV",          img: "cars/vw_tiguan2.jpg" },
  { brand: "Volkswagen", model: "Touareg R",               year: "2021–",     cat: "Plug-in-Hybrid-SUV", img: "cars/vw_touareg_r.jpg" },
  { brand: "Volkswagen", model: "ID.3",                    year: "2019–",     cat: "Elektro",      img: "cars/vw_id3.png" },
  { brand: "Volkswagen", model: "ID.4",                    year: "2020–",     cat: "Elektro-SUV",  img: "cars/vw_id4.webp" },
  { brand: "Volkswagen", model: "ID.5",                    year: "2021–",     cat: "Elektro-SUV",  img: "cars/vw_id5.jpg" },
  { brand: "Volkswagen", model: "ID.7",                    year: "2023–",     cat: "Elektro",      img: "cars/vw_id7.jpg" },
  { brand: "Volkswagen", model: "ID. Buzz",                year: "2022–",     cat: "Elektro-Van",  img: "cars/vw_id_buzz.jpg" },
  { brand: "Volkswagen", model: "Up! GTI",                 year: "2017–2023", cat: "Hot Hatch",    img: "cars/vw_up_gti.jpg" },
  { brand: "Volkswagen", model: "T-Roc R",                 year: "2019–",     cat: "Hot Hatch-SUV",img: "cars/vw_troc_r.jpg" },
  { brand: "Volkswagen", model: "Transporter T7",          year: "2021–",     cat: "Van",          img: "cars/vw_t7.webp" },

  /* ── TESLA ──────────────────────────────────────────── */
  { brand: "Tesla", model: "Roadster (1. Gen)",            year: "2008–2012", cat: "Roadster",     img: "cars/tesla_roadster1.jpg" },
  { brand: "Tesla", model: "Model S",                      year: "2012–",     cat: "Elektro",      img: "cars/tesla_model_s.jpg" },
  { brand: "Tesla", model: "Model S Plaid",                year: "2021–",     cat: "Elektro",      img: "cars/tesla_model_s_plaid.avif" },
  { brand: "Tesla", model: "Model S Plaid+",               year: "2021–",     cat: "Elektro",      img: "cars/tesla_model_s_plaidplus.jpg" },
  { brand: "Tesla", model: "Model X",                      year: "2015–",     cat: "Elektro-SUV",  img: "cars/tesla_model_x.jpg" },
  { brand: "Tesla", model: "Model 3",                      year: "2017–",     cat: "Elektro",      img: "cars/tesla_model3.jpg" },
  { brand: "Tesla", model: "Model 3 Performance",          year: "2024–",     cat: "Elektro",      img: "cars/tesla_model3_perf.jpg" },
  { brand: "Tesla", model: "Model Y",                      year: "2020–",     cat: "Elektro-SUV",  img: "cars/tesla_model_y.jpg" },
  { brand: "Tesla", model: "Cybertruck",                   year: "2023–",     cat: "Elektro-Pick-up", img: "cars/tesla_cybertruck.jpg" },
  { brand: "Tesla", model: "Roadster (2. Gen)",            year: "2025–",     cat: "Hypercar",     img: "cars/tesla_roadster2.jpg" },

  /* ── AUDI ────────────────────────────────────────────── */
  { brand: "Audi", model: "Quattro Ur-quattro",            year: "1980–1991", cat: "Ikone",        img: "cars/audi_quattro.jpg" },
  { brand: "Audi", model: "80 B4",                         year: "1991–1996", cat: "Mittelklasse", img: "cars/audi_80_b4.jpg" },
  { brand: "Audi", model: "RS2 Avant",                     year: "1994–1995", cat: "Sportler",     img: "cars/audi_rs2.jpg" },
  { brand: "Audi", model: "A3 (8P)",                       year: "2003–2012", cat: "Kompakt",      img: "cars/audi_a3_8p.jpeg" },
  { brand: "Audi", model: "A3 Sportback (8V)",             year: "2012–2020", cat: "Kompakt",      img: "cars/audi_a3_8v.avif" },
  { brand: "Audi", model: "A3 (8Y)",                       year: "2020–",     cat: "Kompakt",      img: "cars/audi_a3_8y.jpg" },
  { brand: "Audi", model: "S3 (8Y)",                       year: "2020–",     cat: "Sportler",     img: "cars/audi_s3_8y.webp" },
  { brand: "Audi", model: "RS3 (8Y)",                      year: "2021–",     cat: "Sportler",     img: "cars/audi_rs3_8y.webp" },
  { brand: "Audi", model: "A4 B8",                         year: "2007–2015", cat: "Mittelklasse", img: "cars/audi_a4_b8.jpg" },
  { brand: "Audi", model: "A4 B9",                         year: "2015–",     cat: "Mittelklasse", img: "cars/audi_a4_b9.jpg" },
  { brand: "Audi", model: "RS4 B9 Avant",                  year: "2017–",     cat: "Sportler",     img: "cars/audi_rs4_b9.jpg" },
  { brand: "Audi", model: "RS4 B5",                        year: "2000–2001", cat: "Sportler",     img: "cars/audi_rs4_b5.avif" },
  { brand: "Audi", model: "A5 Coupé (F5)",                 year: "2016–",     cat: "Coupé",        img: "cars/audi_a5_f5.jpeg" },
  { brand: "Audi", model: "RS5 (F5)",                      year: "2017–",     cat: "Sportler",     img: "cars/audi_rs5_f5.avif" },
  { brand: "Audi", model: "A6 C8",                         year: "2018–",     cat: "Oberklasse",   img: "cars/audi_a6_c8.png" },
  { brand: "Audi", model: "RS6 C8 Avant",                  year: "2019–",     cat: "Sportler",     img: "cars/audi_rs6_c8.jpg" },
  { brand: "Audi", model: "RS7 (C8)",                      year: "2019–",     cat: "Sportler",     img: "cars/audi_rs7_c8.jpg" },
  { brand: "Audi", model: "A7 Sportback (C8)",             year: "2018–",     cat: "Coupé",        img: "cars/audi_a7_c8.jpg" },
  { brand: "Audi", model: "A8 D5",                         year: "2017–",     cat: "Luxus",        img: "cars/audi_a8_d5.jpg" },
  { brand: "Audi", model: "A8 L W12 (D5)",                 year: "2018–",     cat: "Luxus",        img: "cars/audi_a8_w12.avif" },
  { brand: "Audi", model: "TT RS (8S)",                    year: "2016–2023", cat: "Sportler",     img: "cars/audi_ttrs_8s.jpg" },
  { brand: "Audi", model: "R8 V10 Performance (Mk2)",      year: "2019–2023", cat: "Supercar",     img: "cars/audi_r8_mk2.webp" },
  { brand: "Audi", model: "R8 GT (Mk2)",                   year: "2023–",     cat: "Supercar",     img: "cars/audi_r8_gt.jpeg" },
  { brand: "Audi", model: "e-tron GT",                     year: "2021–",     cat: "Elektro",      img: "cars/audi_etron_gt.webp" },
  { brand: "Audi", model: "RS e-tron GT",                  year: "2021–",     cat: "Elektro",      img: "cars/audi_rs_etron_gt.webp" },
  { brand: "Audi", model: "Q8 (4M)",                       year: "2018–",     cat: "SUV",          img: "cars/audi_q8.jpg" },
  { brand: "Audi", model: "RS Q8",                         year: "2019–",     cat: "Sportler-SUV", img: "cars/audi_rsq8.webp" },
  { brand: "Audi", model: "Q8 e-tron",                     year: "2022–",     cat: "Elektro-SUV",  img: "cars/audi_q8_etron.jpeg" },
  { brand: "Audi", model: "SQ7 (4M)",                      year: "2016–",     cat: "Sportler-SUV", img: "cars/audi_sq7.jpg" },
  { brand: "Audi", model: "SQ8 (4M)",                      year: "2019–",     cat: "Sportler-SUV", img: "cars/audi_sq8.webp" },

  /* ── BMW ──────────────────────────────────────────────── */
  { brand: "BMW", model: "2002 Turbo",                     year: "1973–1974", cat: "Ikone",        img: "cars/bmw_2002_turbo.avif" },
  { brand: "BMW", model: "M1",                             year: "1978–1981", cat: "Supercar",     img: "cars/bmw_m1.jpg" },
  { brand: "BMW", model: "3er E30",                        year: "1982–1994", cat: "Mittelklasse", img: "cars/bmw_e30.jpg" },
  { brand: "BMW", model: "3er E46",                        year: "1998–2006", cat: "Mittelklasse", img: "cars/bmw_e46.jpg" },
  { brand: "BMW", model: "3er E90",                        year: "2005–2011", cat: "Mittelklasse", img: "cars/bmw_e90.jpg" },
  { brand: "BMW", model: "3er G20",                        year: "2018–",     cat: "Mittelklasse", img: "cars/bmw_g20.jpg" },
  { brand: "BMW", model: "4er Gran Coupé (G26)",           year: "2021–",     cat: "Coupé",        img: "cars/bmw_g26.jpg" },
  { brand: "BMW", model: "5er E39",                        year: "1995–2003", cat: "Oberklasse",   img: "cars/bmw_e39.jpg" },
  { brand: "BMW", model: "5er G30",                        year: "2016–",     cat: "Oberklasse",   img: "cars/bmw_g30.avif" },
  { brand: "BMW", model: "5er G60",                        year: "2023–",     cat: "Oberklasse",   img: "cars/bmw_g60.jpg" },
  { brand: "BMW", model: "6er GT (G32)",                   year: "2017–",     cat: "Kombi",        img: "cars/bmw_g32.jpg" },
  { brand: "BMW", model: "7er G11",                        year: "2015–2022", cat: "Luxus",        img: "cars/bmw_g11.jpg" },
  { brand: "BMW", model: "7er G70",                        year: "2022–",     cat: "Luxus",        img: "cars/bmw_g70.jpg" },
  { brand: "BMW", model: "i7 xDrive60 (G70)",              year: "2022–",     cat: "Elektro",      img: "cars/bmw_i7.jpeg" },
  { brand: "BMW", model: "8er Gran Coupé (G16)",           year: "2019–",     cat: "Coupé",        img: "cars/bmw_g16.jpg" },
  { brand: "BMW", model: "8er Cabriolet (G14)",            year: "2018–",     cat: "Cabrio",       img: "cars/bmw_g14.jpg" },
  { brand: "BMW", model: "Z4 G29",                         year: "2018–",     cat: "Roadster",     img: "cars/bmw_g29.avif" },
  { brand: "BMW", model: "Z4 M40i (G29)",                  year: "2019–",     cat: "Roadster",     img: "cars/bmw_z4_m40i.webp" },
  { brand: "BMW", model: "M2 (G87)",                       year: "2022–",     cat: "Sportler",     img: "cars/bmw_m2_g87.jpg" },
  { brand: "BMW", model: "M3 E30",                         year: "1986–1991", cat: "Sportler",     img: "cars/bmw_m3_e30.jpg" },
  { brand: "BMW", model: "M3 E46",                         year: "2000–2006", cat: "Sportler",     img: "cars/bmw_m3_e46.avif" },
  { brand: "BMW", model: "M3 (G80)",                       year: "2020–",     cat: "Sportler",     img: "cars/bmw_m3_g80.jpg" },
  { brand: "BMW", model: "M3 CS (G80)",                    year: "2023–",     cat: "Sportler",     img: "cars/bmw_m3_cs.jpg" },
  { brand: "BMW", model: "M4 Competition (G82)",           year: "2020–",     cat: "Sportler",     img: "cars/bmw_m4_g82.jpg" },
  { brand: "BMW", model: "M4 CSL (G82)",                   year: "2022–",     cat: "Sportler",     img: "cars/bmw_m4_csl.jpg" },
  { brand: "BMW", model: "M5 E39",                         year: "1998–2003", cat: "Sportler",     img: "cars/bmw_m5_e39.avif" },
  { brand: "BMW", model: "M5 F90",                         year: "2017–",     cat: "Sportler",     img: "cars/bmw_m5_f90.jpg" },
  { brand: "BMW", model: "M5 G90",                         year: "2024–",     cat: "Sportler",     img: "cars/bmw_m5_g90.jpg" },
  { brand: "BMW", model: "M8 Competition Coupé (F92)",     year: "2019–",     cat: "Sportler",     img: "cars/bmw_m8_f92.jpg" },
  { brand: "BMW", model: "XM",                             year: "2022–",     cat: "Sportler-SUV", img: "cars/bmw_xm.jpg" },
  { brand: "BMW", model: "XM Label Red",                   year: "2023–",     cat: "Sportler-SUV", img: "cars/bmw_xm_red.webp" },
  { brand: "BMW", model: "X5 M (F95)",                     year: "2019–",     cat: "Sportler-SUV", img: "cars/bmw_x5m_f95.jpg" },
  { brand: "BMW", model: "X6 M (F96)",                     year: "2019–",     cat: "Sportler-SUV", img: "cars/bmw_x6m_f96.webp" },
  { brand: "BMW", model: "i3",                             year: "2013–2022", cat: "Elektro",      img: "cars/bmw_i3.jpg" },
  { brand: "BMW", model: "i4 M50 (G26)",                   year: "2021–",     cat: "Elektro",      img: "cars/bmw_i4_m50.webp" },
  { brand: "BMW", model: "iX M60",                         year: "2021–",     cat: "Elektro-SUV",  img: "cars/bmw_ix_m60.webp" },
  { brand: "BMW", model: "i8",                             year: "2014–2020", cat: "Sportwagen",   img: "cars/bmw_i8.jpg" },

  /* ── PORSCHE ──────────────────────────────────────────── */
  { brand: "Porsche", model: "356",                        year: "1948–1965", cat: "Ikone",        img: "cars/porsche_356.webp" },
  { brand: "Porsche", model: "911 G-Modell",               year: "1973–1989", cat: "Ikone",        img: "cars/porsche_911_g.jpg" },
  { brand: "Porsche", model: "911 Turbo (930)",            year: "1975–1989", cat: "Ikone",        img: "cars/porsche_930.webp" },
  { brand: "Porsche", model: "911 964 Carrera RS",         year: "1991–1992", cat: "Sportler",     img: "cars/porsche_964_rs.jpg" },
  { brand: "Porsche", model: "911 993",                    year: "1993–1998", cat: "Sportwagen",   img: "cars/porsche_993.webp" },
  { brand: "Porsche", model: "911 996 GT3",                year: "1999–2005", cat: "Sportler",     img: "cars/porsche_996_gt3.webp" },
  { brand: "Porsche", model: "911 997 GT3 RS",             year: "2006–2012", cat: "Sportler",     img: "cars/porsche_997_gt3rs.webp" },
  { brand: "Porsche", model: "911 991",                    year: "2011–2019", cat: "Sportwagen",   img: "cars/porsche_991.jpg" },
  { brand: "Porsche", model: "911 991 GT3",                year: "2013–2017", cat: "Sportler",     img: "cars/porsche_991_gt3.jpg" },
  { brand: "Porsche", model: "911 991 GT3 RS",             year: "2015–2019", cat: "Sportler",     img: "cars/porsche_991_gt3rs.jpg" },
  { brand: "Porsche", model: "911 991 R",                  year: "2016–2017", cat: "Sportler",     img: "cars/porsche_991_r.jpg" },
  { brand: "Porsche", model: "911 Turbo S (991.2)",        year: "2016–2019", cat: "Supercar",     img: "cars/porsche_991_turbos.webp" },
  { brand: "Porsche", model: "911 992",                    year: "2019–",     cat: "Sportwagen",   img: "cars/porsche_992.jpg" },
  { brand: "Porsche", model: "911 992 GT3",                year: "2021–",     cat: "Sportler",     img: "cars/porsche_992_gt3.webp" },
  { brand: "Porsche", model: "911 992 GT3 RS",             year: "2022–",     cat: "Sportler",     img: "cars/porsche_992_gt3rs.jpg" },
  { brand: "Porsche", model: "911 Turbo S (992)",          year: "2020–",     cat: "Supercar",     img: "cars/porsche_992_turbos.jpg" },
  { brand: "Porsche", model: "911 Dakar",                  year: "2022–",     cat: "Sportwagen",   img: "cars/porsche_992_dakar.jpg" },
  { brand: "Porsche", model: "918 Spyder",                 year: "2013–2015", cat: "Hypercar",     img: "cars/porsche_918.jpg" },
  { brand: "Porsche", model: "928",                        year: "1977–1995", cat: "GT",           img: "cars/porsche_928.jpg" },
  { brand: "Porsche", model: "Boxster 718 GTS 4.0",        year: "2020–",     cat: "Roadster",     img: "cars/porsche_boxster_718_gts.webp" },
  { brand: "Porsche", model: "Cayman GT4",                 year: "2019–",     cat: "Sportwagen",   img: "cars/porsche_cayman_gt4.jpg" },
  { brand: "Porsche", model: "Cayman GT4 RS",              year: "2021–",     cat: "Sportler",     img: "cars/porsche_cayman_gt4rs.jpeg" },
  { brand: "Porsche", model: "Panamera Turbo S E-Hybrid",  year: "2020–",     cat: "Hybrid-Luxus", img: "cars/porsche_panamera_turbo_s.jpg" },
  { brand: "Porsche", model: "Cayenne Turbo GT",           year: "2021–",     cat: "Sportler-SUV", img: "cars/porsche_cayenne_turbo_gt.avif" },
  { brand: "Porsche", model: "Cayenne S",                  year: "2023–",     cat: "SUV",          img: "cars/porsche_cayenne_s.webp" },
  { brand: "Porsche", model: "Taycan Turbo S",             year: "2019–",     cat: "Elektro",      img: "cars/porsche_taycan_turbos.webp" },
  { brand: "Porsche", model: "Taycan Turbo GT",            year: "2024–",     cat: "Hypercar",     img: "cars/porsche_taycan_turbo_gt.jpg" },
  { brand: "Porsche", model: "Taycan Cross Turismo",       year: "2021–",     cat: "Elektro",      img: "cars/porsche_taycan_cross.jpeg" },

  /* ── FERRARI ──────────────────────────────────────────── */
  { brand: "Ferrari", model: "250 GTO",                    year: "1962–1964", cat: "Ikone",        img: "cars/ferrari_250gto.webp" },
  { brand: "Ferrari", model: "Dino 246 GT",                year: "1969–1974", cat: "Sportwagen",   img: "cars/ferrari_dino_246.webp" },
  { brand: "Ferrari", model: "308 GTB",                    year: "1975–1985", cat: "Supercar",     img: "cars/ferrari_308gtb.avif" },
  { brand: "Ferrari", model: "Testarossa",                 year: "1984–1991", cat: "Supercar",     img: "cars/ferrari_testarossa.jpg" },
  { brand: "Ferrari", model: "F40",                        year: "1987–1992", cat: "Hypercar",     img: "cars/ferrari_f40.avif" },
  { brand: "Ferrari", model: "F50",                        year: "1995–1997", cat: "Hypercar",     img: "cars/ferrari_f50.jpeg" },
  { brand: "Ferrari", model: "360 Modena",                 year: "1999–2005", cat: "Supercar",     img: "cars/ferrari_360modena.jpg" },
  { brand: "Ferrari", model: "Enzo",                       year: "2002–2004", cat: "Hypercar",     img: "cars/ferrari_enzo.webp" },
  { brand: "Ferrari", model: "F430",                       year: "2004–2009", cat: "Supercar",     img: "cars/ferrari_f430.webp" },
  { brand: "Ferrari", model: "599 GTB Fiorano",            year: "2006–2012", cat: "GT",           img: "cars/ferrari_599.jpeg" },
  { brand: "Ferrari", model: "458 Italia",                 year: "2009–2015", cat: "Supercar",     img: "cars/ferrari_458.jpg" },
  { brand: "Ferrari", model: "458 Speciale",               year: "2013–2015", cat: "Supercar",     img: "cars/ferrari_458speciale.avif" },
  { brand: "Ferrari", model: "LaFerrari",                  year: "2013–2016", cat: "Hypercar",     img: "cars/ferrari_laferrari.webp" },
  { brand: "Ferrari", model: "LaFerrari Aperta",           year: "2016–2017", cat: "Hypercar",     img: "cars/ferrari_laferrari_aparta.jpg" },
  { brand: "Ferrari", model: "488 GTB",                    year: "2015–2020", cat: "Supercar",     img: "cars/ferrari_488gtb.jpg" },
  { brand: "Ferrari", model: "488 Pista",                  year: "2018–2020", cat: "Supercar",     img: "cars/ferrari_488pista.webp" },
  { brand: "Ferrari", model: "812 Superfast",              year: "2017–2022", cat: "GT",           img: "cars/ferrari_812superfast.jpg" },
  { brand: "Ferrari", model: "812 GTS",                    year: "2019–",     cat: "GT",           img: "cars/ferrari_812gts.avif" },
  { brand: "Ferrari", model: "812 Competizione",           year: "2021–2022", cat: "Supercar",     img: "cars/ferrari_812comp.jpg" },
  { brand: "Ferrari", model: "SF90 Stradale",              year: "2019–",     cat: "Hypercar",     img: "cars/ferrari_sf90.jpg" },
  { brand: "Ferrari", model: "SF90 Spider",                year: "2021–",     cat: "Hypercar",     img: "cars/ferrari_sf90_spider.jpg" },
  { brand: "Ferrari", model: "F8 Tributo",                 year: "2019–2023", cat: "Supercar",     img: "cars/ferrari_f8tributo.jpg" },
  { brand: "Ferrari", model: "F8 Spider",                  year: "2019–2023", cat: "Supercar",     img: "cars/ferrari_f8spider.jpg" },
  { brand: "Ferrari", model: "Roma",                       year: "2020–",     cat: "GT",           img: "cars/ferrari_roma.avif" },
  { brand: "Ferrari", model: "Portofino M",                year: "2020–",     cat: "GT",           img: "cars/ferrari_portofino_m.jpg" },
  { brand: "Ferrari", model: "296 GTB",                    year: "2021–",     cat: "Supercar",     img: "cars/ferrari_296gtb.jpeg" },
  { brand: "Ferrari", model: "296 GTS",                    year: "2022–",     cat: "Supercar",     img: "cars/ferrari_296gts.jpg" },
  { brand: "Ferrari", model: "Daytona SP3",                year: "2022–",     cat: "Hypercar",     img: "cars/ferrari_daytona_sp3.avif" },
  { brand: "Ferrari", model: "Purosangue",                 year: "2022–",     cat: "SUV",          img: "cars/ferrari_purosangue.jpg" },
  { brand: "Ferrari", model: "499P Modificata",            year: "2023–",     cat: "Hypercar",     img: "cars/ferrari_499p.jpg" },
  { brand: "Ferrari", model: "12Cilindri",                 year: "2024–",     cat: "GT",           img: "cars/ferrari_12cilindri.webp" },

  /* ── LAMBORGHINI ──────────────────────────────────────── */
  { brand: "Lamborghini", model: "Miura P400",             year: "1966–1973", cat: "Ikone",        img: "cars/lamborghini_miura.avif" },
  { brand: "Lamborghini", model: "Countach LP400",         year: "1974–1990", cat: "Ikone",        img: "cars/lamborghini_countach.webp" },
  { brand: "Lamborghini", model: "Countach LPI 800-4",     year: "2021–2022", cat: "Hypercar",     img: "cars/lamborghini_countach_lpi.webp" },
  { brand: "Lamborghini", model: "Diablo SV",              year: "1995–2001", cat: "Supercar",     img: "cars/lamborghini_diablo_sv.webp" },
  { brand: "Lamborghini", model: "Murciélago",             year: "2001–2010", cat: "Supercar",     img: "cars/lamborghini_murcielago.webp" },
  { brand: "Lamborghini", model: "Murciélago LP 670-4 SV", year: "2009–2010", cat: "Supercar",    img: "cars/lamborghini_murcielago_sv.jpg" },
  { brand: "Lamborghini", model: "Gallardo LP570-4 Superleggera", year: "2010–2013", cat: "Supercar", img: "cars/lamborghini_gallardo_sl.webp" },
  { brand: "Lamborghini", model: "Sesto Elemento",         year: "2010–2012", cat: "Hypercar",     img: "cars/lamborghini_sesto_elemento.webp" },
  { brand: "Lamborghini", model: "Aventador LP700-4",      year: "2011–2022", cat: "Supercar",     img: "cars/lamborghini_aventador.webp" },
  { brand: "Lamborghini", model: "Aventador LP750-4 SV",   year: "2015–2017", cat: "Supercar",     img: "cars/lamborghini_aventador_sv.webp" },
  { brand: "Lamborghini", model: "Aventador SVJ",          year: "2018–2022", cat: "Supercar",     img: "cars/lamborghini_aventador_svj.jpg" },
  { brand: "Lamborghini", model: "Sián FKP 37",            year: "2020–2021", cat: "Hypercar",     img: "cars/lamborghini_sian.avif" },
  { brand: "Lamborghini", model: "Huracán LP610-4",        year: "2014–2016", cat: "Supercar",     img: "cars/lamborghini_huracan.webp" },
  { brand: "Lamborghini", model: "Huracán Performante",    year: "2017–2019", cat: "Supercar",     img: "cars/lamborghini_huracan_perf.webp" },
  { brand: "Lamborghini", model: "Huracán STO",            year: "2020–",     cat: "Supercar",     img: "cars/lamborghini_huracan_sto.jpg" },
  { brand: "Lamborghini", model: "Huracán Tecnica",        year: "2022–",     cat: "Supercar",     img: "cars/lamborghini_huracan_tecnica.jpg" },
  { brand: "Lamborghini", model: "Urus",                   year: "2018–",     cat: "Sportler-SUV", img: "cars/lamborghini_urus.jpg" },
  { brand: "Lamborghini", model: "Urus Performante",       year: "2022–",     cat: "Sportler-SUV", img: "cars/lamborghini_urus_perf.webp" },
  { brand: "Lamborghini", model: "Revuelto",               year: "2023–",     cat: "Hypercar",     img: "cars/lamborghini_revuelto.jpg" },
  { brand: "Lamborghini", model: "Urus SE",                year: "2024–",     cat: "Hybrid-SUV",   img: "cars/lamborghini_urus_se.webp" },

  /* ── ŠKODA ────────────────────────────────────────────── */
  { brand: "Škoda", model: "110 R Coupé",                  year: "1970–1980", cat: "Coupé",        img: "cars/skoda_110r.jpg" },
  { brand: "Škoda", model: "Octavia Mk1",                  year: "1996–2010", cat: "Kompakt",      img: "cars/skoda_octavia_mk1.webp" },
  { brand: "Škoda", model: "Octavia Mk2",                  year: "2004–2013", cat: "Kompakt",      img: "cars/skoda_octavia_mk2.jpg" },
  { brand: "Škoda", model: "Octavia Mk3",                  year: "2012–2020", cat: "Kompakt",      img: "cars/skoda_octavia_mk3.webp" },
  { brand: "Škoda", model: "Octavia Mk4",                  year: "2020–",     cat: "Kompakt",      img: "cars/skoda_octavia_mk4.jpg" },
  { brand: "Škoda", model: "Octavia RS (5E)",              year: "2012–2020", cat: "Sportler",     img: "cars/skoda_octavia_rs.jpg" },
  { brand: "Škoda", model: "Fabia Mk3",                    year: "2014–2021", cat: "Kleinwagen",   img: "cars/skoda_fabia_mk3.jpg" },
  { brand: "Škoda", model: "Fabia Mk4",                    year: "2021–",     cat: "Kleinwagen",   img: "cars/skoda_fabia_mk4.jpg" },
  { brand: "Škoda", model: "Superb Mk3",                   year: "2015–",     cat: "Oberklasse",   img: "cars/skoda_superb_mk3.webp" },
  { brand: "Škoda", model: "Superb iV",                    year: "2019–",     cat: "Plug-in-Hybrid",img: "cars/skoda_superb_iv.webp" },
  { brand: "Škoda", model: "Kodiaq RS",                    year: "2019–",     cat: "Sportler-SUV", img: "cars/skoda_kodiaq_rs.jpg" },
  { brand: "Škoda", model: "Karoq",                        year: "2017–",     cat: "SUV",          img: "cars/skoda_karoq.jpg" },
  { brand: "Škoda", model: "Enyaq iV 80",                  year: "2020–",     cat: "Elektro-SUV",  img: "cars/skoda_enyaq.webp" },
  { brand: "Škoda", model: "Enyaq RS iV",                  year: "2021–",     cat: "Elektro-SUV",  img: "cars/skoda_enyaq_rs.jpg" },
  { brand: "Škoda", model: "Elroq",                        year: "2024–",     cat: "Elektro-SUV",  img: "cars/skoda_elroq.webp" },
  { brand: "Škoda", model: "Scala",                        year: "2019–",     cat: "Kompakt",      img: "cars/skoda_scala.webp" },
  { brand: "Škoda", model: "Kamiq",                        year: "2019–",     cat: "SUV",          img: "cars/skoda_kamiq.jpg" },

  /* ── OPEL ─────────────────────────────────────────────── */
  { brand: "Opel", model: "GT",                            year: "1968–1973", cat: "Sportwagen",   img: "cars/opel_gt.webp" },
  { brand: "Opel", model: "Manta B",                       year: "1975–1988", cat: "Coupé",        img: "cars/opel_manta_b.jpg" },
  { brand: "Opel", model: "Calibra",                       year: "1989–1997", cat: "Coupé",        img: "cars/opel_calibra.jpeg" },
  { brand: "Opel", model: "Omega B",                       year: "1993–2003", cat: "Oberklasse",   img: "cars/opel_omega_b.webp" },
  { brand: "Opel", model: "Astra H OPC",                   year: "2005–2010", cat: "Hot Hatch",    img: "cars/opel_astra_h_opc.jpg" },
  { brand: "Opel", model: "Astra J",                       year: "2009–2015", cat: "Kompakt",      img: "cars/opel_astra_j.jpg" },
  { brand: "Opel", model: "Astra K",                       year: "2015–2021", cat: "Kompakt",      img: "cars/opel_astra_k.webp" },
  { brand: "Opel", model: "Astra L",                       year: "2021–",     cat: "Kompakt",      img: "cars/opel_astra_l.jpg" },
  { brand: "Opel", model: "Astra Electric",                year: "2023–",     cat: "Elektro",      img: "cars/opel_astra_electric.jpg" },
  { brand: "Opel", model: "Corsa E",                       year: "2014–2019", cat: "Kleinwagen",   img: "cars/opel_corsa_e.jpg" },
  { brand: "Opel", model: "Corsa F",                       year: "2019–",     cat: "Kleinwagen",   img: "cars/opel_corsa_f.jpeg" },
  { brand: "Opel", model: "Corsa Electric",                year: "2019–",     cat: "Elektro",      img: "cars/opel_corsa_electric.webp" },
  { brand: "Opel", model: "Insignia B",                    year: "2017–2024", cat: "Mittelklasse", img: "cars/opel_insignia_b.jpg" },
  { brand: "Opel", model: "Mokka B",                       year: "2020–",     cat: "SUV",          img: "cars/opel_mokka_b.avif" },
  { brand: "Opel", model: "Mokka Electric",                year: "2020–",     cat: "Elektro-SUV",  img: "cars/opel_mokka_electric.webp" },
  { brand: "Opel", model: "Crossland",                     year: "2021–",     cat: "SUV",          img: "cars/opel_crossland.jpg" },
  { brand: "Opel", model: "Grandland GSe",                 year: "2022–",     cat: "Hybrid-SUV",   img: "cars/opel_grandland_gse.jpg" },
  { brand: "Opel", model: "Grandland Electric",            year: "2024–",     cat: "Elektro-SUV",  img: "cars/opel_grandland_electric.webp" },
  { brand: "Opel", model: "Vectra OPC",                    year: "2005–2009", cat: "Hot Hatch",    img: "cars/opel_vectra_opc.jpeg" },
  { brand: "Opel", model: "Frontera (Mk2)",                year: "2024–",     cat: "Elektro-SUV",  img: "cars/opel_frontera_mk2.jpg" },

  /* ── MINI ─────────────────────────────────────────────── */
  { brand: "Mini", model: "Mini Cooper S (ADO15)",         year: "1963–1971", cat: "Ikone",        img: "cars/mini_cooper_s_ado15.jpg" },
  { brand: "Mini", model: "Mini Cooper S (R53)",           year: "2002–2006", cat: "Hot Hatch",    img: "cars/mini_cooper_s_r53.webp" },
  { brand: "Mini", model: "Mini JCW (R56)",                year: "2008–2013", cat: "Hot Hatch",    img: "cars/mini_jcw_r56.jpg" },
  { brand: "Mini", model: "Mini Clubman (R55)",            year: "2007–2015", cat: "Kombi",        img: "cars/mini_clubman_r55.jpg" },
  { brand: "Mini", model: "Mini Countryman (R60)",         year: "2010–2016", cat: "SUV",          img: "cars/mini_countryman_r60.jpg" },
  { brand: "Mini", model: "Mini Cooper (F56)",             year: "2014–2023", cat: "Kleinwagen",   img: "cars/mini_cooper_f56.webp" },
  { brand: "Mini", model: "Mini Cooper S (F56)",           year: "2014–2023", cat: "Hot Hatch",    img: "cars/mini_cooper_s_f56.webp" },
  { brand: "Mini", model: "Mini JCW (F56)",                year: "2015–2023", cat: "Hot Hatch",    img: "cars/mini_jcw_f56.jpg" },
  { brand: "Mini", model: "Mini Cabrio (F57)",             year: "2015–2023", cat: "Cabrio",       img: "cars/mini_cabrio_f57.jpg" },
  { brand: "Mini", model: "Mini Clubman (F54)",            year: "2015–2023", cat: "Kombi",        img: "cars/mini_clubman_f54.webp" },
  { brand: "Mini", model: "Mini Countryman (F60)",         year: "2017–2023", cat: "SUV",          img: "cars/mini_countryman_f60.avif" },
  { brand: "Mini", model: "Mini Countryman JCW (F60)",     year: "2020–2023", cat: "Sportler-SUV", img: "cars/mini_countryman_jcw_f60.jpg" },
  { brand: "Mini", model: "Mini Electric (F56 SE)",        year: "2019–2023", cat: "Elektro",      img: "cars/mini_electric_f56.jpg" },
  { brand: "Mini", model: "Mini Cooper C (J01)",           year: "2024–",     cat: "Kleinwagen",   img: "cars/mini_cooper_j01.jpg" },
  { brand: "Mini", model: "Mini Cooper S (J01)",           year: "2024–",     cat: "Hot Hatch",    img: "cars/mini_cooper_s_j01.jpg" },
  { brand: "Mini", model: "Mini JCW (J01)",                year: "2024–",     cat: "Hot Hatch",    img: "cars/mini_jcw_j01.jpg" },
  { brand: "Mini", model: "Mini Aceman Electric",          year: "2024–",     cat: "Elektro-SUV",  img: "cars/mini_aceman.jpg" },
  { brand: "Mini", model: "Mini Countryman (C50)",         year: "2023–",     cat: "SUV",          img: "cars/mini_countryman_c50.webp" },
  { brand: "Mini", model: "Mini Pacesetter",               year: "2022",      cat: "Concept",      img: "cars/mini_pacesetter.jpg" },

  /* ── BENTLEY ──────────────────────────────────────────── */
  { brand: "Bentley", model: "Turbo R",                    year: "1985–1997", cat: "Luxus",        img: "cars/bentley_turbo_r.jpg" },
  { brand: "Bentley", model: "Azure (Mk1)",                year: "1995–2003", cat: "Luxus-Cabrio", img: "cars/bentley_azure_mk1.jpg" },
  { brand: "Bentley", model: "Arnage T",                   year: "2002–2009", cat: "Luxus",        img: "cars/bentley_arnage.jpg" },
  { brand: "Bentley", model: "Continental GT (Mk1)",       year: "2003–2011", cat: "GT",           img: "cars/bentley_continental_gt_mk1.webp" },
  { brand: "Bentley", model: "Continental GTC (Mk1)",      year: "2006–2011", cat: "GT-Cabrio",    img: "cars/bentley_continental_gtc_mk1.webp" },
  { brand: "Bentley", model: "Continental Supersports",    year: "2009–2011", cat: "Supercar",     img: "cars/bentley_continental_ss.jpeg" },
  { brand: "Bentley", model: "Mulsanne Speed",             year: "2014–2020", cat: "Luxus",        img: "cars/bentley_mulsanne_speed.avif" },
  { brand: "Bentley", model: "Bentayga V8",                year: "2020–",     cat: "Luxus-SUV",    img: "cars/bentley_bentayga_v8.jpg" },
  { brand: "Bentley", model: "Bentayga Speed",             year: "2020–",     cat: "Luxus-SUV",    img: "cars/bentley_bentayga_speed.jpg" },
  { brand: "Bentley", model: "Bentayga EWB",               year: "2022–",     cat: "Luxus-SUV",    img: "cars/bentley_bentayga_ewb.jpg" },
  { brand: "Bentley", model: "Continental GT (Mk3)",       year: "2018–",     cat: "GT",           img: "cars/bentley_continental_gt_mk3.webp" },
  { brand: "Bentley", model: "Continental GT Speed (Mk3)", year: "2021–",     cat: "GT",           img: "cars/bentley_continental_gt_speed.jpg" },
  { brand: "Bentley", model: "Flying Spur (Mk3)",          year: "2019–",     cat: "Luxus",        img: "cars/bentley_flying_spur_mk3.avif" },
  { brand: "Bentley", model: "Flying Spur S",              year: "2023–",     cat: "Luxus",        img: "cars/bentley_flying_spur_s.jpg" },
  { brand: "Bentley", model: "Batur",                      year: "2023–",     cat: "Hypercar",     img: "cars/bentley_batur.jpg" },
  { brand: "Bentley", model: "Mulliner Bacalar",           year: "2021–",     cat: "Hypercar",     img: "cars/bentley_bacalar.jpeg" },
  { brand: "Bentley", model: "Continental GT W12 Final Series", year: "2024",  cat: "GT",          img: "cars/bentley_continental_gt_final.jpg" },

  /* ── MERCEDES-BENZ ────────────────────────────────────── */
  { brand: "Mercedes-Benz", model: "300 SL (W198)",        year: "1954–1963", cat: "Ikone",        img: "cars/mb_300sl.jpg" },
  { brand: "Mercedes-Benz", model: "Pagode (W113)",        year: "1963–1971", cat: "Roadster",     img: "cars/mb_w113.jpg" },
  { brand: "Mercedes-Benz", model: "SL R107",              year: "1971–1989", cat: "Roadster",     img: "cars/mb_r107.jpg" },
  { brand: "Mercedes-Benz", model: "W124 (E-Klasse)",      year: "1984–1997", cat: "Mittelklasse", img: "cars/mb_w124.jpg" },
  { brand: "Mercedes-Benz", model: "190 E 2.3-16 (W201)",  year: "1983–1988", cat: "Sportler",     img: "cars/mb_w201_cosworth.webp" },
  { brand: "Mercedes-Benz", model: "SL R129",              year: "1989–2001", cat: "Roadster",     img: "cars/mb_r129.avif" },
  { brand: "Mercedes-Benz", model: "G-Klasse W463",        year: "1990–",     cat: "SUV",          img: "cars/mb_w463.jpg" },
  { brand: "Mercedes-Benz", model: "C-Klasse W204 AMG",    year: "2007–2014", cat: "Sportler",     img: "cars/mb_c63_w204.webp" },
  { brand: "Mercedes-Benz", model: "C 63 AMG (W205)",      year: "2014–2021", cat: "Sportler",     img: "cars/mb_c63_w205.webp" },
  { brand: "Mercedes-Benz", model: "C 63 S E Performance (W206)", year: "2022–", cat: "Hybrid",   img: "cars/mb_c63_w206.webp" },
  { brand: "Mercedes-Benz", model: "C-Klasse W206",        year: "2021–",     cat: "Mittelklasse", img: "cars/mb_w206.jpg" },
  { brand: "Mercedes-Benz", model: "E-Klasse W212",        year: "2009–2016", cat: "Oberklasse",   img: "cars/mb_w212.jpg" },
  { brand: "Mercedes-Benz", model: "E-Klasse W213",        year: "2016–2023", cat: "Oberklasse",   img: "cars/mb_w213.jpg" },
  { brand: "Mercedes-Benz", model: "E-Klasse W214",        year: "2023–",     cat: "Oberklasse",   img: "cars/mb_w214.webp" },
  { brand: "Mercedes-Benz", model: "E 63 S AMG (W213)",    year: "2017–2023", cat: "Sportler",     img: "cars/mb_e63_w213.jpg" },
  { brand: "Mercedes-Benz", model: "S-Klasse W222",        year: "2013–2020", cat: "Luxus",        img: "cars/mb_w222.webp" },
  { brand: "Mercedes-Benz", model: "S-Klasse W223",        year: "2020–",     cat: "Luxus",        img: "cars/mb_w223.avif" },
  { brand: "Mercedes-Benz", model: "S 63 AMG (W223)",      year: "2021–",     cat: "Luxus-Sportler",img: "cars/mb_s63_w223.jpg" },
  { brand: "Mercedes-Benz", model: "Maybach S 680",        year: "2021–",     cat: "Ultra-Luxus",  img: "cars/mb_maybach_s680.webp" },
  { brand: "Mercedes-Benz", model: "Maybach S 600 (W222)", year: "2015–2021", cat: "Ultra-Luxus",  img: "cars/mb_maybach_s600.jpg" },
  { brand: "Mercedes-Benz", model: "Maybach GLS 600",      year: "2020–",     cat: "Luxus-SUV",    img: "cars/mb_maybach_gls600.avif" },
  { brand: "Mercedes-Benz", model: "CLS (C257)",           year: "2018–",     cat: "Coupé",        img: "cars/mb_c257.jpg" },
  { brand: "Mercedes-Benz", model: "CLA (C118)",           year: "2019–",     cat: "Kompakt",      img: "cars/mb_c118.jpg" },
  { brand: "Mercedes-Benz", model: "AMG GT R (C190)",      year: "2016–2023", cat: "Supercar",     img: "cars/mb_amg_gt_r.jpg" },
  { brand: "Mercedes-Benz", model: "AMG GT Black Series",  year: "2020–2021", cat: "Supercar",     img: "cars/mb_amg_gt_black.jpg" },
  { brand: "Mercedes-Benz", model: "AMG GT (R190)",        year: "2023–",     cat: "Sportwagen",   img: "cars/mb_amg_gt_r190.jpg" },
  { brand: "Mercedes-Benz", model: "AMG GT 63 S (R190)",   year: "2023–",     cat: "Sportwagen",   img: "cars/mb_amg_gt63s_r190.jpg" },
  { brand: "Mercedes-Benz", model: "SL (R232)",            year: "2021–",     cat: "Roadster",     img: "cars/mb_r232.jpg" },
  { brand: "Mercedes-Benz", model: "SL 63 AMG (R232)",     year: "2022–",     cat: "Roadster",     img: "cars/mb_sl63_r232.jpg" },
  { brand: "Mercedes-Benz", model: "GLE Coupé (C167)",     year: "2020–",     cat: "SUV-Coupé",    img: "cars/mb_c167.jpg" },
  { brand: "Mercedes-Benz", model: "GLE 63 S AMG (W167)",  year: "2020–",     cat: "Sportler-SUV", img: "cars/mb_gle63s.jpg" },
  { brand: "Mercedes-Benz", model: "GLS 63 AMG (X167)",    year: "2020–",     cat: "Sportler-SUV", img: "cars/mb_gls63.jpg" },
  { brand: "Mercedes-Benz", model: "G 63 AMG (W463A)",     year: "2018–",     cat: "Sportler-SUV", img: "cars/mb_g63.jpeg" },
  { brand: "Mercedes-Benz", model: "G 63 AMG Brabus 800",  year: "2021–",     cat: "Sportler-SUV", img: "cars/mb_g63_brabus.jpg" },
  { brand: "Mercedes-Benz", model: "EQS 53 AMG",           year: "2022–",     cat: "Elektro",      img: "cars/mb_eqs53.jpg" },
  { brand: "Mercedes-Benz", model: "EQG",                  year: "2024–",     cat: "Elektro-SUV",  img: "cars/mb_eqg.png" },
  { brand: "Mercedes-Benz", model: "ONE (C298)",           year: "2022–",     cat: "Hypercar",     img: "cars/mb_one.jpg" },

];