const CARS = [

  { brand: "Volkswagen", model: "Up!",              year: "2016", cat: "PKW",        img: "cars/vw-up.jpeg" },
  { brand: "Volkswagen", model: "Fox",              year: "2011", cat: "PKW",        img: "cars/vw-fox.avif" },
  { brand: "Volkswagen", model: "Polo",             year: "2024", cat: "PKW",        img: "cars/vw-polo.avif" },
  { brand: "Volkswagen", model: "Golf",             year: "2026", cat: "PKW",        img: "cars/vw-golf.avif" },
  { brand: "Volkswagen", model: "Jetta",             year: "2018", cat: "PKW",        img: "cars/vw-jetta.avif" },
  { brand: "Volkswagen", model: "Scirocco",             year: "2014", cat: "PKW",        img: "cars/vw-scirocco.jpg" },
  { brand: "Volkswagen", model: "Beetle",             year: "2019", cat: "PKW",        img: "cars/vw-beetle.jpg" },
  { brand: "Volkswagen", model: "EOS",             year: "2015", cat: "PKW",        img: "cars/vw-eos.jpg" },
  { brand: "Volkswagen", model: "CC",             year: "2016", cat: "PKW",        img: "cars/cc.avif" },
  { brand: "Volkswagen", model: "Passat",             year: "2024", cat: "PKW",        img: "cars/vw-passat.webp" },
  { brand: "Volkswagen", model: "Arteon",             year: "2024", cat: "PKW",        img: "cars/vw-arteon.avif" },
  { brand: "Volkswagen", model: "Phaeton",             year: "2024", cat: "PKW",        img: "cars/vw-phaeton.jpg" },
  { brand: "Volkswagen", model: "ID.3",             year: "2026", cat: "PKW",        img: "cars/vw-id3.jpg" },
  { brand: "Volkswagen", model: "ID.4",             year: "2026", cat: "PKW",        img: "cars/vw-id4.jpg" },
  { brand: "Volkswagen", model: "ID.5",             year: "2022", cat: "PKW",        img: "cars/vw-id5.jpg" },
  { brand: "Volkswagen", model: "ID.7",             year: "2026", cat: "PKW",        img: "cars/vw-id7.webp" },
  { brand: "Volkswagen", model: "ID.Buzz",             year: "2026", cat: "PKW",        img: "cars/idbuzz.jpg" },
  { brand: "Volkswagen", model: "ID.Polo",             year: "2026", cat: "PKW",        img: "cars/vw-idpolo.webp" },
  { brand: "Volkswagen", model: "ID.Cross",             year: "2026", cat: "PKW",        img: "cars/vw-idcross.jpg" },
  { brand: "Volkswagen", model: "ID.Every1",             year: "2026", cat: "PKW",        img: "cars/vw-idevery1.jpg" },
  { brand: "Volkswagen", model: "ID.Unyx 09",             year: "2026", cat: "PKW",        img: "cars/vw-unyx09.jpg" },
  { brand: "Volkswagen", model: "ID.Era 9x",             year: "2026", cat: "PKW",        img: "cars/vw-era9x.jpg" },
  { brand: "Volkswagen", model: "ID.Aura T6",             year: "2026", cat: "PKW",        img: "cars/vw-aurat6.jpg" },
  { brand: "Volkswagen", model: "Tiguan",             year: "2026", cat: "PKW",        img: "cars/vw-tiguan.avif" },
  { brand: "Volkswagen", model: "Touareg",             year: "2026", cat: "PKW",        img: "cars/vw-touareg.jpg" },
  { brand: "Volkswagen", model: "T-Roc",             year: "2026", cat: "PKW",        img: "cars/vw-troc.jpg" },
  { brand: "Volkswagen", model: "Taigo",             year: "2026", cat: "PKW",        img: "cars/vw-taigo.jpg" },
  { brand: "Volkswagen", model: "Touran",             year: "2026", cat: "PKW",        img: "cars/vw-touran.jpg" },
  { brand: "Volkswagen", model: "Sharan",             year: "2026", cat: "PKW",        img: "cars/vw-sharan.jpg" },
  { brand: "Volkswagen", model: "Caddy",             year: "2026", cat: "PKW",        img: "cars/vw-caddy.avif" },
  { brand: "Volkswagen", model: "Multivan",             year: "2026", cat: "PKW",        img: "cars/vw-multivan.jpeg" },
  { brand: "Volkswagen", model: "Transporter",             year: "2026", cat: "PKW",        img: "cars/vw-transporter.avif" },
  { brand: "Volkswagen", model: "Caravelle",             year: "2026", cat: "PKW",        img: "cars/vw-caravelle.jpg" },
  { brand: "Volkswagen", model: "Amarok",             year: "2026", cat: "PKW",        img: "cars/vw-amarok.avif" },

  { brand: "Audi", model: "A1",             year: "2026", cat: "PKW",        img: "cars/a1.jpg" },
  { brand: "Audi", model: "A2",             year: "2026", cat: "PKW",        img: "cars/a2.jpg" },
  { brand: "Audi", model: "A3",             year: "2026", cat: "PKW",        img: "cars/a3.webp" },
  { brand: "Audi", model: "A4",             year: "2026", cat: "PKW",        img: "cars/a4.avif" },
  { brand: "Audi", model: "A5",             year: "2026", cat: "PKW",        img: "cars/a5.avif" },
  { brand: "Audi", model: "A6",             year: "2026", cat: "PKW",        img: "cars/a6.jpg" },
  { brand: "Audi", model: "A6 e-tron",             year: "2026", cat: "PKW",        img: "cars/a6etron.avif" },
  { brand: "Audi", model: "A7",             year: "2026", cat: "PKW",        img: "cars/a7.jpg" },
  { brand: "Audi", model: "A8",             year: "2026", cat: "PKW",        img: "cars/a8.webp" },
  { brand: "Audi", model: "Q2",             year: "2026", cat: "PKW",        img: "cars/q2.jpg" },
  { brand: "Audi", model: "Q3",             year: "2026", cat: "PKW",        img: "cars/q3.jpg" },
  { brand: "Audi", model: "Q4 e-tron",             year: "2026", cat: "PKW",        img: "cars/q4etron.avif" },
  { brand: "Audi", model: "Q5",             year: "2026", cat: "PKW",        img: "cars/q5.webp" },
  { brand: "Audi", model: "Q6 e-tron",             year: "2026", cat: "PKW",        img: "cars/q6etron.jpg" },
  { brand: "Audi", model: "Q7",             year: "2026", cat: "PKW",        img: "cars/q7.avif" },
  { brand: "Audi", model: "Q8",             year: "2026", cat: "PKW",        img: "cars/q8.webp" },
  { brand: "Audi", model: "Q8 e-tron",             year: "2026", cat: "PKW",        img: "cars/q8etron.avif" },
  { brand: "Audi", model: "Q9",             year: "2026", cat: "PKW",        img: "cars/q9.webp" },
  { brand: "Audi", model: "E-tron GT",             year: "2026", cat: "PKW",        img: "cars/etrongt.jpg" },
  { brand: "Audi", model: "R8",             year: "2026", cat: "PKW",        img: "cars/r8.webp" },
  { brand: "Audi", model: "TT",             year: "2026", cat: "PKW",        img: "cars/tt.jpg" },
  { brand: "Audi", model: "RS3",             year: "2026", cat: "PKW",        img: "cars/rs3.avif" },
  { brand: "Audi", model: "S4",             year: "2026", cat: "PKW",        img: "cars/s4.avif" },
  { brand: "Audi", model: "RS5",             year: "2026", cat: "PKW",        img: "cars/rs5.webp" },
  { brand: "Audi", model: "S6",             year: "2026", cat: "PKW",        img: "cars/s6.jpg" },
  { brand: "Audi", model: "RS7",             year: "2026", cat: "PKW",        img: "cars/rs7.jpg" },
  { brand: "Audi", model: "SQ5",             year: "2026", cat: "PKW",        img: "cars/sq5.jpg" },
  { brand: "Audi", model: "SQ8",             year: "2026", cat: "PKW",        img: "cars/sq8.jpg" },
  { brand: "Audi", model: "RSQ8",             year: "2026", cat: "PKW",        img: "cars/rsq8.jpg" },
  { brand: "Audi", model: "Nuvolari",             year: "2026", cat: "PKW",        img: "cars/nuvolari.jpg" },

  { brand: "Mercedes-Benz", model: "A-Klasse",             year: "2026", cat: "PKW",        img: "cars/aklasse.avif" },
  { brand: "Mercedes-Benz", model: "B-Klasse",             year: "2026", cat: "PKW",        img: "cars/bklasse.avif" },
  { brand: "Mercedes-Benz", model: "CLA",             year: "2026", cat: "PKW",        img: "cars/cla.jpeg" },
  { brand: "Mercedes-Benz", model: "CLS",             year: "2026", cat: "PKW",        img: "cars/cls.jpg" },
  { brand: "Mercedes-Benz", model: "CLE",             year: "2026", cat: "PKW",        img: "cars/cle.jpg" },
  { brand: "Mercedes-Benz", model: "C-Klasse",             year: "2026", cat: "PKW",        img: "cars/cklasse.jpg" },
  { brand: "Mercedes-Benz", model: "E-Klasse",             year: "2026", cat: "PKW",        img: "cars/eklasse.webp" },
  { brand: "Mercedes-Benz", model: "S-Klasse",             year: "2026", cat: "PKW",        img: "cars/sklasse.jpg" },
  { brand: "Mercedes-Benz", model: "SL",             year: "2026", cat: "PKW",        img: "cars/sl.jpg" },
  { brand: "Mercedes-Benz", model: "GLA",             year: "2026", cat: "PKW",        img: "cars/gla.webp" },
  { brand: "Mercedes-Benz", model: "GLB",             year: "2026", cat: "PKW",        img: "cars/glb.jpg" },
  { brand: "Mercedes-Benz", model: "GLC",             year: "2026", cat: "PKW",        img: "cars/glc.avif" },
  { brand: "Mercedes-Benz", model: "GLE",             year: "2026", cat: "PKW",        img: "cars/gle.avif" },
  { brand: "Mercedes-Benz", model: "GLS",             year: "2026", cat: "PKW",        img: "cars/gls.avif" },
  { brand: "Mercedes-Benz", model: "G-Klasse",             year: "2026", cat: "PKW",        img: "cars/gklasse.jpg" },
  { brand: "Mercedes-Benz", model: "EQA",             year: "2026", cat: "PKW",        img: "cars/eqa.jpg" },
  { brand: "Mercedes-Benz", model: "EQB",             year: "2026", cat: "PKW",        img: "cars/eqb.jpg" },
  { brand: "Mercedes-Benz", model: "EQC",             year: "2026", cat: "PKW",        img: "cars/eqc.jpg" },
  { brand: "Mercedes-Benz", model: "EQE",             year: "2026", cat: "PKW",        img: "cars/eqe.webp" },
  { brand: "Mercedes-Benz", model: "EQS",             year: "2026", cat: "PKW",        img: "cars/eqs.webp" },
  { brand: "Mercedes-Benz", model: "EQT",             year: "2026", cat: "PKW",        img: "cars/eqt.webp" },
  { brand: "Mercedes-Benz", model: "AMG ONE",             year: "2026", cat: "PKW",        img: "cars/amgone.jpg" },
  { brand: "Mercedes-Benz", model: "AMG GT",             year: "2026", cat: "PKW",        img: "cars/amggt.jpg" },
  { brand: "Mercedes-Benz", model: "AMG Purespeed",             year: "2026", cat: "PKW",        img: "cars/amgpurespeed.jpg" },
  { brand: "Mercedes-Benz", model: "Citan",             year: "2026", cat: "PKW",        img: "cars/citan.jpg" },
  { brand: "Mercedes-Benz", model: "T-Klasse",             year: "2026", cat: "PKW",        img: "cars/tklasse.jpg" },
  { brand: "Mercedes-Benz", model: "V-Klasse",             year: "2026", cat: "PKW",        img: "cars/vklasse.webp" },
  { brand: "Mercedes-Benz", model: "M-Klasse",             year: "2026", cat: "PKW",        img: "cars/mklasse.jpg" },
  { brand: "Mercedes-Benz", model: "SLS AMG",             year: "2026", cat: "PKW",        img: "cars/slsamg.webp" },
  { brand: "Mercedes-Benz", model: "Maybach S-Klasse",             year: "2026", cat: "PKW",        img: "cars/maybachsklasse.jpg" },
  { brand: "Mercedes-Benz", model: "Maybach GLS",             year: "2026", cat: "PKW",        img: "cars/maybachgls.avif" },

  { brand: "Porsche", model: "911",             year: "2026", cat: "PKW",        img: "cars/911.jpg" },
  { brand: "Porsche", model: "718",             year: "2026", cat: "PKW",        img: "cars/718.jpeg" },
  { brand: "Porsche", model: "Cayenne",             year: "2026", cat: "PKW",        img: "cars/cayenne.webp" },
  { brand: "Porsche", model: "Macan",             year: "2026", cat: "PKW",        img: "cars/macan.webp" },
  { brand: "Porsche", model: "Panamera",             year: "2026", cat: "PKW",        img: "cars/panamera.jpg" },
  { brand: "Porsche", model: "Taycan",             year: "2026", cat: "PKW",        img: "cars/taycan.jpg" },
  { brand: "Porsche", model: "911 GT3",             year: "2026", cat: "PKW",        img: "cars/gt3.jpeg" },
  { brand: "Porsche", model: "911 GT3 RS",             year: "2026", cat: "PKW",        img: "cars/gt3rs.webp" },
  { brand: "Porsche", model: "718 Cayman GT4",             year: "2026", cat: "PKW",        img: "cars/gt4.webp" },
  { brand: "Porsche", model: "911 Turbo S",             year: "2026", cat: "PKW",        img: "cars/turbos.webp" },

  { brand: "Lamborghini", model: "Temerario",             year: "2026", cat: "PKW",        img: "cars/temerario.jpg" },
  { brand: "Lamborghini", model: "Revuelto",             year: "2026", cat: "PKW",        img: "cars/revuelto.jpeg" },
  { brand: "Lamborghini", model: "Urus",             year: "2026", cat: "PKW",        img: "cars/urus.webp" },
  { brand: "Lamborghini", model: "Huracan",             year: "2026", cat: "PKW",        img: "cars/huracan.avif" },
  { brand: "Lamborghini", model: "Aventador",             year: "2026", cat: "PKW",        img: "cars/aventador.webp" },
  { brand: "Lamborghini", model: "Gallardo",             year: "2026", cat: "PKW",        img: "cars/gallardo.webp" },

  { brand: "BYD", model: "Han",             year: "2026", cat: "PKW",        img: "cars/han.jpg" },
  { brand: "BYD", model: "Tang",             year: "2026", cat: "PKW",        img: "cars/tang.jpg" },
  { brand: "BYD", model: "Song",             year: "2026", cat: "PKW",        img: "cars/song.jpg" },
  { brand: "BYD", model: "Qin",             year: "2026", cat: "PKW",        img: "cars/qin.webp" },
  { brand: "BYD", model: "Yuan",             year: "2026", cat: "PKW",        img: "cars/yuan.jpg" },
  { brand: "BYD", model: "Datang",             year: "2026", cat: "PKW",        img: "cars/datang.jpg" },
  { brand: "BYD", model: "Seal",             year: "2026", cat: "PKW",        img: "cars/seal.jpg" },
  { brand: "BYD", model: "Dolphin",             year: "2026", cat: "PKW",        img: "cars/dolphin.webp" },
  { brand: "BYD", model: "Sealion",             year: "2026", cat: "PKW",        img: "cars/sealion.webp" },

  { brand: "Xiaomi", model: "SU7",             year: "2026", cat: "PKW",        img: "cars/su7.webp" },
  { brand: "Xiaomi", model: "SU7 Ultra",             year: "2026", cat: "PKW",        img: "cars/su7ultra.jpg" },
  { brand: "Xiaomi", model: "YU7",             year: "2026", cat: "PKW",        img: "cars/yu7.jpg" },
  { brand: "Xiaomi", model: "YU9",             year: "2026", cat: "PKW",        img: "cars/yu9.webp" },

  { brand: "SEAT", model: "Ibiza",             year: "2026", cat: "PKW",        img: "cars/ibiza.jpeg" },
  { brand: "SEAT", model: "Arona",             year: "2026", cat: "PKW",        img: "cars/arona.webp" },
  { brand: "SEAT", model: "Leon",             year: "2026", cat: "PKW",        img: "cars/leon.avif" },
  { brand: "SEAT", model: "Ateca",             year: "2026", cat: "PKW",        img: "cars/ateca.jpg" },
  { brand: "SEAT", model: "Tarraco",             year: "2026", cat: "PKW",        img: "cars/tarraco.webp" },

  { brand: "Cupra", model: "Formentor",             year: "2026", cat: "PKW",        img: "cars/formentor.avif" },
  { brand: "Cupra", model: "Leon",             year: "2026", cat: "PKW",        img: "cars/cleon.jpg" },
  { brand: "Cupra", model: "Born",             year: "2026", cat: "PKW",        img: "cars/born.webp" },
  { brand: "Cupra", model: "Tavascan",             year: "2026", cat: "PKW",        img: "cars/tavascan.webp" },
  { brand: "Cupra", model: "Terramar",             year: "2026", cat: "PKW",        img: "cars/terramar.avif" },
  { brand: "Cupra", model: "Raval",             year: "2026", cat: "PKW",        img: "cars/raval.webp" },
  { brand: "Cupra", model: "Ateca",             year: "2026", cat: "PKW",        img: "cars/cateca.jpg" },

  { brand: "Skoda", model: "Fabia",             year: "2026", cat: "PKW",        img: "cars/fabia.webp" },
  { brand: "Skoda", model: "Scala",             year: "2026", cat: "PKW",        img: "cars/scala.webp" },
  { brand: "Skoda", model: "Octavia",             year: "2026", cat: "PKW",        img: "cars/octavia.webp" },
  { brand: "Skoda", model: "Superb",             year: "2026", cat: "PKW",        img: "cars/superb.jpg" },
  { brand: "Skoda", model: "Kamiq",             year: "2026", cat: "PKW",        img: "cars/kamiq.webp" },
  { brand: "Skoda", model: "Karoq",             year: "2026", cat: "PKW",        img: "cars/karoq.webp" },
  { brand: "Skoda", model: "Kodiaq",             year: "2026", cat: "PKW",        img: "cars/kodiaq.avif" },
  { brand: "Skoda", model: "Elroq",             year: "2026", cat: "PKW",        img: "cars/elroq.webp" },
  { brand: "Skoda", model: "Enyaq",             year: "2026", cat: "PKW",        img: "cars/enyaq.jpg" },
  { brand: "Skoda", model: "Epiq",             year: "2026", cat: "PKW",        img: "cars/epiq.jpg" },
  { brand: "Skoda", model: "Peaq",             year: "2026", cat: "PKW",        img: "cars/peaq.jpeg" },
  { brand: "Skoda", model: "Fabia",             year: "2026", cat: "PKW",        img: "cars/fabia.webp" },

  { brand: "Bugatti", model: "Tourbillon",             year: "2026", cat: "PKW",        img: "cars/tourbillon.jpg" },
  { brand: "Bugatti", model: "Chiron",             year: "2026", cat: "PKW",        img: "cars/chiron.webp" },
  { brand: "Bugatti", model: "Mistral",             year: "2026", cat: "PKW",        img: "cars/mistral.webp" },
  { brand: "Bugatti", model: "Bolide",             year: "2026", cat: "PKW",        img: "cars/bolide.avif" },
  { brand: "Bugatti", model: "Brouillard",             year: "2026", cat: "PKW",        img: "cars/brouillard.jpg" },
  { brand: "Bugatti", model: "F.K.P Hommage",             year: "2026", cat: "PKW",        img: "cars/fkp.jpg" },

  { brand: "Bentley", model: "Continental GT",             year: "2026", cat: "PKW",        img: "cars/continental.jpg" },
  { brand: "Bentley", model: "Flying Spur",             year: "2026", cat: "PKW",        img: "cars/flyingspur.jpg" },
  { brand: "Bentley", model: "Batur",             year: "2026", cat: "PKW",        img: "cars/batur.jpg" },
  { brand: "Bentley", model: "Bacalar",             year: "2026", cat: "PKW",        img: "cars/bacalar.jpg" },
  { brand: "Bentley", model: "Blower",             year: "2026", cat: "PKW",        img: "cars/blower.avif" },
  { brand: "Bentley", model: "Urban SUV",             year: "2026", cat: "PKW",        img: "cars/urbansuv.jpg" },


{ brand: "Lexus", model: "LBX",             year: "2026", cat: "PKW",        img: "cars/lbx.jpeg" },
{ brand: "Lexus", model: "UX",             year: "2026", cat: "PKW",        img: "cars/ux.avif" },
{ brand: "Lexus", model: "NX",             year: "2026", cat: "PKW",        img: "cars/nx.avif" },
{ brand: "Lexus", model: "RX",             year: "2026", cat: "PKW",        img: "cars/rx.avif" },
{ brand: "Lexus", model: "ES",             year: "2026", cat: "PKW",        img: "cars/es.webp" },
{ brand: "Lexus", model: "IS",             year: "2026", cat: "PKW",        img: "cars/is.avif" },
{ brand: "Lexus", model: "LS",             year: "2026", cat: "PKW",        img: "cars/ls.webp" },
{ brand: "Lexus", model: "LX",             year: "2026", cat: "PKW",        img: "cars/lx.jpg" },
{ brand: "Lexus", model: "GX",             year: "2026", cat: "PKW",        img: "cars/gx.avif" },
{ brand: "Lexus", model: "TX",             year: "2026", cat: "PKW",        img: "cars/tx.avif" },
{ brand: "Lexus", model: "RZ",             year: "2026", cat: "PKW",        img: "cars/rz.webp" },
{ brand: "Lexus", model: "LC",             year: "2026", cat: "PKW",        img: "cars/lc.jpg" },
{ brand: "Lexus", model: "LM",             year: "2026", cat: "PKW",        img: "cars/lm.jpeg" },

{ brand: "Toyota", model: "Aygo X",             year: "2026", cat: "PKW",        img: "cars/aygox.webp" },
{ brand: "Toyota", model: "Yaris",             year: "2026", cat: "PKW",        img: "cars/yaris.webp" },
{ brand: "Toyota", model: "Yaris Cross",             year: "2026", cat: "PKW",        img: "cars/yariscross.jpg" },
{ brand: "Toyota", model: "Corolla",             year: "2026", cat: "PKW",        img: "cars/corolla.jpg" },
{ brand: "Toyota", model: "Corolla Cross",             year: "2026", cat: "PKW",        img: "cars/corollacross.jpeg" },
{ brand: "Toyota", model: "C-HR",             year: "2026", cat: "PKW",        img: "cars/chr.jpeg" },
{ brand: "Toyota", model: "C-HR+",             year: "2026", cat: "PKW",        img: "cars/chrplus.webp" },
{ brand: "Toyota", model: "RAV4",             year: "2026", cat: "PKW",        img: "cars/rav4.webp" },
{ brand: "Toyota", model: "Highlander",             year: "2026", cat: "PKW",        img: "cars/highlander.jpg" },
{ brand: "Toyota", model: "Land Cruiser",             year: "2026", cat: "PKW",        img: "cars/landcruiser.webp" },
{ brand: "Toyota", model: "Camry",             year: "2026", cat: "PKW",        img: "cars/camry.jpg" },
{ brand: "Toyota", model: "Prius",             year: "2026", cat: "PKW",        img: "cars/prius.jpg" },
{ brand: "Toyota", model: "bZ4X",             year: "2026", cat: "PKW",        img: "cars/bz4x.jpg" },
{ brand: "Toyota", model: "Urban Cruiser",             year: "2026", cat: "PKW",        img: "cars/urbancruiser.webp" },
{ brand: "Toyota", model: "GR86",             year: "2026", cat: "PKW",        img: "cars/gr86.jpg" },
{ brand: "Toyota", model: "GR Yaris",             year: "2026", cat: "PKW",        img: "cars/gryaris.jpg" },
{ brand: "Toyota", model: "GR Supra",             year: "2026", cat: "PKW",        img: "cars/grsupra.avif" },
{ brand: "Toyota", model: "Hilux",             year: "2026", cat: "PKW",        img: "cars/hilux.avif" },

{ brand: "Tesla", model: "Model 3",             year: "2026", cat: "PKW",        img: "cars/model3.jpg" },
{ brand: "Tesla", model: "Model Y",             year: "2026", cat: "PKW",        img: "cars/modely.avif" },
{ brand: "Tesla", model: "Model S",             year: "2026", cat: "PKW",        img: "cars/models.jpg" },
{ brand: "Tesla", model: "Model X",             year: "2026", cat: "PKW",        img: "cars/modelx.webp" },
{ brand: "Tesla", model: "Cybertruck",             year: "2026", cat: "PKW",        img: "cars/cybertruck.jpeg" },
{ brand: "Tesla", model: "Roadster",             year: "2026", cat: "PKW",        img: "cars/roadster.webp" },

{ brand: "Aston Martin", model: "DB12",             year: "2026", cat: "PKW",        img: "cars/db12.jpg" },
{ brand: "Aston Martin", model: "Vantage",             year: "2026", cat: "PKW",        img: "cars/vantage.avif" },
{ brand: "Aston Martin", model: "DBX",             year: "2026", cat: "PKW",        img: "cars/dbx.webp" },
{ brand: "Aston Martin", model: "Vanquish",             year: "2026", cat: "PKW",        img: "cars/vanquish.webp" },
{ brand: "Aston Martin", model: "Valhalla",             year: "2026", cat: "PKW",        img: "cars/valhalla.jpg" },

{ brand: "Maserati", model: "Grecale",             year: "2026", cat: "PKW",        img: "cars/grecale.webp" },
{ brand: "Maserati", model: "GranTurismo",             year: "2026", cat: "PKW",        img: "cars/granturismo.jpg" },
{ brand: "Maserati", model: "GranCabrio",             year: "2026", cat: "PKW",        img: "cars/grancabrio.jpg" },
{ brand: "Maserati", model: "Levante",             year: "2026", cat: "PKW",        img: "cars/levante.jpg" },
{ brand: "Maserati", model: "Quattroporte",             year: "2026", cat: "PKW",        img: "cars/quattroporte.webp" },
{ brand: "Maserati", model: "MCPura",             year: "2026", cat: "PKW",        img: "cars/mcpura.avif" },
{ brand: "Maserati", model: "GT2 Stradale",             year: "2026", cat: "PKW",        img: "cars/gt2stradale.webp" },

{ brand: "Jaguar", model: "Type 01",             year: "2026", cat: "PKW",        img: "cars/type01.webp" },
{ brand: "Jaguar", model: "F-Pace",             year: "2026", cat: "PKW",        img: "cars/fpace.jpg" },
{ brand: "Jaguar", model: "F-Type",             year: "2026", cat: "PKW",        img: "cars/ftype.webp" },
{ brand: "Jaguar", model: "XF",             year: "2026", cat: "PKW",        img: "cars/xf.avif" },
{ brand: "Jaguar", model: "E-Pace",             year: "2026", cat: "PKW",        img: "cars/epace.jpg" },
{ brand: "Jaguar", model: "I-Pace",             year: "2026", cat: "PKW",        img: "cars/ipace.avif" },

{ brand: "Renault", model: "Clio",             year: "2026", cat: "PKW",        img: "cars/clio.jpg" },
{ brand: "Renault", model: "Megane E-Tech",             year: "2026", cat: "PKW",        img: "cars/megane.webp" },
{ brand: "Renault", model: "Scenic E-Tech",             year: "2026", cat: "PKW",        img: "cars/scenic.jpg" },
{ brand: "Renault", model: "Espace",             year: "2026", cat: "PKW",        img: "cars/espace.jpg" },
{ brand: "Renault", model: "Captur",             year: "2026", cat: "PKW",        img: "cars/captur.webp" },
{ brand: "Renault", model: "Austral",             year: "2026", cat: "PKW",        img: "cars/austral.png" },
{ brand: "Renault", model: "Symbioz",             year: "2026", cat: "PKW",        img: "cars/symbioz.jpg" },
{ brand: "Renault", model: "Arkana",             year: "2026", cat: "PKW",        img: "cars/arkana.webp" },
{ brand: "Renault", model: "Twingo",             year: "2026", cat: "PKW",        img: "cars/twingo.webp" },
{ brand: "Renault", model: "Zoe",             year: "2026", cat: "PKW",        img: "cars/zoe.jpg" },
{ brand: "Renault", model: "Kangoo",             year: "2026", cat: "PKW",        img: "cars/kangoo.webp" },
{ brand: "Renault", model: "4 E-Tech",             year: "2026", cat: "PKW",        img: "cars/renault4.webp" },
{ brand: "Renault", model: "5 E-Tech",             year: "2026", cat: "PKW",        img: "cars/renault5.jpg" },
{ brand: "Renault", model: "Koleos",             year: "2026", cat: "PKW",        img: "cars/koleos.webp" },
{ brand: "Renault", model: "Rafale",             year: "2026", cat: "PKW",        img: "cars/rafale.webp" },

{ brand: "McLaren", model: "Artura",             year: "2026", cat: "PKW",        img: "cars/artura.jpg" },
{ brand: "McLaren", model: "750S",             year: "2026", cat: "PKW",        img: "cars/750s.jpg" },
{ brand: "McLaren", model: "GT",             year: "2026", cat: "PKW",        img: "cars/mclarengt.avif" },
{ brand: "McLaren", model: "GTS",             year: "2026", cat: "PKW",        img: "cars/gts.jpg" },
{ brand: "McLaren", model: "W1",             year: "2026", cat: "PKW",        img: "cars/w1.jpg" },

{ brand: "BMW", model: "1er",             year: "2026", cat: "PKW",        img: "cars/bmw1er.avif" },
{ brand: "BMW", model: "2er",             year: "2026", cat: "PKW",        img: "cars/bmw2er.jpg" },
{ brand: "BMW", model: "3er",             year: "2026", cat: "PKW",        img: "cars/bmw3er.webp" },
{ brand: "BMW", model: "4er",             year: "2026", cat: "PKW",        img: "cars/bmw4er.jpg" },
{ brand: "BMW", model: "5er",             year: "2026", cat: "PKW",        img: "cars/bmw5er.jpeg" },
{ brand: "BMW", model: "7er",             year: "2026", cat: "PKW",        img: "cars/bmw7er.jpg" },
{ brand: "BMW", model: "X1",             year: "2026", cat: "PKW",        img: "cars/bmwx1.webp" },
{ brand: "BMW", model: "X3",             year: "2026", cat: "PKW",        img: "cars/bmwx3.avif" },
{ brand: "BMW", model: "X5",             year: "2026", cat: "PKW",        img: "cars/bmwx5.png" },
{ brand: "BMW", model: "X7",             year: "2026", cat: "PKW",        img: "cars/bmwx7.jpg" },
{ brand: "BMW", model: "i4",             year: "2026", cat: "PKW",        img: "cars/bmwi4.webp" },
{ brand: "BMW", model: "i5",             year: "2026", cat: "PKW",        img: "cars/bmwi5.webp" },
{ brand: "BMW", model: "i7",             year: "2026", cat: "PKW",        img: "cars/bmwi7.jpeg" },
{ brand: "BMW", model: "iX",             year: "2026", cat: "PKW",        img: "cars/bmwix.webp" },
{ brand: "BMW", model: "iX3",             year: "2026", cat: "PKW",        img: "cars/bmwix3.jpg" },
{ brand: "BMW", model: "Z4",             year: "2026", cat: "PKW",        img: "cars/bmwz4.jpg" },

{ brand: "Ferrari", model: "296 GTB",             year: "2026", cat: "PKW",        img: "cars/296gtb.jpg" },
{ brand: "Ferrari", model: "Amalfi",             year: "2026", cat: "PKW",        img: "cars/amalfi.jpg" },
{ brand: "Ferrari", model: "849 Testarossa",             year: "2026", cat: "PKW",        img: "cars/849testarossa.jpg" },
{ brand: "Ferrari", model: "12Cilindri",             year: "2026", cat: "PKW",        img: "cars/12cilindri.avif" },
{ brand: "Ferrari", model: "Purosangue",             year: "2026", cat: "PKW",        img: "cars/purosangue.avif" },
{ brand: "Ferrari", model: "SF90",             year: "2026", cat: "PKW",        img: "cars/sf90.jpg" },
{ brand: "Ferrari", model: "F80",             year: "2026", cat: "PKW",        img: "cars/f80.jpg" },

{ brand: "Rolls Royce", model: "Ghost",             year: "2026", cat: "PKW",        img: "cars/ghost.jpg" },
{ brand: "Rolls Royce", model: "Phantom",             year: "2026", cat: "PKW",        img: "cars/phantom.avif" },
{ brand: "Rolls Royce", model: "Cullinan",             year: "2026", cat: "PKW",        img: "cars/cullinan.webp" },
{ brand: "Rolls Royce", model: "Spectre",             year: "2026", cat: "PKW",        img: "cars/spectre.webp" },
];