/* ═══════════════════════════════════════════════════════
   WAPPEN.JS  –  Stadtwappen-Quiz Datenbank
   Format: { stadt, bundesland, region, img }
   img = relativer Bildpfad  →  img/<dateiname>.png
   (Bilder werden später unter /quiz/wappen/img/ ergänzt)
═══════════════════════════════════════════════════════ */

const WAPPEN = [

  { stadt: "Potsdam",    bundesland: "Brandenburg",          region: "Ost", img: "img/1.svg" },
  { stadt: "Berlin",   bundesland: "Berlin",          region: "Ost", img: "img/2.webp" },
  { stadt: "Hamburg",   bundesland: "Hamburg",         region: "Nord", img: "img/3.webp" },
	{ stadt: "Teltow",   bundesland: "Brandenburg",         region: "Ost", img: "img/4.webp" },
	{ stadt: "Werder (Havel)",   bundesland: "Brandenburg",         region: "Ost", img: "img/5.webp" },
	{ stadt: "Beelitz",   bundesland: "Brandenburg",         region: "Ost", img: "img/6.png" },
	{ stadt: "Frankfurt (Oder)",   bundesland: "Brandenburg",         region: "Ost", img: "img/7.webp" },
	{ stadt: "Brandenburg",   bundesland: "Brandenburg",         region: "Ost", img: "img/8.webp" },
	{ stadt: "Falkensee",   bundesland: "Brandenburg",         region: "Ost", img: "img/9.webp" },
	{ stadt: "Nauen",   bundesland: "Brandenburg",         region: "Ost", img: "img/10.png" },
	{ stadt: "Königs Wusterhausen",   bundesland: "Brandenburg",         region: "Ost", img: "img/11.webp" },
	{ stadt: "Strausberg",   bundesland: "Brandenburg",         region: "Ost", img: "img/12.webp" },
	{ stadt: "Eberswalde",   bundesland: "Brandenburg",         region: "Ost", img: "img/13.webp" },
	{ stadt: "Bernau bei Berlin",   bundesland: "Brandenburg",         region: "Ost", img: "img/14.png" },
	{ stadt: "Oranienburg",   bundesland: "Brandenburg",         region: "Ost", img: "img/15.webp" },
	{ stadt: "Rathenow",   bundesland: "Brandenburg",         region: "Ost", img: "img/16.webp" },
	{ stadt: "Neuruppin",   bundesland: "Brandenburg",         region: "Ost", img: "img/17.png" },
	{ stadt: "Templin",   bundesland: "Brandenburg",         region: "Ost", img: "img/18.webp" },
	{ stadt: "Guben",   bundesland: "Brandenburg",         region: "Ost", img: "img/19.webp" },
	{ stadt: "Cottbus",   bundesland: "Brandenburg",         region: "Ost", img: "img/20.webp" },
	{ stadt: "Senftenberg",   bundesland: "Brandenburg",         region: "Ost", img: "img/21.png" },
	{ stadt: "Eisenhüttenstadt",   bundesland: "Brandenburg",         region: "Ost", img: "img/22.png" },
	{ stadt: "Spremberg",   bundesland: "Brandenburg",         region: "Ost", img: "img/23.png" },
	{ stadt: "Fürstenwalde",   bundesland: "Brandenburg",         region: "Ost", img: "img/24.png" },
	{ stadt: "Schwedt",   bundesland: "Brandenburg",         region: "Ost", img: "img/25.webp" },
	{ stadt: "Prenzlau",   bundesland: "Brandenburg",         region: "Ost", img: "img/26.webp" },
	{ stadt: "Wittstock/Dosse",   bundesland: "Brandenburg",         region: "Ost", img: "img/27.svg" },
	{ stadt: "Perleberg",   bundesland: "Brandenburg",         region: "Ost", img: "img/28.svg" },
	{ stadt: "Lübben",   bundesland: "Brandenburg",         region: "Ost", img: "img/29.png" },
	{ stadt: "Henningsdorf",   bundesland: "Brandenburg",         region: "Ost", img: "img/30.png" },
	{ stadt: "Zossen",   bundesland: "Brandenburg",         region: "Ost", img: "img/31.png" },
	{ stadt: "Trebbin",   bundesland: "Brandenburg",         region: "Ost", img: "img/32.svg" },
	{ stadt: "Schönefeld",   bundesland: "Brandenburg",         region: "Ost", img: "img/33.svg" },
	{ stadt: "Jüterbog",   bundesland: "Brandenburg",         region: "Ost", img: "img/34.png" },
	{ stadt: "Beeskow",   bundesland: "Brandenburg",         region: "Ost", img: "img/35.png" },
	{ stadt: "Angermünde",   bundesland: "Brandenburg",         region: "Ost", img: "img/36.png" },
	{ stadt: "Wustermark",   bundesland: "Brandenburg",         region: "Ost", img: "img/37.png" },
	{ stadt: "Hoyerswerda",   bundesland: "Sachsen",         region: "Ost", img: "img/38.png" },
	{ stadt: "Kamenz",   bundesland: "Sachsen",         region: "Ost", img: "img/39.svg" },
	{ stadt: "Bautzen",   bundesland: "Sachsen",         region: "Ost", img: "img/40.svg" },
	{ stadt: "Görlitz",   bundesland: "Sachsen",         region: "Ost", img: "img/41.svg" },
	{ stadt: "Zittau",   bundesland: "Sachsen",         region: "Ost", img: "img/42.svg" },
	{ stadt: "Pirna",   bundesland: "Sachsen",         region: "Ost", img: "img/43.png" },
	{ stadt: "Dresden",   bundesland: "Sachsen",         region: "Ost", img: "img/44.svg" },
	{ stadt: "Radebeul",   bundesland: "Sachsen",         region: "Ost", img: "img/45.svg" },
	{ stadt: "Freiberg",   bundesland: "Sachsen",         region: "Ost", img: "img/46.svg" },
	{ stadt: "Chemnitz",   bundesland: "Sachsen",         region: "Ost", img: "img/47.svg" },
	{ stadt: "Zwickau",   bundesland: "Sachsen",         region: "Ost", img: "img/48.svg" },
	{ stadt: "Annaberg-Buchholz",   bundesland: "Sachsen",         region: "Ost", img: "img/49.svg" },
	{ stadt: "Plauen",   bundesland: "Sachsen",         region: "Ost", img: "img/50.svg" },
	{ stadt: "Grimma",   bundesland: "Sachsen",         region: "Ost", img: "img/51.svg" },
	{ stadt: "Leipzig",   bundesland: "Sachsen",         region: "Ost", img: "img/52.svg" },
	{ stadt: "Halle",   bundesland: "Sachsen",         region: "Ost", img: "img/53.svg" },
	{ stadt: "Zeitz",   bundesland: "Sachsen-Anhalt",         region: "Ost", img: "img/54.png" },
	{ stadt: "Gera",   bundesland: "Thüringen",         region: "Ost", img: "img/55.svg" },
	{ stadt: "Dessau",   bundesland: "Sachsen-Anhalt",         region: "Ost", img: "img/56.svg" },
	{ stadt: "Köthen",   bundesland: "Sachsen-Anhalt",         region: "Ost", img: "img/57.svg" },
	{ stadt: "Bernburg",   bundesland: "Sachsen-Anhalt",         region: "Ost", img: "img/58.svg" },
	{ stadt: "Magdeburg",   bundesland: "Sachsen-Anhalt",         region: "Ost", img: "img/59.svg" },
	{ stadt: "Stendal",   bundesland: "Sachsen-Anhalt",         region: "Ost", img: "img/60.svg" },
	{ stadt: "Salzwedel",   bundesland: "Sachsen-Anhalt",         region: "Ost", img: "img/61.svg" },
	{ stadt: "Gardelegen",   bundesland: "Sachsen-Anhalt",         region: "Ost", img: "img/62.png" },
	{ stadt: "Eisleben",   bundesland: "Sachsen-Anhalt",         region: "Ost", img: "img/63.svg" },
	{ stadt: "Quedlinburg",   bundesland: "Sachsen-Anhalt",         region: "Ost", img: "img/64.svg" },
	{ stadt: "Wittenberg",   bundesland: "Sachsen-Anhalt",         region: "Ost", img: "img/65.svg" },
	{ stadt: "Wernigerode",   bundesland: "Sachsen-Anhalt",         region: "Ost", img: "img/66.svg" },
	{ stadt: "Pasewalk",   bundesland: "Mecklenburg-Vorpommern",         region: "Nord", img: "img/67.svg" },
	{ stadt: "Neustrelitz",   bundesland: "Mecklenburg-Vorpommern",         region: "Nord", img: "img/68.svg" },
	{ stadt: "Waren",   bundesland: "Mecklenburg-Vorpommern",         region: "Nord", img: "img/69.svg" },
	{ stadt: "Parchim",   bundesland: "Mecklenburg-Vorpommern",         region: "Nord", img: "img/70.svg" },
	{ stadt: "Neubrandenburg",   bundesland: "Mecklenburg-Vorpommern",         region: "Nord", img: "img/71.svg" },
	{ stadt: "Güstrow",   bundesland: "Mecklenburg-Vorpommern",         region: "Nord", img: "img/72.svg" },
	{ stadt: "Teterow",   bundesland: "Mecklenburg-Vorpommern",         region: "Nord", img: "img/73.png" },
	{ stadt: "Schwerin",   bundesland: "Mecklenburg-Vorpommern",         region: "Nord", img: "img/74.svg" },
	{ stadt: "Wismar",   bundesland: "Mecklenburg-Vorpommern",         region: "Nord", img: "img/75.svg" },
	{ stadt: "Kühlungsborn",   bundesland: "Mecklenburg-Vorpommern",         region: "Nord", img: "img/76.svg" },
	{ stadt: "Rostock",   bundesland: "Mecklenburg-Vorpommern",         region: "Nord", img: "img/77.svg" },
	{ stadt: "Stralsund",   bundesland: "Mecklenburg-Vorpommern",         region: "Nord", img: "img/78.svg" },
	{ stadt: "Zingst",   bundesland: "Mecklenburg-Vorpommern",         region: "Nord", img: "img/79.svg" },
	{ stadt: "Greifswald",   bundesland: "Mecklenburg-Vorpommern",         region: "Nord", img: "img/80.svg" },
	{ stadt: "Anklam",   bundesland: "Mecklenburg-Vorpommern",         region: "Nord", img: "img/81.svg" },
	{ stadt: "Ueckermünde",   bundesland: "Mecklenburg-Vorpommern",         region: "Nord", img: "img/82.svg" },
	{ stadt: "Heringsdorf",   bundesland: "Mecklenburg-Vorpommern",         region: "Nord", img: "img/83.svg" },
	{ stadt: "Lübeck",   bundesland: "Schleswig-Holstein",         region: "Nord", img: "img/84.svg" },
	{ stadt: "Ratzeburg",   bundesland: "Schleswig-Holstein",         region: "Nord", img: "img/85.svg" },
	{ stadt: "Plön",   bundesland: "Schleswig-Holstein",         region: "Nord", img: "img/86.svg" },
	{ stadt: "Kiel",   bundesland: "Schleswig-Holstein",         region: "Nord", img: "img/87.svg" },
	{ stadt: "Neumünster",   bundesland: "Schleswig-Holstein",         region: "Nord", img: "img/88.svg" },
	{ stadt: "Itzehoe",   bundesland: "Schleswig-Holstein",         region: "Nord", img: "img/89.svg" },
	{ stadt: "Elmshorn",   bundesland: "Schleswig-Holstein",         region: "Nord", img: "img/90.png" },
	{ stadt: "Flensburg",   bundesland: "Schleswig-Holstein",         region: "Nord", img: "img/91.svg" },
	{ stadt: "Niebüll",   bundesland: "Schleswig-Holstein",         region: "Nord", img: "img/92.svg" },
	{ stadt: "St. Peter Ording",   bundesland: "Schleswig-Holstein",         region: "Nord", img: "img/93.svg" },
	{ stadt: "Husum",   bundesland: "Schleswig-Holstein",         region: "Nord", img: "img/94.svg" },
	{ stadt: "Bad Segeberg",   bundesland: "Schleswig-Holstein",         region: "Nord", img: "img/95.svg" },
	{ stadt: "Wyk auf Föhr",   bundesland: "Schleswig-Holstein",         region: "Nord", img: "img/96.svg" },
	{ stadt: "Westerland",   bundesland: "Schleswig-Holstein",         region: "Nord", img: "img/97.png" },
	{ stadt: "Pinneberg",   bundesland: "Schleswig-Holstein",         region: "Nord", img: "img/98.svg" },
	{ stadt: "Meldorf",   bundesland: "Schleswig-Holstein",         region: "Nord", img: "img/99.svg" },
	{ stadt: "Uelzen",   bundesland: "Niedersachsen",         region: "Nord", img: "img/100.svg" },
	{ stadt: "Celle",   bundesland: "Niedersachsen",         region: "Nord", img: "img/101.svg" },
	{ stadt: "Gifhorn",   bundesland: "Niedersachsen",         region: "Nord", img: "img/102.svg" },
	{ stadt: "Helmstedt",   bundesland: "Niedersachsen",         region: "Nord", img: "img/103.png" },
	{ stadt: "Peine",   bundesland: "Niedersachsen",         region: "Nord", img: "img/104.png" },
	{ stadt: "Göttingen",   bundesland: "Niedersachsen",         region: "Nord", img: "img/105.svg" },
	{ stadt: "Salzgitter",   bundesland: "Niedersachsen",         region: "Nord", img: "img/106.svg" },
	{ stadt: "Braunschweig",   bundesland: "Niedersachsen",         region: "Nord", img: "img/107.svg" },
	{ stadt: "Hildesheim",   bundesland: "Niedersachsen",         region: "Nord", img: "img/108.svg" },
	{ stadt: "Hameln",   bundesland: "Niedersachsen",         region: "Nord", img: "img/109.svg" },
	{ stadt: "Langenhagen",   bundesland: "Niedersachsen",         region: "Nord", img: "img/110.svg" },
	{ stadt: "Hannover",   bundesland: "Niedersachsen",         region: "Nord", img: "img/111.svg" },
	{ stadt: "Nienburg",   bundesland: "Niedersachsen",         region: "Nord", img: "img/112.svg" },
	{ stadt: "Sulingen",   bundesland: "Niedersachsen",         region: "Nord", img: "img/113.svg" },
	{ stadt: "Stadthagen",   bundesland: "Niedersachsen",         region: "Nord", img: "img/114.svg" },
	{ stadt: "Diepholz",   bundesland: "Niedersachsen",         region: "Nord", img: "img/115.svg" },
	{ stadt: "Vechta",   bundesland: "Niedersachsen",         region: "Nord", img: "img/116.svg" },
	{ stadt: "Osnabrück",   bundesland: "Niedersachsen",         region: "Nord", img: "img/117.svg" },
	{ stadt: "Melle",   bundesland: "Niedersachsen",         region: "Nord", img: "img/118.svg" },
	{ stadt: "Quakenbrück",   bundesland: "Niedersachsen",         region: "Nord", img: "img/119.svg" },
	{ stadt: "Cloppenburg",   bundesland: "Niedersachsen",         region: "Nord", img: "img/120.svg" },
	{ stadt: "Oldenburg",   bundesland: "Niedersachsen",         region: "Nord", img: "img/121.svg" },
	{ stadt: "Delmenhorst",   bundesland: "Niedersachsen",         region: "Nord", img: "img/122.svg" },
	{ stadt: "Soltau",   bundesland: "Niedersachsen",         region: "Nord", img: "img/123.svg" },
	{ stadt: "Buxtehude",   bundesland: "Niedersachsen",         region: "Nord", img: "img/124.svg" },
	{ stadt: "Stade",   bundesland: "Niedersachsen",         region: "Nord", img: "img/125.svg" },
	{ stadt: "Cuxhaven",   bundesland: "Niedersachsen",         region: "Nord", img: "img/126.svg" },
	{ stadt: "Papenburg",   bundesland: "Niedersachsen",         region: "Nord", img: "img/127.svg" },
	{ stadt: "Emden",   bundesland: "Niedersachsen",         region: "Nord", img: "img/128.svg" },
	{ stadt: "Aurich",   bundesland: "Niedersachsen",         region: "Nord", img: "img/129.svg" },
	{ stadt: "Nordhorn",   bundesland: "Niedersachsen",         region: "Nord", img: "img/130.svg" },
	{ stadt: "Wilhelmshaven",   bundesland: "Niedersachsen",         region: "Nord", img: "img/131.svg" },
	{ stadt: "Lingen",   bundesland: "Niedersachsen",         region: "Nord", img: "img/132.png" },
	{ stadt: "Norden",   bundesland: "Niedersachsen",         region: "Nord", img: "img/133.svg" },
	{ stadt: "Garbsen",   bundesland: "Niedersachsen",         region: "Nord", img: "img/134.svg" },
	{ stadt: "Bremen",   bundesland: "Bremen",         region: "Nord", img: "img/135.svg" },
	{ stadt: "Poitiers",   bundesland: "Vienne",         region: "Nord", img: "img/136.svg" },
	{ stadt: "Paris",   bundesland: "Paris",         region: "Nord", img: "img/137.svg" },
	{ stadt: "Minden",   bundesland: "Nordrhein-Westfalen",         region: "West", img: "img/138.svg" },
	{ stadt: "Lemgo",   bundesland: "Nordrhein-Westfalen",         region: "West", img: "img/139.svg" },
	{ stadt: "Detmold",   bundesland: "Nordrhein-Westfalen",         region: "West", img: "img/140.svg" },
	{ stadt: "Paderborn",   bundesland: "Nordrhein-Westfalen",         region: "West", img: "img/141.svg" },
	{ stadt: "Bielefeld",   bundesland: "Nordrhein-Westfalen",         region: "West", img: "img/142.svg" },
	{ stadt: "Herford",   bundesland: "Nordrhein-Westfalen",         region: "West", img: "img/143.svg" },
	{ stadt: "Gütersloh",   bundesland: "Nordrhein-Westfalen",         region: "West", img: "img/144.svg" },
	{ stadt: "Münster",   bundesland: "Nordrhein-Westfalen",         region: "West", img: "img/145.svg" },

	
	

	



];