/* ═══════════════════════════════════════════════════════════════
   CAPITALS DATA — all recognized countries (196 total)
   category: "europe" | "asia" | "africa" | "americas" | "oceania"
═══════════════════════════════════════════════════════════════ */
const quizCapitals = [
  // ── EUROPE ──
  { country: "Germany",             capital: "Berlin",           category: "europe" },
  { country: "France",              capital: "Paris",            category: "europe" },
  { country: "Spain",               capital: "Madrid",           category: "europe" },
  { country: "Italy",               capital: "Rome",             category: "europe" },
  { country: "Portugal",            capital: "Lisbon",           category: "europe" },
  { country: "Netherlands",         capital: "Amsterdam",        category: "europe" },
  { country: "Belgium",             capital: "Brussels",         category: "europe" },
  { country: "Luxembourg",          capital: "Luxembourg",       category: "europe" },
  { country: "Switzerland",         capital: "Bern",             category: "europe" },
  { country: "Austria",             capital: "Vienna",           category: "europe" },
  { country: "Poland",              capital: "Warsaw",           category: "europe" },
  { country: "Czech Republic",      capital: "Prague",           category: "europe" },
  { country: "Slovakia",            capital: "Bratislava",       category: "europe" },
  { country: "Hungary",             capital: "Budapest",         category: "europe" },
  { country: "Slovenia",            capital: "Ljubljana",        category: "europe" },
  { country: "Croatia",             capital: "Zagreb",           category: "europe" },
  { country: "Bosnia and Herzegovina", capital: "Sarajevo",      category: "europe" },
  { country: "Serbia",              capital: "Belgrade",         category: "europe" },
  { country: "Montenegro",          capital: "Podgorica",        category: "europe" },
  { country: "North Macedonia",     capital: "Skopje",           category: "europe" },
  { country: "Albania",             capital: "Tirana",           category: "europe" },
  { country: "Kosovo",              capital: "Pristina",         category: "europe" },
  { country: "Greece",              capital: "Athens",           category: "europe" },
  { country: "Bulgaria",            capital: "Sofia",            category: "europe" },
  { country: "Romania",             capital: "Bucharest",        category: "europe" },
  { country: "Moldova",             capital: "Chișinău",         category: "europe" },
  { country: "Ukraine",             capital: "Kyiv",             category: "europe" },
  { country: "Belarus",             capital: "Minsk",            category: "europe" },
  { country: "Lithuania",           capital: "Vilnius",          category: "europe" },
  { country: "Latvia",              capital: "Riga",             category: "europe" },
  { country: "Estonia",             capital: "Tallinn",          category: "europe" },
  { country: "Finland",             capital: "Helsinki",         category: "europe" },
  { country: "Sweden",              capital: "Stockholm",        category: "europe" },
  { country: "Norway",              capital: "Oslo",             category: "europe" },
  { country: "Denmark",             capital: "Copenhagen",       category: "europe" },
  { country: "Iceland",             capital: "Reykjavik",        category: "europe" },
  { country: "Ireland",             capital: "Dublin",           category: "europe" },
  { country: "United Kingdom",      capital: "London",           category: "europe" },
  { country: "Russia",              capital: "Moscow",           category: "europe" },
  { country: "Vatican City",        capital: "Vatican City",     category: "europe" },
  { country: "San Marino",          capital: "San Marino",       category: "europe" },
  { country: "Monaco",              capital: "Monaco",           category: "europe" },
  { country: "Andorra",             capital: "Andorra la Vella", category: "europe" },
  { country: "Liechtenstein",       capital: "Vaduz",            category: "europe" },
  { country: "Malta",               capital: "Valletta",         category: "europe" },
  { country: "Cyprus",              capital: "Nicosia",          category: "europe" },

  // ── ASIA ──
  { country: "China",               capital: "Beijing",          category: "asia" },
  { country: "Japan",               capital: "Tokyo",            category: "asia" },
  { country: "South Korea",         capital: "Seoul",            category: "asia" },
  { country: "North Korea",         capital: "Pyongyang",        category: "asia" },
  { country: "Taiwan",              capital: "Taipei",           category: "asia" },
  { country: "Mongolia",            capital: "Ulaanbaatar",      category: "asia" },
  { country: "Vietnam",             capital: "Hanoi",            category: "asia" },
  { country: "Thailand",            capital: "Bangkok",          category: "asia" },
  { country: "Myanmar",             capital: "Naypyidaw",        category: "asia" },
  { country: "Cambodia",            capital: "Phnom Penh",       category: "asia" },
  { country: "Laos",                capital: "Vientiane",        category: "asia" },
  { country: "Malaysia",            capital: "Kuala Lumpur",     category: "asia" },
  { country: "Singapore",           capital: "Singapore",        category: "asia" },
  { country: "Indonesia",           capital: "Jakarta",          category: "asia" },
  { country: "Philippines",         capital: "Manila",           category: "asia" },
  { country: "Brunei",              capital: "Bandar Seri Begawan", category: "asia" },
  { country: "Timor-Leste",         capital: "Dili",             category: "asia" },
  { country: "India",               capital: "New Delhi",        category: "asia" },
  { country: "Pakistan",            capital: "Islamabad",        category: "asia" },
  { country: "Bangladesh",          capital: "Dhaka",            category: "asia" },
  { country: "Sri Lanka",           capital: "Sri Jayawardenepura Kotte", category: "asia" },
  { country: "Nepal",               capital: "Kathmandu",        category: "asia" },
  { country: "Bhutan",              capital: "Thimphu",          category: "asia" },
  { country: "Maldives",            capital: "Malé",             category: "asia" },
  { country: "Afghanistan",         capital: "Kabul",            category: "asia" },
  { country: "Iran",                capital: "Tehran",           category: "asia" },
  { country: "Iraq",                capital: "Baghdad",          category: "asia" },
  { country: "Syria",               capital: "Damascus",         category: "asia" },
  { country: "Lebanon",             capital: "Beirut",           category: "asia" },
  { country: "Israel",              capital: "Jerusalem",        category: "asia" },
  { country: "Jordan",              capital: "Amman",            category: "asia" },
  { country: "Saudi Arabia",        capital: "Riyadh",           category: "asia" },
  { country: "Yemen",               capital: "Sana'a",           category: "asia" },
  { country: "Oman",                capital: "Muscat",           category: "asia" },
  { country: "United Arab Emirates", capital: "Abu Dhabi",       category: "asia" },
  { country: "Qatar",               capital: "Doha",             category: "asia" },
  { country: "Bahrain",             capital: "Manama",           category: "asia" },
  { country: "Kuwait",              capital: "Kuwait City",      category: "asia" },
  { country: "Turkey",              capital: "Ankara",           category: "asia" },
  { country: "Georgia",             capital: "Tbilisi",          category: "asia" },
  { country: "Armenia",             capital: "Yerevan",          category: "asia" },
  { country: "Azerbaijan",          capital: "Baku",             category: "asia" },
  { country: "Kazakhstan",          capital: "Astana",           category: "asia" },
  { country: "Uzbekistan",          capital: "Tashkent",         category: "asia" },
  { country: "Turkmenistan",        capital: "Ashgabat",         category: "asia" },
  { country: "Tajikistan",          capital: "Dushanbe",         category: "asia" },
  { country: "Kyrgyzstan",          capital: "Bishkek",          category: "asia" },

  // ── AFRICA ──
  { country: "Egypt",               capital: "Cairo",            category: "africa" },
  { country: "Libya",               capital: "Tripoli",          category: "africa" },
  { country: "Tunisia",             capital: "Tunis",            category: "africa" },
  { country: "Algeria",             capital: "Algiers",          category: "africa" },
  { country: "Morocco",             capital: "Rabat",            category: "africa" },
  { country: "Mauritania",          capital: "Nouakchott",       category: "africa" },
  { country: "Mali",                capital: "Bamako",           category: "africa" },
  { country: "Niger",               capital: "Niamey",           category: "africa" },
  { country: "Chad",                capital: "N'Djamena",        category: "africa" },
  { country: "Sudan",               capital: "Khartoum",         category: "africa" },
  { country: "South Sudan",         capital: "Juba",             category: "africa" },
  { country: "Eritrea",             capital: "Asmara",           category: "africa" },
  { country: "Ethiopia",            capital: "Addis Ababa",      category: "africa" },
  { country: "Djibouti",            capital: "Djibouti",         category: "africa" },
  { country: "Somalia",             capital: "Mogadishu",        category: "africa" },
  { country: "Kenya",               capital: "Nairobi",          category: "africa" },
  { country: "Uganda",              capital: "Kampala",          category: "africa" },
  { country: "Tanzania",            capital: "Dodoma",           category: "africa" },
  { country: "Rwanda",              capital: "Kigali",           category: "africa" },
  { country: "Burundi",             capital: "Gitega",           category: "africa" },
  { country: "DR Congo",            capital: "Kinshasa",         category: "africa" },
  { country: "Republic of Congo",   capital: "Brazzaville",      category: "africa" },
  { country: "Central African Republic", capital: "Bangui",      category: "africa" },
  { country: "Cameroon",            capital: "Yaoundé",          category: "africa" },
  { country: "Nigeria",             capital: "Abuja",            category: "africa" },
  { country: "Benin",               capital: "Porto-Novo",       category: "africa" },
  { country: "Togo",                capital: "Lomé",             category: "africa" },
  { country: "Ghana",               capital: "Accra",            category: "africa" },
  { country: "Ivory Coast",         capital: "Yamoussoukro",     category: "africa" },
  { country: "Liberia",             capital: "Monrovia",         category: "africa" },
  { country: "Sierra Leone",        capital: "Freetown",         category: "africa" },
  { country: "Guinea",              capital: "Conakry",          category: "africa" },
  { country: "Guinea-Bissau",       capital: "Bissau",           category: "africa" },
  { country: "Gambia",              capital: "Banjul",           category: "africa" },
  { country: "Senegal",             capital: "Dakar",            category: "africa" },
  { country: "Burkina Faso",        capital: "Ouagadougou",      category: "africa" },
  { country: "Equatorial Guinea",   capital: "Malabo",           category: "africa" },
  { country: "Gabon",               capital: "Libreville",       category: "africa" },
  { country: "São Tomé and Príncipe", capital: "São Tomé",       category: "africa" },
  { country: "Angola",              capital: "Luanda",           category: "africa" },
  { country: "Zambia",              capital: "Lusaka",           category: "africa" },
  { country: "Malawi",              capital: "Lilongwe",         category: "africa" },
  { country: "Mozambique",          capital: "Maputo",           category: "africa" },
  { country: "Zimbabwe",            capital: "Harare",           category: "africa" },
  { country: "Botswana",            capital: "Gaborone",         category: "africa" },
  { country: "Namibia",             capital: "Windhoek",         category: "africa" },
  { country: "South Africa",        capital: "Pretoria",         category: "africa" },
  { country: "Lesotho",             capital: "Maseru",           category: "africa" },
  { country: "Eswatini",            capital: "Mbabane",          category: "africa" },
  { country: "Madagascar",          capital: "Antananarivo",     category: "africa" },
  { country: "Comoros",             capital: "Moroni",           category: "africa" },
  { country: "Mauritius",           capital: "Port Louis",       category: "africa" },
  { country: "Seychelles",          capital: "Victoria",         category: "africa" },
  { country: "Cape Verde",          capital: "Praia",            category: "africa" },

  // ── AMERICAS ──
  { country: "United States",       capital: "Washington, D.C.", category: "americas" },
  { country: "Canada",              capital: "Ottawa",           category: "americas" },
  { country: "Mexico",              capital: "Mexico City",      category: "americas" },
  { country: "Guatemala",           capital: "Guatemala City",   category: "americas" },
  { country: "Belize",              capital: "Belmopan",         category: "americas" },
  { country: "Honduras",            capital: "Tegucigalpa",      category: "americas" },
  { country: "El Salvador",         capital: "San Salvador",     category: "americas" },
  { country: "Nicaragua",           capital: "Managua",          category: "americas" },
  { country: "Costa Rica",          capital: "San José",         category: "americas" },
  { country: "Panama",              capital: "Panama City",      category: "americas" },
  { country: "Cuba",                capital: "Havana",           category: "americas" },
  { country: "Jamaica",             capital: "Kingston",         category: "americas" },
  { country: "Haiti",               capital: "Port-au-Prince",   category: "americas" },
  { country: "Dominican Republic",  capital: "Santo Domingo",    category: "americas" },
  { country: "Trinidad and Tobago", capital: "Port of Spain",    category: "americas" },
  { country: "Barbados",            capital: "Bridgetown",       category: "americas" },
  { country: "Grenada",             capital: "St. George's",     category: "americas" },
  { country: "Saint Lucia",         capital: "Castries",         category: "americas" },
  { country: "Saint Vincent and the Grenadines", capital: "Kingstown", category: "americas" },
  { country: "Antigua and Barbuda", capital: "St. John's",       category: "americas" },
  { country: "Dominica",            capital: "Roseau",           category: "americas" },
  { country: "Saint Kitts and Nevis", capital: "Basseterre",     category: "americas" },
  { country: "Bahamas",             capital: "Nassau",           category: "americas" },
  { country: "Colombia",            capital: "Bogotá",           category: "americas" },
  { country: "Venezuela",           capital: "Caracas",          category: "americas" },
  { country: "Guyana",              capital: "Georgetown",       category: "americas" },
  { country: "Suriname",            capital: "Paramaribo",       category: "americas" },
  { country: "Brazil",              capital: "Brasília",         category: "americas" },
  { country: "Ecuador",             capital: "Quito",            category: "americas" },
  { country: "Peru",                capital: "Lima",             category: "americas" },
  { country: "Bolivia",             capital: "Sucre",            category: "americas" },
  { country: "Chile",               capital: "Santiago",         category: "americas" },
  { country: "Argentina",           capital: "Buenos Aires",     category: "americas" },
  { country: "Uruguay",             capital: "Montevideo",       category: "americas" },
  { country: "Paraguay",            capital: "Asunción",         category: "americas" },

  // ── OCEANIA ──
  { country: "Australia",           capital: "Canberra",         category: "oceania" },
  { country: "New Zealand",         capital: "Wellington",       category: "oceania" },
  { country: "Papua New Guinea",    capital: "Port Moresby",     category: "oceania" },
  { country: "Fiji",                capital: "Suva",             category: "oceania" },
  { country: "Solomon Islands",     capital: "Honiara",          category: "oceania" },
  { country: "Vanuatu",             capital: "Port Vila",        category: "oceania" },
  { country: "Samoa",               capital: "Apia",             category: "oceania" },
  { country: "Tonga",               capital: "Nukuʻalofa",       category: "oceania" },
  { country: "Kiribati",            capital: "South Tarawa",     category: "oceania" },
  { country: "Micronesia",          capital: "Palikir",          category: "oceania" },
  { country: "Marshall Islands",    capital: "Majuro",           category: "oceania" },
  { country: "Palau",               capital: "Ngerulmud",        category: "oceania" },
  { country: "Nauru",               capital: "Yaren",            category: "oceania" },
  { country: "Tuvalu",              capital: "Funafuti",         category: "oceania" },
];