/* ═══════════════════════════════════════════════════════════════
   BRANDS DATA
   Images at /quiz/brands/brands-img/<filename>
   category: "cars" | "tech" | "luxury" | "food" | "fashion" | "sports"
═══════════════════════════════════════════════════════════════ */
const quizBrands = [

    // ── CARS ──
    { name: "Ferrari",       category: "cars",    img: "/quiz/brands/brands-img/ferrari.svg" },
    { name: "Lamborghini",   category: "cars",    img: "/quiz/brands/brands-img/lamborghini.svg" },
    { name: "Porsche",       category: "cars",    img: "/quiz/brands/brands-img/porsche.svg" },
    { name: "BMW",           category: "cars",    img: "/quiz/brands/brands-img/bmw.png" },
    { name: "Mercedes",      category: "cars",    img: "/quiz/brands/brands-img/mercedes.svg" },
    { name: "Audi",          category: "cars",    img: "/quiz/brands/brands-img/audi.svg" },
    { name: "Volkswagen",    category: "cars",    img: "/quiz/brands/brands-img/volkswagen.svg" },
    { name: "Toyota",        category: "cars",    img: "/quiz/brands/brands-img/toyota.svg" },
    { name: "Honda",         category: "cars",    img: "/quiz/brands/brands-img/honda.svg" },
    { name: "Ford",          category: "cars",    img: "/quiz/brands/brands-img/ford.svg" },
    { name: "Chevrolet",     category: "cars",    img: "/quiz/brands/brands-img/chevrolet.svg" },
    { name: "Tesla",         category: "cars",    img: "/quiz/brands/brands-img/tesla.png" },
    { name: "Bugatti",       category: "cars",    img: "/quiz/brands/brands-img/bugatti.svg" },
    { name: "Maserati",      category: "cars",    img: "/quiz/brands/brands-img/maserati.png" },
    { name: "Alfa Romeo",    category: "cars",    img: "/quiz/brands/brands-img/alfa-romeo.png" },
    { name: "Jaguar",        category: "cars",    img: "/quiz/brands/brands-img/jaguar.png" },
    { name: "Land Rover",    category: "cars",    img: "/quiz/brands/brands-img/land-rover.webp" },
    { name: "Rolls-Royce",   category: "cars",    img: "/quiz/brands/brands-img/rolls-royce.png" },
    { name: "Bentley",       category: "cars",    img: "/quiz/brands/brands-img/bentley.png" },
    { name: "Aston Martin",  category: "cars",    img: "/quiz/brands/brands-img/aston-martin.jpeg" },
    { name: "McLaren",       category: "cars",    img: "/quiz/brands/brands-img/mclaren.svg" },
    { name: "Subaru",        category: "cars",    img: "/quiz/brands/brands-img/subaru.svg" },
    { name: "Nissan",        category: "cars",    img: "/quiz/brands/brands-img/nissan.svg" },
    { name: "Mazda",         category: "cars",    img: "/quiz/brands/brands-img/mazda.jpeg" },
    { name: "Hyundai",       category: "cars",    img: "/quiz/brands/brands-img/hyundai.svg" },
    { name: "Kia",           category: "cars",    img: "/quiz/brands/brands-img/kia.avif" },
    { name: "Volvo",         category: "cars",    img: "/quiz/brands/brands-img/volvo.svg" },
    { name: "Peugeot",       category: "cars",    img: "/quiz/brands/brands-img/peugeot.webp" },
    { name: "Renault",       category: "cars",    img: "/quiz/brands/brands-img/renault.png" },
    { name: "Citroën",       category: "cars",    img: "/quiz/brands/brands-img/citroen.png" },
    { name: "Fiat",          category: "cars",    img: "/quiz/brands/brands-img/fiat.svg" },
    { name: "Jeep",          category: "cars",    img: "/quiz/brands/brands-img/jeep.jpg" },
    { name: "Dodge",         category: "cars",    img: "/quiz/brands/brands-img/dodge.jpg" },
    { name: "Cadillac",      category: "cars",    img: "/quiz/brands/brands-img/cadillac.webp" },
    { name: "Lexus",         category: "cars",    img: "/quiz/brands/brands-img/lexus.jpg" },
    { name: "Infiniti",      category: "cars",    img: "/quiz/brands/brands-img/infiniti.jpg" },
    { name: "Acura",         category: "cars",    img: "/quiz/brands/brands-img/acura.jpg" },
    { name: "Mitsubishi",    category: "cars",    img: "/quiz/brands/brands-img/mitsubishi.jpeg" },
    { name: "Seat",          category: "cars",    img: "/quiz/brands/brands-img/seat.png" },
    { name: "Skoda",         category: "cars",    img: "/quiz/brands/brands-img/skoda.png" },
    { name: "Opel",          category: "cars",    img: "/quiz/brands/brands-img/opel.png" },
    { name: "Mini",          category: "cars",    img: "/quiz/brands/brands-img/mini.svg" },

    // ── TECH ──
    { name: "Apple",         category: "tech",    img: "/quiz/brands/brands-img/apple.png" },
    { name: "Google",        category: "tech",    img: "/quiz/brands/brands-img/google.png" },
    { name: "Microsoft",     category: "tech",    img: "/quiz/brands/brands-img/microsoft.webp" },
    { name: "Samsung",       category: "tech",    img: "/quiz/brands/brands-img/samsung.png" },
    { name: "Intel",         category: "tech",    img: "/quiz/brands/brands-img/intel.svg" },
    { name: "Nvidia",        category: "tech",    img: "/quiz/brands/brands-img/nvidia.svg" },
    { name: "Amazon",        category: "tech",    img: "/quiz/brands/brands-img/amazon.png" },
    { name: "Meta",          category: "tech",    img: "/quiz/brands/brands-img/meta.webp" },
    { name: "X",             category: "tech",    img: "/quiz/brands/brands-img/x.png" },
    { name: "Spotify",       category: "tech",    img: "/quiz/brands/brands-img/spotify.png" },
    { name: "Netflix",       category: "tech",    img: "/quiz/brands/brands-img/netflix.png" },
    { name: "YouTube",       category: "tech",    img: "/quiz/brands/brands-img/youtube.png" },
    { name: "Adobe",         category: "tech",    img: "/quiz/brands/brands-img/adobe.png" },
    { name: "Huawei",        category: "tech",    img: "/quiz/brands/brands-img/huawei.png" },
    { name: "Sony",          category: "tech",    img: "/quiz/brands/brands-img/sony.svg" },
    { name: "LG",            category: "tech",    img: "/quiz/brands/brands-img/lg.png" },
    { name: "Dell",          category: "tech",    img: "/quiz/brands/brands-img/dell.png" },
    { name: "HP",            category: "tech",    img: "/quiz/brands/brands-img/hp.png" },
    { name: "Lenovo",        category: "tech",    img: "/quiz/brands/brands-img/lenovo.webp" },
    { name: "Asus",          category: "tech",    img: "/quiz/brands/brands-img/asus.png" },
    { name: "Xiaomi",        category: "tech",    img: "/quiz/brands/brands-img/xiaomi.png" },
    { name: "PayPal",        category: "tech",    img: "/quiz/brands/brands-img/paypal.png" },
    { name: "Snapchat",      category: "tech",    img: "/quiz/brands/brands-img/snapchat.svg" },
    { name: "TikTok",        category: "tech",    img: "/quiz/brands/brands-img/tiktok.png" },
    { name: "Discord",       category: "tech",    img: "/quiz/brands/brands-img/discord.png" },
    { name: "Twitch",        category: "tech",    img: "/quiz/brands/brands-img/twitch.png" },
    { name: "Airbnb",        category: "tech",    img: "/quiz/brands/brands-img/airbnb.png" },
    { name: "Uber",          category: "tech",    img: "/quiz/brands/brands-img/uber.png" },
		{ name: "Rtx",          category: "tech",    img: "/quiz/brands/brands-img/rtx.png" },
		{ name: "Rheinmetall",          category: "tech",    img: "/quiz/brands/brands-img/rheinmetall.png" },
		{ name: "Palantir",          category: "tech",    img: "/quiz/brands/brands-img/palantir.png" },
		{ name: "AMD",          category: "tech",    img: "/quiz/brands/brands-img/amd.svg" },
		{ name: "Shell",          category: "tech",    img: "/quiz/brands/brands-img/shell.svg" },
		{ name: "Mastercard",          category: "tech",    img: "/quiz/brands/brands-img/mastercard.svg" },
		{ name: "Eli Lilly",          category: "tech",    img: "/quiz/brands/brands-img/eli-lilly.svg" },
		{ name: "Lockheed Martin",          category: "tech",    img: "/quiz/brands/brands-img/lockheed-martin.svg" },
		{ name: "Walmart",          category: "tech",    img: "/quiz/brands/brands-img/walmart.svg" },
		{ name: "Nasdaq",          category: "tech",    img: "/quiz/brands/brands-img/nasdaq.svg" },
		{ name: "American Express",          category: "tech",    img: "/quiz/brands/brands-img/amex.svg" },
		{ name: "Nestle",          category: "tech",    img: "/quiz/brands/brands-img/nestle.svg" },
		{ name: "Zalando",          category: "tech",    img: "/quiz/brands/brands-img/zalando.svg" },
		{ name: "Target",          category: "tech",    img: "/quiz/brands/brands-img/target.svg" },
		{ name: "BYD",          category: "tech",    img: "/quiz/brands/brands-img/byd.svg" },
		{ name: "Klarna",          category: "tech",    img: "/quiz/brands/brands-img/klarna.svg" },
		{ name: "UBS",          category: "tech",    img: "/quiz/brands/brands-img/ubs.svg" },
		


    // ── LUXURY ──
    { name: "Louis Vuitton", category: "luxury",  img: "/quiz/brands/brands-img/louis-vuitton.png" },
    { name: "Gucci",         category: "luxury",  img: "/quiz/brands/brands-img/gucci.png" },
    { name: "Chanel",        category: "luxury",  img: "/quiz/brands/brands-img/chanel.webp" },
    { name: "Hermès",        category: "luxury",  img: "/quiz/brands/brands-img/hermes.png" },
    { name: "Prada",         category: "luxury",  img: "/quiz/brands/brands-img/prada.png" },
    { name: "Versace",       category: "luxury",  img: "/quiz/brands/brands-img/versace.png" },
    { name: "Dior",          category: "luxury",  img: "/quiz/brands/brands-img/dior.png" },
    { name: "Balenciaga",    category: "luxury",  img: "/quiz/brands/brands-img/balenciaga.png" },
    { name: "Burberry",      category: "luxury",  img: "/quiz/brands/brands-img/burberry.png" },
    { name: "Rolex",         category: "luxury",  img: "/quiz/brands/brands-img/rolex.png" },
    { name: "Cartier",       category: "luxury",  img: "/quiz/brands/brands-img/cartier.png" },
    { name: "Tiffany",       category: "luxury",  img: "/quiz/brands/brands-img/tiffany.png" },
    { name: "Fendi",         category: "luxury",  img: "/quiz/brands/brands-img/fendi.png" },
    { name: "Givenchy",      category: "luxury",  img: "/quiz/brands/brands-img/givenchy.png" },
    { name: "Valentino",     category: "luxury",  img: "/quiz/brands/brands-img/valentino.png" },
    { name: "YSL",           category: "luxury",  img: "/quiz/brands/brands-img/ysl.png" },
    { name: "Bottega Veneta",category: "luxury",  img: "/quiz/brands/brands-img/bottega-veneta.png" },
    { name: "Omega",         category: "luxury",  img: "/quiz/brands/brands-img/omega.webp" },
    { name: "Tag Heuer",     category: "luxury",  img: "/quiz/brands/brands-img/tag-heuer.png" },
    { name: "Patek Philippe",category: "luxury",  img: "/quiz/brands/brands-img/patek-philippe.png" },
		{ name: "Maison Margiela",category: "luxury",  img: "/quiz/brands/brands-img/maison-margiela.png" },
		{ name: "Moncler",       category: "luxury",  img: "/quiz/brands/brands-img/moncler.png" },
		{ name: "Ralph Lauren",category: "luxury",  img: "/quiz/brands/brands-img/ralph-lauren.png" },

    // ── FOOD & DRINK ──
    { name: "McDonald's",    category: "food",    img: "/quiz/brands/brands-img/mcdonalds.png" },
    { name: "Coca-Cola",     category: "food",    img: "/quiz/brands/brands-img/coca-cola.webp" },
    { name: "Pepsi",         category: "food",    img: "/quiz/brands/brands-img/pepsi.png" },
    { name: "Starbucks",     category: "food",    img: "/quiz/brands/brands-img/starbucks.png" },
    { name: "KFC",           category: "food",    img: "/quiz/brands/brands-img/kfc.png" },
    { name: "Burger King",   category: "food",    img: "/quiz/brands/brands-img/burger-king.png" },
    { name: "Subway",        category: "food",    img: "/quiz/brands/brands-img/subway.png" },
    { name: "Pizza Hut",     category: "food",    img: "/quiz/brands/brands-img/pizza-hut.png" },
    { name: "Domino's",      category: "food",    img: "/quiz/brands/brands-img/dominos.png" },
    { name: "Red Bull",      category: "food",    img: "/quiz/brands/brands-img/red-bull.png" },
    { name: "Heineken",      category: "food",    img: "/quiz/brands/brands-img/heineken.png" },
    { name: "Nescafé",       category: "food",    img: "/quiz/brands/brands-img/nescafe.png" },
    { name: "Nutella",       category: "food",    img: "/quiz/brands/brands-img/nutella.png" },
    { name: "Oreo",          category: "food",    img: "/quiz/brands/brands-img/oreo.png" },
    { name: "Pringles",      category: "food",    img: "/quiz/brands/brands-img/pringles.png" },
    { name: "Lay's",         category: "food",    img: "/quiz/brands/brands-img/lays.png" },
    { name: "Nespresso",     category: "food",    img: "/quiz/brands/brands-img/nespresso.png" },
    { name: "Ferrero",       category: "food",    img: "/quiz/brands/brands-img/ferrero.svg" },
    { name: "Milka",         category: "food",    img: "/quiz/brands/brands-img/milka.png" },
    { name: "Toblerone",     category: "food",    img: "/quiz/brands/brands-img/toblerone.png" },

    // ── FASHION & SPORTS ──
    { name: "Nike",          category: "sports",  img: "/quiz/brands/brands-img/nike.webp" },
    { name: "Adidas",        category: "sports",  img: "/quiz/brands/brands-img/adidas.webp" },
    { name: "Puma",          category: "sports",  img: "/quiz/brands/brands-img/puma.png" },
    { name: "Under Armour",  category: "sports",  img: "/quiz/brands/brands-img/under-armour.png" },
    { name: "New Balance",   category: "sports",  img: "/quiz/brands/brands-img/new-balance.svg" },
    { name: "Reebok",        category: "sports",  img: "/quiz/brands/brands-img/reebok.svg" },
    { name: "Converse",      category: "sports",  img: "/quiz/brands/brands-img/converse.svg" },
    { name: "Vans",          category: "sports",  img: "/quiz/brands/brands-img/vans.svg" },
    { name: "The North Face",category: "sports",  img: "/quiz/brands/brands-img/the-north-face.svg" },
    { name: "Patagonia",     category: "sports",  img: "/quiz/brands/brands-img/patagonia.svg" },
    { name: "Columbia",      category: "sports",  img: "/quiz/brands/brands-img/columbia.svg" },
    { name: "Asics",         category: "sports",  img: "/quiz/brands/brands-img/asics.svg" },
    { name: "Salomon",       category: "sports",  img: "/quiz/brands/brands-img/salomon.svg" },
    { name: "Oakley",        category: "sports",  img: "/quiz/brands/brands-img/oakley.svg" },
    { name: "Tommy Hilfiger",category: "sports",  img: "/quiz/brands/brands-img/tommy-hilfiger.svg" },
    { name: "Calvin Klein",  category: "sports",  img: "/quiz/brands/brands-img/calvin-klein.svg" },
    { name: "H&M",           category: "sports",  img: "/quiz/brands/brands-img/hm.svg" },
    { name: "Zara",          category: "sports",  img: "/quiz/brands/brands-img/zara.svg" },
];