// Deutsche Anzeigenamen der irischen Countys im Kennzeichen-Quiz.
// Key = "code"-Feld aus ireland-counties.geojson (Kennzeichen-Kuerzel), Value = deutscher Name.
const countyNamesDE = {
  "C": "Cork",
  "CE": "Clare",
  "CN": "Cavan",
  "CW": "Carlow",
  "D": "Dublin",
  "DL": "Donegal",
  "G": "Galway",
  "KE": "Kildare",
  "KK": "Kilkenny",
  "KY": "Kerry",
  "L": "Limerick",
  "LD": "Longford",
  "LH": "Louth",
  "LM": "Leitrim",
  "LS": "Laois",
  "MH": "Meath",
  "MN": "Monaghan",
  "MO": "Mayo",
  "OY": "Offaly",
  "RN": "Roscommon",
  "SO": "Sligo",
  "T": "Tipperary",
  "W": "Waterford",
  "WH": "Westmeath",
  "WW": "Wicklow",
  "WX": "Wexford",
};