// Deutsche Anzeigenamen der Schweizer Kantone im Kennzeichen-Quiz.
// Key = "abbr"-Feld aus switzerland-cantons.geojson (Kennzeichen-Kuerzel), Value = deutscher Name.
const kantonNamesDE = {
  "AG": "Aargau",
  "AI": "Appenzell Innerrhoden",
  "AR": "Appenzell Ausserrhoden",
  "BE": "Bern",
  "BL": "Basel-Landschaft",
  "BS": "Basel-Stadt",
  "FR": "Freiburg",
  "GE": "Genf",
  "GL": "Glarus",
  "GR": "Graubünden",
  "JU": "Jura",
  "LU": "Luzern",
  "NE": "Neuenburg",
  "NW": "Nidwalden",
  "OW": "Obwalden",
  "SG": "St. Gallen",
  "SH": "Schaffhausen",
  "SO": "Solothurn",
  "SZ": "Schwyz",
  "TG": "Thurgau",
  "TI": "Tessin",
  "UR": "Uri",
  "VD": "Waadt",
  "VS": "Wallis",
  "ZG": "Zug",
  "ZH": "Zürich",
};