// Deutsche Anzeigenamen der ukrainischen Oblaste im Kennzeichen-Quiz.
// Key = "iso"-Feld aus ukraine-oblasts.geojson (ISO 3166-2), Value = deutscher Name.
const oblastNamesDE = {
  "UA-05": "Winnyzja",
  "UA-07": "Wolyn",
  "UA-09": "Luhansk",
  "UA-12": "Dnipropetrowsk",
  "UA-14": "Donezk",
  "UA-18": "Schytomyr",
  "UA-21": "Transkarpatien",
  "UA-23": "Saporischschja",
  "UA-26": "Iwano-Frankiwsk",
  "UA-30": "Kiew (Stadt)",
  "UA-32": "Kiew (Oblast)",
  "UA-35": "Kirowohrad",
  "UA-43": "Krim (Autonome Republik)",
  "UA-46": "Lwiw",
  "UA-48": "Mykolajiw",
  "UA-51": "Odessa",
  "UA-53": "Poltawa",
  "UA-56": "Riwne",
  "UA-59": "Sumy",
  "UA-61": "Ternopil",
  "UA-63": "Charkiw",
  "UA-65": "Cherson",
  "UA-68": "Chmelnyzkyj",
  "UA-71": "Tscherkassy",
  "UA-74": "Tschernihiw",
  "UA-77": "Czernowitz",
};