// Deutsche/italienische Anzeigenamen der italienischen Provinzen im Kennzeichen-Quiz.
// Key = "code"-Feld aus italy-provinces.geojson (Kennzeichen-Kuerzel), Value = Anzeigename.
const provinceNamesDE = {
  "AG": "Agrigento",
  "AL": "Alessandria",
  "AN": "Ancona",
  "AO": "Aostatal",
  "AP": "Ascoli Piceno",
  "AQ": "L'Aquila",
  "AR": "Arezzo",
  "AT": "Asti",
  "AV": "Avellino",
  "BA": "Bari",
  "BG": "Bergamo",
  "BI": "Biella",
  "BL": "Belluno",
  "BN": "Benevento",
  "BO": "Bologna",
  "BR": "Brindisi",
  "BS": "Brescia",
  "BT": "Barletta-Andria-Trani",
  "BZ": "Südtirol (Bozen)",
  "CA": "Cagliari",
  "CB": "Campobasso",
  "CE": "Caserta",
  "CH": "Chieti",
  "CL": "Caltanissetta",
  "CN": "Cuneo",
  "CO": "Como",
  "CR": "Cremona",
  "CS": "Cosenza",
  "CT": "Catania",
  "CZ": "Catanzaro",
  "EN": "Enna",
  "FC": "Forlì-Cesena",
  "FE": "Ferrara",
  "FG": "Foggia",
  "FI": "Florenz",
  "FM": "Fermo",
  "FR": "Frosinone",
  "GE": "Genua",
  "GO": "Gorizia",
  "GR": "Grosseto",
  "IM": "Imperia",
  "IS": "Isernia",
  "KR": "Crotone",
  "LC": "Lecco",
  "LE": "Lecce",
  "LI": "Livorno",
  "LO": "Lodi",
  "LT": "Latina",
  "LU": "Lucca",
  "MB": "Monza e della Brianza",
  "MC": "Macerata",
  "ME": "Messina",
  "MI": "Mailand",
  "MN": "Mantova",
  "MO": "Modena",
  "MS": "Massa-Carrara",
  "MT": "Matera",
  "NA": "Neapel",
  "NO": "Novara",
  "NU": "Nuoro",
  "OG": "Ogliastra",
  "OR": "Oristano",
  "OT": "Gallura Nord-Est Sardegna",
  "PA": "Palermo",
  "PC": "Piacenza",
  "PD": "Padua",
  "PE": "Pescara",
  "PG": "Perugia",
  "PI": "Pisa",
  "PN": "Pordenone",
  "PO": "Prato",
  "PR": "Parma",
  "PT": "Pistoia",
  "PU": "Pesaro e Urbino",
  "PV": "Pavia",
  "PZ": "Potenza",
  "RA": "Ravenna",
  "RC": "Reggio Calabria",
  "RE": "Reggio Emilia",
  "RG": "Ragusa",
  "RI": "Rieti",
  "RM": "Rom",
  "RN": "Rimini",
  "RO": "Rovigo",
  "SA": "Salerno",
  "SI": "Siena",
  "SO": "Sondrio",
  "SP": "La Spezia",
  "SR": "Syrakus",
  "SS": "Sassari",
  "SU": "Sulcis Iglesiente",
  "SV": "Savona",
  "TA": "Taranto",
  "TE": "Teramo",
  "TN": "Trient",
  "TO": "Turin",
  "TP": "Trapani",
  "TR": "Terni",
  "TS": "Trieste",
  "TV": "Treviso",
  "UD": "Udine",
  "VA": "Varese",
  "VB": "Verbano-Cusio-Ossola",
  "VC": "Vercelli",
  "VE": "Venedig",
  "VI": "Vicenza",
  "VR": "Verona",
  "VS": "Medio Campidano",
  "VT": "Viterbo",
  "VV": "Vibo Valentia",
};