/* ═══════════════════════════════════════════════════════
   LAENDER.JS  –  Länder-Wappen-Quiz Datenbank
   Format: { land, kontinent, img }
   img = relativer Bildpfad  →  img/<dateiname>.svg|png|webp
   (Bilder werden später unter /quiz/laender/img/ ergänzt)
═══════════════════════════════════════════════════════ */

const LAENDER = [

  /* ── Europa ── */
  { land: "Deutschland",              kontinent: "Europa", img: "img/de.svg" },
  { land: "Frankreich",               kontinent: "Europa", img: "img/fr.svg" },
  { land: "Spanien",                  kontinent: "Europa", img: "img/es.svg" },
  { land: "Italien",                  kontinent: "Europa", img: "img/it.svg" },
  { land: "Portugal",                 kontinent: "Europa", img: "img/pt.svg" },
  { land: "Vereinigtes Königreich",   kontinent: "Europa", img: "img/gb.svg" },
  { land: "Irland",                   kontinent: "Europa", img: "img/ie.svg" },
  { land: "Niederlande",              kontinent: "Europa", img: "img/nl.svg" },
  { land: "Belgien",                  kontinent: "Europa", img: "img/be.svg" },
  { land: "Luxemburg",                kontinent: "Europa", img: "img/lu.svg" },
  { land: "Schweiz",                  kontinent: "Europa", img: "img/ch.svg" },
  { land: "Österreich",               kontinent: "Europa", img: "img/at.svg" },
  { land: "Liechtenstein",            kontinent: "Europa", img: "img/li.svg" },
  { land: "Dänemark",                 kontinent: "Europa", img: "img/dk.svg" },
  { land: "Schweden",                 kontinent: "Europa", img: "img/se.svg" },
  { land: "Norwegen",                 kontinent: "Europa", img: "img/no.svg" },
  { land: "Finnland",                 kontinent: "Europa", img: "img/fi.svg" },
  { land: "Island",                   kontinent: "Europa", img: "img/is.svg" },
  { land: "Polen",                    kontinent: "Europa", img: "img/pl.svg" },
  { land: "Tschechien",               kontinent: "Europa", img: "img/cz.svg" },
  { land: "Slowakei",                 kontinent: "Europa", img: "img/sk.svg" },
  { land: "Ungarn",                   kontinent: "Europa", img: "img/hu.svg" },
  { land: "Slowenien",                kontinent: "Europa", img: "img/si.svg" },
  { land: "Kroatien",                 kontinent: "Europa", img: "img/hr.svg" },
  { land: "Bosnien und Herzegowina",  kontinent: "Europa", img: "img/ba.svg" },
  { land: "Serbien",                  kontinent: "Europa", img: "img/rs.svg" },
  { land: "Montenegro",               kontinent: "Europa", img: "img/me.svg" },
  { land: "Nordmazedonien",           kontinent: "Europa", img: "img/mk.svg" },
  { land: "Albanien",                 kontinent: "Europa", img: "img/al.svg" },
  { land: "Kosovo",                   kontinent: "Europa", img: "img/xk.svg" },
  { land: "Griechenland",             kontinent: "Europa", img: "img/gr.svg" },
  { land: "Bulgarien",                kontinent: "Europa", img: "img/bg.svg" },
  { land: "Rumänien",                 kontinent: "Europa", img: "img/ro.svg" },
  { land: "Moldau",                   kontinent: "Europa", img: "img/md.svg" },
  { land: "Ukraine",                  kontinent: "Europa", img: "img/ua.svg" },
  { land: "Belarus",                  kontinent: "Europa", img: "img/by.svg" },
  { land: "Russland",                 kontinent: "Europa", img: "img/ru.svg" },
  { land: "Litauen",                  kontinent: "Europa", img: "img/lt.svg" },
  { land: "Lettland",                 kontinent: "Europa", img: "img/lv.svg" },
  { land: "Estland",                  kontinent: "Europa", img: "img/ee.svg" },
  { land: "Malta",                    kontinent: "Europa", img: "img/mt.svg" },
  { land: "Zypern",                   kontinent: "Europa", img: "img/cy.svg" },
  { land: "Monaco",                   kontinent: "Europa", img: "img/mc.svg" },
  { land: "Andorra",                  kontinent: "Europa", img: "img/ad.svg" },
  { land: "San Marino",               kontinent: "Europa", img: "img/sm.svg" },
  { land: "Vatikanstadt",             kontinent: "Europa", img: "img/va.svg" },

  /* ── Afrika ── */
  { land: "Ägypten",                  kontinent: "Afrika", img: "img/eg.svg" },
  { land: "Libyen",                   kontinent: "Afrika", img: "img/ly.svg" },
  { land: "Tunesien",                 kontinent: "Afrika", img: "img/tn.svg" },
  { land: "Algerien",                 kontinent: "Afrika", img: "img/dz.svg" },
  { land: "Marokko",                  kontinent: "Afrika", img: "img/ma.svg" },
  { land: "Mauretanien",              kontinent: "Afrika", img: "img/mr.svg" },
  { land: "Mali",                     kontinent: "Afrika", img: "img/ml.svg" },
  { land: "Niger",                    kontinent: "Afrika", img: "img/ne.svg" },
  { land: "Tschad",                   kontinent: "Afrika", img: "img/td.svg" },
  { land: "Sudan",                    kontinent: "Afrika", img: "img/sd.svg" },
  { land: "Südsudan",                 kontinent: "Afrika", img: "img/ss.svg" },
  { land: "Eritrea",                  kontinent: "Afrika", img: "img/er.svg" },
  { land: "Dschibuti",                kontinent: "Afrika", img: "img/dj.svg" },
  { land: "Äthiopien",                kontinent: "Afrika", img: "img/et.svg" },
  { land: "Somalia",                  kontinent: "Afrika", img: "img/so.svg" },
  { land: "Kenia",                    kontinent: "Afrika", img: "img/ke.svg" },
  { land: "Uganda",                   kontinent: "Afrika", img: "img/ug.svg" },
  { land: "Ruanda",                   kontinent: "Afrika", img: "img/rw.svg" },
  { land: "Burundi",                  kontinent: "Afrika", img: "img/bi.svg" },
  { land: "Tansania",                 kontinent: "Afrika", img: "img/ts.svg" },
  { land: "Senegal",                  kontinent: "Afrika", img: "img/sn.svg" },
  { land: "Gambia",                   kontinent: "Afrika", img: "img/gm.svg" },
  { land: "Guinea-Bissau",            kontinent: "Afrika", img: "img/gw.svg" },
  { land: "Guinea",                   kontinent: "Afrika", img: "img/gn.svg" },
  { land: "Sierra Leone",             kontinent: "Afrika", img: "img/sl.svg" },
  { land: "Liberia",                  kontinent: "Afrika", img: "img/lr.svg" },
  { land: "Elfenbeinküste",           kontinent: "Afrika", img: "img/ci.svg" },
  { land: "Ghana",                    kontinent: "Afrika", img: "img/gh.svg" },
  { land: "Togo",                     kontinent: "Afrika", img: "img/tg.svg" },
  { land: "Benin",                    kontinent: "Afrika", img: "img/bn.svg" },
  { land: "Nigeria",                  kontinent: "Afrika", img: "img/ng.svg" },
  { land: "Kamerun",                  kontinent: "Afrika", img: "img/cm.svg" },
  { land: "Zentralafrikanische Republik", kontinent: "Afrika", img: "img/cf.svg" },
  { land: "Äquatorialguinea",         kontinent: "Afrika", img: "img/gq.svg" },
  { land: "Gabun",                    kontinent: "Afrika", img: "img/ga.svg" },
  { land: "Demokratische Republik Kongo", kontinent: "Afrika", img: "img/cd.svg" },
  { land: "Angola",                   kontinent: "Afrika", img: "img/ao.svg" },
  { land: "Sambia",                   kontinent: "Afrika", img: "img/zm.svg" },
  { land: "Malawi",                   kontinent: "Afrika", img: "img/mw.svg" },
  { land: "Mosambik",                 kontinent: "Afrika", img: "img/mz.svg" },
  { land: "Simbabwe",                 kontinent: "Afrika", img: "img/zw.svg" },
  { land: "Botswana",                 kontinent: "Afrika", img: "img/bw.svg" },
  { land: "Namibia",                  kontinent: "Afrika", img: "img/na.svg" },
  { land: "Südafrika",                kontinent: "Afrika", img: "img/za.svg" },
  { land: "Lesotho",                  kontinent: "Afrika", img: "img/ls.svg" },
  { land: "Eswatini",                 kontinent: "Afrika", img: "img/sz.svg" },
  { land: "Madagaskar",               kontinent: "Afrika", img: "img/mg.svg" },
  { land: "Mauritius",                kontinent: "Afrika", img: "img/mu.svg" },
  { land: "Komoren",                  kontinent: "Afrika", img: "img/km.svg" },
  { land: "Kap Verde",                kontinent: "Afrika", img: "img/cv.svg" },
  { land: "São Tomé und Príncipe",    kontinent: "Afrika", img: "img/st.svg" },
  { land: "Burkina Faso",             kontinent: "Afrika", img: "img/bf.svg" },

  /* ── Asien ── */
  { land: "China",                    kontinent: "Asien", img: "img/cn.svg" },
  { land: "Japan",                    kontinent: "Asien", img: "img/jp.svg" },
  { land: "Südkorea",                 kontinent: "Asien", img: "img/kr.svg" },
  { land: "Nordkorea",                kontinent: "Asien", img: "img/kp.svg" },
  { land: "Mongolei",                 kontinent: "Asien", img: "img/mn.svg" },
  { land: "Taiwan",                   kontinent: "Asien", img: "img/tw.svg" },
  { land: "Vietnam",                  kontinent: "Asien", img: "img/vn.svg" },
  { land: "Laos",                     kontinent: "Asien", img: "img/la.png" },
  { land: "Kambodscha",               kontinent: "Asien", img: "img/kh.svg" },
  { land: "Thailand",                 kontinent: "Asien", img: "img/th.svg" },
  { land: "Myanmar",                  kontinent: "Asien", img: "img/mm.svg" },
  { land: "Malaysia",                 kontinent: "Asien", img: "img/my.svg" },
  { land: "Singapur",                 kontinent: "Asien", img: "img/sg.svg" },
  { land: "Indonesien",               kontinent: "Asien", img: "img/id.svg" },
  { land: "Brunei",                   kontinent: "Asien", img: "img/bn.svg" },
  { land: "Philippinen",              kontinent: "Asien", img: "img/ph.svg" },
  { land: "Osttimor",                 kontinent: "Asien", img: "img/tl.svg" },
  { land: "Indien",                   kontinent: "Asien", img: "img/in.svg" },
  { land: "Pakistan",                 kontinent: "Asien", img: "img/pk.svg" },
  { land: "Bangladesch",              kontinent: "Asien", img: "img/bd.svg" },
  { land: "Nepal",                    kontinent: "Asien", img: "img/np.svg" },
  { land: "Bhutan",                   kontinent: "Asien", img: "img/bt.svg" },
  { land: "Sri Lanka",                kontinent: "Asien", img: "img/lk.svg" },
  { land: "Malediven",                kontinent: "Asien", img: "img/mv.svg" },
  { land: "Afghanistan",              kontinent: "Asien", img: "img/af.svg" },
  { land: "Iran",                     kontinent: "Asien", img: "img/ir.svg" },
  { land: "Irak",                     kontinent: "Asien", img: "img/iq.svg" },
  { land: "Syrien",                   kontinent: "Asien", img: "img/sy.svg" },
  { land: "Libanon",                  kontinent: "Asien", img: "img/lb.svg" },
  { land: "Jordanien",                kontinent: "Asien", img: "img/jo.svg" },
  { land: "Israel",                   kontinent: "Asien", img: "img/il.svg" },
  { land: "Palästina",                kontinent: "Asien", img: "img/ps.svg" },
  { land: "Saudi-Arabien",            kontinent: "Asien", img: "img/sa.svg" },
  { land: "Jemen",                    kontinent: "Asien", img: "img/ye.svg" },
  { land: "Oman",                     kontinent: "Asien", img: "img/om.svg" },
  { land: "Vereinigte Arabische Emirate", kontinent: "Asien", img: "img/uae.svg" },
  { land: "Katar",                    kontinent: "Asien", img: "img/qa.svg" },
  { land: "Bahrain",                  kontinent: "Asien", img: "img/bh.svg" },
  { land: "Kuwait",                   kontinent: "Asien", img: "img/kw.svg" },
  { land: "Türkei",                   kontinent: "Asien", img: "img/tr.svg" },
  { land: "Georgien",                 kontinent: "Asien", img: "img/ge.svg" },
  { land: "Armenien",                 kontinent: "Asien", img: "img/am.svg" },
  { land: "Aserbaidschan",            kontinent: "Asien", img: "img/az.svg" },
  { land: "Kasachstan",               kontinent: "Asien", img: "img/kz.svg" },
  { land: "Usbekistan",               kontinent: "Asien", img: "img/uz.svg" },
  { land: "Turkmenistan",             kontinent: "Asien", img: "img/tm.svg" },
  { land: "Tadschikistan",            kontinent: "Asien", img: "img/tj.svg" },
  { land: "Kirgisistan",              kontinent: "Asien", img: "img/kg.svg" },

  /* ── Nordamerika ── */
  { land: "USA",                      kontinent: "Nordamerika", img: "img/us.svg" },
  { land: "Kanada",                   kontinent: "Nordamerika", img: "img/ca.svg" },
  { land: "Mexiko",                   kontinent: "Nordamerika", img: "img/mx.svg" },
  { land: "Guatemala",                kontinent: "Nordamerika", img: "img/gt.svg" },
  { land: "Belize",                   kontinent: "Nordamerika", img: "img/bz.svg" },
  { land: "Honduras",                 kontinent: "Nordamerika", img: "img/hn.svg" },
  { land: "El Salvador",              kontinent: "Nordamerika", img: "img/sv.svg" },
  { land: "Nicaragua",                kontinent: "Nordamerika", img: "img/ni.svg" },
  { land: "Costa Rica",               kontinent: "Nordamerika", img: "img/cr.svg" },
  { land: "Panama",                   kontinent: "Nordamerika", img: "img/pa.svg" },
  { land: "Kuba",                     kontinent: "Nordamerika", img: "img/cu.svg" },
  { land: "Jamaika",                  kontinent: "Nordamerika", img: "img/jm.svg" },
  { land: "Haiti",                    kontinent: "Nordamerika", img: "img/ht.svg" },
  { land: "Dominikanische Republik",  kontinent: "Nordamerika", img: "img/do.svg" },
  { land: "Bahamas",                  kontinent: "Nordamerika", img: "img/bs.svg" },
  { land: "Trinidad und Tobago",      kontinent: "Nordamerika", img: "img/tt.svg" },
  { land: "Barbados",                 kontinent: "Nordamerika", img: "img/bb.svg" },

  /* ── Südamerika ── */
  { land: "Brasilien",                kontinent: "Südamerika", img: "img/bra.svg" },
  { land: "Argentinien",              kontinent: "Südamerika", img: "img/ar.svg" },
  { land: "Chile",                    kontinent: "Südamerika", img: "img/cl.svg" },
  { land: "Peru",                     kontinent: "Südamerika", img: "img/pe.svg" },
  { land: "Bolivien",                 kontinent: "Südamerika", img: "img/bo.svg" },
  { land: "Ecuador",                  kontinent: "Südamerika", img: "img/ec.svg" },
  { land: "Kolumbien",                kontinent: "Südamerika", img: "img/co.svg" },
  { land: "Venezuela",                kontinent: "Südamerika", img: "img/ve.svg" },
  { land: "Guyana",                   kontinent: "Südamerika", img: "img/gy.svg" },
  { land: "Suriname",                 kontinent: "Südamerika", img: "img/sr.svg" },
  { land: "Paraguay",                 kontinent: "Südamerika", img: "img/py.svg" },
  { land: "Uruguay",                  kontinent: "Südamerika", img: "img/uy.svg" },

  /* ── Ozeanien ── */
  { land: "Australien",               kontinent: "Ozeanien", img: "img/au.svg" },
  { land: "Neuseeland",               kontinent: "Ozeanien", img: "img/nz.svg" },
  { land: "Papua-Neuguinea",          kontinent: "Ozeanien", img: "img/pg.svg" },
  { land: "Fidschi",                  kontinent: "Ozeanien", img: "img/fj.svg" },
  { land: "Salomonen",                kontinent: "Ozeanien", img: "img/sb.svg" },
  { land: "Vanuatu",                  kontinent: "Ozeanien", img: "img/vu.svg" },
  { land: "Samoa",                    kontinent: "Ozeanien", img: "img/ws.svg" },
  { land: "Tonga",                    kontinent: "Ozeanien", img: "img/to.svg" },
  { land: "Kiribati",                 kontinent: "Ozeanien", img: "img/ki.svg" },
  { land: "Palau",                    kontinent: "Ozeanien", img: "img/pw.svg" },
  { land: "Mikronesien",              kontinent: "Ozeanien", img: "img/fm.svg" },
  { land: "Marshallinseln",           kontinent: "Ozeanien", img: "img/mh.svg" },
  { land: "Nauru",                    kontinent: "Ozeanien", img: "img/nr.svg" },
  { land: "Tuvalu",                   kontinent: "Ozeanien", img: "img/tv.svg" },

];